function [directionalSlownessZX, diagnostics] = ...
        buildDirectionalSlowness( ...
            csMapZX, directionXYZ, referenceCsMps)
%BUILDDIRECTIONALSLOWNESS Reduced slowness for projected-3D Eikonal.
%
% The medium is invariant along y. For a conserved transverse slowness py,
%
%   |grad_xz(tau)|^2 = 1/cs(x,z)^2 - py^2.
%
% directionXYZ defines the incident three-dimensional direction in the
% reference medium:
%
%   py = direction_y / referenceCsMps.

validateattributes( ...
    csMapZX, ...
    {'numeric'}, ...
    {'2d', 'nonempty', 'real', 'finite', 'positive'});

validateattributes( ...
    directionXYZ, ...
    {'numeric'}, ...
    {'vector', 'numel', 3, 'real', 'finite'});

validateattributes( ...
    referenceCsMps, ...
    {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'});

directionXYZ = double(directionXYZ(:).');

directionNorm = norm(directionXYZ);

if directionNorm <= eps
    error( ...
        "swsynth:InvalidProjected3DDirection", ...
        "directionXYZ must have nonzero magnitude.");
end

unitDirectionXYZ = directionXYZ / directionNorm;

transverseSlownessSPerM = ...
    unitDirectionXYZ(2) / referenceCsMps;

inverseSpeedSquared = ...
    1 ./ double(csMapZX).^2;

radicand = ...
    inverseSpeedSquared - ...
    transverseSlownessSPerM^2;

numericalTolerance = ...
    100 * eps(max([ ...
        1; ...
        inverseSpeedSquared(:); ...
        transverseSlownessSPerM^2]));

if min(radicand(:)) < -numericalTolerance
    error( ...
        "swsynth:Projected3DEvanescentRegion", ...
        ["The selected transverse slowness is not propagating " + ...
         "throughout the medium. Minimum squared projected " + ...
         "slowness = %.6e s^2/m^2."], ...
        min(radicand(:)));
end

radicand(radicand < 0) = 0;

directionalSlownessZX = sqrt(radicand);

diagnostics = struct();
diagnostics.unit_direction_xyz = unitDirectionXYZ;
diagnostics.reference_cs_m_s = referenceCsMps;
diagnostics.transverse_slowness_s_m = ...
    transverseSlownessSPerM;
diagnostics.projected_direction_norm = ...
    hypot(unitDirectionXYZ(1), unitDirectionXYZ(3));
diagnostics.minimum_directional_slowness_s_m = ...
    min(directionalSlownessZX(:));
diagnostics.maximum_directional_slowness_s_m = ...
    max(directionalSlownessZX(:));
diagnostics.propagating_everywhere = true;

end
