function [phaseDelayZX, diagnostics] = ...
        computeDirectionalPhaseDelay( ...
            csMapZX, xM, zM, directionXYZ, ...
            referenceCsMps, solverOptions)
%COMPUTEDIRECTIONALPHASEDELAY Projected-3D Eikonal phase delay.
%
% The medium is assumed invariant along y:
%
%   cs(x,y,z) = cs(x,z)
%
% A three-dimensional incident direction defines the conserved transverse
% slowness py. The reduced x-z Eikonal problem is then solved using the
% internal fast-sweeping kernel.
%
% phaseDelayZX is measured in seconds and is defined up to the deterministic
% upstream-corner reference used by buildIncidentBoundaryCondition.

if nargin < 6 || isempty(solverOptions)
    solverOptions = struct();
end

validateattributes( ...
    csMapZX, ...
    {'numeric'}, ...
    {'2d', 'nonempty', 'real', 'finite', 'positive'});

xM = double(xM(:).');
zM = double(zM(:));
csMapZX = double(csMapZX);

if ~isequal(size(csMapZX), [numel(zM), numel(xM)])
    error( ...
        "swsynth:Projected3DMapSizeMismatch", ...
        "csMapZX must have size [numel(zM), numel(xM)].");
end

if numel(xM) < 2 || numel(zM) < 2
    error( ...
        "swsynth:Projected3DGridTooSmall", ...
        "The projected-3D Eikonal grid requires at least 2-by-2 nodes.");
end

dxValues = diff(xM);
dzValues = diff(zM);

dxM = mean(dxValues);
dzM = mean(dzValues);

spacingTolerance = 1e-10;

if max(abs(dxValues - dxM)) > ...
        spacingTolerance * max(1, abs(dxM))
    error( ...
        "swsynth:Projected3DNonuniformXGrid", ...
        "xM must be uniformly spaced.");
end

if max(abs(dzValues - dzM)) > ...
        spacingTolerance * max(1, abs(dzM))
    error( ...
        "swsynth:Projected3DNonuniformZGrid", ...
        "zM must be uniformly spaced.");
end

[directionalSlownessZX, slownessDiagnostics] = ...
    swsynth.propagation.projected3d.buildDirectionalSlowness( ...
        csMapZX, ...
        directionXYZ, ...
        referenceCsMps);

[initialTimeZX, fixedMaskZX, boundaryDiagnostics] = ...
    swsynth.propagation.projected3d. ...
        buildIncidentBoundaryCondition( ...
            xM, ...
            zM, ...
            directionXYZ, ...
            referenceCsMps);

if boundaryDiagnostics.projected_direction_norm <= 1e-12
    phaseDelayZX = zeros(size(csMapZX));

    solverDiagnostics = struct();
    solverDiagnostics.method = "pure_out_of_plane_exact";
    solverDiagnostics.converged = true;
    solverDiagnostics.iterations = 0;
    solverDiagnostics.last_change_s = 0;
else
    [phaseDelayZX, solverDiagnostics] = ...
        swsynth.numerics.eikonal.solveFastSweeping2D( ...
            directionalSlownessZX, ...
            dxM, ...
            dzM, ...
            initialTimeZX, ...
            fixedMaskZX, ...
            solverOptions);

    solverDiagnostics.method = "fast_sweeping_2d";

    if ~solverDiagnostics.converged
        error( ...
            "swsynth:Projected3DEikonalDidNotConverge", ...
            ["Projected-3D Eikonal did not converge after %d " + ...
             "iterations. Last change = %.6e s."], ...
            solverDiagnostics.iterations, ...
            solverDiagnostics.last_change_s);
    end
end

diagnostics = struct();
diagnostics.model = "projected3d_directional_eikonal";
diagnostics.reference_cs_m_s = referenceCsMps;
diagnostics.grid_spacing_x_m = dxM;
diagnostics.grid_spacing_z_m = dzM;
diagnostics.slowness = slownessDiagnostics;
diagnostics.boundary = boundaryDiagnostics;
diagnostics.solver = solverDiagnostics;

end
