function [keepMask, diagnostics] = ...
        filterPropagatingDirections( ...
            csMapZX, directionsXYZ, referenceCsMps)
%FILTERPROPAGATINGDIRECTIONS Identify globally propagating components.
%
% For each direction n:
%
%   py_n = uy_n / referenceCsMps(n)
%
% A direction is retained only when
%
%   1/cs(x,z)^2 - py_n^2 >= 0
%
% throughout the complete medium map.
%
% This function does not silently alter directions and does not clip
% evanescent regions. It only returns a deterministic keep mask.

validateattributes( ...
    csMapZX, ...
    {'numeric'}, ...
    {'2d', 'nonempty', 'real', 'finite', 'positive'});

validateattributes( ...
    directionsXYZ, ...
    {'numeric'}, ...
    {'2d', 'nonempty', 'real', 'finite'});

if size(directionsXYZ, 2) ~= 3
    error( ...
        "swsynth:Projected3DDirectionShape", ...
        "directionsXYZ must have size N-by-3.");
end

directionCount = size(directionsXYZ, 1);

validateattributes( ...
    referenceCsMps, ...
    {'numeric'}, ...
    {'vector', 'nonempty', 'real', 'finite', 'positive'});

referenceCsMps = double(referenceCsMps(:));

if isscalar(referenceCsMps)
    referenceCsMps = repmat( ...
        referenceCsMps, ...
        directionCount, ...
        1);

elseif numel(referenceCsMps) ~= directionCount
    error( ...
        "swsynth:Projected3DReferenceSpeedCountMismatch", ...
        ["referenceCsMps must be a positive scalar or contain " + ...
         "one value per direction."]);
end

directionsXYZ = double(directionsXYZ);

directionNorms = vecnorm(directionsXYZ, 2, 2);

if any(directionNorms <= eps)
    error( ...
        "swsynth:InvalidProjected3DDirection", ...
        "Every direction must have nonzero magnitude.");
end

unitDirectionsXYZ = ...
    directionsXYZ ./ directionNorms;

transverseSlownessSPerM = ...
    unitDirectionsXYZ(:,2) ./ referenceCsMps;

minimumInverseSpeedSquared = ...
    min(1 ./ double(csMapZX(:)).^2);

minimumRadicand = ...
    minimumInverseSpeedSquared - ...
    transverseSlownessSPerM.^2;

numericalTolerance = ...
    100 * eps(max([ ...
        1; ...
        minimumInverseSpeedSquared; ...
        transverseSlownessSPerM.^2]));

keepMask = ...
    minimumRadicand >= -numericalTolerance;

diagnostics = struct();
diagnostics.direction_count_requested = directionCount;
diagnostics.direction_count_retained = nnz(keepMask);
diagnostics.direction_count_rejected = nnz(~keepMask);
diagnostics.retained_fraction = nnz(keepMask) / directionCount;

diagnostics.keep_mask = keepMask;
diagnostics.rejected_indices = find(~keepMask);

diagnostics.reference_cs_m_s = referenceCsMps;
diagnostics.transverse_slowness_s_m = ...
    transverseSlownessSPerM;
diagnostics.minimum_radicand_s2_m2 = ...
    minimumRadicand;

diagnostics.minimum_medium_cs_m_s = ...
    min(csMapZX(:));
diagnostics.maximum_medium_cs_m_s = ...
    max(csMapZX(:));

end
