function [selectedDirectionsXYZ, selectedReferenceCsMps, diagnostics] = ...
        selectPropagatingDirections( ...
            csMapZX, ...
            initialDirectionsXYZ, ...
            solidAngleSr, ...
            axisXYZ, ...
            inPlaneCount, ...
            options)
%SELECTPROPAGATINGDIRECTIONS Select an exact propagating direction count.
%
% The requested number of final directions is taken from the number of rows
% in initialDirectionsXYZ. If the initial deterministic sample contains
% nonpropagating components, progressively denser candidate sets are
% generated over the same solid-angle support.
%
% Exact in-plane directions are preserved. Remaining eligible candidates
% are selected using deterministic farthest-point angular sampling.

arguments
    csMapZX (:,:) double
    initialDirectionsXYZ (:,3) double
    solidAngleSr (1,1) double
    axisXYZ (1,3) double
    inPlaneCount (1,1) double
    options.MaximumCandidateMultiplier (1,1) double = 16
end

validateattributes( ...
    csMapZX, ...
    {'numeric'}, ...
    {'2d', 'nonempty', 'real', 'finite', 'positive'});

validateattributes( ...
    initialDirectionsXYZ, ...
    {'numeric'}, ...
    {'2d', 'nonempty', 'real', 'finite', 'ncols', 3});

requestedDirectionCount = size(initialDirectionsXYZ,1);

validateattributes( ...
    inPlaneCount, ...
    {'numeric'}, ...
    {'scalar', 'integer', 'nonnegative', ...
     '<=', requestedDirectionCount});

validateattributes( ...
    options.MaximumCandidateMultiplier, ...
    {'numeric'}, ...
    {'scalar', 'integer', 'positive', 'finite'});

initialDirectionsXYZ = normalizeRows(initialDirectionsXYZ);

candidateMultipliers = [
    1
    2
    3
    4
    6
    8
    12
    16];

candidateMultipliers = candidateMultipliers( ...
    candidateMultipliers <= options.MaximumCandidateMultiplier);

if isempty(candidateMultipliers) || candidateMultipliers(1) ~= 1
    candidateMultipliers = [
        1
        candidateMultipliers];
end

selectedDirectionsXYZ = zeros(0,3);
selectedReferenceCsMps = zeros(0,1);

lastCandidateCount = 0;
lastEligibleCount = 0;
lastRejectedCount = 0;
lastEligibility = struct();

for multiplierIndex = 1:numel(candidateMultipliers)

    multiplier = candidateMultipliers(multiplierIndex);

    if multiplier == 1
        candidateDirectionsXYZ = initialDirectionsXYZ;
    else
        candidateOutOfPlaneCount = ...
            multiplier * ...
            (requestedDirectionCount - inPlaneCount);

        candidateDirectionCount = ...
            inPlaneCount + candidateOutOfPlaneCount;

        candidateDirectionsXYZ = ...
            swsynth.sampleSolidAngleDirections( ...
                candidateDirectionCount, ...
                solidAngleSr, ...
                axisXYZ, ...
                inPlaneCount);
    end

    candidateDirectionsXYZ = ...
        normalizeRows(candidateDirectionsXYZ);

    candidateReferenceCsMps = ...
        swsynth.propagation.projected3d. ...
            resolveReferenceSpeeds( ...
                csMapZX, ...
                candidateDirectionsXYZ);

    [eligibleMask, eligibility] = ...
        swsynth.propagation.projected3d. ...
            filterPropagatingDirections( ...
                csMapZX, ...
                candidateDirectionsXYZ, ...
                candidateReferenceCsMps);

    inPlaneMask = ...
        abs(candidateDirectionsXYZ(:,2)) <= 1e-12;

    if nnz(inPlaneMask) ~= inPlaneCount
        error( ...
            "swsynth:Projected3DInPlaneCandidateMismatch", ...
            ["The candidate sampler produced %d in-plane directions, " + ...
             "but %d were requested."], ...
            nnz(inPlaneMask), ...
            inPlaneCount);
    end

    if any(inPlaneMask & ~eligibleMask)
        error( ...
            "swsynth:Projected3DInPlaneDirectionNotPropagating", ...
            ["At least one required in-plane direction is not globally " + ...
             "propagating. This indicates an inconsistent projected-3D " + ...
             "medium configuration."]);
    end

    lastCandidateCount = size(candidateDirectionsXYZ,1);
    lastEligibleCount = nnz(eligibleMask);
    lastRejectedCount = nnz(~eligibleMask);
    lastEligibility = eligibility;

    % Preserve the original deterministic sample exactly when every
    % initially requested direction is already globally propagating.
    if multiplier == 1 && all(eligibleMask)
        selectedDirectionsXYZ = candidateDirectionsXYZ;
        selectedReferenceCsMps = candidateReferenceCsMps;
        break;
    end

    if lastEligibleCount < requestedDirectionCount
        continue;
    end

    selectedIndices = selectAngularlySeparatedIndices( ...
        candidateDirectionsXYZ, ...
        eligibleMask, ...
        inPlaneMask, ...
        requestedDirectionCount);

    selectedDirectionsXYZ = ...
        candidateDirectionsXYZ(selectedIndices,:);

    selectedReferenceCsMps = ...
        candidateReferenceCsMps(selectedIndices);

    break;
end

if isempty(selectedDirectionsXYZ)
    error( ...
        "swsynth:Projected3DInsufficientPropagatingDirections", ...
        ["Could not obtain %d globally propagating directions after " + ...
         "testing %d candidates. Increase " + ...
         "MaximumCandidateMultiplier or reduce the requested support."], ...
        requestedDirectionCount, ...
        lastCandidateCount);
end

selectedInPlaneCount = ...
    nnz(abs(selectedDirectionsXYZ(:,2)) <= 1e-12);

if size(selectedDirectionsXYZ,1) ~= requestedDirectionCount
    error( ...
        "swsynth:Projected3DDirectionSelectionFailure", ...
        "The final direction count does not match the requested count.");
end

if selectedInPlaneCount ~= inPlaneCount
    error( ...
        "swsynth:Projected3DSelectedInPlaneCountMismatch", ...
        ["The final set contains %d in-plane directions, but %d " + ...
         "were requested."], ...
        selectedInPlaneCount, ...
        inPlaneCount);
end

diagnostics = struct();
diagnostics.requested_direction_count = ...
    requestedDirectionCount;
diagnostics.candidate_direction_count = ...
    lastCandidateCount;
diagnostics.eligible_candidate_count = ...
    lastEligibleCount;
diagnostics.rejected_candidate_count = ...
    lastRejectedCount;
diagnostics.selected_direction_count = ...
    size(selectedDirectionsXYZ,1);
diagnostics.selected_in_plane_count = ...
    selectedInPlaneCount;
diagnostics.candidate_multiplier = ...
    lastCandidateCount / requestedDirectionCount;
diagnostics.selection_method = ...
    "preserve_in_plane_then_farthest_point";
diagnostics.propagation_eligibility = ...
    lastEligibility;

end

function selectedIndices = selectAngularlySeparatedIndices( ...
        directionsXYZ, eligibleMask, inPlaneMask, requestedCount)

requiredIndices = find(eligibleMask & inPlaneMask);
optionalIndices = find(eligibleMask & ~inPlaneMask);

selectedIndices = requiredIndices(:);

remainingCount = requestedCount - numel(selectedIndices);

if remainingCount < 0
    error( ...
        "swsynth:Projected3DTooManyRequiredDirections", ...
        "The required in-plane count exceeds the final direction count.");
end

if remainingCount == 0
    return;
end

if numel(optionalIndices) < remainingCount
    error( ...
        "swsynth:Projected3DInsufficientEligibleCandidates", ...
        "There are not enough eligible out-of-plane candidates.");
end

availableMask = true(numel(optionalIndices),1);

if isempty(selectedIndices)
    % Deterministic first seed. The Fibonacci candidate order is itself
    % deterministic.
    firstLocalIndex = find(availableMask, 1, "first");

    selectedIndices = optionalIndices(firstLocalIndex);
    availableMask(firstLocalIndex) = false;
end

while numel(selectedIndices) < requestedCount

    availableLocalIndices = find(availableMask);
    availableGlobalIndices = ...
        optionalIndices(availableLocalIndices);

    candidateXYZ = ...
        directionsXYZ(availableGlobalIndices,:);

    selectedXYZ = ...
        directionsXYZ(selectedIndices,:);

    cosineSimilarity = ...
        candidateXYZ * selectedXYZ.';

    minimumAngularDistance = ...
        min(1 - cosineSimilarity, [], 2);

    maximumDistance = max(minimumAngularDistance);

    % find(...,1) provides deterministic tie breaking.
    chosenRelativeIndex = find( ...
        minimumAngularDistance >= ...
        maximumDistance - 100*eps(maximumDistance), ...
        1, ...
        "first");

    chosenLocalIndex = ...
        availableLocalIndices(chosenRelativeIndex);

    selectedIndices(end+1,1) = ... %#ok<AGROW>
        optionalIndices(chosenLocalIndex);

    availableMask(chosenLocalIndex) = false;
end

end

function normalizedXYZ = normalizeRows(valuesXYZ)

rowNorm = vecnorm(valuesXYZ,2,2);

if any(rowNorm <= eps)
    error( ...
        "swsynth:InvalidProjected3DDirection", ...
        "Every direction must have nonzero magnitude.");
end

normalizedXYZ = valuesXYZ ./ rowNorm;

end
