function wavefield = synthesizeProjected3DEikonal( ...
        cfg, maps, directions)
%SYNTHESIZEPROJECTED3DEIKONAL Projected-3D Eikonal field synthesis.
%
% The physical medium is represented by cs(x,z) and is assumed invariant
% along y. Three-dimensional directional components are projected onto the
% x-z observation plane while conserving transverse slowness.
%
% The output follows the common swsynth contract:
%
%   wavefield.U_zx
%   wavefield.component
%   wavefield.frequency_hz
%   wavefield.weights
%   wavefield.phase_rad
%   wavefield.amplitude
%   wavefield.polarization_z
%   wavefield.diagnostics

arguments
    cfg (1,1) struct
    maps (1,1) struct
    directions (1,1) struct
end

[cfg, ~] = swsynth.validateConfig(cfg);

if cfg.propagation.model ~= "projected3d_eikonal"
    error( ...
        "swsynth:IncorrectProjected3DPropagationModel", ...
        ["synthesizeProjected3DEikonal requires " + ...
         "propagation.model = projected3d_eikonal."]);
end

requiredMapFields = ["x_m", "z_m", "cs_map_zx"];

for fieldIndex = 1:numel(requiredMapFields)
    fieldName = requiredMapFields(fieldIndex);

    if ~isfield(maps, fieldName)
        error( ...
            "swsynth:MissingMapField", ...
            "maps.%s is required.", ...
            fieldName);
    end
end

requiredDirectionFields = ["ux", "uy", "uz"];

for fieldIndex = 1:numel(requiredDirectionFields)
    fieldName = requiredDirectionFields(fieldIndex);

    if ~isfield(directions, fieldName)
        error( ...
            "swsynth:MissingDirectionComponent", ...
            "directions.%s is required.", ...
            fieldName);
    end
end

directionsXYZ = double([
    directions.ux(:), ...
    directions.uy(:), ...
    directions.uz(:)]);

requestedDirectionCount = size(directionsXYZ,1);

if requestedDirectionCount ~= cfg.directions.count
    error( ...
        "swsynth:DirectionCountMismatch", ...
        ["Generated direction count does not match " + ...
         "cfg.directions.count."]);
end

referenceCsRequestedMps = ...
    swsynth.propagation.projected3d. ...
        resolveReferenceSpeeds( ...
            maps.cs_map_zx, ...
            directionsXYZ);

[initialKeepMask, initialEligibility] = ...
    swsynth.propagation.projected3d. ...
        filterPropagatingDirections( ...
            maps.cs_map_zx, ...
            directionsXYZ, ...
            referenceCsRequestedMps);

selectionDiagnostics = struct();

if any(~initialKeepMask)
    switch cfg.propagation.nonpropagating_policy
        case "error"
            error( ...
                "swsynth:Projected3DNonpropagatingDirections", ...
                ["%d of %d initially sampled directions are not " + ...
                 "propagating throughout the medium."], ...
                nnz(~initialKeepMask), ...
                requestedDirectionCount);

        case "filter"
            [directionsXYZ, referenceCsMps, ...
                    selectionDiagnostics] = ...
                swsynth.propagation.projected3d. ...
                    selectPropagatingDirections( ...
                        maps.cs_map_zx, ...
                        directionsXYZ, ...
                        cfg.directions.support.solid_angle_sr, ...
                        cfg.directions.support.axis_xyz, ...
                        cfg.directions.in_plane_count);
    end
else
    referenceCsMps = referenceCsRequestedMps;

    selectionDiagnostics = struct();
    selectionDiagnostics.requested_direction_count = ...
        requestedDirectionCount;
    selectionDiagnostics.candidate_direction_count = ...
        requestedDirectionCount;
    selectionDiagnostics.eligible_candidate_count = ...
        requestedDirectionCount;
    selectionDiagnostics.rejected_candidate_count = 0;
    selectionDiagnostics.selected_direction_count = ...
        requestedDirectionCount;
    selectionDiagnostics.selected_in_plane_count = ...
        nnz(abs(directionsXYZ(:,2)) <= 1e-12);
    selectionDiagnostics.candidate_multiplier = 1;
    selectionDiagnostics.selection_method = ...
        "initial_sample_all_eligible";
    selectionDiagnostics.propagation_eligibility = ...
        initialEligibility;
end

retainedDirectionCount = size(directionsXYZ,1);

if retainedDirectionCount == 0
    error( ...
        "swsynth:Projected3DNoPropagatingDirections", ...
        "No propagating directions remain after applying the policy.");
end

% Shared excitation contract across propagation backends.
excitation = ...
    swsynth.generateDirectionalExcitation( ...
        cfg, ...
        directionsXYZ);

phaseRad = excitation.phase_rad;
amplitude = excitation.amplitude;
polarizationXYZ = excitation.polarization_xyz;
polarizationZ = excitation.polarization_z;
weights = excitation.weights;

options = struct();
options.UseParallel = ...
    logical(cfg.execution.use_parallel);

[fieldZX, synthesisDiagnostics] = ...
    swsynth.propagation.projected3d. ...
        synthesizeDirectionalField( ...
            maps.cs_map_zx, ...
            maps.x_m, ...
            maps.z_m, ...
            directionsXYZ, ...
            weights, ...
            cfg.wavefield.frequency_hz, ...
            referenceCsMps, ...
            options);

if isfinite(cfg.noise.snr_db)
    signalPower = mean(abs(fieldZX(:)).^2);
    noisePower = ...
        signalPower / ...
        (10^(double(cfg.noise.snr_db)/10));

    noiseReal = ...
        sqrt(noisePower/2) .* ...
        randn(size(fieldZX));

    noiseImag = ...
        sqrt(noisePower/2) .* ...
        randn(size(fieldZX));

    fieldZX = ...
        fieldZX + ...
        complex(noiseReal, noiseImag);
end

wavefield = struct();

wavefield.U_zx = fieldZX;
wavefield.component = ...
    cfg.wavefield.observed_component;
wavefield.frequency_hz = ...
    cfg.wavefield.frequency_hz;

wavefield.propagation_model = ...
    "projected3d_eikonal";
wavefield.phase_model = ...
    "projected3d_directional_eikonal";

wavefield.is_complex = true;
wavefield.output_convention = "U(z,x)";

wavefield.polarization_z = polarizationZ;
wavefield.polarization_xyz = polarizationXYZ;
wavefield.weights = weights;
wavefield.phase_rad = phaseRad;
wavefield.amplitude = amplitude;

% These are directional components rather than finite-distance point
% sources.
wavefield.sources = struct( ...
    "x_m", [], ...
    "y_m", [], ...
    "z_m", [], ...
    "radius_m", []);

wavefield.directions_xyz = directionsXYZ;
wavefield.reference_cs_m_s = referenceCsMps;

wavefield.diagnostics = struct();
wavefield.diagnostics.requested_direction_count = ...
    requestedDirectionCount;
wavefield.diagnostics.retained_direction_count = ...
    retainedDirectionCount;
wavefield.diagnostics.rejected_direction_count = ...
    requestedDirectionCount - retainedDirectionCount;

wavefield.diagnostics.candidate_direction_count = ...
    selectionDiagnostics.candidate_direction_count;
wavefield.diagnostics.eligible_candidate_count = ...
    selectionDiagnostics.eligible_candidate_count;
wavefield.diagnostics.rejected_candidate_count = ...
    selectionDiagnostics.rejected_candidate_count;
wavefield.diagnostics.selected_in_plane_count = ...
    selectionDiagnostics.selected_in_plane_count;

wavefield.diagnostics.nonpropagating_policy = ...
    cfg.propagation.nonpropagating_policy;
wavefield.diagnostics.direction_selection = ...
    selectionDiagnostics;
wavefield.diagnostics.synthesis = ...
    synthesisDiagnostics;

end
