function report = evaluateDirectionalHarmonic3D(result)
%EVALUATEDIRECTIONALHARMONIC3D Validate a homogeneous directional 3D field.
%
% Acceptance checks:
%   - finite harmonic fields
%   - expected source geometry
%   - shear-wave phase velocity
%   - cross-polarization inside the directional core
%   - global compressional-to-shear leakage
%   - bounded effective-center reflection symmetry
%
% Global and central-axis polarization ratios are retained as descriptive
% metrics but do not independently determine pass/fail.

arguments
    result struct
end

cfg = result.config_resolved;

speed = ...
    kwsim.analysis.estimateDirectionalSpeed3D( ...
        result);

field_metrics = ...
    kwsim.analysis.directionalFieldMetrics3D( ...
        result);

expected_polarization = [0, 0, 1];
expected_direction = [1, 0, 0];

polarization_error = norm( ...
    double(cfg.source.polarization_xyz) - ...
    expected_polarization);

direction_error = norm( ...
    double(cfg.source.target_direction_xyz) - ...
    expected_direction);

is_homogeneous = ...
    isfield(result, "truth") && ...
    isfield(result.truth, "homogeneous") && ...
    logical(result.truth.homogeneous);

speed_relative_error = ...
    abs(speed.speed_m_s - cfg.medium.cs_m_s) / ...
    cfg.medium.cs_m_s;

checks = repmat( ...
    emptyCheck(), ...
    0, 1);

addCheck( ...
    "homogeneous_medium", ...
    is_homogeneous, ...
    double(is_homogeneous), ...
    1, ...
    "Directional harmonic validation requires a homogeneous medium.");

addCheck( ...
    "expected_z_polarization", ...
    polarization_error <= 1e-12, ...
    polarization_error, ...
    1e-12, ...
    "Expected imposed source motion [0 0 1].");

addCheck( ...
    "expected_positive_x_direction", ...
    direction_error <= 1e-12, ...
    direction_error, ...
    1e-12, ...
    "Expected nominal propagation direction [1 0 0].");

addCheck( ...
    "finite_harmonic_fields", ...
    field_metrics.finite_fields, ...
    double(field_metrics.finite_fields), ...
    1, ...
    "All six harmonic P/S component volumes must be finite.");

addCheck( ...
    "shear_speed_relative_error", ...
    isfinite(speed_relative_error) && ...
    speed_relative_error <= ...
        cfg.diagnostics.maximum_speed_relative_error, ...
    speed_relative_error, ...
    cfg.diagnostics.maximum_speed_relative_error, ...
    "Phase-gradient speed must match the homogeneous shear-wave speed.");

addCheck( ...
    "directional_core_cross_polarization_ratio", ...
    isfinite(field_metrics.core_cross_polarization_ratio) && ...
    field_metrics.core_cross_polarization_ratio <= ...
        cfg.diagnostics.maximum_cross_polarization_ratio, ...
    field_metrics.core_cross_polarization_ratio, ...
    cfg.diagnostics.maximum_cross_polarization_ratio, ...
    ["Cross-polarized shear energy is evaluated in the directional " ...
     "core, not over the complete divergent field."]);

addCheck( ...
    "global_longitudinal_leakage_ratio", ...
    isfinite(field_metrics.longitudinal_leakage_ratio) && ...
    field_metrics.longitudinal_leakage_ratio <= ...
        cfg.diagnostics.maximum_longitudinal_leakage_ratio, ...
    field_metrics.longitudinal_leakage_ratio, ...
    cfg.diagnostics.maximum_longitudinal_leakage_ratio, ...
    "Global compressional energy must remain small relative to shear energy.");

addCheck( ...
    "y_even_symmetry_error", ...
    isfinite(field_metrics.y_even_symmetry_error) && ...
    field_metrics.y_even_symmetry_error <= ...
        cfg.diagnostics.maximum_symmetry_error, ...
    field_metrics.y_even_symmetry_error, ...
    cfg.diagnostics.maximum_symmetry_error, ...
    ["The dominant z-shear field must be symmetric about a bounded " ...
     "effective y center near the source."]);

addCheck( ...
    "z_even_symmetry_error", ...
    isfinite(field_metrics.z_even_symmetry_error) && ...
    field_metrics.z_even_symmetry_error <= ...
        cfg.diagnostics.maximum_symmetry_error, ...
    field_metrics.z_even_symmetry_error, ...
    cfg.diagnostics.maximum_symmetry_error, ...
    ["The dominant z-shear field must be symmetric about a bounded " ...
     "effective z center near the source."]);

report = struct();

report.scope = ...
    "homogeneous_directional_harmonic_3d";

report.valid = ...
    all([checks.pass]);

report.checks = ...
    checks;

report.metrics = struct();

report.metrics.speed = ...
    speed;

report.metrics.speed_relative_error = ...
    speed_relative_error;

report.metrics.field = ...
    field_metrics;

report.frequency_evaluated = false;

report.frequency_reason = ...
    ["Temporal frequency requires retained time-series data; " ...
     "the extracted phasor alone is insufficient."];

report.summary = sprintf([ ...
    'harmonic valid=%d, cs=%.5f m/s (error %.3f%%), ', ...
    'fit R2=%.6f, cross global/core/axis=%.4g/%.4g/%.4g, ', ...
    'P/S leakage=%.4g, ', ...
    'symmetry y nominal/best=%.4g/%.4g (offset %.3f vox), ', ...
    'z nominal/best=%.4g/%.4g (offset %.3f vox)'], ...
    report.valid, ...
    speed.speed_m_s, ...
    100 * speed_relative_error, ...
    speed.r_squared, ...
    field_metrics.global_cross_polarization_ratio, ...
    field_metrics.core_cross_polarization_ratio, ...
    field_metrics.central_axis_cross_polarization_ratio, ...
    field_metrics.longitudinal_leakage_ratio, ...
    field_metrics.y_nominal_even_symmetry_error, ...
    field_metrics.y_even_symmetry_error, ...
    field_metrics.y_symmetry_center_offset_voxels, ...
    field_metrics.z_nominal_even_symmetry_error, ...
    field_metrics.z_even_symmetry_error, ...
    field_metrics.z_symmetry_center_offset_voxels);

if isfield(result, "preflight")
    report.preflight = ...
        result.preflight;
end

    function addCheck( ...
            name, pass, value, threshold, message)

        check = emptyCheck();

        check.name = string(name);
        check.pass = logical(pass);
        check.value = double(value);
        check.threshold = double(threshold);
        check.message = string(message);

        checks(end + 1, 1) = check;

    end

end


function check = emptyCheck()

check = struct( ...
    "name", "", ...
    "pass", false, ...
    "value", NaN, ...
    "threshold", NaN, ...
    "message", "");

end
