function report = evaluateMultiSourceHarmonic3D(result, options)
%EVALUATEMULTISOURCEHARMONIC3D Validate a homogeneous multi-source 3D field.
%
% Acceptance checks:
%   - homogeneous truth medium
%   - resolved vibrator-bank source contract
%   - multiple distinct, non-overlapping contacts
%   - finite positive amplitudes and phases
%   - unit propagation and polarization vectors
%   - transverse source polarization
%   - normalized total source drive
%   - finite harmonic fields
%   - bounded global longitudinal-to-shear leakage
%
% The following directional quantities are retained only as descriptive
% metrics and do not determine pass/fail:
%   - apparent one-direction phase velocity
%   - directional fit R2
%   - cross-polarization ratios
%   - reflection-symmetry errors
%
% Temporal frequency cannot be independently verified from an extracted
% phasor when the original time series is not retained.
%
% DirectionalReport may be supplied to reuse a previously computed report
% or to construct isolated unit tests. Production calls normally omit it.

arguments
    result struct
    options.DirectionalReport struct = struct()
end

if ~isfield(result, "config_resolved")
    error( ...
        "kwsim:InvalidMultiSourceValidationInput", ...
        "The result must contain config_resolved.");
end

cfg = result.config_resolved;

if isempty(fieldnames(options.DirectionalReport))
    directional_report = ...
        kwsim.validation. ...
        evaluateDirectionalHarmonic3D(result);
else
    directional_report = ...
        options.DirectionalReport;
end

validateDirectionalReportContract( ...
    directional_report);

field_metrics = ...
    directional_report.metrics.field;

speed = ...
    directional_report.metrics.speed;

source = cfg.source;

required_source_fields = [
    "layout"
    "regime"
    "vibrator_count"
    "vibrators"
    "velocity_amplitude_m_s"
    "reference_single_contact_node_count"
];

for field_name = required_source_fields.'
    if ~isfield(source, char(field_name))
        error( ...
            "kwsim:InvalidResolvedVibratorBank", ...
            "Resolved source configuration is missing '%s'.", ...
            field_name);
    end
end

vibrators = ...
    source.vibrators;

number_of_vibrators = ...
    numel(vibrators);

if number_of_vibrators == 0
    error( ...
        "kwsim:InvalidResolvedVibratorBank", ...
        "Resolved source.vibrators is empty.");
end

required_vibrator_fields = [
    "node_linear_indices"
    "center_index_xyz"
    "polarization_xyz"
    "nominal_propagation_xyz"
    "phase_rad"
    "velocity_amplitude_m_s"
];

for vibrator_index = 1:number_of_vibrators
    for field_name = required_vibrator_fields.'
        if ~isfield( ...
                vibrators(vibrator_index), ...
                char(field_name))
            error( ...
                "kwsim:InvalidResolvedVibratorBank", ...
                "Vibrator %d is missing '%s'.", ...
                vibrator_index, ...
                field_name);
        end
    end
end

centers_index_xyz = ...
    vertcat(vibrators.center_index_xyz);

polarizations_xyz = ...
    double(vertcat(vibrators.polarization_xyz));

directions_xyz = ...
    double(vertcat( ...
        vibrators.nominal_propagation_xyz));

phases_rad = ...
    double([vibrators.phase_rad]).';

amplitudes_m_s = ...
    double([ ...
        vibrators.velocity_amplitude_m_s]).';

node_counts = ...
    zeros(number_of_vibrators, 1);

all_node_indices = ...
    zeros(0, 1);

for vibrator_index = 1:number_of_vibrators
    nodes = ...
        double( ...
            vibrators(vibrator_index). ...
            node_linear_indices(:));

    node_counts(vibrator_index) = ...
        numel(nodes);

    all_node_indices = [
        all_node_indices
        nodes
    ]; %#ok<AGROW>
end

unique_center_count = ...
    size(unique(centers_index_xyz, "rows"), 1);

unique_phase_count = ...
    numel(unique(phases_rad));

unique_node_count = ...
    numel(unique(all_node_indices));

total_node_count = ...
    numel(all_node_indices);

source_parameters_finite = ...
    all(isfinite(phases_rad)) && ...
    all(isfinite(amplitudes_m_s)) && ...
    all(amplitudes_m_s > 0) && ...
    all(node_counts > 0);

source_vectors_finite = ...
    all(isfinite(polarizations_xyz), "all") && ...
    all(isfinite(directions_xyz), "all");

polarization_norm_error = ...
    abs(vecnorm( ...
        polarizations_xyz, ...
        2, ...
        2) - 1);

direction_norm_error = ...
    abs(vecnorm( ...
        directions_xyz, ...
        2, ...
        2) - 1);

maximum_vector_norm_error = ...
    max([
        polarization_norm_error
        direction_norm_error
    ]);

transverse_dot_products = ...
    sum( ...
        polarizations_xyz .* ...
        directions_xyz, ...
        2);

maximum_transverse_error = ...
    max(abs(transverse_dot_products));

realized_total_drive_rms_squared = ...
    sum( ...
        node_counts .* ...
        amplitudes_m_s.^2 / 2);

expected_total_drive_rms_squared = ...
    double( ...
        source. ...
        reference_single_contact_node_count) * ...
    double(source.velocity_amplitude_m_s)^2 / 2;

total_drive_relative_error = ...
    abs( ...
        realized_total_drive_rms_squared - ...
        expected_total_drive_rms_squared) / ...
    max( ...
        abs(expected_total_drive_rms_squared), ...
        eps);

is_homogeneous = ...
    isfield(result, "truth") && ...
    isfield(result.truth, "homogeneous") && ...
    logical(result.truth.homogeneous);

layout_is_bank = ...
    lower(string(source.layout)) == ...
    "vibrator_bank";

multiple_vibrators_resolved = ...
    number_of_vibrators >= 2 && ...
    number_of_vibrators == ...
        double(source.vibrator_count);

centers_are_distinct = ...
    unique_center_count == ...
    number_of_vibrators;

contacts_do_not_overlap = ...
    unique_node_count == ...
    total_node_count;

phases_are_distinct = ...
    unique_phase_count >= 2;

unit_source_vectors = ...
    source_vectors_finite && ...
    maximum_vector_norm_error <= 1e-10;

transverse_source_vectors = ...
    source_vectors_finite && ...
    maximum_transverse_error <= 1e-10;

drive_is_normalized = ...
    isfinite(total_drive_relative_error) && ...
    total_drive_relative_error <= 1e-10;

finite_harmonic_fields = ...
    logical(field_metrics.finite_fields);

longitudinal_leakage_is_bounded = ...
    isfinite( ...
        field_metrics. ...
        longitudinal_leakage_ratio) && ...
    field_metrics.longitudinal_leakage_ratio <= ...
        cfg.diagnostics. ...
        maximum_longitudinal_leakage_ratio;

speed_relative_error = ...
    abs(speed.speed_m_s - cfg.medium.cs_m_s) / ...
    cfg.medium.cs_m_s;

checks = repmat( ...
    emptyCheck(), ...
    0, 1);

addCheck( ...
    "homogeneous_medium", ...
    is_homogeneous, ...
    double(is_homogeneous), ...
    1, ...
    "Multi-source benchmark validation requires homogeneous truth.");

addCheck( ...
    "vibrator_bank_layout", ...
    layout_is_bank, ...
    double(layout_is_bank), ...
    1, ...
    "Resolved source.layout must be vibrator_bank.");

addCheck( ...
    "multiple_vibrators_resolved", ...
    multiple_vibrators_resolved, ...
    number_of_vibrators, ...
    double(source.vibrator_count), ...
    "The resolved vibrator count must match the configuration.");

addCheck( ...
    "distinct_vibrator_centers", ...
    centers_are_distinct, ...
    unique_center_count, ...
    number_of_vibrators, ...
    "Every vibrator must have a distinct resolved center.");

addCheck( ...
    "nonoverlapping_contact_nodes", ...
    contacts_do_not_overlap, ...
    unique_node_count, ...
    total_node_count, ...
    "Vibrator contact-node sets must not overlap.");

addCheck( ...
    "finite_positive_source_parameters", ...
    source_parameters_finite, ...
    double(source_parameters_finite), ...
    1, ...
    "All source phases, amplitudes, and node counts must be valid.");

addCheck( ...
    "distinct_source_phases", ...
    phases_are_distinct, ...
    unique_phase_count, ...
    2, ...
    "A multi-source random-phase bank must contain distinct phases.");

addCheck( ...
    "unit_source_vectors", ...
    unit_source_vectors, ...
    maximum_vector_norm_error, ...
    1e-10, ...
    "Propagation and polarization vectors must have unit norm.");

addCheck( ...
    "transverse_source_polarizations", ...
    transverse_source_vectors, ...
    maximum_transverse_error, ...
    1e-10, ...
    "Each source polarization must be transverse to propagation.");

addCheck( ...
    "normalized_total_drive_rms", ...
    drive_is_normalized, ...
    total_drive_relative_error, ...
    1e-10, ...
    "Total vibrator-bank RMS drive must match the single-contact reference.");

addCheck( ...
    "finite_harmonic_fields", ...
    finite_harmonic_fields, ...
    double(finite_harmonic_fields), ...
    1, ...
    "All extracted harmonic P/S component volumes must be finite.");

addCheck( ...
    "global_longitudinal_leakage_ratio", ...
    longitudinal_leakage_is_bounded, ...
    field_metrics.longitudinal_leakage_ratio, ...
    cfg.diagnostics. ...
        maximum_longitudinal_leakage_ratio, ...
    "Global compressional energy must remain small relative to shear energy.");

report = struct();

report.scope = ...
    "homogeneous_multi_source_harmonic_3d";

report.validation_context = ...
    "physical_multi_source_validation";

report.directional_thresholds_applicable = ...
    false;

report.valid = ...
    all([checks.pass]);

report.checks = ...
    checks;

report.metrics = struct();

report.metrics.source = struct();

report.metrics.source.layout = ...
    string(source.layout);

report.metrics.source.regime = ...
    string(source.regime);

report.metrics.source.vibrator_count = ...
    number_of_vibrators;

report.metrics.source.unique_center_count = ...
    unique_center_count;

report.metrics.source.unique_phase_count = ...
    unique_phase_count;

report.metrics.source.contact_node_count = ...
    total_node_count;

report.metrics.source.maximum_vector_norm_error = ...
    maximum_vector_norm_error;

report.metrics.source.maximum_transverse_error = ...
    maximum_transverse_error;

report.metrics.source.realized_total_drive_rms_squared_m2_s2 = ...
    realized_total_drive_rms_squared;

report.metrics.source.expected_total_drive_rms_squared_m2_s2 = ...
    expected_total_drive_rms_squared;

report.metrics.source.total_drive_relative_error = ...
    total_drive_relative_error;

report.metrics.apparent_directional_speed = ...
    speed;

report.metrics.apparent_speed_relative_error = ...
    speed_relative_error;

report.metrics.field = ...
    field_metrics;

report.metrics.directional_reference_valid = ...
    logical(directional_report.valid);

report.frequency_evaluated = ...
    false;

report.frequency_reason = ...
    "Temporal frequency cannot be independently evaluated from " + ...
    "the extracted phasor when time-series data are not retained.";

report.req_validation_evaluated = ...
    false;

report.req_validation_reason = ...
    "REQ readiness and exported-sample integrity are assessed " + ...
    "separately by kwsim.req.assessValidationSample.";

report.summary = sprintf([ ...
    'multi-source valid=%d, vibrators=%d, unique phases=%d, ', ...
    'finite=%d, P/S leakage=%.4g, drive RMS error=%.3g, ', ...
    'apparent directional cs=%.5f m/s ', ...
    '(descriptive error %.3f%%), fit R2=%.6f, ', ...
    'cross global/core/axis=%.4g/%.4g/%.4g, ', ...
    'symmetry y/z best=%.4g/%.4g'], ...
    report.valid, ...
    number_of_vibrators, ...
    unique_phase_count, ...
    finite_harmonic_fields, ...
    field_metrics.longitudinal_leakage_ratio, ...
    total_drive_relative_error, ...
    speed.speed_m_s, ...
    100 * speed_relative_error, ...
    speed.r_squared, ...
    field_metrics.global_cross_polarization_ratio, ...
    field_metrics.core_cross_polarization_ratio, ...
    field_metrics.central_axis_cross_polarization_ratio, ...
    field_metrics.y_even_symmetry_error, ...
    field_metrics.z_even_symmetry_error);

if isfield(result, "preflight")
    report.preflight = ...
        result.preflight;
end

    function addCheck( ...
            name, pass, value, threshold, message)

        check = emptyCheck();

        check.name = string(name);
        check.pass = logical(pass);
        check.value = double(value);
        check.threshold = double(threshold);
        check.message = string(message);

        checks(end + 1, 1) = check;

    end

end


function validateDirectionalReportContract(report)

required_fields = [
    "valid"
    "metrics"
];

for field_name = required_fields.'
    if ~isfield(report, char(field_name))
        error( ...
            "kwsim:InvalidDirectionalReferenceReport", ...
            "Directional reference report is missing '%s'.", ...
            field_name);
    end
end

if ~isfield(report.metrics, "speed") || ...
        ~isfield(report.metrics, "field")
    error( ...
        "kwsim:InvalidDirectionalReferenceReport", ...
        "Directional reference report must contain speed and field metrics.");
end

end


function check = emptyCheck()

check = struct( ...
    "name", "", ...
    "pass", false, ...
    "value", NaN, ...
    "threshold", NaN, ...
    "message", "");

end
