function report = evaluateHeterogeneousHarmonic3D(result)
%EVALUATEHETEROGENEOUSHARMONIC3D Validate a heterogeneous 3D harmonic run.
%
% Acceptance checks focus on the software and physical-data contract:
%   - all six harmonic P/S components exist, agree in size, and are finite;
%   - nonzero shear energy is present;
%   - public truth maps exist, agree with the field size, and are physical;
%   - configured material IDs are present in the sensor ROI;
%   - the output is marked heterogeneous;
%   - the extracted field frequency matches the source frequency.
%
% Global directional speed, symmetry, and P/S leakage are not acceptance
% criteria because reflection, refraction, and mode conversion are expected
% at material interfaces.

arguments
    result struct
end

cfg = ...
    result.config_resolved;

checks = ...
    repmat( ...
        emptyCheck(), ...
        0, ...
        1);

component_names = [
    "x_shear_zyx"
    "y_shear_zyx"
    "z_shear_zyx"
    "x_compression_zyx"
    "y_compression_zyx"
    "z_compression_zyx"
];

component_energy = ...
    struct();

component_contract_present = ...
    isfield(result, "fields") && ...
    isfield(result.fields, "harmonic_velocity");

finite_harmonic_fields = ...
    component_contract_present;

consistent_field_sizes = ...
    component_contract_present;

field_size_zyx = ...
    [];

if component_contract_present
    velocity = ...
        result.fields.harmonic_velocity;

    for component_index = 1:numel(component_names)
        component_name = ...
            component_names(component_index);

        if ~isfield(velocity, component_name)
            component_contract_present = ...
                false;

            finite_harmonic_fields = ...
                false;

            consistent_field_sizes = ...
                false;

            component_energy.(component_name) = ...
                NaN;

            continue
        end

        values = ...
            velocity.(component_name);

        if isempty(field_size_zyx)
            field_size_zyx = ...
                size(values);
        elseif ~isequal(size(values), field_size_zyx)
            consistent_field_sizes = ...
                false;
        end

        finite_harmonic_fields = ...
            finite_harmonic_fields && ...
            all(isfinite(values), "all");

        component_energy.(component_name) = ...
            double(sum(abs(values).^2, "all"));
    end
else
    for component_index = 1:numel(component_names)
        component_energy.(component_names(component_index)) = ...
            NaN;
    end
end

if component_contract_present && ...
        consistent_field_sizes

    total_shear_energy = ...
        component_energy.x_shear_zyx + ...
        component_energy.y_shear_zyx + ...
        component_energy.z_shear_zyx;

    total_compression_energy = ...
        component_energy.x_compression_zyx + ...
        component_energy.y_compression_zyx + ...
        component_energy.z_compression_zyx;
else
    total_shear_energy = ...
        NaN;

    total_compression_energy = ...
        NaN;
end

nonzero_shear_energy = ...
    isfinite(total_shear_energy) && ...
    total_shear_energy > 0;

longitudinal_leakage_ratio = ...
    total_compression_energy / ...
    max(total_shear_energy, eps);

dominant_z_shear_fraction = ...
    component_energy.z_shear_zyx / ...
    max(total_shear_energy, eps);

%% Truth-map contract

truth_names = [
    "cp_m_s_zyx"
    "cs_m_s_zyx"
    "rho_kg_m3_zyx"
    "material_id_zyx"
];

truth_contract_present = ...
    isfield(result, "truth");

if truth_contract_present
    for truth_index = 1:numel(truth_names)
        truth_contract_present = ...
            truth_contract_present && ...
            isfield( ...
                result.truth, ...
                truth_names(truth_index));
    end
end

truth_sizes_match = ...
    false;

positive_finite_properties = ...
    false;

actual_material_ids = ...
    zeros(0, 1);

if truth_contract_present
    cp_zyx = ...
        result.truth.cp_m_s_zyx;

    cs_zyx = ...
        result.truth.cs_m_s_zyx;

    rho_zyx = ...
        result.truth.rho_kg_m3_zyx;

    material_id_zyx = ...
        result.truth.material_id_zyx;

    truth_sizes_match = ...
        ~isempty(field_size_zyx) && ...
        isequal(size(cp_zyx), field_size_zyx) && ...
        isequal(size(cs_zyx), field_size_zyx) && ...
        isequal(size(rho_zyx), field_size_zyx) && ...
        isequal(size(material_id_zyx), field_size_zyx);

    positive_finite_properties = ...
        all(isfinite(cp_zyx), "all") && ...
        all(isfinite(cs_zyx), "all") && ...
        all(isfinite(rho_zyx), "all") && ...
        all(cp_zyx > 0, "all") && ...
        all(cs_zyx > 0, "all") && ...
        all(rho_zyx > 0, "all") && ...
        all(material_id_zyx >= 1, "all");

    actual_material_ids = ...
        sort( ...
            unique( ...
                double(material_id_zyx(:))));
end

expected_material_ids = ...
    expectedMaterialIds(cfg);

material_ids_match = ...
    isequal( ...
        actual_material_ids(:), ...
        expected_material_ids(:));

is_heterogeneous = ...
    isfield(result, "truth") && ...
    isfield(result.truth, "homogeneous") && ...
    ~logical(result.truth.homogeneous) && ...
    numel(actual_material_ids) >= 2;

public_truth_orientation = ...
    isfield(result, "truth") && ...
    isfield(result.truth, "orientation") && ...
    string(result.truth.orientation) == "[Nz,Ny,Nx]";

frequency_relative_error = ...
    NaN;

frequency_contract_valid = ...
    isfield(result, "fields") && ...
    isfield(result.fields, "frequency_hz");

if frequency_contract_valid
    frequency_relative_error = ...
        abs( ...
            double(result.fields.frequency_hz) - ...
            double(cfg.source.f0_hz)) / ...
        double(cfg.source.f0_hz);

    frequency_contract_valid = ...
        isfinite(frequency_relative_error) && ...
        frequency_relative_error <= 1e-12;
end

%% Acceptance checks

addCheck( ...
    "heterogeneous_truth", ...
    is_heterogeneous, ...
    double(is_heterogeneous), ...
    1, ...
    "The run must contain at least two realized materials.");

addCheck( ...
    "harmonic_component_contract", ...
    component_contract_present && ...
        consistent_field_sizes, ...
    double( ...
        component_contract_present && ...
        consistent_field_sizes), ...
    1, ...
    "All six harmonic P/S volumes must exist and have the same dimensions.");

addCheck( ...
    "finite_harmonic_fields", ...
    finite_harmonic_fields, ...
    double(finite_harmonic_fields), ...
    1, ...
    "All harmonic component volumes must contain finite values.");

addCheck( ...
    "nonzero_shear_energy", ...
    nonzero_shear_energy, ...
    total_shear_energy, ...
    0, ...
    "The harmonic result must contain nonzero shear energy.");

addCheck( ...
    "truth_map_contract", ...
    truth_contract_present, ...
    double(truth_contract_present), ...
    1, ...
    "cp, cs, density, and material-ID truth maps must be present.");

addCheck( ...
    "truth_map_dimensions", ...
    truth_sizes_match, ...
    double(truth_sizes_match), ...
    1, ...
    "Truth maps must match the public harmonic-volume dimensions.");

addCheck( ...
    "positive_finite_material_properties", ...
    positive_finite_properties, ...
    double(positive_finite_properties), ...
    1, ...
    "All material-property voxels must be finite and positive.");

addCheck( ...
    "configured_material_ids_present", ...
    material_ids_match, ...
    double(material_ids_match), ...
    1, ...
    "The sensor ROI must contain exactly the configured material IDs.");

addCheck( ...
    "public_truth_orientation", ...
    public_truth_orientation, ...
    double(public_truth_orientation), ...
    1, ...
    "Public truth maps must use [Nz,Ny,Nx] orientation.");

addCheck( ...
    "harmonic_frequency_contract", ...
    frequency_contract_valid, ...
    frequency_relative_error, ...
    1e-12, ...
    "The packaged harmonic frequency must match source.f0_hz.");

%% Report

report = ...
    struct();

report.scope = ...
    "heterogeneous_harmonic_3d";

report.valid = ...
    all([checks.pass]);

report.checks = ...
    checks;

report.metrics = ...
    struct();

report.metrics.component_energy = ...
    component_energy;

report.metrics.total_shear_energy = ...
    total_shear_energy;

report.metrics.total_compression_energy = ...
    total_compression_energy;

report.metrics.longitudinal_leakage_ratio = ...
    longitudinal_leakage_ratio;

report.metrics.dominant_z_shear_fraction = ...
    dominant_z_shear_fraction;

report.metrics.expected_material_ids = ...
    expected_material_ids;

report.metrics.actual_material_ids = ...
    actual_material_ids;

report.metrics.frequency_relative_error = ...
    frequency_relative_error;

report.frequency_evaluated = ...
    false;

report.frequency_reason = ...
    ["The phasor package records the configured extraction frequency; " ...
     "independent temporal-frequency estimation requires retained time series."];

summary_format = [
    'heterogeneous valid=%d, materials expected/actual=%s/%s, ' ...
    'shear energy=%.6g, compression energy=%.6g, ' ...
    'P/S energy ratio=%.4g, z-shear fraction=%.4g'
];

report.summary = ...
    sprintf( ...
        summary_format, ...
        report.valid, ...
        mat2str(expected_material_ids.'), ...
        mat2str(actual_material_ids.'), ...
        total_shear_energy, ...
        total_compression_energy, ...
        longitudinal_leakage_ratio, ...
        dominant_z_shear_fraction);

if isfield(result, "preflight")
    report.preflight = ...
        result.preflight;
end

    function addCheck( ...
            name, ...
            pass, ...
            value, ...
            threshold, ...
            message)

        check = ...
            emptyCheck();

        check.name = ...
            string(name);

        check.pass = ...
            logical(pass);

        check.value = ...
            double(value);

        check.threshold = ...
            double(threshold);

        check.message = ...
            string(message);

        checks(end + 1, 1) = ...
            check;
    end

end


function material_ids = expectedMaterialIds(cfg)

if cfg.geometry.bilayer.enabled
    material_ids = [
        double( ...
            cfg.geometry.bilayer. ...
            negative_material.material_id)
        double( ...
            cfg.geometry.bilayer. ...
            positive_material.material_id)
    ];
else
    material_ids = ...
        double( ...
            cfg.geometry.background_material_id);
end

if ~isempty(cfg.geometry.objects)
    material_ids = [
        material_ids(:)
        double([cfg.geometry.objects.material_id]).'
    ];
end

material_ids = ...
    sort( ...
        unique(material_ids));

end


function check = emptyCheck()

check = ...
    struct( ...
        "name", "", ...
        "pass", false, ...
        "value", NaN, ...
        "threshold", NaN, ...
        "message", "");

end
