function tests = test_partial_diffuse_3d_configured_smoke
%TEST_PARTIAL_DIFFUSE_3D_CONFIGURED_SMOKE
% End-to-end physical smoke test for the partial-diffuse 3D source bank.

tests = functiontests(localfunctions);

end


function setupOnce(testCase)

repository_root = string(fileparts(fileparts(fileparts( ...
    mfilename("fullpath")))));

addpath(fullfile(repository_root, "src"));

kwave_root = string(getenv("KWSIM_KWAVE_PATH"));

if strlength(kwave_root) == 0
    kwave_root = fullfile( ...
        repository_root, ...
        "k-wave-toolbox-version-1.4.1");
end

assumeTrue( ...
    testCase, ...
    isfolder(kwave_root), ...
    "The local k-Wave toolbox is not available.");

solver_file = fullfile( ...
    kwave_root, ...
    "pstdElastic3D.m");

assumeTrue( ...
    testCase, ...
    isfile(solver_file), ...
    "pstdElastic3D.m was not found in the k-Wave toolbox.");

toolbox_path = genpath(char(kwave_root));
addpath(toolbox_path);

testCase.TestData.repository_root = ...
    repository_root;

testCase.TestData.kwave_root = ...
    kwave_root;

testCase.TestData.toolbox_path = ...
    toolbox_path;

end


function teardownOnce(testCase)

if isfield(testCase.TestData, "toolbox_path")
    rmpath(testCase.TestData.toolbox_path);
end

end


function testConfiguredPartialDiffuseReqPipeline(testCase)

repository_root = ...
    testCase.TestData.repository_root;

canonical_config = fullfile( ...
    repository_root, ...
    "configs", ...
    "three_d", ...
    "homogeneous_partial_diffuse8_req_validation.json");

requested_cfg = jsondecode( ...
    fileread(canonical_config));

% Use the local toolbox explicitly.
requested_cfg.solver.kwave_path = ...
    char(testCase.TestData.kwave_root);

% Exercise REQ construction without writing a persistent run directory.
requested_cfg.output.enabled = false;
requested_cfg.output.save_result = false;
requested_cfg.output.save_summary = false;
requested_cfg.output.save_config_mat = false;
requested_cfg.output.save_config_json = false;
requested_cfg.output.save_time_series = false;
requested_cfg.output.save_req_validation_sample = true;
requested_cfg.output.save_figures = false;
requested_cfg.output.save_matlab_figures = false;

requested_cfg.diagnostics.fail_on_invalid = ...
    true;

temporary_config = ...
    string(tempname) + ".json";

cleanup = onCleanup( ...
    @() deleteIfPresent(temporary_config));

writeJson( ...
    temporary_config, ...
    requested_cfg);

outcome = ...
    kwsim.cli.runConfig(temporary_config);

verifyEqual( ...
    testCase, ...
    outcome.status, ...
    "completed_valid");

verifyTrue( ...
    testCase, ...
    outcome.report.valid, ...
    outcome.report.summary);

verifyTrue( ...
    testCase, ...
    outcome.report.physical_valid);

verifyEqual( ...
    testCase, ...
    outcome.report.scope, ...
    "homogeneous_multi_source_harmonic_3d");

verifyTrue( ...
    testCase, ...
    outcome.report.req_validation_evaluated);

verifyTrue( ...
    testCase, ...
    outcome.req_readiness.valid, ...
    outcome.req_readiness.summary);

verifyTrue( ...
    testCase, ...
    outcome.req_validation_sample.req_readiness.valid);

source = ...
    outcome.result.config_resolved.source;

verifyEqual( ...
    testCase, ...
    string(source.layout), ...
    "vibrator_bank");

verifyEqual( ...
    testCase, ...
    double(source.vibrator_count), ...
    8);

verifyEqual( ...
    testCase, ...
    numel(source.vibrators), ...
    8);

phases_rad = ...
    double([source.vibrators.phase_rad]);

verifyEqual( ...
    testCase, ...
    numel(unique(phases_rad)), ...
    8);

verifyLessThanOrEqual( ...
    testCase, ...
    outcome.report.metrics.source.total_drive_relative_error, ...
    1e-10);

sample = ...
    outcome.req_validation_sample;

verifyTrue( ...
    testCase, ...
    isfield(sample, ...
        "wavefield_complex_zx"));

verifySize( ...
    testCase, ...
    sample.wavefield_complex_zx, ...
    [ ...
        numel(sample.axes.z_m), ...
        numel(sample.axes.x_m) ...
    ]);

verifyTrue( ...
    testCase, ...
    all(isfinite( ...
        sample.wavefield_complex_zx), ...
        "all"));

verifyGreaterThan( ...
    testCase, ...
    sum(abs( ...
        sample.wavefield_complex_zx).^2, ...
        "all"), ...
    0);

verifyGreaterThanOrEqual( ...
    testCase, ...
    outcome.req_readiness.placements_x, ...
    outcome.req_readiness.parameters.minimum_placements_per_axis);

verifyGreaterThanOrEqual( ...
    testCase, ...
    outcome.req_readiness.placements_z, ...
    outcome.req_readiness.parameters.minimum_placements_per_axis);

check_names = ...
    string([outcome.report.checks.name]);

verifyTrue( ...
    testCase, ...
    any(check_names == ...
        "req_validation_sample_ready"));

verifyTrue( ...
    testCase, ...
    contains( ...
        string(outcome.report.summary), ...
        "REQ-ready=1"));

% Output saving was intentionally disabled.
verifyEqual( ...
    testCase, ...
    outcome.req_validation_sample_path, ...
    "");

verifyTrue( ...
    testCase, ...
    isempty(fieldnames(outcome.paths)));

clear cleanup

end


function writeJson(path_value, value)

[file_id, message] = fopen( ...
    path_value, ...
    "w");

if file_id < 0
    error( ...
        "Test:CannotCreateTemporaryConfig", ...
        "Could not create temporary JSON: %s", ...
        message);
end

cleanup = onCleanup( ...
    @() fclose(file_id));

encoded = jsonencode( ...
    value, ...
    PrettyPrint=true);

fprintf( ...
    file_id, ...
    "%s\n", ...
    encoded);

clear cleanup

end


function deleteIfPresent(path_value)

if isfile(path_value)
    delete(path_value);
end

end
