%% Projected-3D patch-spectrum diagnostic
%
% Directly compares:
%   1. Full-field axial realization spectrum
%   2. Central-patch axial realization spectrum
%   3. Central-patch scalar realization spectrum
%   4. Patch axial ensemble conditioned on sampled polarizations
%   5. Patch theoretical axial ensemble averaged over polarization
%
% Spectra are displayed in linear normalized power with coordinates k/k0.

clear;
close all;

scriptDirectory = fileparts(mfilename("fullpath"));
repositoryRoot = fileparts(fileparts(scriptDirectory));

addpath(fullfile(repositoryRoot, "src"));

outputDirectory = fullfile( ...
    repositoryRoot, ...
    "outputs", ...
    "diagnostics", ...
    "projected3d_patch_spectrum");

if ~isfolder(outputDirectory)
    mkdir(outputDirectory);
end

%% Configuration

directionCount = 128;
patchSizePixels = 64;

domainLengthXM = 0.050;
domainLengthZM = 0.050;

dxM = 0.00025;
dzM = 0.00025;

frequencyHz = 250;
csMps = 2.0;

omegaRadS = 2*pi*frequencyHz;
referenceWavenumberRadM = omegaRadS / csMps;

cfg = swsynth.defaultConfig();

cfg.seed = 7401;

cfg.domain.Lx_m = domainLengthXM;
cfg.domain.Lz_m = domainLengthZM;
cfg.domain.dx_m = dxM;
cfg.domain.dz_m = dzM;

cfg.medium.background_cs_m_s = csMps;
cfg.medium.objects = {};

cfg.wavefield.frequency_hz = frequencyHz;

cfg.directions.count = directionCount;
cfg.directions.space = "three_dimensional";
cfg.directions.sampling_method = "fibonacci";
cfg.directions.require_in_plane = false;
cfg.directions.support.type = "full_sphere";

cfg.execution.use_parallel = false;

[cfg, ~] = swsynth.validateConfig(cfg);

maps = swsynth.buildMediumMaps(cfg);
directions = swsynth.generateDirections(cfg);

xM = maps.x_m;
zM = maps.z_m;

directionsXYZ = double([
    directions.ux(:), ...
    directions.uy(:), ...
    directions.uz(:)]);

Nz = numel(zM);
Nx = numel(xM);

if patchSizePixels > min(Nz, Nx)
    error( ...
        "swsynth:DiagnosticPatchTooLarge", ...
        "patchSizePixels exceeds the available field dimensions.");
end

%% Central patch

patchStartX = floor((Nx - patchSizePixels)/2) + 1;
patchStartZ = floor((Nz - patchSizePixels)/2) + 1;

patchIndicesX = ...
    patchStartX:(patchStartX + patchSizePixels - 1);

patchIndicesZ = ...
    patchStartZ:(patchStartZ + patchSizePixels - 1);

xPatchM = xM(patchIndicesX);
zPatchM = zM(patchIndicesZ);

patchLengthXM = ...
    (patchSizePixels - 1) * dxM;

patchLengthZM = ...
    (patchSizePixels - 1) * dzM;

%% Random phases and sampled shear polarizations

rng(8401);

initialPhaseRad = ...
    2*pi*rand(directionCount, 1);

scalarWeights = ...
    exp(1i .* initialPhaseRad) ./ ...
    sqrt(directionCount);

rng(8402);

[polarizationXYZ, polarizationDiagnostics] = ...
    swsynth.propagation.projected3d. ...
        sampleTransversePolarization( ...
            directionsXYZ);

sampledAxialPower = ...
    polarizationXYZ(:, 3).^2;

expectedAxialPower = ...
    (1 - directionsXYZ(:, 3).^2) ./ 2;

axialWeights = ...
    polarizationXYZ(:, 3) .* ...
    exp(1i .* initialPhaseRad) ./ ...
    sqrt(directionCount);

fieldOptions = struct();
fieldOptions.UseParallel = false;

%% Full-field realizations

scalarFieldZX = ...
    swsynth.propagation.projected3d. ...
        synthesizeDirectionalField( ...
            maps.cs_map_zx, ...
            xM, ...
            zM, ...
            directionsXYZ, ...
            scalarWeights, ...
            frequencyHz, ...
            csMps, ...
            fieldOptions);

axialFieldZX = ...
    swsynth.propagation.projected3d. ...
        synthesizeDirectionalField( ...
            maps.cs_map_zx, ...
            xM, ...
            zM, ...
            directionsXYZ, ...
            axialWeights, ...
            frequencyHz, ...
            csMps, ...
            fieldOptions);

scalarPatchZX = ...
    scalarFieldZX(patchIndicesZ, patchIndicesX);

axialPatchZX = ...
    axialFieldZX(patchIndicesZ, patchIndicesX);

%% Windows

fullWindowX = hannVector(Nx);
fullWindowZ = hannVector(Nz);

fullWindowZX = ...
    fullWindowZ(:) * fullWindowX(:).';

patchWindowX = hannVector(patchSizePixels);
patchWindowZ = hannVector(patchSizePixels);

patchWindowZX = ...
    patchWindowZ(:) * patchWindowX(:).';

%% FFT grids

fullFftSizeX = 4 * 2^nextpow2(Nx);
fullFftSizeZ = 4 * 2^nextpow2(Nz);

patchFftSizeX = 4 * 2^nextpow2(patchSizePixels);
patchFftSizeZ = 4 * 2^nextpow2(patchSizePixels);

fullKxRadM = fftAxis(fullFftSizeX, dxM);
fullKzRadM = fftAxis(fullFftSizeZ, dzM);

patchKxRadM = fftAxis(patchFftSizeX, dxM);
patchKzRadM = fftAxis(patchFftSizeZ, dzM);

fullNormalizedKx = ...
    fullKxRadM ./ referenceWavenumberRadM;

fullNormalizedKz = ...
    fullKzRadM ./ referenceWavenumberRadM;

patchNormalizedKx = ...
    patchKxRadM ./ referenceWavenumberRadM;

patchNormalizedKz = ...
    patchKzRadM ./ referenceWavenumberRadM;

%% Single-realization spectra

fullAxialSpectrum = fftshift(fft2( ...
    axialFieldZX .* fullWindowZX, ...
    fullFftSizeZ, ...
    fullFftSizeX));

fullAxialPower = ...
    abs(fullAxialSpectrum).^2;

patchAxialSpectrum = fftshift(fft2( ...
    axialPatchZX .* patchWindowZX, ...
    patchFftSizeZ, ...
    patchFftSizeX));

patchAxialPower = ...
    abs(patchAxialSpectrum).^2;

patchScalarSpectrum = fftshift(fft2( ...
    scalarPatchZX .* patchWindowZX, ...
    patchFftSizeZ, ...
    patchFftSizeX));

patchScalarPower = ...
    abs(patchScalarSpectrum).^2;

%% Exact patch ensemble spectra

patchScalarEnsemblePower = ...
    zeros(patchFftSizeZ, patchFftSizeX);

patchAxialConditionalPower = ...
    zeros(patchFftSizeZ, patchFftSizeX);

patchAxialTheoreticalPower = ...
    zeros(patchFftSizeZ, patchFftSizeX);

timerHandle = tic;

for directionIndex = 1:directionCount

    phaseDelayZX = ...
        swsynth.propagation.projected3d. ...
            computeDirectionalPhaseDelay( ...
                maps.cs_map_zx, ...
                xM, ...
                zM, ...
                directionsXYZ(directionIndex, :), ...
                csMps);

    directionalPatchZX = exp( ...
        1i .* omegaRadS .* ...
        phaseDelayZX(patchIndicesZ, patchIndicesX));

    directionalPatchSpectrum = fftshift(fft2( ...
        directionalPatchZX .* patchWindowZX, ...
        patchFftSizeZ, ...
        patchFftSizeX));

    directionalPatchPower = ...
        abs(directionalPatchSpectrum).^2;

    patchScalarEnsemblePower = ...
        patchScalarEnsemblePower + ...
        directionalPatchPower ./ directionCount;

    patchAxialConditionalPower = ...
        patchAxialConditionalPower + ...
        sampledAxialPower(directionIndex) .* ...
        directionalPatchPower ./ directionCount;

    patchAxialTheoreticalPower = ...
        patchAxialTheoreticalPower + ...
        expectedAxialPower(directionIndex) .* ...
        directionalPatchPower ./ directionCount;
end

ensembleRuntimeS = toc(timerHandle);

%% Normalize maps for visualization

fullAxialPowerNormalized = ...
    fullAxialPower ./ max(fullAxialPower(:));

patchAxialPowerNormalized = ...
    patchAxialPower ./ max(patchAxialPower(:));

patchScalarPowerNormalized = ...
    patchScalarPower ./ max(patchScalarPower(:));

patchAxialConditionalNormalized = ...
    patchAxialConditionalPower ./ ...
    max(patchAxialConditionalPower(:));

patchAxialTheoreticalNormalized = ...
    patchAxialTheoreticalPower ./ ...
    max(patchAxialTheoreticalPower(:));

%% Quantitative comparisons

conditionalToScalarTotalPowerRatio = ...
    sum(patchAxialConditionalPower(:)) ./ ...
    sum(patchScalarEnsemblePower(:));

theoreticalToScalarTotalPowerRatio = ...
    sum(patchAxialTheoreticalPower(:)) ./ ...
    sum(patchScalarEnsemblePower(:));

expectedSampledAxialPowerRatio = ...
    mean(sampledAxialPower);

expectedTheoreticalAxialPowerRatio = ...
    mean(expectedAxialPower);

conditionalTheoryRelativeDifference = ...
    norm( ...
        patchAxialConditionalNormalized(:) - ...
        patchAxialTheoreticalNormalized(:)) ./ ...
    norm(patchAxialTheoreticalNormalized(:));

%% Figure

figureHandle = figure( ...
    "Visible", "off", ...
    "Color", "w", ...
    "Position", [50, 50, 1500, 1020]);

tiledlayout( ...
    2, ...
    3, ...
    "TileSpacing", "compact", ...
    "Padding", "compact");

spectralLimit = 1.35;
circleAngle = linspace(0, 2*pi, 361);

nexttile;

imagesc( ...
    xPatchM*1e3, ...
    zPatchM*1e3, ...
    real(axialPatchZX));

axis image;
set(gca, "YDir", "normal");
colorbar;

xlabel("x (mm)");
ylabel("z (mm)");

title(sprintf( ...
    "Axial patch: Real(U_z), %d x %d", ...
    patchSizePixels, ...
    patchSizePixels));

nexttile;

plotSpectrum( ...
    fullNormalizedKx, ...
    fullNormalizedKz, ...
    fullAxialPowerNormalized, ...
    spectralLimit, ...
    circleAngle, ...
    "Full-field axial spectrum");

nexttile;

plotSpectrum( ...
    patchNormalizedKx, ...
    patchNormalizedKz, ...
    patchAxialPowerNormalized, ...
    spectralLimit, ...
    circleAngle, ...
    "Patch axial spectrum");

nexttile;

plotSpectrum( ...
    patchNormalizedKx, ...
    patchNormalizedKz, ...
    patchScalarPowerNormalized, ...
    spectralLimit, ...
    circleAngle, ...
    "Patch scalar spectrum");

nexttile;

plotSpectrum( ...
    patchNormalizedKx, ...
    patchNormalizedKz, ...
    patchAxialConditionalNormalized, ...
    spectralLimit, ...
    circleAngle, ...
    "Patch axial ensemble: sampled p_z");

nexttile;

plotSpectrum( ...
    patchNormalizedKx, ...
    patchNormalizedKz, ...
    patchAxialTheoreticalNormalized, ...
    spectralLimit, ...
    circleAngle, ...
    "Patch axial ensemble: E[p_z^2|u]");

sgtitle(sprintf( ...
    ["Projected-3D patch spectrum | N=%d | " + ...
     "patch=%.2f x %.2f mm | f=%g Hz"], ...
    directionCount, ...
    patchLengthXM*1e3, ...
    patchLengthZM*1e3, ...
    frequencyHz));

figurePath = fullfile( ...
    outputDirectory, ...
    "projected3d_patch_spectrum.png");

exportgraphics( ...
    figureHandle, ...
    figurePath, ...
    "Resolution", 180);

close(figureHandle);

%% Summary

summaryTable = table( ...
    directionCount, ...
    patchSizePixels, ...
    patchLengthXM, ...
    patchLengthZM, ...
    frequencyHz, ...
    csMps, ...
    ensembleRuntimeS, ...
    conditionalToScalarTotalPowerRatio, ...
    theoreticalToScalarTotalPowerRatio, ...
    expectedSampledAxialPowerRatio, ...
    expectedTheoreticalAxialPowerRatio, ...
    conditionalTheoryRelativeDifference, ...
    polarizationDiagnostics.maximum_orthogonality_error, ...
    VariableNames=[ ...
        "direction_count", ...
        "patch_size_pixels", ...
        "patch_length_x_m", ...
        "patch_length_z_m", ...
        "frequency_hz", ...
        "cs_m_s", ...
        "ensemble_runtime_s", ...
        "conditional_to_scalar_total_power_ratio", ...
        "theoretical_to_scalar_total_power_ratio", ...
        "expected_sampled_axial_power_ratio", ...
        "expected_theoretical_axial_power_ratio", ...
        "conditional_theory_relative_difference", ...
        "maximum_polarization_orthogonality_error"]);

summaryPath = fullfile( ...
    outputDirectory, ...
    "summary.csv");

writetable(summaryTable, summaryPath);

disp(summaryTable);

fprintf("\nPatch size                     : %d x %d pixels\n", ...
    patchSizePixels, ...
    patchSizePixels);

fprintf("Patch physical size            : %.3f x %.3f mm\n", ...
    patchLengthXM*1e3, ...
    patchLengthZM*1e3);

fprintf("Conditional axial/scalar power : %.5f\n", ...
    conditionalToScalarTotalPowerRatio);

fprintf("Theory axial/scalar power      : %.5f\n", ...
    theoreticalToScalarTotalPowerRatio);

fprintf("Expected sampled <p_z^2>       : %.5f\n", ...
    expectedSampledAxialPowerRatio);

fprintf("Expected theoretical <p_z^2>   : %.5f\n", ...
    expectedTheoreticalAxialPowerRatio);

fprintf("Conditional/theory difference  : %.5f\n", ...
    conditionalTheoryRelativeDifference);

fprintf("Ensemble runtime               : %.3f s\n", ...
    ensembleRuntimeS);

fprintf("Saved figure: %s\n", figurePath);
fprintf("Saved summary: %s\n", summaryPath);

%% Local functions

function vector = hannVector(sampleCount)

if sampleCount == 1
    vector = 1;
    return;
end

index = 0:(sampleCount - 1);

vector = ...
    0.5 - ...
    0.5*cos(2*pi*index/(sampleCount - 1));

end

function axisRadM = fftAxis(fftSize, spacingM)

axisRadM = ...
    2*pi .* ...
    ((-floor(fftSize/2)):(ceil(fftSize/2)-1)) ./ ...
    (fftSize * spacingM);

end

function plotSpectrum( ...
    normalizedKx, ...
    normalizedKz, ...
    normalizedPower, ...
    spectralLimit, ...
    circleAngle, ...
    plotTitle)

imagesc( ...
    normalizedKx, ...
    normalizedKz, ...
    normalizedPower);

axis image;
set(gca, "YDir", "normal");

xlim([-spectralLimit, spectralLimit]);
ylim([-spectralLimit, spectralLimit]);

clim([0, 1]);

colorbar;

hold on;

plot( ...
    cos(circleAngle), ...
    sin(circleAngle), ...
    "w--", ...
    "LineWidth", 1.5);

hold off;

xlabel("k_x / k_0");
ylabel("k_z / k_0");
title(plotTitle);

end
