%% Projected-3D homogeneous disk-formation diagnostic
%
% Compares N = 1, 8, 32, and 128 directions sampled over the full sphere.
% Each 3D direction produces one projected x-z wavevector:
%
%   k_xz = k0 [ux, uz].
%
% As the number of directions increases, the spectral samples should fill
% the interior of the projected disk bounded by |k_xz| <= k0.

clear;
close all;

scriptDirectory = fileparts(mfilename("fullpath"));
repositoryRoot = fileparts(fileparts(scriptDirectory));

addpath(fullfile(repositoryRoot, "src"));

outputDirectory = fullfile( ...
    repositoryRoot, ...
    "outputs", ...
    "diagnostics", ...
    "projected3d_eikonal_disk_formation");

if ~isfolder(outputDirectory)
    mkdir(outputDirectory);
end

%% Shared physical configuration

directionCounts = [1, 8, 32, 128];

domainLengthXM = 0.050;
domainLengthZM = 0.050;

dxM = 0.00025;
dzM = 0.00025;

frequencyHz = 250;
csMps = 2.0;

omegaRadS = 2*pi*frequencyHz;
referenceWavenumberRadM = omegaRadS / csMps;

cfgBase = swsynth.defaultConfig();

cfgBase.seed = 7001;

cfgBase.domain.Lx_m = domainLengthXM;
cfgBase.domain.Lz_m = domainLengthZM;
cfgBase.domain.dx_m = dxM;
cfgBase.domain.dz_m = dzM;

cfgBase.medium.background_cs_m_s = csMps;
cfgBase.medium.objects = {};

cfgBase.wavefield.frequency_hz = frequencyHz;

cfgBase.directions.space = "three_dimensional";
cfgBase.directions.sampling_method = "fibonacci";
cfgBase.directions.require_in_plane = false;
cfgBase.directions.support.type = "full_sphere";

cfgBase.execution.use_parallel = false;

[cfgBase, ~] = swsynth.validateConfig(cfgBase);

maps = swsynth.buildMediumMaps(cfgBase);

xM = maps.x_m;
zM = maps.z_m;

Nx = numel(xM);
Nz = numel(zM);

%% Spectral window and zero padding

windowX = ...
    0.5 - 0.5*cos(2*pi*(0:Nx-1)/(Nx-1));

windowZ = ...
    0.5 - 0.5*cos(2*pi*(0:Nz-1)/(Nz-1));

windowZX = windowZ(:) * windowX(:).';

fftSizeX = 4 * 2^nextpow2(Nx);
fftSizeZ = 4 * 2^nextpow2(Nz);

kxRadM = ...
    2*pi .* ((-floor(fftSizeX/2)):(ceil(fftSizeX/2)-1)) ./ ...
    (fftSizeX * dxM);

kzRadM = ...
    2*pi .* ((-floor(fftSizeZ/2)):(ceil(fftSizeZ/2)-1)) ./ ...
    (fftSizeZ * dzM);

spectralAngle = linspace(0, 2*pi, 361);

spectralDisplayLimitRadMm = ...
    1.15 * referenceWavenumberRadM / 1e3;

%% Storage

runtimeS = zeros(numel(directionCounts), 1);
meanProjectedNorm = zeros(numel(directionCounts), 1);
minimumProjectedNorm = zeros(numel(directionCounts), 1);
maximumProjectedNorm = zeros(numel(directionCounts), 1);
outOfPlaneFraction = zeros(numel(directionCounts), 1);
allHomogeneousExact = false(numel(directionCounts), 1);

figureHandle = figure( ...
    "Visible", "off", ...
    "Color", "w", ...
    "Position", [50, 50, 1350, 1750]);

tiledlayout( ...
    numel(directionCounts), ...
    2, ...
    "TileSpacing", "compact", ...
    "Padding", "compact");

%% Simulate each direction count

for countIndex = 1:numel(directionCounts)

    directionCount = directionCounts(countIndex);

    cfg = cfgBase;
    cfg.directions.count = directionCount;

    [cfg, ~] = swsynth.validateConfig(cfg);

    directions = swsynth.generateDirections(cfg);

    directionsXYZ = double([
        directions.ux(:), ...
        directions.uy(:), ...
        directions.uz(:)]);

    % Deterministic random initial phases.
    rng(9000 + directionCount);

    initialPhaseRad = ...
        2*pi*rand(directionCount, 1);

    weights = ...
        exp(1i .* initialPhaseRad) ./ ...
        sqrt(directionCount);

    options = struct();
    options.UseParallel = false;

    timerHandle = tic;

    [fieldZX, diagnostics] = ...
        swsynth.propagation.projected3d. ...
            synthesizeDirectionalField( ...
                maps.cs_map_zx, ...
                xM, ...
                zM, ...
                directionsXYZ, ...
                weights, ...
                frequencyHz, ...
                csMps, ...
                options);

    runtimeS(countIndex) = toc(timerHandle);

    projectedNorm = hypot( ...
        directionsXYZ(:, 1), ...
        directionsXYZ(:, 3));

    meanProjectedNorm(countIndex) = ...
        mean(projectedNorm);

    minimumProjectedNorm(countIndex) = ...
        min(projectedNorm);

    maximumProjectedNorm(countIndex) = ...
        max(projectedNorm);

    outOfPlaneFraction(countIndex) = ...
        mean(abs(directionsXYZ(:, 2)) > 1e-6);

    allHomogeneousExact(countIndex) = ...
        all( ...
            diagnostics.solver_methods == "homogeneous_exact" | ...
            diagnostics.solver_methods == "pure_out_of_plane_exact");

    %% Spectrum

    windowedFieldZX = fieldZX .* windowZX;

    powerSpectrumZX = abs( ...
        fftshift( ...
            fft2( ...
                windowedFieldZX, ...
                fftSizeZ, ...
                fftSizeX))).^2;

    normalizedPowerZX = ...
        powerSpectrumZX ./ ...
        max(powerSpectrumZX(:));

    powerDbZX = ...
        10*log10(normalizedPowerZX + eps);

    expectedKxRadM = ...
        referenceWavenumberRadM .* ...
        directionsXYZ(:, 1);

    expectedKzRadM = ...
        referenceWavenumberRadM .* ...
        directionsXYZ(:, 3);

    %% Spatial field

    nexttile;

    imagesc( ...
        xM*1e3, ...
        zM*1e3, ...
        real(fieldZX));

    axis image;
    set(gca, "YDir", "normal");
    colorbar;

    xlabel("x (mm)");
    ylabel("z (mm)");

    title(sprintf( ...
        "Real(U), N = %d", ...
        directionCount));

    %% Power spectrum

    nexttile;

    imagesc( ...
        kxRadM/1e3, ...
        kzRadM/1e3, ...
        powerDbZX);

    axis image;
    set(gca, "YDir", "normal");

    clim([-50, 0]);

    xlim([
        -spectralDisplayLimitRadMm, ...
         spectralDisplayLimitRadMm]);

    ylim([
        -spectralDisplayLimitRadMm, ...
         spectralDisplayLimitRadMm]);

    colorbar;

    hold on;

    plot( ...
        referenceWavenumberRadM .* ...
            cos(spectralAngle) ./ 1e3, ...
        referenceWavenumberRadM .* ...
            sin(spectralAngle) ./ 1e3, ...
        "--", ...
        "LineWidth", 1);

    scatter( ...
        expectedKxRadM/1e3, ...
        expectedKzRadM/1e3, ...
        22, ...
        "o", ...
        "LineWidth", 1);

    hold off;

    xlabel("k_x (rad/mm)");
    ylabel("k_z (rad/mm)");

    title(sprintf( ...
        "Projected spectrum, N = %d", ...
        directionCount));

    legend( ...
        "Reference k_0", ...
        "Expected projected directions", ...
        "Location", "southoutside");
end

sgtitle(sprintf( ...
    ["Homogeneous projected-3D disk formation | " + ...
     "f = %g Hz | c_s = %.1f m/s"], ...
    frequencyHz, ...
    csMps));

figurePath = fullfile( ...
    outputDirectory, ...
    "projected3d_disk_formation.png");

exportgraphics( ...
    figureHandle, ...
    figurePath, ...
    "Resolution", 180);

close(figureHandle);

%% Save numerical summary

summaryTable = table( ...
    directionCounts(:), ...
    runtimeS, ...
    meanProjectedNorm, ...
    minimumProjectedNorm, ...
    maximumProjectedNorm, ...
    outOfPlaneFraction, ...
    allHomogeneousExact, ...
    VariableNames=[ ...
        "direction_count", ...
        "runtime_s", ...
        "mean_projected_direction_norm", ...
        "minimum_projected_direction_norm", ...
        "maximum_projected_direction_norm", ...
        "out_of_plane_fraction", ...
        "all_homogeneous_exact"]);

summaryPath = fullfile( ...
    outputDirectory, ...
    "summary.csv");

writetable(summaryTable, summaryPath);

disp(summaryTable);

fprintf("\nReference k0: %.6f rad/m\n", ...
    referenceWavenumberRadM);

fprintf("Saved figure: %s\n", figurePath);
fprintf("Saved summary: %s\n", summaryPath);
