%% Compare homogeneous projected-3D Eikonal and plane-wave propagation

clear;
close all;

scriptDirectory = fileparts(mfilename("fullpath"));
repositoryRoot = fileparts(fileparts(scriptDirectory));
addpath(fullfile(repositoryRoot, "src"));

configDirectory = fullfile( ...
    repositoryRoot, ...
    "configs", ...
    "swsynth", ...
    "validation", ...
    "homogeneous_eikonal_vs_plane_wave");

outputDirectory = fullfile( ...
    repositoryRoot, ...
    "outputs", ...
    "diagnostics", ...
    "homogeneous_eikonal_vs_plane_wave");

if ~isfolder(outputDirectory)
    mkdir(outputDirectory);
end

singleEikonal = runJson(fullfile( ...
    configDirectory, "single_eikonal.json"));

singlePlane = runJson(fullfile( ...
    configDirectory, "single_plane_wave.json"));

diffuseEikonal = runJson(fullfile( ...
    configDirectory, "diffuse32_eikonal.json"));

diffusePlane = runJson(fullfile( ...
    configDirectory, "diffuse32_plane_wave.json"));

xM = singleEikonal.medium.x_m;
zM = singleEikonal.medium.z_m;

dxM = mean(diff(xM));
dzM = mean(diff(zM));

frequencyHz = singleEikonal.wavefield.frequency_hz;
csMps = singleEikonal.config.medium.background_cs_m_s;
expectedKRadM = 2*pi*frequencyHz/csMps;

%% Direct field comparison after complex scaling

[singlePlaneAlignedZX, singleComplexScale] = ...
    alignComplexField( ...
        singleEikonal.wavefield.U_zx, ...
        singlePlane.wavefield.U_zx);

singleRelativeError = ...
    relativeComplexError( ...
        singleEikonal.wavefield.U_zx, ...
        singlePlaneAlignedZX);

singleCorrelation = ...
    complexCorrelation( ...
        singleEikonal.wavefield.U_zx, ...
        singlePlaneAlignedZX);

[diffusePlaneAlignedZX, diffuseComplexScale] = ...
    alignComplexField( ...
        diffuseEikonal.wavefield.U_zx, ...
        diffusePlane.wavefield.U_zx);

diffuseRelativeError = ...
    relativeComplexError( ...
        diffuseEikonal.wavefield.U_zx, ...
        diffusePlaneAlignedZX);

diffuseCorrelation = ...
    complexCorrelation( ...
        diffuseEikonal.wavefield.U_zx, ...
        diffusePlaneAlignedZX);

%% Power spectra

[singleEikonalPower, kxRadM, kzRadM] = ...
    fieldPowerSpectrum( ...
        singleEikonal.wavefield.U_zx, ...
        dxM, ...
        dzM);

singlePlanePower = ...
    fieldPowerSpectrum( ...
        singlePlane.wavefield.U_zx, ...
        dxM, ...
        dzM);

diffuseEikonalPower = ...
    fieldPowerSpectrum( ...
        diffuseEikonal.wavefield.U_zx, ...
        dxM, ...
        dzM);

diffusePlanePower = ...
    fieldPowerSpectrum( ...
        diffusePlane.wavefield.U_zx, ...
        dxM, ...
        dzM);

singleEikonalPeak = dominantSpectralPeak( ...
    singleEikonalPower, kxRadM, kzRadM);

singlePlanePeak = dominantSpectralPeak( ...
    singlePlanePower, kxRadM, kzRadM);

diffusePowerCorrelation = normalizedPowerCorrelation( ...
    diffuseEikonalPower, ...
    diffusePlanePower);

%% Spectral entropy

entropyOptions = struct( ...
    "AngularBinCount", 36, ...
    "RadialBinCount", 32, ...
    "MinimumRadiusRadM", 0.2*expectedKRadM, ...
    "MaximumRadiusRadM", 1.5*expectedKRadM, ...
    "HalfPlane", "all");

diffuseEikonalEntropy = ...
    swsynth.metrics.computeSpectralEntropy( ...
        diffuseEikonalPower, ...
        kxRadM, ...
        kzRadM, ...
        entropyOptions);

diffusePlaneEntropy = ...
    swsynth.metrics.computeSpectralEntropy( ...
        diffusePlanePower, ...
        kxRadM, ...
        kzRadM, ...
        entropyOptions);

%% Summary

summary = table( ...
    expectedKRadM, ...
    singleEikonalPeak.radius_rad_m, ...
    singlePlanePeak.radius_rad_m, ...
    singleRelativeError, ...
    singleCorrelation, ...
    diffuseRelativeError, ...
    diffuseCorrelation, ...
    diffusePowerCorrelation, ...
    diffuseEikonalEntropy.angular_entropy, ...
    diffusePlaneEntropy.angular_entropy, ...
    diffuseEikonalEntropy.radial_entropy, ...
    diffusePlaneEntropy.radial_entropy, ...
    abs(singleComplexScale), ...
    angle(singleComplexScale), ...
    abs(diffuseComplexScale), ...
    angle(diffuseComplexScale), ...
    VariableNames=[ ...
        "expected_k_rad_m", ...
        "single_eikonal_peak_k_rad_m", ...
        "single_plane_peak_k_rad_m", ...
        "single_relative_complex_error", ...
        "single_complex_correlation", ...
        "diffuse_relative_complex_error", ...
        "diffuse_complex_correlation", ...
        "diffuse_power_correlation", ...
        "diffuse_eikonal_angular_entropy", ...
        "diffuse_plane_angular_entropy", ...
        "diffuse_eikonal_radial_entropy", ...
        "diffuse_plane_radial_entropy", ...
        "single_alignment_amplitude", ...
        "single_alignment_phase_rad", ...
        "diffuse_alignment_amplitude", ...
        "diffuse_alignment_phase_rad"]);

disp(summary);

writetable( ...
    summary, ...
    fullfile(outputDirectory, "comparison_summary.csv"));

%% Figure

figureHandle = figure( ...
    "Visible", "off", ...
    "Color", "w", ...
    "Position", [50,50,1500,1000]);

tiledlayout( ...
    2, ...
    4, ...
    "TileSpacing", "compact", ...
    "Padding", "compact");

plotField( ...
    xM, zM, ...
    singleEikonal.wavefield.U_zx, ...
    "1 direction: Eikonal");

plotField( ...
    xM, zM, ...
    singlePlaneAlignedZX, ...
    "1 direction: plane wave");

plotSpectrum( ...
    singleEikonalPower, ...
    kxRadM/expectedKRadM, ...
    kzRadM/expectedKRadM, ...
    "1 direction: Eikonal spectrum");

plotSpectrum( ...
    singlePlanePower, ...
    kxRadM/expectedKRadM, ...
    kzRadM/expectedKRadM, ...
    "1 direction: plane-wave spectrum");

plotField( ...
    xM, zM, ...
    diffuseEikonal.wavefield.U_zx, ...
    "32 directions: Eikonal");

plotField( ...
    xM, zM, ...
    diffusePlaneAlignedZX, ...
    "32 directions: plane wave");

plotSpectrum( ...
    diffuseEikonalPower, ...
    kxRadM/expectedKRadM, ...
    kzRadM/expectedKRadM, ...
    "32 directions: Eikonal spectrum");

plotSpectrum( ...
    diffusePlanePower, ...
    kxRadM/expectedKRadM, ...
    kzRadM/expectedKRadM, ...
    "32 directions: plane-wave spectrum");

sgtitle(sprintf( ...
    ["Homogeneous Eikonal vs plane-wave validation | " + ...
     "c_s = %.1f m/s, f = %.0f Hz"], ...
    csMps, frequencyHz));

figurePath = fullfile( ...
    outputDirectory, ...
    "homogeneous_eikonal_vs_plane_wave.png");

exportgraphics( ...
    figureHandle, ...
    figurePath, ...
    "Resolution", 180);

close(figureHandle);

fprintf("\nSaved figure: %s\n", figurePath);

%% Local functions

function result = runJson(path)

requested = jsondecode(fileread(path));
result = swsynth.run(requested);

end

function [alignedZX, scale] = alignComplexField(referenceZX, testZX)

referenceVector = referenceZX(:);
testVector = testZX(:);

denominator = sum(abs(testVector).^2);

if denominator <= eps
    error( ...
        "swsynth:ZeroValidationField", ...
        "Cannot align a zero-valued validation field.");
end

scale = ...
    sum(conj(testVector).*referenceVector) / denominator;

alignedZX = scale .* testZX;

end

function value = relativeComplexError(referenceZX, testZX)

value = ...
    norm(testZX(:) - referenceZX(:)) / ...
    norm(referenceZX(:));

end

function value = complexCorrelation(referenceZX, testZX)

numerator = abs(sum( ...
    conj(referenceZX(:)) .* testZX(:)));

denominator = ...
    norm(referenceZX(:)) * norm(testZX(:));

value = numerator / denominator;

end

function [powerZX, kxRadM, kzRadM] = ...
        fieldPowerSpectrum(fieldZX, dxM, dzM)

[nz, nx] = size(fieldZX);

windowX = ...
    0.5 - 0.5*cos(2*pi*(0:nx-1)/(nx-1));

windowZ = ...
    0.5 - 0.5*cos(2*pi*(0:nz-1)/(nz-1));

windowZX = windowZ(:) * windowX(:).';

spectrumZX = fftshift(fft2(fieldZX .* windowZX));
powerZX = abs(spectrumZX).^2;

maximumPower = max(powerZX(:));

if maximumPower > 0
    powerZX = powerZX ./ maximumPower;
end

kxRadM = ...
    2*pi .* ...
    ((-floor(nx/2)):(ceil(nx/2)-1)) ./ ...
    (nx*dxM);

kzRadM = ...
    2*pi .* ...
    ((-floor(nz/2)):(ceil(nz/2)-1)) ./ ...
    (nz*dzM);

end

function peak = dominantSpectralPeak(powerZX, kxRadM, kzRadM)

[~, linearIndex] = max(powerZX(:));
[kzIndex, kxIndex] = ind2sub(size(powerZX), linearIndex);

peak = struct();
peak.kx_rad_m = kxRadM(kxIndex);
peak.kz_rad_m = kzRadM(kzIndex);
peak.radius_rad_m = hypot( ...
    peak.kx_rad_m, ...
    peak.kz_rad_m);

end

function value = normalizedPowerCorrelation(powerA, powerB)

a = powerA(:) - mean(powerA(:));
b = powerB(:) - mean(powerB(:));

denominator = norm(a)*norm(b);

if denominator <= eps
    value = NaN;
else
    value = dot(a,b)/denominator;
end

end

function plotField(xM, zM, fieldZX, plotTitle)

nexttile;

imagesc(xM*1e3, zM*1e3, real(fieldZX));

axis image;
set(gca, "YDir", "normal");

xlabel("x (mm)");
ylabel("z (mm)");
title(plotTitle);
colorbar;

end

function plotSpectrum( ...
        powerZX, normalizedKX, normalizedKZ, plotTitle)

nexttile;

imagesc(normalizedKX, normalizedKZ, powerZX);

axis image;
set(gca, "YDir", "normal");

xlim([-1.5,1.5]);
ylim([-1.5,1.5]);
clim([0,1]);

xlabel("k_x/k_0");
ylabel("k_z/k_0");
title(plotTitle);
colorbar;

end
