function fig = plotVolumetricAmplitudeSlices(sample, options)
%PLOTVOLUMETRICAMPLITUDESLICES Plot normalized |U| on XY, XZ, and YZ slices.

arguments
    sample (1,1) struct
    options.Visible (1,1) string = "off"
end

s = simviz.volumetricSlices(sample);

global_max = max(abs(sample.wavefield.data_zyx),[],"all");

if ~(isfinite(global_max) && global_max > 0)
    global_max = 1;
end

fig = figure( ...
    "Visible",char(options.Visible), ...
    "Color","w", ...
    "Position",[100,100,1500,520]);

tl = tiledlayout(fig,1,3, ...
    "TileSpacing","compact", ...
    "Padding","compact");

plotSlice( ...
    nexttile(tl), ...
    s.xy.x_mm, ...
    s.xy.y_mm, ...
    abs(s.xy.U)/global_max, ...
    "x [mm]", ...
    "y [mm]");

plotSlice( ...
    nexttile(tl), ...
    s.xz.x_mm, ...
    s.xz.z_mm, ...
    abs(s.xz.U)/global_max, ...
    "x [mm]", ...
    "z [mm]");

plotSlice( ...
    nexttile(tl), ...
    s.yz.y_mm, ...
    s.yz.z_mm, ...
    abs(s.yz.U)/global_max, ...
    "y [mm]", ...
    "z [mm]");

colormap(fig,simviz.colormapAmplitude(256));
simviz.applyFigureStyle(fig);

end


function plotSlice(ax,x,y,data,xLabel,yLabel)

imagesc(ax,x,y,data);
axis(ax,"image");
set(ax,"YDir","normal");

xlabel(ax,xLabel);
ylabel(ax,yLabel);

clim(ax,[0,1]);

cb = colorbar(ax);
cb.Ticks = 0:0.2:1;
ylabel(cb,"Normalized |U|");

end
