function fig = plotVolumetricSwsSlices(sample, options)
%PLOTVOLUMETRICSWSSLICES Plot central XY, XZ, and YZ SWS slices.

arguments
    sample (1,1) struct
    options.Visible (1,1) string = "off"
end

s = simviz.volumetricSlices(sample);
theme = simviz.paperTheme();

values = [
    s.xy.cs(:)
    s.xz.cs(:)
    s.yz.cs(:)
];

limits = [min(values), max(values)];

if limits(1) == limits(2)
    pad = max(abs(limits(1))*0.25, 1);
    limits = limits + [-pad, pad];
end

fig = figure( ...
    "Visible", char(options.Visible), ...
    "Color", "w", ...
    "Position", [100,100,1500,520]);

tl = tiledlayout(fig,1,3, ...
    "TileSpacing","compact", ...
    "Padding","compact");

plotSlice( ...
    nexttile(tl), ...
    s.xy.x_mm, ...
    s.xy.y_mm, ...
    s.xy.cs, ...
    "x [mm]", ...
    "y [mm]", ...
    limits);

plotSlice( ...
    nexttile(tl), ...
    s.xz.x_mm, ...
    s.xz.z_mm, ...
    s.xz.cs, ...
    "x [mm]", ...
    "z [mm]", ...
    limits);

plotSlice( ...
    nexttile(tl), ...
    s.yz.y_mm, ...
    s.yz.z_mm, ...
    s.yz.cs, ...
    "y [mm]", ...
    "z [mm]", ...
    limits);

colormap(fig,simviz.colormapSws(256));

simviz.applyFigureStyle(fig,theme);

end


function plotSlice(ax,x,y,data,xLabel,yLabel,limits)

imagesc(ax,x,y,data);
axis(ax,"image");
set(ax,"YDir","normal");

xlabel(ax,xLabel);
ylabel(ax,yLabel);

clim(ax,limits);

cb = colorbar(ax);
ylabel(cb,"SWS [m/s]");

end
