function slices = volumetricSlices(sample)
%VOLUMETRICSLICES Extract central XY, XZ, and YZ slices from a 3D sample.
%
% Public volumetric array order:
%
%   data_zyx(z,y,x)
%
% Returned image matrices:
%
%   XY -> y-by-x
%   XZ -> z-by-x
%   YZ -> z-by-y

arguments
    sample (1,1) struct
end

if double(sample.spatial_dimension) ~= 3
    error( ...
        "simviz:NotVolumetric", ...
        "volumetricSlices requires spatial_dimension == 3.");
end

U = double(sample.wavefield.data_zyx);
cs = double(sample.truth.cs_map_zyx);

x_mm = 1e3 * double(sample.coordinates.x_m(:));
y_mm = 1e3 * double(sample.coordinates.y_m(:));
z_mm = 1e3 * double(sample.coordinates.z_m(:));

iz = round((size(U,1) + 1) / 2);
iy = round((size(U,2) + 1) / 2);
ix = round((size(U,3) + 1) / 2);

slices = struct();

slices.indices = struct( ...
    "z", iz, ...
    "y", iy, ...
    "x", ix);

slices.positions_mm = struct( ...
    "z", z_mm(iz), ...
    "y", y_mm(iy), ...
    "x", x_mm(ix));

slices.xy = struct( ...
    "x_mm", x_mm, ...
    "y_mm", y_mm, ...
    "U", squeeze(U(iz,:,:)), ...
    "cs", squeeze(cs(iz,:,:)));

slices.xz = struct( ...
    "x_mm", x_mm, ...
    "z_mm", z_mm, ...
    "U", squeeze(U(:,iy,:)), ...
    "cs", squeeze(cs(:,iy,:)));

slices.yz = struct( ...
    "y_mm", y_mm, ...
    "z_mm", z_mm, ...
    "U", squeeze(U(:,:,ix)), ...
    "cs", squeeze(cs(:,:,ix)));

end
