function metrics = summarizeSourceGeometry3D(cfg)
%SUMMARIZESOURCEGEOMETRY3D Quantify resolved 3D source angular coverage.
%
% The angular second-moment matrix is
%
%   M = sum_i w_i d_i d_i'
%
% where d_i is a unit nominal propagation direction and w_i is the
% normalized node-weighted RMS drive of source i.
%
% Its eigenvalues sum to one. The effective angular dimension is
%
%   D_eff = 1 / sum(lambda_i^2)
%
% with the following interpretation:
%
%   D_eff = 1: line-like or strongly directional angular support
%   D_eff = 2: predominantly planar angular support
%   D_eff = 3: isotropic three-dimensional angular support
%
% D_eff is sign-insensitive because d*d' is unchanged under d -> -d.
% The weighted mean-direction magnitude is reported separately to measure
% directional imbalance between opposite directions.

arguments
    cfg struct
end

if ~isfield(cfg, "source")
    error( ...
        "kwsim:InvalidSourceGeometryInput", ...
        "The configuration must contain a resolved source.");
end

source = ...
    cfg.source;

layout = ...
    lower(string(source.layout));

switch layout
    case "single_contact"
        directions_xyz = ...
            double(source.target_direction_xyz(:).');

        centers_index_xyz = ...
            double(source.center_index_xyz(:).');

        node_counts = ...
            double(source.contact_node_count);

        amplitudes_m_s = ...
            double(source.velocity_amplitude_m_s);

        faces = ...
            faceFromSingleSide(source);

        acquisition_y_index = ...
            resolveAcquisitionYIndex(cfg);

        centered_on_plane = ...
            centers_index_xyz(2) == acquisition_y_index;

        intersects_plane = ...
            singleContactIntersectsPlane( ...
                source, ...
                acquisition_y_index);

    case "vibrator_bank"
        if ~isfield(source, "vibrators") || ...
                isempty(source.vibrators)
            error( ...
                "kwsim:InvalidSourceGeometryInput", ...
                "A resolved vibrator bank must contain source.vibrators.");
        end

        vibrators = ...
            source.vibrators;

        number_of_sources = ...
            numel(vibrators);

        directions_xyz = ...
            double(vertcat( ...
                vibrators.nominal_propagation_xyz));

        centers_index_xyz = ...
            double(vertcat( ...
                vibrators.center_index_xyz));

        node_counts = ...
            zeros(number_of_sources, 1);

        amplitudes_m_s = ...
            zeros(number_of_sources, 1);

        faces = ...
            strings(number_of_sources, 1);

        centered_on_plane = ...
            false(number_of_sources, 1);

        intersects_plane = ...
            false(number_of_sources, 1);

        acquisition_y_index = ...
            resolveAcquisitionYIndex(cfg);

        for source_index = 1:number_of_sources
            vibrator = ...
                vibrators(source_index);

            node_counts(source_index) = ...
                numel(vibrator.node_linear_indices);

            amplitudes_m_s(source_index) = ...
                double(vibrator.velocity_amplitude_m_s);

            if isfield(vibrator, "face") && ...
                    strlength(string(vibrator.face)) > 0
                faces(source_index) = ...
                    lower(string(vibrator.face));
            else
                faces(source_index) = ...
                    inferFaceFromResolvedSource( ...
                        cfg, ...
                        source, ...
                        vibrator.center_index_xyz);
            end

            centered_on_plane(source_index) = ...
                vibrator.center_index_xyz(2) == ...
                acquisition_y_index;

            if isfield( ...
                    vibrator, ...
                    "intersects_acquisition_plane") && ...
                    ~isempty( ...
                    vibrator.intersects_acquisition_plane)

                intersects_plane(source_index) = ...
                    logical( ...
                    vibrator.intersects_acquisition_plane);
            else
                [~, node_y, ~] = ...
                    ind2sub( ...
                        [ ...
                            cfg.grid.Nx, ...
                            cfg.grid.Ny, ...
                            cfg.grid.Nz ...
                        ], ...
                        vibrator.node_linear_indices);

                intersects_plane(source_index) = ...
                    any(node_y == acquisition_y_index);
            end
        end

    otherwise
        error( ...
            "kwsim:InvalidSourceGeometryInput", ...
            "Unsupported resolved source layout: %s.", ...
            layout);
end

number_of_sources = ...
    size(directions_xyz, 1);

if number_of_sources < 1 || ...
        size(directions_xyz, 2) ~= 3 || ...
        any(~isfinite(directions_xyz), "all")
    error( ...
        "kwsim:InvalidSourceGeometryInput", ...
        "Resolved propagation directions must form a finite N-by-3 array.");
end

direction_norms = ...
    vecnorm( ...
        directions_xyz, ...
        2, ...
        2);

if any(direction_norms <= 0)
    error( ...
        "kwsim:InvalidSourceGeometryInput", ...
        "Resolved propagation directions must be nonzero.");
end

maximum_direction_norm_error = ...
    max(abs(direction_norms - 1));

directions_xyz = ...
    directions_xyz ./ direction_norms;

node_counts = ...
    double(node_counts(:));

amplitudes_m_s = ...
    double(amplitudes_m_s(:));

if numel(node_counts) ~= number_of_sources || ...
        numel(amplitudes_m_s) ~= number_of_sources || ...
        any(~isfinite(node_counts)) || ...
        any(node_counts <= 0) || ...
        any(~isfinite(amplitudes_m_s)) || ...
        any(amplitudes_m_s <= 0)
    error( ...
        "kwsim:InvalidSourceGeometryInput", ...
        "Every source must have a positive finite node count and amplitude.");
end

drive_rms_squared_by_source = ...
    node_counts .* ...
    amplitudes_m_s.^2 / ...
    2;

total_drive_rms_squared = ...
    sum(drive_rms_squared_by_source);

if ~(isfinite(total_drive_rms_squared) && ...
        total_drive_rms_squared > 0)
    error( ...
        "kwsim:InvalidSourceGeometryInput", ...
        "The total source drive must be finite and positive.");
end

weights = ...
    drive_rms_squared_by_source / ...
    total_drive_rms_squared;

weighted_mean_direction_xyz = ...
    sum( ...
        directions_xyz .* weights, ...
        1);

directional_bias = ...
    norm(weighted_mean_direction_xyz);

second_moment_xyz = ...
    directions_xyz.' * ...
    (directions_xyz .* weights);

second_moment_xyz = ...
    0.5 * ...
    (second_moment_xyz + second_moment_xyz.');

[eigenvectors_xyz, eigenvalue_matrix] = ...
    eig(second_moment_xyz);

eigenvalues = ...
    real(diag(eigenvalue_matrix));

eigenvalues = ...
    max(eigenvalues, 0);

[eigenvalues, order] = ...
    sort( ...
        eigenvalues, ...
        "descend");

eigenvectors_xyz = ...
    real(eigenvectors_xyz(:, order));

if sum(eigenvalues) <= 0
    error( ...
        "kwsim:InvalidSourceGeometryInput", ...
        "The angular second moment has zero trace.");
end

eigenvalues = ...
    eigenvalues / ...
    sum(eigenvalues);

effective_angular_dimension = ...
    1 / ...
    sum(eigenvalues.^2);

axis_energy_fraction_xyz = ...
    diag(second_moment_xyz).';

[
    pairwise_direction_angles_deg, ...
    pairwise_axis_angles_deg ...
] = pairwiseAngles(directions_xyz);

plane_deviation_deg = ...
    asind(abs(directions_xyz(:, 2)));

weighted_mean_plane_deviation_deg = ...
    sum(weights .* plane_deviation_deg);

weighted_rms_out_of_plane_component = ...
    sqrt( ...
        sum( ...
            weights .* ...
            directions_xyz(:, 2).^2));

supported_faces = [
    "x_min"
    "x_max"
    "y_min"
    "y_max"
    "z_min"
    "z_max"
];

face_counts = ...
    zeros(numel(supported_faces), 1);

for face_index = 1:numel(supported_faces)
    face_counts(face_index) = ...
        nnz(faces == supported_faces(face_index));
end

recognized_faces = ...
    ismember(faces, supported_faces);

recognized_face_set = ...
    unique( ...
        faces(recognized_faces), ...
        "stable");

metrics = struct();

metrics.layout = ...
    layout;

metrics.source_count = ...
    number_of_sources;

metrics.propagation_directions_xyz = ...
    directions_xyz;

metrics.centers_index_xyz = ...
    centers_index_xyz;

metrics.drive_weights = ...
    weights;

metrics.drive_rms_squared_by_source_m2_s2 = ...
    drive_rms_squared_by_source;

metrics.total_drive_rms_squared_m2_s2 = ...
    total_drive_rms_squared;

metrics.maximum_direction_norm_error = ...
    maximum_direction_norm_error;

metrics.faces = ...
    faces;

metrics.supported_faces = ...
    supported_faces;

metrics.face_counts = ...
    face_counts;

metrics.face_set = ...
    recognized_face_set;

metrics.unique_face_count = ...
    numel(recognized_face_set);

metrics.unknown_face_count = ...
    nnz(~recognized_faces);

metrics.acquisition_plane = ...
    "x-z";

metrics.acquisition_plane_y_index_full = ...
    acquisition_y_index;

metrics.contact_intersects_plane = ...
    intersects_plane;

metrics.contact_centered_on_plane = ...
    centered_on_plane;

metrics.in_plane_contact_count = ...
    nnz(intersects_plane);

metrics.centered_in_plane_contact_count = ...
    nnz(centered_on_plane);

metrics.out_of_plane_contact_count = ...
    number_of_sources - ...
    nnz(intersects_plane);

metrics.weighted_mean_direction_xyz = ...
    weighted_mean_direction_xyz;

metrics.directional_bias = ...
    directional_bias;

metrics.angular_second_moment_xyz = ...
    second_moment_xyz;

metrics.angular_eigenvalues_descending = ...
    eigenvalues;

metrics.angular_eigenvectors_xyz = ...
    eigenvectors_xyz;

metrics.effective_angular_dimension = ...
    effective_angular_dimension;

metrics.axis_energy_fraction_xyz = ...
    axis_energy_fraction_xyz;

metrics.pairwise_direction_angle_min_deg = ...
    minimumOrNaN(pairwise_direction_angles_deg);

metrics.pairwise_direction_angle_median_deg = ...
    medianOrNaN(pairwise_direction_angles_deg);

metrics.pairwise_direction_angle_max_deg = ...
    maximumOrNaN(pairwise_direction_angles_deg);

metrics.pairwise_axis_angle_min_deg = ...
    minimumOrNaN(pairwise_axis_angles_deg);

metrics.pairwise_axis_angle_median_deg = ...
    medianOrNaN(pairwise_axis_angles_deg);

metrics.pairwise_axis_angle_max_deg = ...
    maximumOrNaN(pairwise_axis_angles_deg);

metrics.direction_plane_deviation_deg = ...
    plane_deviation_deg;

metrics.weighted_mean_plane_deviation_deg = ...
    weighted_mean_plane_deviation_deg;

metrics.weighted_rms_out_of_plane_component = ...
    weighted_rms_out_of_plane_component;

end


function acquisition_y_index = resolveAcquisitionYIndex(cfg)

if isfield(cfg.source, "acquisition_plane_y_index_full")
    acquisition_y_index = ...
        double( ...
            cfg.source.acquisition_plane_y_index_full);

elseif isfield(cfg, "sensor") && ...
        isfield(cfg.sensor, "acquisition_y_index_full")
    acquisition_y_index = ...
        double( ...
            cfg.sensor.acquisition_y_index_full);

else
    acquisition_y_index = ...
        round((cfg.grid.Ny + 1) / 2);
end

end


function intersects_plane = singleContactIntersectsPlane( ...
        source, ...
        acquisition_y_index)

intersects_plane = ...
    source.center_index_xyz(2) == ...
    acquisition_y_index;

if isfield(source, "contact_node_subscripts_yz") && ...
        ~isempty(source.contact_node_subscripts_yz)
    intersects_plane = ...
        any( ...
            source.contact_node_subscripts_yz(:, 1) == ...
            acquisition_y_index);
end

end


function face = faceFromSingleSide(source)

side = ...
    lower(string(source.side));

switch side
    case "left"
        face = ...
            "x_min";

    case "right"
        face = ...
            "x_max";

    otherwise
        face = ...
            "unknown";
end

end


function face = inferFaceFromResolvedSource( ...
        cfg, ...
        source, ...
        center_index_xyz)

if isfield(source, "side")
    side = ...
        lower(string(source.side));

    if side == "left"
        face = ...
            "x_min";
        return
    elseif side == "right"
        face = ...
            "x_max";
        return
    end
end

center_index_xyz = ...
    double(center_index_xyz);

grid_size_xyz = [
    cfg.grid.Nx, ...
    cfg.grid.Ny, ...
    cfg.grid.Nz
];

grid_spacing_m_xyz = [
    cfg.grid.dx_m, ...
    cfg.grid.dy_m, ...
    cfg.grid.dz_m
];

margin_points_xyz = ...
    round( ...
        cfg.source.boundary_margin_m ./ ...
        grid_spacing_m_xyz);

minimum_planes_xyz = ...
    1 + margin_points_xyz;

maximum_planes_xyz = ...
    grid_size_xyz - margin_points_xyz;

if center_index_xyz(1) == minimum_planes_xyz(1)
    face = "x_min";
elseif center_index_xyz(1) == maximum_planes_xyz(1)
    face = "x_max";
elseif center_index_xyz(2) == minimum_planes_xyz(2)
    face = "y_min";
elseif center_index_xyz(2) == maximum_planes_xyz(2)
    face = "y_max";
elseif center_index_xyz(3) == minimum_planes_xyz(3)
    face = "z_min";
elseif center_index_xyz(3) == maximum_planes_xyz(3)
    face = "z_max";
else
    face = "unknown";
end

end


function [direction_angles_deg, axis_angles_deg] = ...
        pairwiseAngles(directions_xyz)

number_of_sources = ...
    size(directions_xyz, 1);

number_of_pairs = ...
    number_of_sources * ...
    (number_of_sources - 1) / ...
    2;

direction_angles_deg = ...
    zeros(number_of_pairs, 1);

axis_angles_deg = ...
    zeros(number_of_pairs, 1);

pair_index = 0;

for first_index = 1:(number_of_sources - 1)
    for second_index = (first_index + 1):number_of_sources
        pair_index = ...
            pair_index + 1;

        dot_product = ...
            dot( ...
                directions_xyz(first_index, :), ...
                directions_xyz(second_index, :));

        dot_product = ...
            max(-1, min(1, dot_product));

        direction_angles_deg(pair_index) = ...
            acosd(dot_product);

        axis_angles_deg(pair_index) = ...
            acosd(abs(dot_product));
    end
end

end


function value = minimumOrNaN(values)

if isempty(values)
    value = NaN;
else
    value = min(values);
end

end


function value = medianOrNaN(values)

if isempty(values)
    value = NaN;
else
    value = median(values);
end

end


function value = maximumOrNaN(values)

if isempty(values)
    value = NaN;
else
    value = max(values);
end

end
