function truth = buildMaterialMaps(cfg)
%BUILDMATERIALMAPS Build internal 3D material maps in [Nx,Ny,Nz].
%
% Precedence:
%   background -> bilayer -> cylinders -> spheres

arguments
    cfg struct
end

if ~isfield(cfg.geometry, "resolved") || ...
        ~cfg.geometry.resolved
    cfg = ...
        kwsim.three_d.resolveMaterialGeometryConfig(cfg);
end

grid_size_xyz = [
    cfg.grid.Nx, ...
    cfg.grid.Ny, ...
    cfg.grid.Nz
];

x_m = ...
    (0:(cfg.grid.Nx - 1)) * ...
    cfg.grid.dx_m;

y_m = ...
    (0:(cfg.grid.Ny - 1)) * ...
    cfg.grid.dy_m;

z_m = ...
    (0:(cfg.grid.Nz - 1)) * ...
    cfg.grid.dz_m;

[X_m, Y_m, Z_m] = ...
    ndgrid( ...
        x_m, ...
        y_m, ...
        z_m);

truth = struct();

truth.cp_m_s_xyz = ...
    single(cfg.medium.cp_m_s) * ...
    ones(grid_size_xyz, "single");

truth.cs_m_s_xyz = ...
    single(cfg.medium.cs_m_s) * ...
    ones(grid_size_xyz, "single");

truth.rho_kg_m3_xyz = ...
    single(cfg.medium.rho_kg_m3) * ...
    ones(grid_size_xyz, "single");

truth.material_id_xyz = ...
    cfg.geometry.background_material_id * ...
    ones(grid_size_xyz, "uint16");

region_template = struct( ...
    "name", "", ...
    "type", "", ...
    "material_id", uint16(0), ...
    "voxel_count", 0);

region_summary = ...
    repmat(region_template, 0, 1);

%% Bilayer

bilayer = ...
    cfg.geometry.bilayer;

if bilayer.enabled
    point = ...
        bilayer.interface_point_m_xyz;

    normal = ...
        bilayer.normal_xyz;

    signed_distance_m = ...
        (X_m - point(1)) * normal(1) + ...
        (Y_m - point(2)) * normal(2) + ...
        (Z_m - point(3)) * normal(3);

    negative_mask = ...
        signed_distance_m < 0;

    positive_mask = ...
        ~negative_mask;

    truth = ...
        applyMaterial( ...
            truth, ...
            negative_mask, ...
            bilayer.negative_material);

    truth = ...
        applyMaterial( ...
            truth, ...
            positive_mask, ...
            bilayer.positive_material);

    region_summary(end + 1) = ...
        makeRegionSummary( ...
            "bilayer_negative", ...
            "bilayer", ...
            bilayer.negative_material.material_id, ...
            nnz(negative_mask));

    region_summary(end + 1) = ...
        makeRegionSummary( ...
            "bilayer_positive", ...
            "bilayer", ...
            bilayer.positive_material.material_id, ...
            nnz(positive_mask));
end

%% Cylinders

objects = ...
    cfg.geometry.objects;

for object_index = 1:numel(objects)
    object = ...
        objects(object_index);

    if object.type ~= "cylinder"
        continue
    end

    dx = ...
        X_m - object.center_m_xyz(1);

    dy = ...
        Y_m - object.center_m_xyz(2);

    dz = ...
        Z_m - object.center_m_xyz(3);

    axial_m = ...
        dx * object.axis_xyz(1) + ...
        dy * object.axis_xyz(2) + ...
        dz * object.axis_xyz(3);

    radial_squared_m2 = ...
        dx.^2 + ...
        dy.^2 + ...
        dz.^2 - ...
        axial_m.^2;

    mask = ...
        abs(axial_m) <= ...
            0.5 * object.length_m + ...
            10*eps(object.length_m) & ...
        radial_squared_m2 <= ...
            object.radius_m^2 + ...
            10*eps(object.radius_m^2);

    truth = ...
        applyMaterial( ...
            truth, ...
            mask, ...
            object);

    region_summary(end + 1) = ...
        makeRegionSummary( ...
            object.name, ...
            object.type, ...
            object.material_id, ...
            nnz(mask));
end

%% Spheres

for object_index = 1:numel(objects)
    object = ...
        objects(object_index);

    if object.type ~= "sphere"
        continue
    end

    squared_distance_m2 = ...
        (X_m - object.center_m_xyz(1)).^2 + ...
        (Y_m - object.center_m_xyz(2)).^2 + ...
        (Z_m - object.center_m_xyz(3)).^2;

    mask = ...
        squared_distance_m2 <= ...
        object.radius_m^2 + ...
        10*eps(object.radius_m^2);

    truth = ...
        applyMaterial( ...
            truth, ...
            mask, ...
            object);

    region_summary(end + 1) = ...
        makeRegionSummary( ...
            object.name, ...
            object.type, ...
            object.material_id, ...
            nnz(mask));
end

truth.orientation = ...
    "[Nx,Ny,Nz]";

reference_cp_m_s = ...
    truth.cp_m_s_xyz(1);

reference_cs_m_s = ...
    truth.cs_m_s_xyz(1);

reference_rho_kg_m3 = ...
    truth.rho_kg_m3_xyz(1);

truth.homogeneous = ...
    all( ...
        truth.cp_m_s_xyz == reference_cp_m_s, ...
        "all") && ...
    all( ...
        truth.cs_m_s_xyz == reference_cs_m_s, ...
        "all") && ...
    all( ...
        truth.rho_kg_m3_xyz == reference_rho_kg_m3, ...
        "all");

truth.region_summary = ...
    region_summary;

truth.attenuation = struct( ...
    "enabled", ...
    false, ...
    "model", ...
    string(cfg.attenuation.model));

end


function truth = applyMaterial( ...
        truth, ...
        mask, ...
        material)

truth.cp_m_s_xyz(mask) = ...
    single(material.cp_m_s);

truth.cs_m_s_xyz(mask) = ...
    single(material.cs_m_s);

truth.rho_kg_m3_xyz(mask) = ...
    single(material.rho_kg_m3);

truth.material_id_xyz(mask) = ...
    uint16(material.material_id);

end


function summary = makeRegionSummary( ...
        name, ...
        type, ...
        material_id, ...
        voxel_count)

summary = struct();
summary.name = string(name);
summary.type = string(type);
summary.material_id = uint16(material_id);
summary.voxel_count = double(voxel_count);

end
