function [source, metadata] = buildVibratorBankSource(cfg, kgrid)
%BUILDVIBRATORBANKSOURCE Build a resolved multi-contact velocity source.
%
% Required resolved contract:
%
%   cfg.source.vibrators(i).node_linear_indices
%   cfg.source.vibrators(i).center_index_xyz
%   cfg.source.vibrators(i).center_m_xyz
%   cfg.source.vibrators(i).polarization_xyz
%   cfg.source.vibrators(i).nominal_propagation_xyz
%   cfg.source.vibrators(i).phase_rad
%   cfg.source.vibrators(i).velocity_amplitude_m_s
%
% source.ux, source.uy, and source.uz contain one row for each active
% source grid point, following find(source.u_mask), which is MATLAB's
% column-wise linear-index ordering.

arguments
    cfg struct
    kgrid
end

if ~isfield(cfg, "source") || ...
        ~isfield(cfg.source, "vibrators")
    error( ...
        "kwsim:MissingResolvedVibratorBank", ...
        "The resolved configuration must define source.vibrators.");
end

vibrators = cfg.source.vibrators;

if isempty(vibrators)
    error( ...
        "kwsim:EmptyVibratorBank", ...
        "source.vibrators must contain at least one vibrator.");
end

grid_size_xyz = [
    cfg.grid.Nx
    cfg.grid.Ny
    cfg.grid.Nz
];

number_of_grid_points = ...
    prod(grid_size_xyz);

number_of_vibrators = ...
    numel(vibrators);

owner_by_linear_index = ...
    zeros(number_of_grid_points, 1, "uint16");

required_fields = [
    "node_linear_indices"
    "center_index_xyz"
    "center_m_xyz"
    "polarization_xyz"
    "nominal_propagation_xyz"
    "phase_rad"
    "velocity_amplitude_m_s"
];

for vibrator_index = 1:number_of_vibrators
    vibrator = vibrators(vibrator_index);

    for field_name = required_fields.'
        if ~isfield(vibrator, char(field_name))
            error( ...
                "kwsim:InvalidResolvedVibrator", ...
                "Vibrator %d is missing field '%s'.", ...
                vibrator_index, ...
                field_name);
        end
    end

    node_indices = ...
        double(vibrator.node_linear_indices(:));

    if isempty(node_indices) || ...
            any(~isfinite(node_indices)) || ...
            any(node_indices ~= fix(node_indices)) || ...
            any(node_indices < 1) || ...
            any(node_indices > number_of_grid_points)
        error( ...
            "kwsim:InvalidVibratorNodeIndices", ...
            "Vibrator %d has invalid source node indices.", ...
            vibrator_index);
    end

    if numel(unique(node_indices)) ~= numel(node_indices)
        error( ...
            "kwsim:DuplicateVibratorNode", ...
            "Vibrator %d contains duplicate source nodes.", ...
            vibrator_index);
    end

    if any(owner_by_linear_index(node_indices) ~= 0)
        error( ...
            "kwsim:OverlappingVibratorContacts", ...
            "Vibrator %d overlaps another source contact.", ...
            vibrator_index);
    end

    polarization = ...
        double(vibrator.polarization_xyz(:));

    propagation = ...
        double(vibrator.nominal_propagation_xyz(:));

    if numel(polarization) ~= 3 || ...
            any(~isfinite(polarization)) || ...
            abs(norm(polarization) - 1) > 1e-10
        error( ...
            "kwsim:InvalidVibratorPolarization", ...
            "Vibrator %d polarization must be a unit 3-vector.", ...
            vibrator_index);
    end

    if numel(propagation) ~= 3 || ...
            any(~isfinite(propagation)) || ...
            abs(norm(propagation) - 1) > 1e-10
        error( ...
            "kwsim:InvalidVibratorDirection", ...
            "Vibrator %d propagation direction must be a unit 3-vector.", ...
            vibrator_index);
    end

    if abs(dot(polarization, propagation)) > 1e-10
        error( ...
            "kwsim:NonTransverseVibrator", ...
            "Vibrator %d polarization is not transverse.", ...
            vibrator_index);
    end

    amplitude_m_s = ...
        double(vibrator.velocity_amplitude_m_s);

    phase_rad = ...
        double(vibrator.phase_rad);

    if ~(isscalar(amplitude_m_s) && ...
            isfinite(amplitude_m_s) && ...
            amplitude_m_s > 0)
        error( ...
            "kwsim:InvalidVibratorAmplitude", ...
            "Vibrator %d amplitude must be positive.", ...
            vibrator_index);
    end

    if ~(isscalar(phase_rad) && isfinite(phase_rad))
        error( ...
            "kwsim:InvalidVibratorPhase", ...
            "Vibrator %d phase must be finite.", ...
            vibrator_index);
    end

    owner_by_linear_index(node_indices) = ...
        uint16(vibrator_index);
end

mask_xyz = reshape( ...
    owner_by_linear_index > 0, ...
    grid_size_xyz.');

active_linear_indices = ...
    find(mask_xyz);

owner_by_source_row = ...
    double(owner_by_linear_index(active_linear_indices));

t_s = ...
    double(kgrid.t_array(:).');

ramp_duration_s = ...
    cfg.source.ramp_cycles / ...
    cfg.source.f0_hz;

envelope = ...
    ones(size(t_s));

ramp_index = ...
    t_s < ramp_duration_s;

envelope(ramp_index) = ...
    0.5 * ...
    (1 - cos( ...
        pi * t_s(ramp_index) / ...
        ramp_duration_s));

number_of_source_points = ...
    numel(active_linear_indices);

number_of_time_samples = ...
    numel(t_s);

ux = zeros( ...
    number_of_source_points, ...
    number_of_time_samples, ...
    "single");

uy = zeros( ...
    number_of_source_points, ...
    number_of_time_samples, ...
    "single");

uz = zeros( ...
    number_of_source_points, ...
    number_of_time_samples, ...
    "single");

nominal_total_drive_rms_squared = 0;

for vibrator_index = 1:number_of_vibrators
    vibrator = vibrators(vibrator_index);

    source_rows = ...
        owner_by_source_row == vibrator_index;

    number_of_contact_nodes = ...
        nnz(source_rows);

    waveform_m_s = ...
        vibrator.velocity_amplitude_m_s .* ...
        envelope .* ...
        sin( ...
            2*pi*cfg.source.f0_hz*t_s + ...
            vibrator.phase_rad);

    polarization = ...
        double(vibrator.polarization_xyz(:));

    ux(source_rows, :) = repmat( ...
        single(polarization(1) .* waveform_m_s), ...
        number_of_contact_nodes, ...
        1);

    uy(source_rows, :) = repmat( ...
        single(polarization(2) .* waveform_m_s), ...
        number_of_contact_nodes, ...
        1);

    uz(source_rows, :) = repmat( ...
        single(polarization(3) .* waveform_m_s), ...
        number_of_contact_nodes, ...
        1);

    nominal_total_drive_rms_squared = ...
        nominal_total_drive_rms_squared + ...
        number_of_contact_nodes * ...
        vibrator.velocity_amplitude_m_s^2 / 2;
end

source = struct();

source.u_mask = mask_xyz;
source.ux = ux;
source.uy = uy;
source.uz = uz;
source.u_mode = char(cfg.source.mode);

metadata = struct();

metadata.kind = ...
    "external_sparse_disk_velocity_bank";

metadata.layout = ...
    "vibrator_bank";

metadata.mode = ...
    string(cfg.source.mode);

metadata.f0_hz = ...
    cfg.source.f0_hz;

metadata.vibrator_count = ...
    number_of_vibrators;

metadata.contact_node_count = ...
    number_of_source_points;

metadata.active_linear_indices = ...
    active_linear_indices;

metadata.owner_vibrator_index_by_source_row = ...
    owner_by_source_row;

metadata.vibrators = ...
    vibrators;

metadata.mask_xyz_internal = ...
    mask_xyz;

metadata.mask_zyx = ...
    permute(mask_xyz, [3, 2, 1]);

metadata.t_s = ...
    t_s;

metadata.envelope = ...
    envelope;

metadata.nominal_total_drive_rms_squared_m2_s2 = ...
    nominal_total_drive_rms_squared;

if isfield(cfg.source, "phase_policy")
    metadata.phase_policy = ...
        string(cfg.source.phase_policy);
else
    metadata.phase_policy = ...
        "resolved_explicit";
end

if isfield(cfg.source, "amplitude_policy")
    metadata.amplitude_policy = ...
        string(cfg.source.amplitude_policy);
else
    metadata.amplitude_policy = ...
        "resolved_explicit";
end

metadata.internal_orientation = ...
    "[Nx,Ny,Nz]";

metadata.public_orientation = ...
    "[Nz,Ny,Nx]";

end
