function [contact_specs, metadata] = contactSpecsFromDirections( ...
        cfg, ...
        directions_xyz, ...
        options)
%CONTACTSPECSFROMDIRECTIONS Map desired propagation directions to box faces.
%
% Each row of directions_xyz is the desired propagation direction from the
% source contact toward the domain center.
%
% A ray is traced backward from the domain center until it intersects one
% of the configured source planes:
%
%   source_position = domain_center - t * direction
%
% The resulting boundary contact is converted to the face/fraction
% contract used by resolveVibratorBankFromFaceSpecs.
%
% This separates angular design from the rectangular simulation geometry.

arguments
    cfg struct
    directions_xyz (:,3) double
    options.Names string = strings(0,1)
end

if isempty(directions_xyz)
    error( ...
        "kwsim:EmptyDirectionSpecification", ...
        "directions_xyz must contain at least one direction.");
end

if any(~isfinite(directions_xyz), "all")
    error( ...
        "kwsim:InvalidDirectionSpecification", ...
        "directions_xyz must contain only finite values.");
end

number_of_directions = ...
    size(directions_xyz, 1);

direction_norms = ...
    vecnorm( ...
        directions_xyz, ...
        2, ...
        2);

if any(direction_norms <= 0)
    error( ...
        "kwsim:InvalidDirectionSpecification", ...
        "Every requested propagation direction must be nonzero.");
end

desired_directions_xyz = ...
    directions_xyz ./ ...
    direction_norms;

names = ...
    string(options.Names(:));

if isempty(names)
    names = ...
        "angular_source_" + ...
        string((1:number_of_directions).');
elseif numel(names) ~= number_of_directions
    error( ...
        "kwsim:DirectionNameCountMismatch", ...
        "Names must contain one value per requested direction.");
end

grid_size_xyz = [
    cfg.grid.Nx, ...
    cfg.grid.Ny, ...
    cfg.grid.Nz
];

grid_spacing_m_xyz = [
    cfg.grid.dx_m, ...
    cfg.grid.dy_m, ...
    cfg.grid.dz_m
];

domain_size_m_xyz = ...
    (grid_size_xyz - 1) .* ...
    grid_spacing_m_xyz;

domain_center_m_xyz = ...
    0.5 * domain_size_m_xyz;

boundary_margin_points_xyz = ...
    round( ...
        cfg.source.boundary_margin_m ./ ...
        grid_spacing_m_xyz);

minimum_source_plane_index_xyz = ...
    1 + boundary_margin_points_xyz;

maximum_source_plane_index_xyz = ...
    grid_size_xyz - ...
    boundary_margin_points_xyz;

minimum_source_plane_m_xyz = ...
    (minimum_source_plane_index_xyz - 1) .* ...
    grid_spacing_m_xyz;

maximum_source_plane_m_xyz = ...
    (maximum_source_plane_index_xyz - 1) .* ...
    grid_spacing_m_xyz;

contact_radius_points_xyz = ...
    ceil( ...
        cfg.source.contact_radius_m ./ ...
        grid_spacing_m_xyz);

minimum_contact_center_index_xyz = ...
    1 + contact_radius_points_xyz;

maximum_contact_center_index_xyz = ...
    grid_size_xyz - ...
    contact_radius_points_xyz;

template = struct( ...
    "name", "", ...
    "face", "", ...
    "center_fraction_tangent", [NaN, NaN]);

contact_specs = ...
    repmat( ...
        template, ...
        number_of_directions, ...
        1);

resolved_centers_index_xyz = ...
    zeros(number_of_directions, 3);

resolved_centers_m_xyz = ...
    zeros(number_of_directions, 3);

realized_directions_xyz = ...
    zeros(number_of_directions, 3);

angular_error_deg = ...
    zeros(number_of_directions, 1);

faces = ...
    strings(number_of_directions, 1);

for direction_index = 1:number_of_directions
    direction = ...
        desired_directions_xyz(direction_index, :);

    [ ...
        face, ...
        fixed_axis, ...
        tangent_axes, ...
        source_plane_index ...
    ] = firstIntersectedFace( ...
        direction, ...
        domain_center_m_xyz, ...
        minimum_source_plane_m_xyz, ...
        maximum_source_plane_m_xyz, ...
        minimum_source_plane_index_xyz, ...
        maximum_source_plane_index_xyz);

    source_plane_m = ...
        (source_plane_index - 1) * ...
        grid_spacing_m_xyz(fixed_axis);

    if direction(fixed_axis) > 0
        ray_distance = ...
            (domain_center_m_xyz(fixed_axis) - ...
            source_plane_m) / ...
            direction(fixed_axis);
    else
        ray_distance = ...
            (source_plane_m - ...
            domain_center_m_xyz(fixed_axis)) / ...
            (-direction(fixed_axis));
    end

    contact_center_m_xyz = ...
        domain_center_m_xyz - ...
        ray_distance * direction;

    contact_center_index_xyz = ...
        round( ...
            contact_center_m_xyz ./ ...
            grid_spacing_m_xyz) + ...
        1;

    contact_center_index_xyz(fixed_axis) = ...
        source_plane_index;

    tangent_center_indices = ...
        contact_center_index_xyz(tangent_axes);

    minimum_tangent_center = ...
        minimum_contact_center_index_xyz(tangent_axes);

    maximum_tangent_center = ...
        maximum_contact_center_index_xyz(tangent_axes);

    if any(tangent_center_indices < minimum_tangent_center) || ...
            any(tangent_center_indices > maximum_tangent_center)
        error( ...
            "kwsim:DirectionContactDoesNotFit", ...
            "Direction %d intersects face %s too close to an edge " + ...
            "for the requested finite contact radius.", ...
            direction_index, ...
            face);
    end

    tangent_denominator = ...
        maximum_tangent_center - ...
        minimum_tangent_center;

    tangent_fraction = ...
        zeros(1, 2);

    for tangent_index = 1:2
        if tangent_denominator(tangent_index) == 0
            tangent_fraction(tangent_index) = ...
                0.5;
        else
            tangent_fraction(tangent_index) = ...
                ( ...
                    tangent_center_indices(tangent_index) - ...
                    minimum_tangent_center(tangent_index) ...
                ) / ...
                tangent_denominator(tangent_index);
        end
    end

    resolved_center_m_xyz = ...
        (contact_center_index_xyz - 1) .* ...
        grid_spacing_m_xyz;

    realized_direction = ...
        domain_center_m_xyz - ...
        resolved_center_m_xyz;

    realized_direction = ...
        realized_direction / ...
        norm(realized_direction);

    direction_dot_product = ...
        dot( ...
            direction, ...
            realized_direction);

    direction_dot_product = ...
        max( ...
            -1, ...
            min(1, direction_dot_product));

    contact_specs(direction_index).name = ...
        names(direction_index);

    contact_specs(direction_index).face = ...
        face;

    contact_specs(direction_index).center_fraction_tangent = ...
        tangent_fraction;

    resolved_centers_index_xyz(direction_index, :) = ...
        contact_center_index_xyz;

    resolved_centers_m_xyz(direction_index, :) = ...
        resolved_center_m_xyz;

    realized_directions_xyz(direction_index, :) = ...
        realized_direction;

    angular_error_deg(direction_index) = ...
        acosd(direction_dot_product);

    faces(direction_index) = ...
        face;
end

metadata = struct();

metadata.desired_directions_xyz = ...
    desired_directions_xyz;

metadata.realized_directions_xyz = ...
    realized_directions_xyz;

metadata.angular_error_deg = ...
    angular_error_deg;

metadata.maximum_angular_error_deg = ...
    max(angular_error_deg);

metadata.centers_index_xyz = ...
    resolved_centers_index_xyz;

metadata.centers_m_xyz = ...
    resolved_centers_m_xyz;

metadata.faces = ...
    faces;

metadata.face_set = ...
    unique(faces, "stable");

metadata.domain_center_m_xyz = ...
    domain_center_m_xyz;

end


function [ ...
        face, ...
        fixed_axis, ...
        tangent_axes, ...
        source_plane_index ...
    ] = firstIntersectedFace( ...
        direction, ...
        domain_center_m_xyz, ...
        minimum_plane_m_xyz, ...
        maximum_plane_m_xyz, ...
        minimum_plane_index_xyz, ...
        maximum_plane_index_xyz)

t_candidates = ...
    inf(1, 3);

candidate_faces = ...
    strings(1, 3);

candidate_plane_indices = ...
    nan(1, 3);

tolerance = ...
    1e-12;

for axis_index = 1:3
    if direction(axis_index) > tolerance
        t_candidates(axis_index) = ...
            ( ...
                domain_center_m_xyz(axis_index) - ...
                minimum_plane_m_xyz(axis_index) ...
            ) / ...
            direction(axis_index);

        candidate_faces(axis_index) = ...
            minimumFaceForAxis(axis_index);

        candidate_plane_indices(axis_index) = ...
            minimum_plane_index_xyz(axis_index);

    elseif direction(axis_index) < -tolerance
        t_candidates(axis_index) = ...
            ( ...
                maximum_plane_m_xyz(axis_index) - ...
                domain_center_m_xyz(axis_index) ...
            ) / ...
            (-direction(axis_index));

        candidate_faces(axis_index) = ...
            maximumFaceForAxis(axis_index);

        candidate_plane_indices(axis_index) = ...
            maximum_plane_index_xyz(axis_index);
    end
end

[ray_distance, fixed_axis] = ...
    min(t_candidates);

if ~(isfinite(ray_distance) && ray_distance > 0)
    error( ...
        "kwsim:InvalidDirectionSpecification", ...
        "Could not intersect the requested direction with a source face.");
end

face = ...
    candidate_faces(fixed_axis);

source_plane_index = ...
    candidate_plane_indices(fixed_axis);

switch fixed_axis
    case 1
        tangent_axes = [2, 3];

    case 2
        tangent_axes = [1, 3];

    case 3
        tangent_axes = [1, 2];

    otherwise
        error( ...
            "kwsim:InvalidDirectionSpecification", ...
            "Invalid fixed source axis.");
end

end


function face = minimumFaceForAxis(axis_index)

switch axis_index
    case 1
        face = "x_min";
    case 2
        face = "y_min";
    case 3
        face = "z_min";
    otherwise
        error("kwsim:InvalidDirectionSpecification", ...
            "Invalid axis index.");
end

end


function face = maximumFaceForAxis(axis_index)

switch axis_index
    case 1
        face = "x_max";
    case 2
        face = "y_max";
    case 3
        face = "z_max";
    otherwise
        error("kwsim:InvalidDirectionSpecification", ...
            "Invalid axis index.");
end

end
