function generated = generatePackedFaceGridBank( ...
        cfg, ...
        total_source_count, ...
        in_plane_source_count)
%GENERATEPACKEDFACEGRIDBANK Generate a collision-free symmetric face bank.
%
% This placement is intended for high source counts for which independent
% random angular placement has an extremely small probability of producing
% a completely non-overlapping finite-contact bank.
%
% Requirements:
%
%   P must be divisible by four:
%     P/4 contacts are placed in-plane on each x/z face.
%
%   N-P must be divisible by six:
%     (N-P)/6 out-of-plane contacts are placed on each boundary face.
%
%   The out-of-plane count per face must be an even square, such as
%   4 or 16, allowing a symmetric two-dimensional lattice.
%
% Opposite faces use mirrored tangent coordinates. This produces paired
% propagation directions and therefore low directional bias.

arguments
    cfg struct
    total_source_count (1,1) double
    in_plane_source_count (1,1) double
end

validateCounts( ...
    total_source_count, ...
    in_plane_source_count);

out_of_plane_source_count = ...
    total_source_count - ...
    in_plane_source_count;

if mod(in_plane_source_count, 4) ~= 0
    error( ...
        "kwsim:InvalidPackedFaceGrid", ...
        "The in-plane source count must be divisible by four.");
end

if mod(out_of_plane_source_count, 6) ~= 0
    error( ...
        "kwsim:InvalidPackedFaceGrid", ...
        "The out-of-plane source count must be divisible by six.");
end

in_plane_per_planar_face = ...
    in_plane_source_count / 4;

out_of_plane_per_face = ...
    out_of_plane_source_count / 6;

[out_grid_rows, out_grid_columns] = ...
    packedGridShape(out_of_plane_per_face);

candidate_cfg = ...
    cfg;

candidate_cfg.source.layout = ...
    "vibrator_bank";

candidate_cfg.source.side = ...
    "multiface";

candidate_cfg.source.vibrator_count = ...
    total_source_count;

acquisition_y_index = ...
    round((cfg.grid.Ny + 1) / 2);

acquisition_y_fraction = ...
    fractionForAxisIndex( ...
        cfg, ...
        2, ...
        acquisition_y_index);

spec_template = struct( ...
    "name", "", ...
    "face", "", ...
    "center_fraction_tangent", [NaN, NaN]);

contact_specs = ...
    repmat( ...
        spec_template, ...
        total_source_count, ...
        1);

spec_index = ...
    0;

%% In-plane contacts on x and z faces

if in_plane_per_planar_face > 0
    [line_low, line_high] = ...
        packedLineFractions( ...
            cfg, ...
            1, ...
            in_plane_per_planar_face);

    for line_index = 1:in_plane_per_planar_face
        spec_index = ...
            spec_index + 1;

        contact_specs(spec_index) = ...
            makeSpec( ...
                "x_min_in_plane_" + string(line_index), ...
                "x_min", ...
                [ ...
                    acquisition_y_fraction, ...
                    line_low(line_index) ...
                ]);

        spec_index = ...
            spec_index + 1;

        contact_specs(spec_index) = ...
            makeSpec( ...
                "x_max_in_plane_" + string(line_index), ...
                "x_max", ...
                [ ...
                    acquisition_y_fraction, ...
                    line_high(line_index) ...
                ]);

        spec_index = ...
            spec_index + 1;

        contact_specs(spec_index) = ...
            makeSpec( ...
                "z_min_in_plane_" + string(line_index), ...
                "z_min", ...
                [ ...
                    line_high(line_index), ...
                    acquisition_y_fraction ...
                ]);

        spec_index = ...
            spec_index + 1;

        contact_specs(spec_index) = ...
            makeSpec( ...
                "z_max_in_plane_" + string(line_index), ...
                "z_max", ...
                [ ...
                    line_low(line_index), ...
                    acquisition_y_fraction ...
                ]);
    end
end

%% Out-of-plane tangent grids

x_levels = ...
    safeInteriorFractions( ...
        cfg, ...
        1, ...
        out_grid_rows);

x_levels_columns = ...
    safeInteriorFractions( ...
        cfg, ...
        1, ...
        out_grid_columns);

z_levels = ...
    safeInteriorFractions( ...
        cfg, ...
        3, ...
        out_grid_columns);

y_levels = ...
    outOfPlaneYFractions( ...
        cfg, ...
        acquisition_y_index, ...
        out_grid_rows);

for first_index = 1:out_grid_rows
    for second_index = 1:out_grid_columns
        y_fraction = ...
            y_levels(first_index);

        x_fraction = ...
            x_levels(first_index);

        x_fraction_column = ...
            x_levels_columns(second_index);

        z_fraction = ...
            z_levels(second_index);

        %% x-face pair: tangent order [y,z]

        spec_index = ...
            spec_index + 1;

        contact_specs(spec_index) = ...
            makeSpec( ...
                "x_min_out_" + string(first_index) + ...
                    "_" + string(second_index), ...
                "x_min", ...
                [y_fraction, z_fraction]);

        spec_index = ...
            spec_index + 1;

        contact_specs(spec_index) = ...
            makeSpec( ...
                "x_max_out_" + string(first_index) + ...
                    "_" + string(second_index), ...
                "x_max", ...
                [1-y_fraction, 1-z_fraction]);

        %% y-face pair: tangent order [x,z]

        spec_index = ...
            spec_index + 1;

        contact_specs(spec_index) = ...
            makeSpec( ...
                "y_min_out_" + string(first_index) + ...
                    "_" + string(second_index), ...
                "y_min", ...
                [x_fraction, z_fraction]);

        spec_index = ...
            spec_index + 1;

        contact_specs(spec_index) = ...
            makeSpec( ...
                "y_max_out_" + string(first_index) + ...
                    "_" + string(second_index), ...
                "y_max", ...
                [1-x_fraction, 1-z_fraction]);

        %% z-face pair: tangent order [x,y]

        spec_index = ...
            spec_index + 1;

        contact_specs(spec_index) = ...
            makeSpec( ...
                "z_min_out_" + string(first_index) + ...
                    "_" + string(second_index), ...
                "z_min", ...
                [x_fraction_column, y_fraction]);

        spec_index = ...
            spec_index + 1;

        contact_specs(spec_index) = ...
            makeSpec( ...
                "z_max_out_" + string(first_index) + ...
                    "_" + string(second_index), ...
                "z_max", ...
                [1-x_fraction_column, 1-y_fraction]);
    end
end

if spec_index ~= total_source_count
    error( ...
        "kwsim:InvalidPackedFaceGrid", ...
        "Internal packed-grid source-count mismatch.");
end

bank = ...
    kwsim.three_d.resolveVibratorBankFromFaceSpecs( ...
        candidate_cfg, ...
        contact_specs);

%% Attach acquisition-plane metadata before calculating geometry metrics

in_plane_count = 0;
centered_in_plane_count = 0;

for vibrator_index = 1:numel(bank.vibrators)
    vibrator = ...
        bank.vibrators(vibrator_index);

    [~, node_y, ~] = ...
        ind2sub( ...
            size(bank.union_mask_xyz), ...
            vibrator.node_linear_indices);

    intersects_plane = ...
        any(node_y == acquisition_y_index);

    centered_on_plane = ...
        vibrator.center_index_xyz(2) == ...
        acquisition_y_index;

    bank.vibrators(vibrator_index). ...
        intersects_acquisition_plane = ...
        intersects_plane;

    bank.vibrators(vibrator_index). ...
        centered_on_acquisition_plane = ...
        centered_on_plane;

    in_plane_count = ...
        in_plane_count + double(intersects_plane);

    centered_in_plane_count = ...
        centered_in_plane_count + ...
        double(centered_on_plane);
end

if in_plane_count ~= in_plane_source_count || ...
        centered_in_plane_count ~= in_plane_source_count
    error( ...
        "kwsim:InvalidPackedFaceGrid", ...
        "Packed grid requested P=%d but resolved %d intersecting " + ...
        "and %d centered contacts.", ...
        in_plane_source_count, ...
        in_plane_count, ...
        centered_in_plane_count);
end

metrics_cfg = ...
    candidate_cfg;

metrics_cfg.source.vibrators = ...
    bank.vibrators;

metrics_cfg.source.face_set = ...
    bank.face_set;

metrics_cfg.source.face_counts = ...
    bank.face_counts;

metrics_cfg.source.acquisition_plane_y_index_full = ...
    acquisition_y_index;

metrics = ...
    kwsim.analysis.summarizeSourceGeometry3D( ...
        metrics_cfg);

realized_directions_xyz = ...
    double(vertcat( ...
        bank.vibrators.nominal_propagation_xyz));

mapping = struct();

mapping.mapping_mode = ...
    "contact_first_identity";

mapping.desired_directions_xyz = ...
    realized_directions_xyz;

mapping.realized_directions_xyz = ...
    realized_directions_xyz;

mapping.angular_error_deg = ...
    zeros(total_source_count, 1);

mapping.maximum_angular_error_deg = ...
    0;

mapping.centers_index_xyz = ...
    double(vertcat( ...
        bank.vibrators.center_index_xyz));

mapping.centers_m_xyz = ...
    double(vertcat( ...
        bank.vibrators.center_m_xyz));

mapping.faces = ...
    string({bank.vibrators.face}).';

mapping.face_set = ...
    bank.face_set;

score = ...
    2.0 * metrics.effective_angular_dimension + ...
    3.0 * metrics.angular_eigenvalues_descending(3) - ...
    2.0 * metrics.directional_bias + ...
    0.10 * metrics.unique_face_count;

rejection_counts = struct( ...
    "mapping_or_overlap", 0, ...
    "plane_count", 0, ...
    "face_count", 0, ...
    "dimension", 0, ...
    "bias", 0, ...
    "third_eigenvalue", 0, ...
    "axis_separation", 0, ...
    "mapping_error", 0);

bank.angular_generation = struct( ...
    "placement_policy", "packed_face_grid", ...
    "total_source_count", total_source_count, ...
    "in_plane_source_count", in_plane_source_count, ...
    "out_of_plane_source_count", ...
        out_of_plane_source_count, ...
    "in_plane_per_planar_face", ...
        in_plane_per_planar_face, ...
    "out_of_plane_per_face", ...
        out_of_plane_per_face, ...
    "selected_candidate_index", 1, ...
    "score", score, ...
    "feasible_candidate_count", 1, ...
    "candidate_count", 1, ...
    "desired_directions_xyz", ...
        realized_directions_xyz, ...
    "maximum_mapping_error_deg", 0, ...
    "effective_angular_dimension", ...
        metrics.effective_angular_dimension, ...
    "directional_bias", ...
        metrics.directional_bias, ...
    "third_angular_eigenvalue", ...
        metrics.angular_eigenvalues_descending(3), ...
    "minimum_axis_separation_deg", ...
        metrics.pairwise_axis_angle_min_deg);

generated = struct();

generated.candidate_index = ...
    1;

generated.score = ...
    score;

generated.desired_directions_xyz = ...
    realized_directions_xyz;

generated.contact_specs = ...
    contact_specs;

generated.mapping = ...
    mapping;

generated.bank = ...
    bank;

generated.geometry_metrics = ...
    metrics;

generated.total_source_count = ...
    total_source_count;

generated.in_plane_source_count = ...
    in_plane_source_count;

generated.out_of_plane_source_count = ...
    out_of_plane_source_count;

generated.seed = ...
    double(cfg.source.geometry_seed);

generated.candidate_count = ...
    1;

generated.feasible_candidate_count = ...
    1;

generated.rejection_counts = ...
    rejection_counts;

end


function [row_count, column_count] = ...
        packedGridShape(contact_count)

row_count = ...
    NaN;

column_count = ...
    NaN;

for candidate_rows = floor(sqrt(contact_count)):-1:2
    if mod(candidate_rows, 2) == 0 && ...
            mod(contact_count, candidate_rows) == 0
        row_count = ...
            candidate_rows;

        column_count = ...
            contact_count / candidate_rows;

        break
    end
end

if ~(isfinite(row_count) && ...
        isfinite(column_count))
    error( ...
        "kwsim:InvalidPackedFaceGrid", ...
        "The out-of-plane count per face must admit an " + ...
        "even-row rectangular grid.");
end

end


function specification = makeSpec(name, face, fractions)

specification = struct( ...
    "name", string(name), ...
    "face", string(face), ...
    "center_fraction_tangent", ...
        double(fractions));

end


function [low_fractions, high_fractions] = ...
        packedLineFractions( ...
            cfg, ...
            axis_index, ...
            count)

if count == 0
    low_fractions = ...
        zeros(0, 1);

    high_fractions = ...
        zeros(0, 1);

    return
end

[
    minimum_center, ...
    maximum_center, ...
    minimum_safe_center, ...
    maximum_safe_center, ...
    separation_points ...
] = axisPackingLimits( ...
    cfg, ...
    axis_index);

safe_capacity = ...
    floor( ...
        (maximum_safe_center - ...
        minimum_safe_center) / ...
        separation_points) + ...
    1;

if count <= safe_capacity
    centers = ...
        round( ...
            linspace( ...
                minimum_safe_center, ...
                maximum_safe_center, ...
                count));

    low_centers = ...
        centers;

    high_centers = ...
        fliplr( ...
            minimum_center + ...
            maximum_center - ...
            centers);
else
    required_span = ...
        separation_points * ...
        (count - 1);

    if minimum_center + required_span > maximum_center
        error( ...
            "kwsim:PackedFaceCapacityExceeded", ...
            "Cannot fit %d in-plane contacts on one face.", ...
            count);
    end

    low_centers = ...
        minimum_center + ...
        (0:(count - 1)) * ...
        separation_points;

    high_centers = ...
        maximum_center - ...
        (count - 1:-1:0) * ...
        separation_points;
end

low_fractions = ...
    indicesToFractions( ...
        low_centers, ...
        minimum_center, ...
        maximum_center);

high_fractions = ...
    indicesToFractions( ...
        high_centers, ...
        minimum_center, ...
        maximum_center);

low_fractions = ...
    low_fractions(:);

high_fractions = ...
    high_fractions(:);

end


function fractions = safeInteriorFractions( ...
        cfg, ...
        axis_index, ...
        count)

[
    minimum_center, ...
    maximum_center, ...
    minimum_safe_center, ...
    maximum_safe_center, ...
    separation_points ...
] = axisPackingLimits( ...
    cfg, ...
    axis_index);

centers = ...
    round( ...
        linspace( ...
            minimum_safe_center, ...
            maximum_safe_center, ...
            count));

if count > 1 && ...
        any(diff(centers) < separation_points)
    error( ...
        "kwsim:PackedFaceCapacityExceeded", ...
        "Cannot fit the requested packed grid along axis %d.", ...
        axis_index);
end

fractions = ...
    indicesToFractions( ...
        centers, ...
        minimum_center, ...
        maximum_center);

fractions = ...
    fractions(:);

end


function fractions = outOfPlaneYFractions( ...
        cfg, ...
        acquisition_y_index, ...
        count)

if mod(count, 2) ~= 0
    error( ...
        "kwsim:InvalidPackedFaceGrid", ...
        "The out-of-plane y-grid side must be even.");
end

[
    minimum_center, ...
    maximum_center, ...
    minimum_safe_center, ...
    maximum_safe_center, ...
    separation_points ...
] = axisPackingLimits( ...
    cfg, ...
    2);

half_count = ...
    count / 2;

% Contacts on opposite faces use mirrored tangent coordinates. Require
% both the original y center and its mirrored center to remain separated
% from the acquisition-plane contacts.
mirrored_center_sum = ...
    minimum_center + ...
    maximum_center;

lower_maximum = ...
    min( ...
        acquisition_y_index - ...
            separation_points, ...
        mirrored_center_sum - ...
            (acquisition_y_index + separation_points));

upper_minimum = ...
    max( ...
        acquisition_y_index + ...
            separation_points, ...
        mirrored_center_sum - ...
            (acquisition_y_index - separation_points));

if minimum_safe_center > lower_maximum || ...
        upper_minimum > maximum_safe_center
    error( ...
        "kwsim:PackedFaceCapacityExceeded", ...
        "There is insufficient y-space around the acquisition plane.");
end

lower_centers = ...
    round( ...
        linspace( ...
            minimum_safe_center, ...
            lower_maximum, ...
            half_count));

upper_centers = ...
    round( ...
        linspace( ...
            upper_minimum, ...
            maximum_safe_center, ...
            half_count));

centers = [
    lower_centers, ...
    upper_centers
];

if half_count > 1 && ...
        ( ...
            any(diff(lower_centers) < separation_points) || ...
            any(diff(upper_centers) < separation_points) ...
        )
    error( ...
        "kwsim:PackedFaceCapacityExceeded", ...
        "Cannot fit the requested out-of-plane y levels.");
end

fractions = ...
    indicesToFractions( ...
        centers, ...
        minimum_center, ...
        maximum_center);

fractions = ...
    fractions(:);

end


function [ ...
        minimum_center, ...
        maximum_center, ...
        minimum_safe_center, ...
        maximum_safe_center, ...
        separation_points ...
    ] = axisPackingLimits( ...
        cfg, ...
        axis_index)

grid_size_xyz = [
    cfg.grid.Nx, ...
    cfg.grid.Ny, ...
    cfg.grid.Nz
];

grid_spacing_m_xyz = [
    cfg.grid.dx_m, ...
    cfg.grid.dy_m, ...
    cfg.grid.dz_m
];

radius_points = ...
    ceil( ...
        cfg.source.contact_radius_m / ...
        grid_spacing_m_xyz(axis_index));

boundary_points = ...
    round( ...
        cfg.source.boundary_margin_m / ...
        grid_spacing_m_xyz(axis_index));

minimum_center = ...
    1 + radius_points;

maximum_center = ...
    grid_size_xyz(axis_index) - ...
    radius_points;

minimum_source_plane = ...
    1 + boundary_points;

maximum_source_plane = ...
    grid_size_xyz(axis_index) - ...
    boundary_points;

separation_points = ...
    2 * radius_points + 1;

minimum_safe_center = ...
    max( ...
        minimum_center, ...
        minimum_source_plane + ...
        radius_points + 1);

maximum_safe_center = ...
    min( ...
        maximum_center, ...
        maximum_source_plane - ...
        radius_points - 1);

end


function fraction = fractionForAxisIndex( ...
        cfg, ...
        axis_index, ...
        target_index)

grid_size_xyz = [
    cfg.grid.Nx, ...
    cfg.grid.Ny, ...
    cfg.grid.Nz
];

grid_spacing_m_xyz = [
    cfg.grid.dx_m, ...
    cfg.grid.dy_m, ...
    cfg.grid.dz_m
];

radius_points = ...
    ceil( ...
        cfg.source.contact_radius_m / ...
        grid_spacing_m_xyz(axis_index));

minimum_center = ...
    1 + radius_points;

maximum_center = ...
    grid_size_xyz(axis_index) - ...
    radius_points;

fraction = ...
    (target_index - minimum_center) / ...
    (maximum_center - minimum_center);

end


function fractions = indicesToFractions( ...
        indices, ...
        minimum_center, ...
        maximum_center)

fractions = ...
    (indices - minimum_center) / ...
    (maximum_center - minimum_center);

end


function validateCounts( ...
        total_source_count, ...
        in_plane_source_count)

if ~( ...
        isfinite(total_source_count) && ...
        total_source_count == fix(total_source_count) && ...
        total_source_count >= 1)
    error( ...
        "kwsim:InvalidPackedFaceGrid", ...
        "total_source_count must be a positive integer.");
end

if ~( ...
        isfinite(in_plane_source_count) && ...
        in_plane_source_count == fix(in_plane_source_count) && ...
        in_plane_source_count >= 0 && ...
        in_plane_source_count <= total_source_count)
    error( ...
        "kwsim:InvalidPackedFaceGrid", ...
        "in_plane_source_count must be an integer between zero and N.");
end

end
