function generated = generateAngularVibratorBank( ...
        cfg, ...
        total_source_count, ...
        in_plane_source_count, ...
        options)
%GENERATEANGULARVIBRATORBANK Generate an optimized multi-face source bank.
%
% The generator creates multiple candidate angular distributions with:
%
%   N = total_source_count
%   P = in_plane_source_count
%
% Exactly P requested propagation directions lie in the x-z acquisition
% plane. Each candidate is mapped to finite boundary contacts, resolved
% using the standard multi-face bank resolver, and evaluated using the
% realized discretized directions.
%
% The best feasible candidate maximizes three-dimensional angular coverage
% while penalizing directional bias, redundant source axes, and mapping
% error.

arguments
    cfg struct
    total_source_count (1,1) double
    in_plane_source_count (1,1) double
    options.Seed (1,1) double = double(cfg.seed)
    options.CandidateCount (1,1) double = 300
    options.MinimumOutOfPlaneComponent (1,1) double = 0.20
    options.MinimumUniqueFaces (1,1) double = 1
    options.MinimumEffectiveDimension (1,1) double = 1
    options.MaximumDirectionalBias (1,1) double = 1
    options.MinimumThirdEigenvalue (1,1) double = 0
    options.MinimumAxisSeparationDeg (1,1) double = 0
    options.MaximumMappingErrorDeg (1,1) double = 10
end

validateCounts( ...
    total_source_count, ...
    in_plane_source_count);

validateOptions(options);

candidate_cfg = ...
    cfg;

candidate_cfg.source.layout = ...
    "vibrator_bank";

candidate_cfg.source.side = ...
    "multiface";

candidate_cfg.source.vibrator_count = ...
    total_source_count;

stream = ...
    RandStream( ...
        "mt19937ar", ...
        "Seed", ...
        double(options.Seed));

best_score = ...
    -Inf;

best_candidate = ...
    struct();

feasible_candidate_count = ...
    0;

rejection_counts = struct( ...
    "mapping_or_overlap", 0, ...
    "plane_count", 0, ...
    "face_count", 0, ...
    "dimension", 0, ...
    "bias", 0, ...
    "third_eigenvalue", 0, ...
    "axis_separation", 0, ...
    "mapping_error", 0);

for candidate_index = 1:options.CandidateCount
    desired_directions_xyz = ...
        generateCandidateDirections( ...
            stream, ...
            total_source_count, ...
            in_plane_source_count, ...
            options.MinimumOutOfPlaneComponent);

    try
        [contact_specs, mapping] = ...
            kwsim.three_d.contactSpecsFromDirections( ...
                candidate_cfg, ...
                desired_directions_xyz);

        bank = ...
            kwsim.three_d.resolveVibratorBankFromFaceSpecs( ...
                candidate_cfg, ...
                contact_specs);

    catch exception
        if isExpectedCandidateFailure(exception)
            rejection_counts.mapping_or_overlap = ...
                rejection_counts.mapping_or_overlap + 1;

            continue
        end

        rethrow(exception)
    end

    metrics_cfg = ...
        candidate_cfg;

    metrics_cfg.source.vibrators = ...
        bank.vibrators;

    metrics_cfg.source.face_set = ...
        bank.face_set;

    metrics_cfg.source.face_counts = ...
        bank.face_counts;

    metrics = ...
        kwsim.analysis.summarizeSourceGeometry3D( ...
            metrics_cfg);

    if metrics.in_plane_contact_count ~= ...
            in_plane_source_count || ...
            metrics.centered_in_plane_contact_count ~= ...
            in_plane_source_count

        rejection_counts.plane_count = ...
            rejection_counts.plane_count + 1;

        continue
    end

    if metrics.unique_face_count < ...
            options.MinimumUniqueFaces

        rejection_counts.face_count = ...
            rejection_counts.face_count + 1;

        continue
    end

    if metrics.effective_angular_dimension < ...
            options.MinimumEffectiveDimension

        rejection_counts.dimension = ...
            rejection_counts.dimension + 1;

        continue
    end

    if metrics.directional_bias > ...
            options.MaximumDirectionalBias

        rejection_counts.bias = ...
            rejection_counts.bias + 1;

        continue
    end

    third_eigenvalue = ...
        metrics.angular_eigenvalues_descending(3);

    if third_eigenvalue < ...
            options.MinimumThirdEigenvalue

        rejection_counts.third_eigenvalue = ...
            rejection_counts.third_eigenvalue + 1;

        continue
    end

    minimum_axis_angle_deg = ...
        metrics.pairwise_axis_angle_min_deg;

    if isnan(minimum_axis_angle_deg)
        minimum_axis_angle_deg = ...
            90;
    end

    if minimum_axis_angle_deg < ...
            options.MinimumAxisSeparationDeg

        rejection_counts.axis_separation = ...
            rejection_counts.axis_separation + 1;

        continue
    end

    if mapping.maximum_angular_error_deg > ...
            options.MaximumMappingErrorDeg

        rejection_counts.mapping_error = ...
            rejection_counts.mapping_error + 1;

        continue
    end

    feasible_candidate_count = ...
        feasible_candidate_count + 1;

    score = ...
        candidateScore( ...
            metrics, ...
            mapping);

    if score > best_score
        best_score = ...
            score;

        best_candidate = struct();

        best_candidate.candidate_index = ...
            candidate_index;

        best_candidate.score = ...
            score;

        best_candidate.desired_directions_xyz = ...
            desired_directions_xyz;

        best_candidate.contact_specs = ...
            contact_specs;

        best_candidate.mapping = ...
            mapping;

        best_candidate.bank = ...
            bank;

        best_candidate.geometry_metrics = ...
            metrics;
    end
end

if ~isfinite(best_score)
    error( ...
        "kwsim:NoFeasibleAngularSourceBank", ...
        "No feasible N=%d, P=%d angular bank was found after %d " + ...
        "candidates. Rejections: mapping/overlap=%d, plane=%d, " + ...
        "faces=%d, Deff=%d, bias=%d, lambda3=%d, axis=%d, mapping=%d.", ...
        total_source_count, ...
        in_plane_source_count, ...
        options.CandidateCount, ...
        rejection_counts.mapping_or_overlap, ...
        rejection_counts.plane_count, ...
        rejection_counts.face_count, ...
        rejection_counts.dimension, ...
        rejection_counts.bias, ...
        rejection_counts.third_eigenvalue, ...
        rejection_counts.axis_separation, ...
        rejection_counts.mapping_error);
end

generated = ...
    best_candidate;

generated.total_source_count = ...
    total_source_count;

generated.in_plane_source_count = ...
    in_plane_source_count;

generated.out_of_plane_source_count = ...
    total_source_count - ...
    in_plane_source_count;

generated.seed = ...
    options.Seed;

generated.candidate_count = ...
    options.CandidateCount;

generated.feasible_candidate_count = ...
    feasible_candidate_count;

generated.rejection_counts = ...
    rejection_counts;

generated.generation_options = ...
    options;

generated.bank.angular_generation = struct( ...
    "total_source_count", total_source_count, ...
    "in_plane_source_count", in_plane_source_count, ...
    "out_of_plane_source_count", ...
        total_source_count - in_plane_source_count, ...
    "seed", options.Seed, ...
    "selected_candidate_index", ...
        best_candidate.candidate_index, ...
    "score", best_score, ...
    "feasible_candidate_count", ...
        feasible_candidate_count, ...
    "candidate_count", ...
        options.CandidateCount, ...
    "desired_directions_xyz", ...
        best_candidate.desired_directions_xyz, ...
    "maximum_mapping_error_deg", ...
        best_candidate.mapping.maximum_angular_error_deg, ...
    "effective_angular_dimension", ...
        best_candidate.geometry_metrics. ...
            effective_angular_dimension, ...
    "directional_bias", ...
        best_candidate.geometry_metrics.directional_bias, ...
    "third_angular_eigenvalue", ...
        best_candidate.geometry_metrics. ...
            angular_eigenvalues_descending(3), ...
    "minimum_axis_separation_deg", ...
        best_candidate.geometry_metrics. ...
            pairwise_axis_angle_min_deg);

end


function directions_xyz = generateCandidateDirections( ...
        stream, ...
        total_source_count, ...
        in_plane_source_count, ...
        minimum_out_of_plane_component)

out_of_plane_source_count = ...
    total_source_count - ...
    in_plane_source_count;

in_plane_directions_xyz = ...
    zeros(in_plane_source_count, 3);

if in_plane_source_count > 0
    angular_offset = ...
        2*pi*rand(stream);

    sector_samples = ...
        ( ...
            (0:(in_plane_source_count - 1)).' + ...
            rand(stream, in_plane_source_count, 1) ...
        ) / ...
        in_plane_source_count;

    in_plane_angles_rad = ...
        angular_offset + ...
        2*pi*sector_samples;

    in_plane_directions_xyz(:, 1) = ...
        cos(in_plane_angles_rad);

    in_plane_directions_xyz(:, 3) = ...
        sin(in_plane_angles_rad);
end

out_of_plane_directions_xyz = ...
    zeros(out_of_plane_source_count, 3);

if out_of_plane_source_count > 0
    azimuth_offset = ...
        2*pi*rand(stream);

    azimuth_fraction = ...
        ( ...
            (0:(out_of_plane_source_count - 1)).' + ...
            rand(stream, out_of_plane_source_count, 1) ...
        ) / ...
        out_of_plane_source_count;

    azimuth_rad = ...
        azimuth_offset + ...
        2*pi*azimuth_fraction;

    maximum_component = ...
        0.92;

    absolute_y_component = ...
        minimum_out_of_plane_component + ...
        ( ...
            maximum_component - ...
            minimum_out_of_plane_component ...
        ) .* ...
        rand(stream, out_of_plane_source_count, 1);

    signs = ...
        ones(out_of_plane_source_count, 1);

    signs(2:2:end) = ...
        -1;

    permutation = ...
        randperm( ...
            stream, ...
            out_of_plane_source_count);

    signs = ...
        signs(permutation);

    y_component = ...
        signs .* ...
        absolute_y_component;

    in_plane_radius = ...
        sqrt( ...
            max( ...
                0, ...
                1 - y_component.^2));

    out_of_plane_directions_xyz(:, 1) = ...
        in_plane_radius .* ...
        cos(azimuth_rad);

    out_of_plane_directions_xyz(:, 2) = ...
        y_component;

    out_of_plane_directions_xyz(:, 3) = ...
        in_plane_radius .* ...
        sin(azimuth_rad);
end

directions_xyz = [
    in_plane_directions_xyz
    out_of_plane_directions_xyz
];

permutation = ...
    randperm( ...
        stream, ...
        total_source_count);

directions_xyz = ...
    directions_xyz(permutation, :);

end


function score = candidateScore(metrics, mapping)

eigenvalues = ...
    metrics.angular_eigenvalues_descending;

minimum_axis_angle_deg = ...
    metrics.pairwise_axis_angle_min_deg;

if isnan(minimum_axis_angle_deg)
    minimum_axis_angle_deg = ...
        90;
end

score = ...
    2.0 * metrics.effective_angular_dimension + ...
    3.0 * eigenvalues(3) - ...
    2.0 * metrics.directional_bias + ...
    0.010 * minimum_axis_angle_deg + ...
    0.10 * metrics.unique_face_count - ...
    0.020 * mapping.maximum_angular_error_deg;

end


function validateCounts( ...
        total_source_count, ...
        in_plane_source_count)

if ~( ...
        isfinite(total_source_count) && ...
        total_source_count == fix(total_source_count) && ...
        total_source_count >= 1)
    error( ...
        "kwsim:InvalidAngularSourceCount", ...
        "total_source_count must be a positive integer.");
end

if ~( ...
        isfinite(in_plane_source_count) && ...
        in_plane_source_count == fix(in_plane_source_count) && ...
        in_plane_source_count >= 0 && ...
        in_plane_source_count <= total_source_count)
    error( ...
        "kwsim:InvalidAngularSourceCount", ...
        "in_plane_source_count must be an integer between 0 and N.");
end

end


function validateOptions(options)

if ~( ...
        isfinite(options.CandidateCount) && ...
        options.CandidateCount == fix(options.CandidateCount) && ...
        options.CandidateCount >= 1)
    error( ...
        "kwsim:InvalidAngularGenerationOptions", ...
        "CandidateCount must be a positive integer.");
end

if ~( ...
        isfinite(options.MinimumOutOfPlaneComponent) && ...
        options.MinimumOutOfPlaneComponent > 0 && ...
        options.MinimumOutOfPlaneComponent < 1)
    error( ...
        "kwsim:InvalidAngularGenerationOptions", ...
        "MinimumOutOfPlaneComponent must lie strictly between 0 and 1.");
end

if options.MinimumUniqueFaces < 1 || ...
        options.MinimumUniqueFaces > 6
    error( ...
        "kwsim:InvalidAngularGenerationOptions", ...
        "MinimumUniqueFaces must lie between 1 and 6.");
end

if options.MinimumEffectiveDimension < 1 || ...
        options.MinimumEffectiveDimension > 3
    error( ...
        "kwsim:InvalidAngularGenerationOptions", ...
        "MinimumEffectiveDimension must lie between 1 and 3.");
end

if options.MaximumDirectionalBias < 0 || ...
        options.MaximumDirectionalBias > 1
    error( ...
        "kwsim:InvalidAngularGenerationOptions", ...
        "MaximumDirectionalBias must lie between 0 and 1.");
end

if options.MinimumThirdEigenvalue < 0 || ...
        options.MinimumThirdEigenvalue > (1/3)
    error( ...
        "kwsim:InvalidAngularGenerationOptions", ...
        "MinimumThirdEigenvalue must lie between 0 and 1/3.");
end

if options.MinimumAxisSeparationDeg < 0 || ...
        options.MinimumAxisSeparationDeg > 90
    error( ...
        "kwsim:InvalidAngularGenerationOptions", ...
        "MinimumAxisSeparationDeg must lie between 0 and 90.");
end

end


function expected = isExpectedCandidateFailure(exception)

expected_identifiers = [
    "kwsim:DirectionContactDoesNotFit"
    "kwsim:OverlappingVibratorContacts"
    "kwsim:InvalidVibratorCenterFraction"
    "kwsim:Invalid3DSourceBank"
];

expected = ...
    any(string(exception.identifier) == expected_identifiers);

end
