function contact = makeSparseDiskMaskOnFace(cfg, face, center_index_xyz)
%MAKESPARSEDISKMASKONFACE Build one sparse finite disk on a 3D grid face.
%
% Public coordinate order is [x,y,z]. The returned logical mask uses the
% k-Wave internal orientation [Nx,Ny,Nz].

arguments
    cfg struct
    face
    center_index_xyz (1,3) double
end

face = lower(string(face));

grid_size_xyz = [
    cfg.grid.Nx, ...
    cfg.grid.Ny, ...
    cfg.grid.Nz
];

grid_spacing_m_xyz = [
    cfg.grid.dx_m, ...
    cfg.grid.dy_m, ...
    cfg.grid.dz_m
];

if any(~isfinite(center_index_xyz)) || ...
        any(center_index_xyz ~= fix(center_index_xyz)) || ...
        any(center_index_xyz < 1) || ...
        any(center_index_xyz > grid_size_xyz)
    error( ...
        "kwsim:Invalid3DSourceCenter", ...
        "center_index_xyz must contain finite in-grid integer indices.");
end

boundary_margin_points_xyz = round( ...
    cfg.source.boundary_margin_m ./ ...
    grid_spacing_m_xyz);

switch face
    case "x_min"
        fixed_axis = 1;
        tangent_axes = [2, 3];
        source_plane_index = ...
            1 + boundary_margin_points_xyz(1);
        face_normal_xyz = [-1, 0, 0];
        tangent_axis_names = ["y", "z"];

    case "x_max"
        fixed_axis = 1;
        tangent_axes = [2, 3];
        source_plane_index = ...
            cfg.grid.Nx - boundary_margin_points_xyz(1);
        face_normal_xyz = [1, 0, 0];
        tangent_axis_names = ["y", "z"];

    case "y_min"
        fixed_axis = 2;
        tangent_axes = [1, 3];
        source_plane_index = ...
            1 + boundary_margin_points_xyz(2);
        face_normal_xyz = [0, -1, 0];
        tangent_axis_names = ["x", "z"];

    case "y_max"
        fixed_axis = 2;
        tangent_axes = [1, 3];
        source_plane_index = ...
            cfg.grid.Ny - boundary_margin_points_xyz(2);
        face_normal_xyz = [0, 1, 0];
        tangent_axis_names = ["x", "z"];

    case "z_min"
        fixed_axis = 3;
        tangent_axes = [1, 2];
        source_plane_index = ...
            1 + boundary_margin_points_xyz(3);
        face_normal_xyz = [0, 0, -1];
        tangent_axis_names = ["x", "y"];

    case "z_max"
        fixed_axis = 3;
        tangent_axes = [1, 2];
        source_plane_index = ...
            cfg.grid.Nz - boundary_margin_points_xyz(3);
        face_normal_xyz = [0, 0, 1];
        tangent_axis_names = ["x", "y"];

    otherwise
        error( ...
            "kwsim:Unsupported3DSourceFace", ...
            "Unsupported 3D source face: %s.", ...
            face);
end

if source_plane_index < 1 || ...
        source_plane_index > grid_size_xyz(fixed_axis)
    error( ...
        "kwsim:Invalid3DSourcePlane", ...
        "The boundary margin places the source plane outside the grid.");
end

if center_index_xyz(fixed_axis) ~= source_plane_index
    error( ...
        "kwsim:SourceCenterNotOnResolvedFace", ...
        "The source center must lie on the resolved %s plane.", ...
        face);
end

radius_m = ...
    double(cfg.source.contact_radius_m);

spacing_points = ...
    double(cfg.source.contact_node_spacing_points);

if ~(isscalar(radius_m) && ...
        isfinite(radius_m) && ...
        radius_m > 0)
    error( ...
        "kwsim:Invalid3DConfig", ...
        "source.contact_radius_m must be a positive finite scalar.");
end

if ~(isscalar(spacing_points) && ...
        isfinite(spacing_points) && ...
        spacing_points == fix(spacing_points) && ...
        spacing_points >= 1)
    error( ...
        "kwsim:Invalid3DConfig", ...
        "source.contact_node_spacing_points must be a positive integer.");
end

tangent_grid_size = ...
    grid_size_xyz(tangent_axes);

tangent_spacing_m = ...
    grid_spacing_m_xyz(tangent_axes);

tangent_center = ...
    center_index_xyz(tangent_axes);

required_radius_points = ...
    ceil(radius_m ./ tangent_spacing_m);

if any(tangent_center - required_radius_points < 1) || ...
        any(tangent_center + required_radius_points > tangent_grid_size)
    error( ...
        "kwsim:SourceContactExceedsTangentGrid", ...
        "The complete source disk must fit inside the tangent-plane grid.");
end

[tangent_grid_1, tangent_grid_2] = ...
    ndgrid( ...
        1:tangent_grid_size(1), ...
        1:tangent_grid_size(2));

offset_1_m = ...
    (tangent_grid_1 - tangent_center(1)) * ...
    tangent_spacing_m(1);

offset_2_m = ...
    (tangent_grid_2 - tangent_center(2)) * ...
    tangent_spacing_m(2);

inside_disk = ...
    offset_1_m.^2 + offset_2_m.^2 <= ...
    radius_m^2 + 10*eps(radius_m^2);

sampled_lattice = ...
    mod( ...
        tangent_grid_1 - tangent_center(1), ...
        spacing_points) == 0 & ...
    mod( ...
        tangent_grid_2 - tangent_center(2), ...
        spacing_points) == 0;

mask_tangent = ...
    inside_disk & sampled_lattice;

if nnz(mask_tangent) < 3
    error( ...
        "kwsim:Invalid3DSourceContact", ...
        "The sparse finite-disk source must contain at least three nodes.");
end

mask_xyz = ...
    false(cfg.grid.Nx, cfg.grid.Ny, cfg.grid.Nz);

switch fixed_axis
    case 1
        mask_xyz(source_plane_index, :, :) = ...
            reshape( ...
                mask_tangent, ...
                1, tangent_grid_size(1), tangent_grid_size(2));

    case 2
        mask_xyz(:, source_plane_index, :) = ...
            reshape( ...
                mask_tangent, ...
                tangent_grid_size(1), 1, tangent_grid_size(2));

    case 3
        mask_xyz(:, :, source_plane_index) = ...
            reshape( ...
                mask_tangent, ...
                tangent_grid_size(1), tangent_grid_size(2), 1);
end

node_linear_indices = ...
    find(mask_xyz);

[node_x, node_y, node_z] = ...
    ind2sub( ...
        grid_size_xyz, ...
        node_linear_indices);

node_subscripts_xyz = ...
    [node_x, node_y, node_z];

center_m_xyz = ...
    (center_index_xyz - 1) .* ...
    grid_spacing_m_xyz;

[tangent_node_1, tangent_node_2] = ...
    find(mask_tangent);

realized_radius_tangent_m = [
    max(abs(tangent_node_1 - tangent_center(1))) * ...
        tangent_spacing_m(1), ...
    max(abs(tangent_node_2 - tangent_center(2))) * ...
        tangent_spacing_m(2)
];

contact = struct();
contact.face = face;
contact.face_normal_xyz = face_normal_xyz;
contact.source_plane_index = source_plane_index;
contact.center_index_xyz = center_index_xyz;
contact.center_m_xyz = center_m_xyz;
contact.mask_xyz = mask_xyz;
contact.node_linear_indices = node_linear_indices;
contact.node_subscripts_xyz = node_subscripts_xyz;
contact.node_count = numel(node_linear_indices);
contact.tangent_axis_names = tangent_axis_names;
contact.realized_radius_tangent_m = ...
    realized_radius_tangent_m;

end
