function disk = makeSparseDiskMaskYZ(cfg, center_y, center_z)
%MAKESPARSEDISKMASKYZ Build one sparse finite disk in a y-z plane.

arguments
    cfg struct
    center_y (1,1) double
    center_z (1,1) double
end

if center_y ~= fix(center_y) || ...
        center_z ~= fix(center_z) || ...
        center_y < 1 || ...
        center_y > cfg.grid.Ny || ...
        center_z < 1 || ...
        center_z > cfg.grid.Nz
    error( ...
        "kwsim:Invalid3DSourceCenter", ...
        "Sparse-disk center indices must lie inside the y-z grid.");
end

[y_grid, z_grid] = ...
    ndgrid(1:cfg.grid.Ny, 1:cfg.grid.Nz);

offset_y_m = ...
    (y_grid - center_y) * cfg.grid.dy_m;

offset_z_m = ...
    (z_grid - center_z) * cfg.grid.dz_m;

inside_disk = ...
    offset_y_m.^2 + offset_z_m.^2 <= ...
    cfg.source.contact_radius_m^2 + ...
    10*eps(cfg.source.contact_radius_m^2);

spacing = ...
    cfg.source.contact_node_spacing_points;

sampled_lattice = ...
    mod(y_grid - center_y, spacing) == 0 & ...
    mod(z_grid - center_z, spacing) == 0;

mask_yz = ...
    inside_disk & sampled_lattice;

if ~any(mask_yz, "all")
    error( ...
        "kwsim:Invalid3DConfig", ...
        "The finite-disk source contains no sampled grid points.");
end

if nnz(mask_yz) < 3
    error( ...
        "kwsim:Invalid3DConfig", ...
        "The finite-disk source must contain at least three sampled nodes.");
end

[node_y, node_z] = ...
    find(mask_yz);

disk = struct();

disk.mask_yz = ...
    mask_yz;

disk.node_subscripts_yz = ...
    [node_y, node_z];

disk.node_count = ...
    nnz(mask_yz);

disk.realized_radius_y_m = ...
    max(abs(node_y - center_y)) * ...
    cfg.grid.dy_m;

disk.realized_radius_z_m = ...
    max(abs(node_z - center_z)) * ...
    cfg.grid.dz_m;

end
