function [cfg, source_x] = resolveGeneratedAngularBankConfig(cfg)
%RESOLVEGENERATEDANGULARBANKCONFIG Resolve an optimized N/P angular bank.
%
% N is source.vibrator_count.
% P is source.exact_in_plane_sources.
%
% Geometry generation uses source.geometry_seed. Source phases continue to
% use cfg.seed, allowing fixed geometry with independent phase replicates.

arguments
    cfg struct
end

number_of_sources = ...
    positiveInteger( ...
        cfg.source.vibrator_count, ...
        "source.vibrator_count");

in_plane_requested = ...
    nonnegativeInteger( ...
        cfg.source.exact_in_plane_sources, ...
        "source.exact_in_plane_sources");

if in_plane_requested > number_of_sources
    error( ...
        "kwsim:InvalidGeneratedAngularBank", ...
        "source.exact_in_plane_sources cannot exceed vibrator_count.");
end

out_of_plane_requested = ...
    number_of_sources - in_plane_requested;

placement_policy = ...
    lower(string(cfg.source.placement_policy));

switch placement_policy
    case "angular_random_search"
        generated = ...
            kwsim.three_d.generateAngularVibratorBank( ...
                cfg, ...
                number_of_sources, ...
                in_plane_requested, ...
                Seed=double(cfg.source.geometry_seed), ...
                CandidateCount=double( ...
                    cfg.source.angular_candidate_count), ...
                MinimumOutOfPlaneComponent=double( ...
                    cfg.source.minimum_out_of_plane_component), ...
                MinimumUniqueFaces=double( ...
                    cfg.source.minimum_unique_faces), ...
                MinimumEffectiveDimension=double( ...
                    cfg.source.minimum_effective_angular_dimension), ...
                MaximumDirectionalBias=double( ...
                    cfg.source.maximum_directional_bias), ...
                MinimumThirdEigenvalue=double( ...
                    cfg.source.minimum_third_angular_eigenvalue), ...
                MinimumAxisSeparationDeg=double( ...
                    cfg.source.minimum_axis_separation_deg), ...
                MaximumMappingErrorDeg=double( ...
                    cfg.source.maximum_mapping_error_deg));

    case "packed_face_grid"
        generated = ...
            kwsim.three_d.generatePackedFaceGridBank( ...
                cfg, ...
                number_of_sources, ...
                in_plane_requested);

    otherwise
        error( ...
            "kwsim:InvalidGeneratedAngularBank", ...
            "Unsupported source.placement_policy: %s.", ...
            placement_policy);
end

bank = ...
    generated.bank;

acquisition_y_index_full = ...
    round((cfg.grid.Ny + 1) / 2);

in_plane_count = 0;
centered_in_plane_count = 0;

for vibrator_index = 1:numel(bank.vibrators)
    node_indices = ...
        bank.vibrators(vibrator_index).node_linear_indices;

    [~, node_y, ~] = ...
        ind2sub( ...
            size(bank.union_mask_xyz), ...
            node_indices);

    intersects_plane = ...
        any(node_y == acquisition_y_index_full);

    centered_on_plane = ...
        bank.vibrators(vibrator_index).center_index_xyz(2) == ...
        acquisition_y_index_full;

    bank.vibrators(vibrator_index). ...
        intersects_acquisition_plane = ...
        intersects_plane;

    bank.vibrators(vibrator_index). ...
        centered_on_acquisition_plane = ...
        centered_on_plane;

    in_plane_count = ...
        in_plane_count + double(intersects_plane);

    centered_in_plane_count = ...
        centered_in_plane_count + ...
        double(centered_on_plane);
end

out_of_plane_count = ...
    bank.contact_count - in_plane_count;

if in_plane_count ~= in_plane_requested || ...
        centered_in_plane_count ~= in_plane_requested || ...
        out_of_plane_count ~= out_of_plane_requested
    error( ...
        "kwsim:InvalidGeneratedAngularBank", ...
        "Generated bank requested P=%d but resolved " + ...
        "%d intersecting, %d centered, and %d out-of-plane contacts.", ...
        in_plane_requested, ...
        in_plane_count, ...
        centered_in_plane_count, ...
        out_of_plane_count);
end

minimum_in_plane_sources = ...
    nonnegativeInteger( ...
        cfg.source.minimum_in_plane_sources, ...
        "source.minimum_in_plane_sources");

minimum_out_of_plane_sources = ...
    nonnegativeInteger( ...
        cfg.source.minimum_out_of_plane_sources, ...
        "source.minimum_out_of_plane_sources");

if in_plane_count < minimum_in_plane_sources
    error( ...
        "kwsim:InsufficientInPlaneSources", ...
        "The generated bank does not meet minimum_in_plane_sources.");
end

if out_of_plane_count < minimum_out_of_plane_sources
    error( ...
        "kwsim:InsufficientOutOfPlaneSources", ...
        "The generated bank does not meet minimum_out_of_plane_sources.");
end

active_linear_indices = ...
    find(bank.union_mask_xyz);

[node_x, node_y, node_z] = ...
    ind2sub( ...
        size(bank.union_mask_xyz), ...
        active_linear_indices);

cfg.source.vibrators = ...
    bank.vibrators;

cfg.source.vibrator_count = ...
    bank.contact_count;

cfg.source.contact_node_count = ...
    bank.total_contact_node_count;

cfg.source.contact_mask_xyz = ...
    bank.union_mask_xyz;

cfg.source.contact_node_subscripts_xyz = ...
    [node_x, node_y, node_z];

cfg.source.reference_single_contact_node_count = ...
    bank.reference_single_contact_node_count;

cfg.source.nominal_total_drive_rms_squared_m2_s2 = ...
    bank.nominal_total_drive_rms_squared_m2_s2;

cfg.source.face_set = ...
    bank.face_set;

cfg.source.supported_faces = ...
    bank.supported_faces;

cfg.source.face_counts = ...
    bank.face_counts;

cfg.source.acquisition_plane_y_index_full = ...
    acquisition_y_index_full;

cfg.source.in_plane_vibrator_count = ...
    in_plane_count;

cfg.source.centered_in_plane_vibrator_count = ...
    centered_in_plane_count;

cfg.source.out_of_plane_vibrator_count = ...
    out_of_plane_count;

cfg.source.contact_specs = ...
    generated.contact_specs;

cfg.source.desired_directions_xyz = ...
    generated.desired_directions_xyz;

cfg.source.angular_mapping = ...
    generated.mapping;

cfg.source.angular_generation = ...
    bank.angular_generation;

cfg.source.angular_generation_score = ...
    generated.score;

cfg.source.angular_generation_candidate_index = ...
    generated.candidate_index;

cfg.source.angular_generation_feasible_candidates = ...
    generated.feasible_candidate_count;

cfg.source.angular_generation_rejection_counts = ...
    generated.rejection_counts;

grid_spacing_m_xyz = [
    cfg.grid.dx_m, ...
    cfg.grid.dy_m, ...
    cfg.grid.dz_m
];

realized_radius_xyz_m = ...
    zeros(1, 3);

for vibrator_index = 1:numel(cfg.source.vibrators)
    vibrator = ...
        cfg.source.vibrators(vibrator_index);

    [node_x_this, node_y_this, node_z_this] = ...
        ind2sub( ...
            size(bank.union_mask_xyz), ...
            vibrator.node_linear_indices);

    node_subscripts_xyz = ...
        [node_x_this, node_y_this, node_z_this];

    offsets_m_xyz = ...
        abs( ...
            (node_subscripts_xyz - ...
            vibrator.center_index_xyz) .* ...
            grid_spacing_m_xyz);

    realized_radius_xyz_m = ...
        max( ...
            realized_radius_xyz_m, ...
            max(offsets_m_xyz, [], 1));
end

cfg.source.realized_radius_x_m = ...
    realized_radius_xyz_m(1);

cfg.source.realized_radius_y_m = ...
    realized_radius_xyz_m(2);

cfg.source.realized_radius_z_m = ...
    realized_radius_xyz_m(3);

source_x = ...
    min(node_x);

cfg.source.source_x_index = ...
    source_x;

cfg.source.center_index_xyz = [
    round((cfg.grid.Nx + 1) / 2), ...
    acquisition_y_index_full, ...
    round((cfg.grid.Nz + 1) / 2)
];

cfg.source.center_m_xyz = ...
    (cfg.source.center_index_xyz - 1) .* ...
    grid_spacing_m_xyz;

end


function value = positiveInteger(value, field_name)

value = ...
    double(value);

if ~(isscalar(value) && ...
        isfinite(value) && ...
        value == fix(value) && ...
        value >= 1)
    error( ...
        "kwsim:InvalidGeneratedAngularBank", ...
        "%s must be a positive integer.", ...
        field_name);
end

end


function value = nonnegativeInteger(value, field_name)

value = ...
    double(value);

if ~(isscalar(value) && ...
        isfinite(value) && ...
        value == fix(value) && ...
        value >= 0)
    error( ...
        "kwsim:InvalidGeneratedAngularBank", ...
        "%s must be a nonnegative integer.", ...
        field_name);
end

end
