function [cfg, source_x] = resolveVibratorBankConfig(cfg)
%RESOLVEVIBRATORBANKCONFIG Resolve the partial-diffuse eight-source bank.
%
% The initial bank places eight non-overlapping contacts on the left x
% plane. Their nominal propagation directions point toward the domain
% center, producing different in-plane and out-of-plane directions.
%
% Random phases are generated with a local reproducible stream and do not
% alter MATLAB's global random-number state.

arguments
    cfg struct
end

bank_name = ...
    lower(string(cfg.source.bank_name));

if bank_name == "generated_angular"
    [cfg, source_x] = ...
        kwsim.three_d.resolveGeneratedAngularBankConfig(cfg);
    return
end

if bank_name == "partial_3d_n8_p2"
    [cfg, source_x] = ...
        kwsim.three_d.resolvePartial3DN8P2Config(cfg);
    return
end

if bank_name ~= "partial_diffuse_8"
    error( ...
        "kwsim:Unsupported3DSourceBank", ...
        "Unsupported 3D source bank: %s.", ...
        bank_name);
end

if cfg.source.vibrator_count ~= 8
    error( ...
        "kwsim:Invalid3DSourceBank", ...
        "partial_diffuse_8 requires source.vibrator_count = 8.");
end

if lower(string(cfg.source.phase_policy)) ~= ...
        "random_uniform"
    error( ...
        "kwsim:Invalid3DSourceBank", ...
        "partial_diffuse_8 requires phase_policy=random_uniform.");
end

if lower(string(cfg.source.amplitude_policy)) ~= ...
        "equal_total_rms"
    error( ...
        "kwsim:Invalid3DSourceBank", ...
        "partial_diffuse_8 requires amplitude_policy=equal_total_rms.");
end

if lower(string(cfg.source.polarization_policy)) ~= ...
        "project_axial_transverse"
    error( ...
        "kwsim:Invalid3DSourceBank", ...
        "Unsupported vibrator-bank polarization policy.");
end

boundary_points_x = ...
    round(cfg.source.boundary_margin_m / cfg.grid.dx_m);

source_x = ...
    1 + boundary_points_x;

if source_x < 1 || source_x > cfg.grid.Nx
    error( ...
        "kwsim:Invalid3DConfig", ...
        "The source boundary margin places the bank outside the grid.");
end

radius_points_y = ...
    ceil(cfg.source.contact_radius_m / cfg.grid.dy_m);

radius_points_z = ...
    ceil(cfg.source.contact_radius_m / cfg.grid.dz_m);

minimum_y = ...
    1 + radius_points_y;

maximum_y = ...
    cfg.grid.Ny - radius_points_y;

minimum_z = ...
    1 + radius_points_z;

maximum_z = ...
    cfg.grid.Nz - radius_points_z;

if minimum_y >= maximum_y || ...
        minimum_z >= maximum_z
    error( ...
        "kwsim:Invalid3DSourceBank", ...
        "The grid is too small for the requested source contacts.");
end

% Eight perimeter positions in the available y-z region. The middle-left
% and middle-right positions intersect the central elevational plane.
center_fractions_yz = [
    0.15, 0.15
    0.50, 0.15
    0.85, 0.15
    0.15, 0.50
    0.85, 0.50
    0.15, 0.85
    0.50, 0.85
    0.85, 0.85
];

center_y = round( ...
    minimum_y + ...
    center_fractions_yz(:,1) * ...
    (maximum_y - minimum_y));

center_z = round( ...
    minimum_z + ...
    center_fractions_yz(:,2) * ...
    (maximum_z - minimum_z));

center_indices_yz = ...
    [center_y, center_z];

if size(unique(center_indices_yz, "rows"), 1) ~= 8
    error( ...
        "kwsim:Invalid3DSourceBank", ...
        "The grid is too small to realize eight distinct contacts.");
end

template = struct( ...
    "name", "", ...
    "node_linear_indices", [], ...
    "center_index_xyz", [NaN, NaN, NaN], ...
    "center_m_xyz", [NaN, NaN, NaN], ...
    "polarization_xyz", [NaN, NaN, NaN], ...
    "nominal_propagation_xyz", [NaN, NaN, NaN], ...
    "phase_rad", NaN, ...
    "velocity_amplitude_m_s", NaN, ...
    "contact_node_count", 0, ...
    "realized_radius_y_m", NaN, ...
    "realized_radius_z_m", NaN);

vibrators = ...
    repmat(template, 8, 1);

occupied_nodes = ...
    false(cfg.grid.Nx, cfg.grid.Ny, cfg.grid.Nz);

domain_center_m_xyz = ...
    0.5 * cfg.derived.domain_size_m_xyz;

node_counts = ...
    zeros(8, 1);

for vibrator_index = 1:8
    this_y = ...
        center_y(vibrator_index);

    this_z = ...
        center_z(vibrator_index);

    disk = ...
        kwsim.three_d.makeSparseDiskMaskYZ( ...
            cfg, ...
            this_y, ...
            this_z);

    contact_mask_xyz = ...
        false(cfg.grid.Nx, cfg.grid.Ny, cfg.grid.Nz);

    contact_mask_xyz(source_x, :, :) = ...
        reshape( ...
            disk.mask_yz, ...
            1, cfg.grid.Ny, cfg.grid.Nz);

    if any( ...
            occupied_nodes & contact_mask_xyz, ...
            "all")
        error( ...
            "kwsim:OverlappingVibratorContacts", ...
            "Resolved vibrator contacts overlap.");
    end

    occupied_nodes = ...
        occupied_nodes | contact_mask_xyz;

    center_index_xyz = ...
        [source_x, this_y, this_z];

    center_m_xyz = [
        cfg.derived.x_full_m(source_x), ...
        cfg.derived.y_full_m(this_y), ...
        cfg.derived.z_full_m(this_z)
    ];

    direction = ...
        domain_center_m_xyz - center_m_xyz;

    direction = ...
        direction / norm(direction);

    % Project the axial unit vector onto the plane perpendicular to the
    % nominal propagation direction. This preserves a strong axial
    % displacement component while maintaining transverse polarization.
    axial_unit = ...
        [0, 0, 1];

    polarization = ...
        axial_unit - ...
        dot(axial_unit, direction) * direction;

    if norm(polarization) < 1e-10
        elevational_unit = ...
            [0, 1, 0];

        polarization = ...
            elevational_unit - ...
            dot(elevational_unit, direction) * direction;
    end

    polarization = ...
        polarization / norm(polarization);

    vibrators(vibrator_index).name = ...
        "vibrator_" + string(vibrator_index);

    vibrators(vibrator_index).node_linear_indices = ...
        find(contact_mask_xyz);

    vibrators(vibrator_index).center_index_xyz = ...
        center_index_xyz;

    vibrators(vibrator_index).center_m_xyz = ...
        center_m_xyz;

    vibrators(vibrator_index).polarization_xyz = ...
        polarization;

    vibrators(vibrator_index).nominal_propagation_xyz = ...
        direction;

    vibrators(vibrator_index).contact_node_count = ...
        disk.node_count;

    vibrators(vibrator_index).realized_radius_y_m = ...
        disk.realized_radius_y_m;

    vibrators(vibrator_index).realized_radius_z_m = ...
        disk.realized_radius_z_m;

    node_counts(vibrator_index) = ...
        disk.node_count;
end

% Reference drive: one central contact using the configured base amplitude.
reference_y = ...
    round((cfg.grid.Ny + 1) / 2);

reference_z = ...
    round((cfg.grid.Nz + 1) / 2);

reference_disk = ...
    kwsim.three_d.makeSparseDiskMaskYZ( ...
        cfg, ...
        reference_y, ...
        reference_z);

reference_node_count = ...
    reference_disk.node_count;

% Give each vibrator one eighth of the reference RMS drive. This also
% handles possible small differences in realized contact-node counts.
for vibrator_index = 1:8
    vibrators(vibrator_index).velocity_amplitude_m_s = ...
        cfg.source.velocity_amplitude_m_s * ...
        sqrt( ...
            reference_node_count / ...
            (8 * node_counts(vibrator_index)));
end

phase_stream = ...
    RandStream( ...
        "mt19937ar", ...
        "Seed", ...
        double(cfg.seed));

phases_rad = ...
    2*pi*rand(phase_stream, 8, 1);

for vibrator_index = 1:8
    vibrators(vibrator_index).phase_rad = ...
        phases_rad(vibrator_index);
end

cfg.source.vibrators = ...
    vibrators;

cfg.source.vibrator_count = ...
    numel(vibrators);

cfg.source.bank_center_fractions_yz = ...
    center_fractions_yz;

cfg.source.reference_single_contact_node_count = ...
    reference_node_count;

cfg.source.contact_node_count = ...
    sum(node_counts);

% Aggregate compatibility metadata. These fields preserve the source
% contract previously established for a single finite-disk contact.
cfg.source.contact_radius_points_y = ...
    round(cfg.source.contact_radius_m / cfg.grid.dy_m);

cfg.source.contact_radius_points_z = ...
    round(cfg.source.contact_radius_m / cfg.grid.dz_m);

cfg.source.realized_radius_y_m = ...
    max([vibrators.realized_radius_y_m]);

cfg.source.realized_radius_z_m = ...
    max([vibrators.realized_radius_z_m]);

% All contacts currently lie on a common x plane. Store the union in the
% legacy y-z mask fields so diagnostics and configuration summaries can
% treat the complete bank as one resolved source layout.
bank_mask_yz = ...
    squeeze(occupied_nodes(source_x, :, :));

[bank_node_y, bank_node_z] = ...
    find(bank_mask_yz);

cfg.source.contact_mask_yz = ...
    bank_mask_yz;

cfg.source.contact_node_subscripts_yz = ...
    [bank_node_y, bank_node_z];

cfg.source.source_x_index = ...
    source_x;

% Representative center retained for compatibility with downstream sensor
% and metadata logic.
cfg.source.center_index_xyz = [
    source_x, ...
    reference_y, ...
    reference_z
];

cfg.source.center_m_xyz = [
    cfg.derived.x_full_m(source_x), ...
    cfg.derived.y_full_m(reference_y), ...
    cfg.derived.z_full_m(reference_z)
];

end
