function cfg = resolveMaterialGeometryConfig(cfg)
%RESOLVEMATERIALGEOMETRYCONFIG Validate and normalize 3D material geometry.
%
% Supported geometry:
%   - zero or one bilayer defined by an infinite plane;
%   - finite spheres;
%   - finite cylinders with arbitrary three-dimensional orientation.
%
% The precedence used later by buildMaterialMaps is:
%
%   background -> bilayer -> cylinders -> spheres
%
% Object coordinates are public physical coordinates [x,y,z] in metres.

arguments
    cfg struct
end

if ~isfield(cfg, "geometry") || ~isstruct(cfg.geometry)
    error( ...
        "kwsim:Invalid3DMaterialGeometry", ...
        "The configuration must contain a geometry structure.");
end

background = struct();
background.material_id = uint16(1);
background.cs_m_s = double(cfg.medium.cs_m_s);
background.cp_m_s = double(cfg.medium.cp_m_s);
background.rho_kg_m3 = double(cfg.medium.rho_kg_m3);

if isfield(cfg.geometry, "background_material_id")
    validateMaterialId( ...
        cfg.geometry.background_material_id, ...
        "geometry.background_material_id");

    background.material_id = ...
        uint16(cfg.geometry.background_material_id);
end

cfg.geometry.background_material_id = ...
    background.material_id;

if ~isfield(cfg.geometry, "minimum_boundary_clearance_m")
    cfg.geometry.minimum_boundary_clearance_m = ...
        0;
end

clearance_m = ...
    double(cfg.geometry.minimum_boundary_clearance_m);

if ~( ...
        isscalar(clearance_m) && ...
        isfinite(clearance_m) && ...
        clearance_m >= 0)
    error( ...
        "kwsim:Invalid3DMaterialGeometry", ...
        "geometry.minimum_boundary_clearance_m must be finite and nonnegative.");
end

if ~isfield(cfg.geometry, "require_objects_inside_sensor_roi")
    cfg.geometry.require_objects_inside_sensor_roi = ...
        false;
end

if ~( ...
        islogical(cfg.geometry.require_objects_inside_sensor_roi) && ...
        isscalar(cfg.geometry.require_objects_inside_sensor_roi))
    error( ...
        "kwsim:Invalid3DMaterialGeometry", ...
        "geometry.require_objects_inside_sensor_roi must be a logical scalar.");
end

domain_max_m_xyz = [
    (cfg.grid.Nx - 1) * cfg.grid.dx_m, ...
    (cfg.grid.Ny - 1) * cfg.grid.dy_m, ...
    (cfg.grid.Nz - 1) * cfg.grid.dz_m
];

%% Bilayer

default_material = struct( ...
    "material_id", uint16(0), ...
    "cs_m_s", NaN, ...
    "cp_m_s", NaN, ...
    "rho_kg_m3", NaN);

default_bilayer = struct( ...
    "enabled", false, ...
    "interface_point_m_xyz", [NaN, NaN, NaN], ...
    "normal_xyz", [NaN, NaN, NaN], ...
    "negative_material", default_material, ...
    "positive_material", default_material);

if ~isfield(cfg.geometry, "bilayer") || ...
        isempty(cfg.geometry.bilayer)
    bilayer = ...
        default_bilayer;
else
    bilayer = ...
        cfg.geometry.bilayer;
end

bilayer.enabled = ...
    fieldOrDefault( ...
        bilayer, ...
        "enabled", ...
        false);

if ~(islogical(bilayer.enabled) && isscalar(bilayer.enabled))
    error( ...
        "kwsim:Invalid3DMaterialGeometry", ...
        "geometry.bilayer.enabled must be a logical scalar.");
end

if bilayer.enabled
    interface_point_m_xyz = ...
        finiteVector3( ...
            fieldOrDefault( ...
                bilayer, ...
                "interface_point_m_xyz", ...
                [NaN, NaN, NaN]), ...
            "geometry.bilayer.interface_point_m_xyz");

    if any(interface_point_m_xyz < 0) || ...
            any(interface_point_m_xyz > domain_max_m_xyz)
        error( ...
            "kwsim:MaterialGeometryOutsideDomain", ...
            "The bilayer interface point must lie inside the domain.");
    end

    normal_xyz = ...
        finiteVector3( ...
            fieldOrDefault( ...
                bilayer, ...
                "normal_xyz", ...
                [NaN, NaN, NaN]), ...
            "geometry.bilayer.normal_xyz");

    if norm(normal_xyz) <= 0
        error( ...
            "kwsim:Invalid3DMaterialGeometry", ...
            "geometry.bilayer.normal_xyz must be nonzero.");
    end

    bilayer.interface_point_m_xyz = ...
        interface_point_m_xyz;

    bilayer.normal_xyz = ...
        normal_xyz / norm(normal_xyz);

    bilayer.negative_material = ...
        resolveMaterial( ...
            fieldOrDefault( ...
                bilayer, ...
                "negative_material", ...
                default_material), ...
            background, ...
            "geometry.bilayer.negative_material");

    bilayer.positive_material = ...
        resolveMaterial( ...
            fieldOrDefault( ...
                bilayer, ...
                "positive_material", ...
                default_material), ...
            background, ...
            "geometry.bilayer.positive_material");
else
    bilayer = ...
        default_bilayer;
end

cfg.geometry.bilayer = ...
    bilayer;

%% Finite objects

if ~isfield(cfg.geometry, "objects") || ...
        isempty(cfg.geometry.objects)
    requested_objects = ...
        struct([]);
elseif ~isstruct(cfg.geometry.objects)
    error( ...
        "kwsim:Invalid3DMaterialGeometry", ...
        "geometry.objects must be a structure array.");
else
    requested_objects = ...
        cfg.geometry.objects;
end

object_template = struct( ...
    "type", "", ...
    "name", "", ...
    "center_m_xyz", [NaN, NaN, NaN], ...
    "axis_xyz", [NaN, NaN, NaN], ...
    "radius_m", NaN, ...
    "length_m", NaN, ...
    "material_id", uint16(0), ...
    "cs_m_s", NaN, ...
    "cp_m_s", NaN, ...
    "rho_kg_m3", NaN, ...
    "bounding_box_min_m_xyz", [NaN, NaN, NaN], ...
    "bounding_box_max_m_xyz", [NaN, NaN, NaN]);

resolved_objects = ...
    repmat( ...
        object_template, ...
        numel(requested_objects), ...
        1);

for object_index = 1:numel(requested_objects)
    requested = ...
        requested_objects(object_index);

    object_type = ...
        lower(string( ...
            fieldOrDefault( ...
                requested, ...
                "type", ...
                "")));

    if ~any(object_type == ["sphere", "cylinder"])
        error( ...
            "kwsim:Unsupported3DMaterialGeometry", ...
            "geometry.objects(%d).type must be sphere or cylinder.", ...
            object_index);
    end

    object_name = ...
        string( ...
            fieldOrDefault( ...
                requested, ...
                "name", ...
                ""));

    if strlength(object_name) == 0
        object_name = ...
            object_type + "_" + string(object_index);
    end

    center_m_xyz = ...
        finiteVector3( ...
            fieldOrDefault( ...
                requested, ...
                "center_m_xyz", ...
                [NaN, NaN, NaN]), ...
            sprintf( ...
                "geometry.objects(%d).center_m_xyz", ...
                object_index));

    radius_m = ...
        positiveScalarValue( ...
            fieldOrDefault( ...
                requested, ...
                "radius_m", ...
                NaN), ...
            sprintf( ...
                "geometry.objects(%d).radius_m", ...
                object_index));

    material = ...
        resolveMaterial( ...
            requested, ...
            background, ...
            sprintf( ...
                "geometry.objects(%d)", ...
                object_index));

    axis_xyz = ...
        [NaN, NaN, NaN];

    length_m = ...
        NaN;

    switch object_type
        case "sphere"
            half_extent_m_xyz = ...
                radius_m * ones(1, 3);

        case "cylinder"
            axis_xyz = ...
                finiteVector3( ...
                    fieldOrDefault( ...
                        requested, ...
                        "axis_xyz", ...
                        [NaN, NaN, NaN]), ...
                    sprintf( ...
                        "geometry.objects(%d).axis_xyz", ...
                        object_index));

            if norm(axis_xyz) <= 0
                error( ...
                    "kwsim:Invalid3DMaterialGeometry", ...
                    "Cylinder axis_xyz must be nonzero.");
            end

            axis_xyz = ...
                axis_xyz / norm(axis_xyz);

            length_m = ...
                positiveScalarValue( ...
                    fieldOrDefault( ...
                        requested, ...
                        "length_m", ...
                        NaN), ...
                    sprintf( ...
                        "geometry.objects(%d).length_m", ...
                        object_index));

            half_extent_m_xyz = ...
                0.5 * length_m * abs(axis_xyz) + ...
                radius_m * ...
                sqrt(max(0, 1 - axis_xyz.^2));
    end

    bounding_box_min_m_xyz = ...
        center_m_xyz - ...
        half_extent_m_xyz;

    bounding_box_max_m_xyz = ...
        center_m_xyz + ...
        half_extent_m_xyz;

    if any( ...
            bounding_box_min_m_xyz < ...
            clearance_m) || ...
            any( ...
            bounding_box_max_m_xyz > ...
            domain_max_m_xyz - clearance_m)
        error( ...
            "kwsim:MaterialGeometryOutsideDomain", ...
            "Material object '%s' does not fit inside the domain clearance.", ...
            object_name);
    end

    resolved_objects(object_index).type = ...
        object_type;

    resolved_objects(object_index).name = ...
        object_name;

    resolved_objects(object_index).center_m_xyz = ...
        center_m_xyz;

    resolved_objects(object_index).axis_xyz = ...
        axis_xyz;

    resolved_objects(object_index).radius_m = ...
        radius_m;

    resolved_objects(object_index).length_m = ...
        length_m;

    resolved_objects(object_index).material_id = ...
        material.material_id;

    resolved_objects(object_index).cs_m_s = ...
        material.cs_m_s;

    resolved_objects(object_index).cp_m_s = ...
        material.cp_m_s;

    resolved_objects(object_index).rho_kg_m3 = ...
        material.rho_kg_m3;

    resolved_objects(object_index).bounding_box_min_m_xyz = ...
        bounding_box_min_m_xyz;

    resolved_objects(object_index).bounding_box_max_m_xyz = ...
        bounding_box_max_m_xyz;
end

cfg.geometry.objects = ...
    resolved_objects;

%% Optional sensor-ROI containment

if cfg.geometry.require_objects_inside_sensor_roi && ...
        isfield(cfg, "sensor") && ...
        isfield(cfg.sensor, "x_indices") && ...
        isfield(cfg.sensor, "y_indices") && ...
        isfield(cfg.sensor, "z_indices")

    sensor_min_m_xyz = [
        (cfg.sensor.x_indices(1) - 1) * cfg.grid.dx_m, ...
        (cfg.sensor.y_indices(1) - 1) * cfg.grid.dy_m, ...
        (cfg.sensor.z_indices(1) - 1) * cfg.grid.dz_m
    ];

    sensor_max_m_xyz = [
        (cfg.sensor.x_indices(end) - 1) * cfg.grid.dx_m, ...
        (cfg.sensor.y_indices(end) - 1) * cfg.grid.dy_m, ...
        (cfg.sensor.z_indices(end) - 1) * cfg.grid.dz_m
    ];

    for object_index = 1:numel(resolved_objects)
        object = ...
            resolved_objects(object_index);

        if any( ...
                object.bounding_box_min_m_xyz < ...
                sensor_min_m_xyz) || ...
                any( ...
                object.bounding_box_max_m_xyz > ...
                sensor_max_m_xyz)
            error( ...
                "kwsim:MaterialGeometryOutsideSensorRoi", ...
                "Material object '%s' does not fit inside the sensor ROI.", ...
                object.name);
        end
    end
end

%% Summary used by PPW checks and reporting

material_cs_m_s = ...
    background.cs_m_s;

material_cp_m_s = ...
    background.cp_m_s;

if bilayer.enabled
    material_cs_m_s = [
        material_cs_m_s, ...
        bilayer.negative_material.cs_m_s, ...
        bilayer.positive_material.cs_m_s
    ];

    material_cp_m_s = [
        material_cp_m_s, ...
        bilayer.negative_material.cp_m_s, ...
        bilayer.positive_material.cp_m_s
    ];
end

if ~isempty(resolved_objects)
    material_cs_m_s = [
        material_cs_m_s, ...
        [resolved_objects.cs_m_s]
    ];

    material_cp_m_s = [
        material_cp_m_s, ...
        [resolved_objects.cp_m_s]
    ];
end

cfg.geometry.minimum_cs_m_s = ...
    min(material_cs_m_s);

cfg.geometry.maximum_cs_m_s = ...
    max(material_cs_m_s);

cfg.geometry.maximum_cp_m_s = ...
    max(material_cp_m_s);

cfg.geometry.object_count = ...
    numel(resolved_objects);

cfg.geometry.has_heterogeneity = ...
    bilayer.enabled || ...
    ~isempty(resolved_objects);

cfg.geometry.resolved = ...
    true;

end


function material = resolveMaterial( ...
        requested, ...
        background, ...
        context)

material_id = ...
    fieldOrDefault( ...
        requested, ...
        "material_id", ...
        uint16(0));

validateMaterialId( ...
    material_id, ...
    context + ".material_id");

material_id = ...
    uint16(material_id);

if material_id == background.material_id
    error( ...
        "kwsim:Invalid3DMaterialGeometry", ...
        "%s.material_id must differ from the background material ID.", ...
        context);
end

cs_m_s = ...
    positiveScalarValue( ...
        fieldOrDefault( ...
            requested, ...
            "cs_m_s", ...
            NaN), ...
        context + ".cs_m_s");

cp_m_s = ...
    double( ...
        fieldOrDefault( ...
            requested, ...
            "cp_m_s", ...
            NaN));

if isnan(cp_m_s)
    cp_m_s = ...
        background.cp_m_s / ...
        background.cs_m_s * ...
        cs_m_s;
else
    cp_m_s = ...
        positiveScalarValue( ...
            cp_m_s, ...
            context + ".cp_m_s");
end

rho_kg_m3 = ...
    double( ...
        fieldOrDefault( ...
            requested, ...
            "rho_kg_m3", ...
            NaN));

if isnan(rho_kg_m3)
    rho_kg_m3 = ...
        background.rho_kg_m3;
else
    rho_kg_m3 = ...
        positiveScalarValue( ...
            rho_kg_m3, ...
            context + ".rho_kg_m3");
end

if cp_m_s / cs_m_s <= sqrt(4/3)
    error( ...
        "kwsim:Invalid3DMaterialGeometry", ...
        "%s must satisfy cp_m_s/cs_m_s > sqrt(4/3).", ...
        context);
end

material = struct();
material.material_id = material_id;
material.cs_m_s = cs_m_s;
material.cp_m_s = cp_m_s;
material.rho_kg_m3 = rho_kg_m3;

end


function validateMaterialId(value, name)

value = ...
    double(value);

if ~( ...
        isscalar(value) && ...
        isfinite(value) && ...
        value == fix(value) && ...
        value >= 1 && ...
        value <= double(intmax("uint16")))
    error( ...
        "kwsim:Invalid3DMaterialGeometry", ...
        "%s must be an integer from 1 through 65535.", ...
        name);
end

end


function value = positiveScalarValue(value, name)

value = ...
    double(value);

if ~( ...
        isscalar(value) && ...
        isfinite(value) && ...
        value > 0)
    error( ...
        "kwsim:Invalid3DMaterialGeometry", ...
        "%s must be a positive finite scalar.", ...
        name);
end

end


function vector = finiteVector3(value, name)

vector = ...
    double(value(:).');

if numel(vector) ~= 3 || ...
        any(~isfinite(vector))
    error( ...
        "kwsim:Invalid3DMaterialGeometry", ...
        "%s must be a finite three-element vector.", ...
        name);
end

end


function value = fieldOrDefault(structure, field_name, default_value)

if isstruct(structure) && ...
        isfield(structure, field_name) && ...
        ~isempty(structure.(field_name))
    value = ...
        structure.(field_name);
else
    value = ...
        default_value;
end

end
