function bank = resolveVibratorBankFromFaceSpecs(cfg, contact_specs)
%RESOLVEVIBRATORBANKFROMFACESPECS Resolve a deterministic multi-face bank.
%
% contact_specs is a nonempty struct array with fields:
%
%   face
%   center_fraction_tangent
%
% An optional name field may be supplied. Tangent-plane fractions use the
% axis order reported by makeSparseDiskMaskOnFace:
%
%   x faces: [y,z]
%   y faces: [x,z]
%   z faces: [x,y]
%
% Fractions are mapped to the range of center indices for which the complete
% requested finite disk fits inside the tangent-plane grid.

arguments
    cfg struct
    contact_specs struct
end

if isempty(contact_specs)
    error( ...
        "kwsim:EmptyVibratorBankSpecification", ...
        "contact_specs must contain at least one contact.");
end

required_spec_fields = [
    "face"
    "center_fraction_tangent"
];

for spec_index = 1:numel(contact_specs)
    for field_name = required_spec_fields.'
        if ~isfield(contact_specs(spec_index), char(field_name))
            error( ...
                "kwsim:InvalidVibratorBankSpecification", ...
                "Contact specification %d is missing field '%s'.", ...
                spec_index, ...
                field_name);
        end
    end
end

number_of_vibrators = ...
    numel(contact_specs);

if ~isfield(cfg, "source") || ...
        ~isfield(cfg.source, "vibrator_count") || ...
        cfg.source.vibrator_count ~= number_of_vibrators
    error( ...
        "kwsim:VibratorCountMismatch", ...
        "source.vibrator_count must equal numel(contact_specs).");
end

if lower(string(cfg.source.phase_policy)) ~= "random_uniform"
    error( ...
        "kwsim:Invalid3DSourceBank", ...
        "Multi-face banks currently require phase_policy=random_uniform.");
end

if lower(string(cfg.source.amplitude_policy)) ~= "equal_total_rms"
    error( ...
        "kwsim:Invalid3DSourceBank", ...
        "Multi-face banks currently require amplitude_policy=equal_total_rms.");
end

if lower(string(cfg.source.polarization_policy)) ~= ...
        "project_axial_transverse"
    error( ...
        "kwsim:Invalid3DSourceBank", ...
        "Multi-face banks require " + ...
        "polarization_policy=project_axial_transverse.");
end

grid_size_xyz = [
    cfg.grid.Nx, ...
    cfg.grid.Ny, ...
    cfg.grid.Nz
];

grid_spacing_m_xyz = [
    cfg.grid.dx_m, ...
    cfg.grid.dy_m, ...
    cfg.grid.dz_m
];

domain_size_m_xyz = ...
    (grid_size_xyz - 1) .* ...
    grid_spacing_m_xyz;

domain_center_m_xyz = ...
    0.5 * domain_size_m_xyz;

template = struct( ...
    "name", "", ...
    "face", "", ...
    "face_normal_xyz", [NaN, NaN, NaN], ...
    "center_fraction_tangent", [NaN, NaN], ...
    "tangent_axis_names", strings(1, 2), ...
    "node_linear_indices", [], ...
    "center_index_xyz", [NaN, NaN, NaN], ...
    "center_m_xyz", [NaN, NaN, NaN], ...
    "polarization_xyz", [NaN, NaN, NaN], ...
    "nominal_propagation_xyz", [NaN, NaN, NaN], ...
    "phase_rad", NaN, ...
    "velocity_amplitude_m_s", NaN, ...
    "contact_node_count", 0, ...
    "realized_radius_tangent_m", [NaN, NaN]);

vibrators = ...
    repmat(template, number_of_vibrators, 1);

union_mask_xyz = ...
    false(cfg.grid.Nx, cfg.grid.Ny, cfg.grid.Nz);

node_counts = ...
    zeros(number_of_vibrators, 1);

faces = ...
    strings(number_of_vibrators, 1);

for vibrator_index = 1:number_of_vibrators
    specification = ...
        contact_specs(vibrator_index);

    face = ...
        lower(string(specification.face));

    center_fraction_tangent = ...
        double(specification.center_fraction_tangent(:).');

    if numel(center_fraction_tangent) ~= 2 || ...
            any(~isfinite(center_fraction_tangent)) || ...
            any(center_fraction_tangent < 0) || ...
            any(center_fraction_tangent > 1)
        error( ...
            "kwsim:InvalidVibratorCenterFraction", ...
            "Contact %d center_fraction_tangent must contain " + ...
            "two finite values in [0,1].", ...
            vibrator_index);
    end

    center_index_xyz = ...
        centerIndexFromFaceFraction( ...
            cfg, ...
            face, ...
            center_fraction_tangent);

    contact = ...
        kwsim.three_d.makeSparseDiskMaskOnFace( ...
            cfg, ...
            face, ...
            center_index_xyz);

    if any(union_mask_xyz & contact.mask_xyz, "all")
        error( ...
            "kwsim:OverlappingVibratorContacts", ...
            "Resolved vibrator contacts overlap.");
    end

    union_mask_xyz = ...
        union_mask_xyz | contact.mask_xyz;

    direction = ...
        domain_center_m_xyz - contact.center_m_xyz;

    if norm(direction) < 1e-12
        error( ...
            "kwsim:InvalidVibratorDirection", ...
            "A source contact cannot coincide with the domain center.");
    end

    direction = ...
        direction / norm(direction);

    polarization = ...
        transverseAxialPolarization(direction);

    if isfield(specification, "name") && ...
            strlength(string(specification.name)) > 0
        vibrator_name = ...
            string(specification.name);
    else
        vibrator_name = ...
            "vibrator_" + string(vibrator_index);
    end

    vibrators(vibrator_index).name = ...
        vibrator_name;

    vibrators(vibrator_index).face = ...
        face;

    vibrators(vibrator_index).face_normal_xyz = ...
        contact.face_normal_xyz;

    vibrators(vibrator_index).center_fraction_tangent = ...
        center_fraction_tangent;

    vibrators(vibrator_index).tangent_axis_names = ...
        contact.tangent_axis_names;

    vibrators(vibrator_index).node_linear_indices = ...
        contact.node_linear_indices;

    vibrators(vibrator_index).center_index_xyz = ...
        contact.center_index_xyz;

    vibrators(vibrator_index).center_m_xyz = ...
        contact.center_m_xyz;

    vibrators(vibrator_index).polarization_xyz = ...
        polarization;

    vibrators(vibrator_index).nominal_propagation_xyz = ...
        direction;

    vibrators(vibrator_index).contact_node_count = ...
        contact.node_count;

    vibrators(vibrator_index).realized_radius_tangent_m = ...
        contact.realized_radius_tangent_m;

    node_counts(vibrator_index) = ...
        contact.node_count;

    faces(vibrator_index) = ...
        face;
end

reference_center_index_xyz = ...
    centerIndexFromFaceFraction( ...
        cfg, ...
        "x_min", ...
        [0.5, 0.5]);

reference_contact = ...
    kwsim.three_d.makeSparseDiskMaskOnFace( ...
        cfg, ...
        "x_min", ...
        reference_center_index_xyz);

reference_node_count = ...
    reference_contact.node_count;

for vibrator_index = 1:number_of_vibrators
    vibrators(vibrator_index).velocity_amplitude_m_s = ...
        cfg.source.velocity_amplitude_m_s * ...
        sqrt( ...
            reference_node_count / ...
            (number_of_vibrators * node_counts(vibrator_index)));
end

phase_stream = ...
    RandStream( ...
        "mt19937ar", ...
        "Seed", ...
        double(cfg.seed));

phases_rad = ...
    2*pi*rand( ...
        phase_stream, ...
        number_of_vibrators, ...
        1);

for vibrator_index = 1:number_of_vibrators
    vibrators(vibrator_index).phase_rad = ...
        phases_rad(vibrator_index);
end

supported_faces = [
    "x_min"
    "x_max"
    "y_min"
    "y_max"
    "z_min"
    "z_max"
];

face_counts = ...
    zeros(size(supported_faces));

for face_index = 1:numel(supported_faces)
    face_counts(face_index) = ...
        nnz(faces == supported_faces(face_index));
end

nominal_total_drive_rms_squared = ...
    sum( ...
        node_counts .* ...
        [vibrators.velocity_amplitude_m_s].'.^2 / ...
        2);

reference_drive_rms_squared = ...
    reference_node_count * ...
    cfg.source.velocity_amplitude_m_s^2 / ...
    2;

bank = struct();

bank.vibrators = ...
    vibrators;

bank.union_mask_xyz = ...
    union_mask_xyz;

bank.contact_count = ...
    number_of_vibrators;

bank.total_contact_node_count = ...
    nnz(union_mask_xyz);

bank.faces = ...
    faces;

bank.face_set = ...
    unique(faces, "stable");

bank.supported_faces = ...
    supported_faces;

bank.face_counts = ...
    face_counts;

bank.reference_face = ...
    "x_min";

bank.reference_center_fraction_tangent = ...
    [0.5, 0.5];

bank.reference_single_contact_node_count = ...
    reference_node_count;

bank.reference_single_contact_drive_rms_squared_m2_s2 = ...
    reference_drive_rms_squared;

bank.nominal_total_drive_rms_squared_m2_s2 = ...
    nominal_total_drive_rms_squared;

bank.phase_policy = ...
    string(cfg.source.phase_policy);

bank.amplitude_policy = ...
    string(cfg.source.amplitude_policy);

bank.polarization_policy = ...
    string(cfg.source.polarization_policy);

bank.internal_orientation = ...
    "[Nx,Ny,Nz]";

bank.public_orientation = ...
    "[Nz,Ny,Nx]";

end

function center_index_xyz = centerIndexFromFaceFraction( ...
        cfg, ...
        face, ...
        center_fraction_tangent)

grid_size_xyz = [
    cfg.grid.Nx, ...
    cfg.grid.Ny, ...
    cfg.grid.Nz
];

grid_spacing_m_xyz = [
    cfg.grid.dx_m, ...
    cfg.grid.dy_m, ...
    cfg.grid.dz_m
];

boundary_margin_points_xyz = round( ...
    cfg.source.boundary_margin_m ./ ...
    grid_spacing_m_xyz);

switch lower(string(face))
    case "x_min"
        fixed_axis = 1;
        tangent_axes = [2, 3];
        source_plane_index = ...
            1 + boundary_margin_points_xyz(1);

    case "x_max"
        fixed_axis = 1;
        tangent_axes = [2, 3];
        source_plane_index = ...
            cfg.grid.Nx - boundary_margin_points_xyz(1);

    case "y_min"
        fixed_axis = 2;
        tangent_axes = [1, 3];
        source_plane_index = ...
            1 + boundary_margin_points_xyz(2);

    case "y_max"
        fixed_axis = 2;
        tangent_axes = [1, 3];
        source_plane_index = ...
            cfg.grid.Ny - boundary_margin_points_xyz(2);

    case "z_min"
        fixed_axis = 3;
        tangent_axes = [1, 2];
        source_plane_index = ...
            1 + boundary_margin_points_xyz(3);

    case "z_max"
        fixed_axis = 3;
        tangent_axes = [1, 2];
        source_plane_index = ...
            cfg.grid.Nz - boundary_margin_points_xyz(3);

    otherwise
        error( ...
            "kwsim:Unsupported3DSourceFace", ...
            "Unsupported 3D source face: %s.", ...
            face);
end

tangent_grid_size = ...
    grid_size_xyz(tangent_axes);

tangent_spacing_m = ...
    grid_spacing_m_xyz(tangent_axes);

required_radius_points = ...
    ceil( ...
        cfg.source.contact_radius_m ./ ...
        tangent_spacing_m);

minimum_tangent_center = ...
    1 + required_radius_points;

maximum_tangent_center = ...
    tangent_grid_size - required_radius_points;

if any(minimum_tangent_center > maximum_tangent_center)
    error( ...
        "kwsim:Invalid3DSourceBank", ...
        "The tangent-plane grid is too small for the requested contact.");
end

tangent_center = round( ...
    minimum_tangent_center + ...
    center_fraction_tangent .* ...
    (maximum_tangent_center - minimum_tangent_center));

center_index_xyz = ...
    round((grid_size_xyz + 1) / 2);

center_index_xyz(fixed_axis) = ...
    source_plane_index;

center_index_xyz(tangent_axes) = ...
    tangent_center;

end

function polarization = transverseAxialPolarization(direction)

axial_unit = ...
    [0, 0, 1];

polarization = ...
    axial_unit - ...
    dot(axial_unit, direction) * direction;

if norm(polarization) < 1e-10
    elevational_unit = ...
        [0, 1, 0];

    polarization = ...
        elevational_unit - ...
        dot(elevational_unit, direction) * direction;
end

if norm(polarization) < 1e-10
    lateral_unit = ...
        [1, 0, 0];

    polarization = ...
        lateral_unit - ...
        dot(lateral_unit, direction) * direction;
end

polarization = ...
    polarization / norm(polarization);

end
