function [cfg, source_x] = resolvePartial3DN8P2Config(cfg)
%RESOLVEPARTIAL3DN8P2CONFIG Resolve the eight-source multi-face P2 bank.
%
% The bank contains eight contacts over all six boundary faces. Exactly two
% contacts intersect and are centered on the central x-z acquisition plane.
% The remaining six contacts are out of plane.

arguments
    cfg struct
end

if cfg.source.vibrator_count ~= 8
    error( ...
        "kwsim:Invalid3DSourceBank", ...
        "partial_3d_n8_p2 requires source.vibrator_count = 8.");
end

if lower(string(cfg.source.side)) ~= "multiface"
    error( ...
        "kwsim:Invalid3DSourceBank", ...
        "partial_3d_n8_p2 requires source.side=multiface.");
end

if lower(string(cfg.source.phase_policy)) ~= "random_uniform"
    error( ...
        "kwsim:Invalid3DSourceBank", ...
        "partial_3d_n8_p2 requires phase_policy=random_uniform.");
end

if lower(string(cfg.source.amplitude_policy)) ~= "equal_total_rms"
    error( ...
        "kwsim:Invalid3DSourceBank", ...
        "partial_3d_n8_p2 requires amplitude_policy=equal_total_rms.");
end

if lower(string(cfg.source.polarization_policy)) ~= ...
        "project_axial_transverse"
    error( ...
        "kwsim:Invalid3DSourceBank", ...
        "partial_3d_n8_p2 requires " + ...
        "polarization_policy=project_axial_transverse.");
end

minimum_in_plane_sources = ...
    nonnegativeInteger( ...
        cfg.source.minimum_in_plane_sources, ...
        "source.minimum_in_plane_sources");

minimum_out_of_plane_sources = ...
    nonnegativeInteger( ...
        cfg.source.minimum_out_of_plane_sources, ...
        "source.minimum_out_of_plane_sources");

acquisition_y_index_full = ...
    round((cfg.grid.Ny + 1) / 2);

in_plane_y_fraction = ...
    centerFractionForAxis( ...
        cfg, ...
        2, ...
        acquisition_y_index_full);

spec_template = struct( ...
    "name", "", ...
    "face", "", ...
    "center_fraction_tangent", [NaN, NaN]);

contact_specs = ...
    repmat(spec_template, 8, 1);

contact_specs(1) = makeSpec( ...
    "x_min_in_plane", ...
    "x_min", ...
    [in_plane_y_fraction, 0.25]);

contact_specs(2) = makeSpec( ...
    "x_max_in_plane", ...
    "x_max", ...
    [in_plane_y_fraction, 0.75]);

contact_specs(3) = makeSpec( ...
    "y_min_out_of_plane", ...
    "y_min", ...
    [0.25, 0.25]);

contact_specs(4) = makeSpec( ...
    "y_max_out_of_plane", ...
    "y_max", ...
    [0.75, 0.75]);

contact_specs(5) = makeSpec( ...
    "z_min_out_of_plane", ...
    "z_min", ...
    [0.25, 0.20]);

contact_specs(6) = makeSpec( ...
    "z_max_out_of_plane", ...
    "z_max", ...
    [0.75, 0.80]);

contact_specs(7) = makeSpec( ...
    "x_min_out_of_plane", ...
    "x_min", ...
    [0.20, 0.75]);

contact_specs(8) = makeSpec( ...
    "x_max_out_of_plane", ...
    "x_max", ...
    [0.80, 0.25]);

bank = ...
    kwsim.three_d.resolveVibratorBankFromFaceSpecs( ...
        cfg, ...
        contact_specs);

in_plane_count = 0;
centered_in_plane_count = 0;

for vibrator_index = 1:numel(bank.vibrators)
    node_indices = ...
        bank.vibrators(vibrator_index).node_linear_indices;

    [~, node_y, ~] = ...
        ind2sub( ...
            size(bank.union_mask_xyz), ...
            node_indices);

    intersects_plane = ...
        any(node_y == acquisition_y_index_full);

    centered_on_plane = ...
        bank.vibrators(vibrator_index).center_index_xyz(2) == ...
        acquisition_y_index_full;

    bank.vibrators(vibrator_index). ...
        intersects_acquisition_plane = ...
        intersects_plane;

    bank.vibrators(vibrator_index). ...
        centered_on_acquisition_plane = ...
        centered_on_plane;

    in_plane_count = ...
        in_plane_count + double(intersects_plane);

    centered_in_plane_count = ...
        centered_in_plane_count + double(centered_on_plane);
end

out_of_plane_count = ...
    bank.contact_count - in_plane_count;

if in_plane_count ~= 2 || ...
        centered_in_plane_count ~= 2 || ...
        out_of_plane_count ~= 6
    error( ...
        "kwsim:InvalidPartial3DN8P2Geometry", ...
        "partial_3d_n8_p2 must resolve exactly two in-plane " + ...
        "and six out-of-plane contacts.");
end

if in_plane_count < minimum_in_plane_sources
    error( ...
        "kwsim:InsufficientInPlaneSources", ...
        "The resolved bank does not meet minimum_in_plane_sources.");
end

if out_of_plane_count < minimum_out_of_plane_sources
    error( ...
        "kwsim:InsufficientOutOfPlaneSources", ...
        "The resolved bank does not meet minimum_out_of_plane_sources.");
end

active_linear_indices = ...
    find(bank.union_mask_xyz);

[node_x, node_y, node_z] = ...
    ind2sub( ...
        size(bank.union_mask_xyz), ...
        active_linear_indices);

cfg.source.vibrators = ...
    bank.vibrators;

cfg.source.vibrator_count = ...
    bank.contact_count;

cfg.source.contact_node_count = ...
    bank.total_contact_node_count;

cfg.source.contact_mask_xyz = ...
    bank.union_mask_xyz;

cfg.source.contact_node_subscripts_xyz = ...
    [node_x, node_y, node_z];

cfg.source.reference_single_contact_node_count = ...
    bank.reference_single_contact_node_count;

cfg.source.nominal_total_drive_rms_squared_m2_s2 = ...
    bank.nominal_total_drive_rms_squared_m2_s2;

cfg.source.face_set = ...
    bank.face_set;

cfg.source.supported_faces = ...
    bank.supported_faces;

cfg.source.face_counts = ...
    bank.face_counts;

cfg.source.acquisition_plane_y_index_full = ...
    acquisition_y_index_full;

cfg.source.in_plane_vibrator_count = ...
    in_plane_count;

cfg.source.out_of_plane_vibrator_count = ...
    out_of_plane_count;

cfg.source.centered_in_plane_vibrator_count = ...
    centered_in_plane_count;

cfg.source.contact_specs = ...
    contact_specs;

grid_spacing_m_xyz = [
    cfg.grid.dx_m, ...
    cfg.grid.dy_m, ...
    cfg.grid.dz_m
];

realized_radius_xyz_m = ...
    zeros(1, 3);

for vibrator_index = 1:numel(cfg.source.vibrators)
    vibrator = ...
        cfg.source.vibrators(vibrator_index);

    [node_x_this, node_y_this, node_z_this] = ...
        ind2sub( ...
            size(bank.union_mask_xyz), ...
            vibrator.node_linear_indices);

    node_subscripts_xyz = ...
        [node_x_this, node_y_this, node_z_this];

    offsets_m_xyz = ...
        abs( ...
            (node_subscripts_xyz - ...
            vibrator.center_index_xyz) .* ...
            grid_spacing_m_xyz);

    realized_radius_xyz_m = ...
        max( ...
            realized_radius_xyz_m, ...
            max(offsets_m_xyz, [], 1));
end

cfg.source.realized_radius_x_m = ...
    realized_radius_xyz_m(1);

cfg.source.realized_radius_y_m = ...
    realized_radius_xyz_m(2);

cfg.source.realized_radius_z_m = ...
    realized_radius_xyz_m(3);

source_x = ...
    min(node_x);

cfg.source.source_x_index = ...
    source_x;

cfg.source.center_index_xyz = [
    round((cfg.grid.Nx + 1) / 2), ...
    acquisition_y_index_full, ...
    round((cfg.grid.Nz + 1) / 2)
];

cfg.source.center_m_xyz = ...
    (cfg.source.center_index_xyz - 1) .* [
        cfg.grid.dx_m, ...
        cfg.grid.dy_m, ...
        cfg.grid.dz_m
    ];

end

function specification = makeSpec(name, face, fractions)

specification = struct( ...
    "name", string(name), ...
    "face", string(face), ...
    "center_fraction_tangent", double(fractions));

end

function fraction = centerFractionForAxis(cfg, axis_index, target_index)

grid_size_xyz = [
    cfg.grid.Nx, ...
    cfg.grid.Ny, ...
    cfg.grid.Nz
];

grid_spacing_m_xyz = [
    cfg.grid.dx_m, ...
    cfg.grid.dy_m, ...
    cfg.grid.dz_m
];

radius_points = ...
    ceil( ...
        cfg.source.contact_radius_m / ...
        grid_spacing_m_xyz(axis_index));

minimum_center = ...
    1 + radius_points;

maximum_center = ...
    grid_size_xyz(axis_index) - radius_points;

if target_index < minimum_center || ...
        target_index > maximum_center
    error( ...
        "kwsim:InvalidPartial3DN8P2Geometry", ...
        "The acquisition-plane center cannot fit the source contact.");
end

if maximum_center == minimum_center
    fraction = ...
        0.5;
else
    fraction = ...
        (target_index - minimum_center) / ...
        (maximum_center - minimum_center);
end

end

function value = nonnegativeInteger(value, field_name)

value = ...
    double(value);

if ~(isscalar(value) && ...
        isfinite(value) && ...
        value == fix(value) && ...
        value >= 0)
    error( ...
        "kwsim:Invalid3DSourceBank", ...
        "%s must be a nonnegative integer.", ...
        field_name);
end

end
