function sensor = resolveSensorIndices(cfg, source_x)
%RESOLVESENSORINDICES Resolve a source-free 3D sensor cuboid.
%
% The legacy left-face layouts preserve the original x-only source buffer.
% Multi-face banks apply the configured source buffer along the inward
% normal direction of every occupied source face.

arguments
    cfg struct
    source_x (1,1) double
end

grid_size_xyz = [
    cfg.grid.Nx, ...
    cfg.grid.Ny, ...
    cfg.grid.Nz
];

grid_spacing_m_xyz = [
    cfg.grid.dx_m, ...
    cfg.grid.dy_m, ...
    cfg.grid.dz_m
];

boundary_points_xyz = ...
    round( ...
        cfg.sensor.boundary_margin_m ./ ...
        grid_spacing_m_xyz);

source_buffer_points_xyz = ...
    round( ...
        cfg.sensor.source_buffer_m ./ ...
        grid_spacing_m_xyz);

start_indices = ...
    1 + boundary_points_xyz;

end_indices = ...
    grid_size_xyz - boundary_points_xyz;

is_multiface = ...
    lower(string(cfg.source.layout)) == "vibrator_bank" && ...
    isfield(cfg.source, "vibrators") && ...
    ~isempty(cfg.source.vibrators) && ...
    isfield(cfg.source.vibrators, "face");

minimum_source_clearance_m = ...
    Inf;

if is_multiface
    for vibrator_index = 1:numel(cfg.source.vibrators)
        vibrator = ...
            cfg.source.vibrators(vibrator_index);

        face = ...
            lower(string(vibrator.face));

        center_index_xyz = ...
            double(vibrator.center_index_xyz);

        switch face
            case "x_min"
                start_indices(1) = max( ...
                    start_indices(1), ...
                    center_index_xyz(1) + ...
                    source_buffer_points_xyz(1) + 1);

            case "x_max"
                end_indices(1) = min( ...
                    end_indices(1), ...
                    center_index_xyz(1) - ...
                    source_buffer_points_xyz(1) - 1);

            case "y_min"
                start_indices(2) = max( ...
                    start_indices(2), ...
                    center_index_xyz(2) + ...
                    source_buffer_points_xyz(2) + 1);

            case "y_max"
                end_indices(2) = min( ...
                    end_indices(2), ...
                    center_index_xyz(2) - ...
                    source_buffer_points_xyz(2) - 1);

            case "z_min"
                start_indices(3) = max( ...
                    start_indices(3), ...
                    center_index_xyz(3) + ...
                    source_buffer_points_xyz(3) + 1);

            case "z_max"
                end_indices(3) = min( ...
                    end_indices(3), ...
                    center_index_xyz(3) - ...
                    source_buffer_points_xyz(3) - 1);

            otherwise
                error( ...
                    "kwsim:Unsupported3DSourceFace", ...
                    "Unsupported resolved source face: %s.", ...
                    face);
        end
    end
else
    start_indices(1) = ...
        source_x + source_buffer_points_xyz(1) + 1;
end

if any(start_indices > end_indices)
    error( ...
        "kwsim:Invalid3DConfig", ...
        "The 3D sensor ROI is empty; enlarge the grid or reduce margins.");
end

if is_multiface
    for vibrator_index = 1:numel(cfg.source.vibrators)
        vibrator = ...
            cfg.source.vibrators(vibrator_index);

        face = ...
            lower(string(vibrator.face));

        center_index_xyz = ...
            double(vibrator.center_index_xyz);

        [axis_index, clearance_points] = ...
            faceClearance( ...
                face, ...
                center_index_xyz, ...
                start_indices, ...
                end_indices);

        clearance_m = ...
            clearance_points * ...
            grid_spacing_m_xyz(axis_index);

        minimum_source_clearance_m = ...
            min( ...
                minimum_source_clearance_m, ...
                clearance_m);

        if clearance_m < cfg.sensor.source_buffer_m
            error( ...
                "kwsim:Invalid3DConfig", ...
                "The realized source-to-sensor buffer is too small " + ...
                "for face %s.", ...
                face);
        end
    end
else
    actual_source_buffer_m = ...
        (start_indices(1) - source_x) * ...
        cfg.grid.dx_m;

    minimum_source_clearance_m = ...
        actual_source_buffer_m;

    if actual_source_buffer_m < cfg.sensor.source_buffer_m
        error( ...
            "kwsim:Invalid3DConfig", ...
            "The realized source-to-sensor buffer is smaller than requested.");
    end
end

sensor = struct();

sensor.x_indices = ...
    start_indices(1):end_indices(1);

sensor.y_indices = ...
    start_indices(2):end_indices(2);

sensor.z_indices = ...
    start_indices(3):end_indices(3);

sensor.acquisition_y_index_full = ...
    round( ...
        0.5 * ...
        (start_indices(2) + end_indices(2)));

sensor.minimum_source_clearance_m = ...
    minimum_source_clearance_m;

end

function [axis_index, clearance_points] = faceClearance( ...
        face, ...
        center_index_xyz, ...
        start_indices, ...
        end_indices)

switch face
    case "x_min"
        axis_index = 1;
        clearance_points = ...
            start_indices(1) - center_index_xyz(1);

    case "x_max"
        axis_index = 1;
        clearance_points = ...
            center_index_xyz(1) - end_indices(1);

    case "y_min"
        axis_index = 2;
        clearance_points = ...
            start_indices(2) - center_index_xyz(2);

    case "y_max"
        axis_index = 2;
        clearance_points = ...
            center_index_xyz(2) - end_indices(2);

    case "z_min"
        axis_index = 3;
        clearance_points = ...
            start_indices(3) - center_index_xyz(3);

    case "z_max"
        axis_index = 3;
        clearance_points = ...
            center_index_xyz(3) - end_indices(3);

    otherwise
        error( ...
            "kwsim:Unsupported3DSourceFace", ...
            "Unsupported resolved source face: %s.", ...
            face);
end

end
