function [cfg, source_x] = resolveSingleContactConfig(cfg)
%RESOLVESINGLECONTACTCONFIG Resolve one left-face sparse disk source.

boundary_points_x = ...
    round(cfg.source.boundary_margin_m / cfg.grid.dx_m);

source_x = ...
    1 + boundary_points_x;

source_y = ...
    round((cfg.grid.Ny + 1) / 2);

source_z = ...
    round((cfg.grid.Nz + 1) / 2);

if source_x < 1 || source_x > cfg.grid.Nx
    error( ...
        "kwsim:Invalid3DConfig", ...
        "The source boundary margin places the source outside the grid.");
end

disk = ...
    kwsim.three_d.makeSparseDiskMaskYZ( ...
        cfg, ...
        source_y, ...
        source_z);

cfg.source.center_index_xyz = ...
    [source_x, source_y, source_z];

cfg.source.center_m_xyz = [
    cfg.derived.x_full_m(source_x), ...
    cfg.derived.y_full_m(source_y), ...
    cfg.derived.z_full_m(source_z)
];

cfg.source.contact_radius_points_y = ...
    round(cfg.source.contact_radius_m / cfg.grid.dy_m);

cfg.source.contact_radius_points_z = ...
    round(cfg.source.contact_radius_m / cfg.grid.dz_m);

cfg.source.contact_mask_yz = ...
    disk.mask_yz;

cfg.source.contact_node_subscripts_yz = ...
    disk.node_subscripts_yz;

cfg.source.contact_node_count = ...
    disk.node_count;

cfg.source.realized_radius_y_m = ...
    disk.realized_radius_y_m;

cfg.source.realized_radius_z_m = ...
    disk.realized_radius_z_m;

end
