%% Projected-3D scalar versus axial ensemble spectrum
%
% This diagnostic distinguishes:
%
% 1. A scalar projected-3D field with equal directional power.
% 2. Axial shear motion with random transverse polarization.
%
% Independent random initial phases imply
%
%   E[|sum_n a_n exp(i phi_n) F_n|^2]
%       = sum_n E[|a_n|^2] |F_n|^2.
%
% Therefore the ensemble power spectrum can be calculated exactly without
% finite Monte Carlo phase noise.
%
% For a random polarization angle perpendicular to u:
%
%   E[p_z^2 | u] = (1 - u_z^2)/2.

clear;
close all;

scriptDirectory = fileparts(mfilename("fullpath"));
repositoryRoot = fileparts(fileparts(scriptDirectory));

addpath(fullfile(repositoryRoot, "src"));

outputDirectory = fullfile( ...
    repositoryRoot, ...
    "outputs", ...
    "diagnostics", ...
    "projected3d_axial_ensemble");

if ~isfolder(outputDirectory)
    mkdir(outputDirectory);
end

%% Configuration

directionCount = 128;

domainLengthXM = 0.050;
domainLengthZM = 0.050;

dxM = 0.00025;
dzM = 0.00025;

frequencyHz = 250;
csMps = 2.0;

omegaRadS = 2*pi*frequencyHz;
referenceWavenumberRadM = omegaRadS / csMps;

cfg = swsynth.defaultConfig();

cfg.seed = 7301;

cfg.domain.Lx_m = domainLengthXM;
cfg.domain.Lz_m = domainLengthZM;
cfg.domain.dx_m = dxM;
cfg.domain.dz_m = dzM;

cfg.medium.background_cs_m_s = csMps;
cfg.medium.objects = {};

cfg.wavefield.frequency_hz = frequencyHz;

cfg.directions.count = directionCount;
cfg.directions.space = "three_dimensional";
cfg.directions.sampling_method = "fibonacci";
cfg.directions.require_in_plane = false;
cfg.directions.support.type = "full_sphere";

cfg.execution.use_parallel = false;

[cfg, ~] = swsynth.validateConfig(cfg);

maps = swsynth.buildMediumMaps(cfg);
directions = swsynth.generateDirections(cfg);

xM = maps.x_m;
zM = maps.z_m;

directionsXYZ = double([
    directions.ux(:), ...
    directions.uy(:), ...
    directions.uz(:)]);

Nx = numel(xM);
Nz = numel(zM);

%% One scalar and one axial realization

rng(8301);

initialPhaseRad = ...
    2*pi*rand(directionCount, 1);

scalarWeights = ...
    exp(1i .* initialPhaseRad) ./ ...
    sqrt(directionCount);

rng(8302);

[polarizationXYZ, polarizationDiagnostics] = ...
    swsynth.propagation.projected3d. ...
        sampleTransversePolarization( ...
            directionsXYZ);

axialWeights = ...
    polarizationXYZ(:, 3) .* ...
    exp(1i .* initialPhaseRad) ./ ...
    sqrt(directionCount);

fieldOptions = struct();
fieldOptions.UseParallel = false;

scalarFieldZX = ...
    swsynth.propagation.projected3d. ...
        synthesizeDirectionalField( ...
            maps.cs_map_zx, ...
            xM, ...
            zM, ...
            directionsXYZ, ...
            scalarWeights, ...
            frequencyHz, ...
            csMps, ...
            fieldOptions);

axialFieldZX = ...
    swsynth.propagation.projected3d. ...
        synthesizeDirectionalField( ...
            maps.cs_map_zx, ...
            xM, ...
            zM, ...
            directionsXYZ, ...
            axialWeights, ...
            frequencyHz, ...
            csMps, ...
            fieldOptions);

%% Window and spectral coordinates

windowX = ...
    0.5 - 0.5*cos(2*pi*(0:Nx-1)/(Nx-1));

windowZ = ...
    0.5 - 0.5*cos(2*pi*(0:Nz-1)/(Nz-1));

windowZX = windowZ(:) * windowX(:).';

fftSizeX = 2 * 2^nextpow2(Nx);
fftSizeZ = 2 * 2^nextpow2(Nz);

kxRadM = ...
    2*pi .* ...
    ((-floor(fftSizeX/2)):(ceil(fftSizeX/2)-1)) ./ ...
    (fftSizeX * dxM);

kzRadM = ...
    2*pi .* ...
    ((-floor(fftSizeZ/2)):(ceil(fftSizeZ/2)-1)) ./ ...
    (fftSizeZ * dzM);

[KXRadM, KZRadM] = meshgrid( ...
    kxRadM, ...
    kzRadM);

normalizedRadiusZX = ...
    hypot(KXRadM, KZRadM) ./ ...
    referenceWavenumberRadM;

spectralAngleZX = atan2( ...
    KZRadM, ...
    KXRadM);

%% Exact random-phase ensemble spectra

scalarEnsemblePowerZX = ...
    zeros(fftSizeZ, fftSizeX);

axialEnsemblePowerZX = ...
    zeros(fftSizeZ, fftSizeX);

expectedAxialPowerByDirection = ...
    (1 - directionsXYZ(:, 3).^2) ./ 2;

timerHandle = tic;

for directionIndex = 1:directionCount

    phaseDelayZX = ...
        swsynth.propagation.projected3d. ...
            computeDirectionalPhaseDelay( ...
                maps.cs_map_zx, ...
                xM, ...
                zM, ...
                directionsXYZ(directionIndex, :), ...
                csMps);

    directionalFieldZX = ...
        exp(1i .* omegaRadS .* phaseDelayZX);

    directionalSpectrumZX = fftshift(fft2( ...
        directionalFieldZX .* windowZX, ...
        fftSizeZ, ...
        fftSizeX));

    directionalPowerZX = ...
        abs(directionalSpectrumZX).^2;

    scalarEnsemblePowerZX = ...
        scalarEnsemblePowerZX + ...
        directionalPowerZX ./ directionCount;

    axialEnsemblePowerZX = ...
        axialEnsemblePowerZX + ...
        expectedAxialPowerByDirection(directionIndex) .* ...
        directionalPowerZX ./ directionCount;

    if mod(directionIndex, 16) == 0
        fprintf( ...
            "Processed %d / %d directions.\n", ...
            directionIndex, ...
            directionCount);
    end
end

ensembleRuntimeS = toc(timerHandle);

%% Normalize spectra for visualization

scalarPowerDbZX = 10*log10( ...
    scalarEnsemblePowerZX ./ ...
    max(scalarEnsemblePowerZX(:)) + eps);

axialPowerDbZX = 10*log10( ...
    axialEnsemblePowerZX ./ ...
    max(axialEnsemblePowerZX(:)) + eps);

%% Radial spectral-density profiles

radialEdges = linspace(0, 0.96, 65);

[radialCenters, scalarRadialProfile] = ...
    radialAnnularMean( ...
        scalarEnsemblePowerZX, ...
        normalizedRadiusZX, ...
        radialEdges);

[~, axialRadialProfile] = ...
    radialAnnularMean( ...
        axialEnsemblePowerZX, ...
        normalizedRadiusZX, ...
        radialEdges);

scalarRadialTheory = ...
    1 ./ sqrt(1 - radialCenters.^2);

axialRadialTheory = ...
    (1 - 0.5*radialCenters.^2) ./ ...
    sqrt(1 - radialCenters.^2);

scalarRadialProfile = normalizeRadialDensity( ...
    radialCenters, ...
    scalarRadialProfile);

axialRadialProfile = normalizeRadialDensity( ...
    radialCenters, ...
    axialRadialProfile);

scalarRadialTheory = normalizeRadialDensity( ...
    radialCenters, ...
    scalarRadialTheory);

axialRadialTheory = normalizeRadialDensity( ...
    radialCenters, ...
    axialRadialTheory);

%% Angular profile in an outer annulus

angularMinimumRadius = 0.78;
angularMaximumRadius = 0.90;

angularEdges = linspace(-pi, pi, 73);

[angularCenters, scalarAngularProfile] = ...
    angularAnnularMean( ...
        scalarEnsemblePowerZX, ...
        normalizedRadiusZX, ...
        spectralAngleZX, ...
        angularMinimumRadius, ...
        angularMaximumRadius, ...
        angularEdges);

[~, axialAngularProfile] = ...
    angularAnnularMean( ...
        axialEnsemblePowerZX, ...
        normalizedRadiusZX, ...
        spectralAngleZX, ...
        angularMinimumRadius, ...
        angularMaximumRadius, ...
        angularEdges);

angularAnnulusMask = ...
    normalizedRadiusZX >= angularMinimumRadius & ...
    normalizedRadiusZX <= angularMaximumRadius;

representativeAngularRadius = mean( ...
    normalizedRadiusZX(angularAnnulusMask));

scalarAngularTheory = ...
    ones(size(angularCenters));

axialAngularTheory = ...
    1 - representativeAngularRadius^2 .* ...
    sin(angularCenters).^2;

scalarAngularProfile = ...
    scalarAngularProfile ./ ...
    mean(scalarAngularProfile, "omitnan");

axialAngularProfile = ...
    axialAngularProfile ./ ...
    mean(axialAngularProfile, "omitnan");

scalarAngularTheory = ...
    scalarAngularTheory ./ ...
    mean(scalarAngularTheory);

axialAngularTheory = ...
    axialAngularTheory ./ ...
    mean(axialAngularTheory);

%% Quantitative comparisons

centralMask = normalizedRadiusZX <= 0.35;

outerMask = ...
    normalizedRadiusZX >= 0.80 & ...
    normalizedRadiusZX <= 0.95;

horizontalOuterMask = ...
    outerMask & ...
    abs(cos(spectralAngleZX)) >= cosd(20);

verticalOuterMask = ...
    outerMask & ...
    abs(sin(spectralAngleZX)) >= cosd(20);

scalarCentralToOuterDensityRatio = ...
    mean(scalarEnsemblePowerZX(centralMask)) ./ ...
    mean(scalarEnsemblePowerZX(outerMask));

axialCentralToOuterDensityRatio = ...
    mean(axialEnsemblePowerZX(centralMask)) ./ ...
    mean(axialEnsemblePowerZX(outerMask));

axialHorizontalToVerticalRatio = ...
    mean(axialEnsemblePowerZX(horizontalOuterMask)) ./ ...
    mean(axialEnsemblePowerZX(verticalOuterMask));

totalAxialToScalarPowerRatio = ...
    sum(axialEnsemblePowerZX(:)) ./ ...
    sum(scalarEnsemblePowerZX(:));

expectedTotalAxialToScalarRatio = ...
    mean(expectedAxialPowerByDirection);

%% Figure

figureHandle = figure( ...
    "Visible", "off", ...
    "Color", "w", ...
    "Position", [50, 50, 1550, 1050]);

tiledlayout( ...
    2, ...
    3, ...
    "TileSpacing", "compact", ...
    "Padding", "compact");

nexttile;

imagesc( ...
    xM*1e3, ...
    zM*1e3, ...
    real(scalarFieldZX));

axis image;
set(gca, "YDir", "normal");
colorbar;

xlabel("x (mm)");
ylabel("z (mm)");
title("Scalar realization: Real(U)");

nexttile;

imagesc( ...
    xM*1e3, ...
    zM*1e3, ...
    real(axialFieldZX));

axis image;
set(gca, "YDir", "normal");
colorbar;

xlabel("x (mm)");
ylabel("z (mm)");
title("Axial realization: Real(U_z)");

nexttile;

plot( ...
    radialCenters, ...
    scalarRadialProfile, ...
    "-", ...
    "LineWidth", 1.5);

hold on;

plot( ...
    radialCenters, ...
    scalarRadialTheory, ...
    "--", ...
    "LineWidth", 1.5);

plot( ...
    radialCenters, ...
    axialRadialProfile, ...
    "-", ...
    "LineWidth", 1.5);

plot( ...
    radialCenters, ...
    axialRadialTheory, ...
    "--", ...
    "LineWidth", 1.5);

hold off;
grid on;

xlabel("Normalized radius k_{xz}/k_0");
ylabel("Normalized spectral density");

title("Radial ensemble profile");

legend( ...
    "Scalar measured", ...
    "Scalar theory", ...
    "Axial measured", ...
    "Axial theory", ...
    "Location", "northwest");

spectralDisplayLimitRadMm = ...
    1.10 * referenceWavenumberRadM / 1e3;

spectralCircleAngle = linspace(0, 2*pi, 361);

nexttile;

imagesc( ...
    kxRadM/1e3, ...
    kzRadM/1e3, ...
    scalarPowerDbZX);

axis image;
set(gca, "YDir", "normal");
clim([-40, 0]);

xlim([
    -spectralDisplayLimitRadMm, ...
     spectralDisplayLimitRadMm]);

ylim([
    -spectralDisplayLimitRadMm, ...
     spectralDisplayLimitRadMm]);

colorbar;
hold on;

plot( ...
    referenceWavenumberRadM .* ...
        cos(spectralCircleAngle) ./ 1e3, ...
    referenceWavenumberRadM .* ...
        sin(spectralCircleAngle) ./ 1e3, ...
    "--", ...
    "LineWidth", 1);

hold off;

xlabel("k_x (rad/mm)");
ylabel("k_z (rad/mm)");
title("Scalar ensemble power (dB)");

nexttile;

imagesc( ...
    kxRadM/1e3, ...
    kzRadM/1e3, ...
    axialPowerDbZX);

axis image;
set(gca, "YDir", "normal");
clim([-40, 0]);

xlim([
    -spectralDisplayLimitRadMm, ...
     spectralDisplayLimitRadMm]);

ylim([
    -spectralDisplayLimitRadMm, ...
     spectralDisplayLimitRadMm]);

colorbar;
hold on;

plot( ...
    referenceWavenumberRadM .* ...
        cos(spectralCircleAngle) ./ 1e3, ...
    referenceWavenumberRadM .* ...
        sin(spectralCircleAngle) ./ 1e3, ...
    "--", ...
    "LineWidth", 1);

hold off;

xlabel("k_x (rad/mm)");
ylabel("k_z (rad/mm)");
title("Axial ensemble power (dB)");

nexttile;

plot( ...
    rad2deg(angularCenters), ...
    scalarAngularProfile, ...
    "-", ...
    "LineWidth", 1.5);

hold on;

plot( ...
    rad2deg(angularCenters), ...
    scalarAngularTheory, ...
    "--", ...
    "LineWidth", 1.5);

plot( ...
    rad2deg(angularCenters), ...
    axialAngularProfile, ...
    "-", ...
    "LineWidth", 1.5);

plot( ...
    rad2deg(angularCenters), ...
    axialAngularTheory, ...
    "--", ...
    "LineWidth", 1.5);

hold off;
grid on;

xlim([-180, 180]);

xlabel("Spectral angle (degrees)");
ylabel("Normalized spectral density");

title(sprintf( ...
    "Angular profile, %.2f <= k/k_0 <= %.2f", ...
    angularMinimumRadius, ...
    angularMaximumRadius));

legend( ...
    "Scalar measured", ...
    "Scalar theory", ...
    "Axial measured", ...
    "Axial theory", ...
    "Location", "best");

sgtitle(sprintf( ...
    ["Projected-3D ensemble | N=%d | " + ...
     "f=%g Hz | c_s=%.1f m/s"], ...
    directionCount, ...
    frequencyHz, ...
    csMps));

figurePath = fullfile( ...
    outputDirectory, ...
    "projected3d_scalar_vs_axial_ensemble.png");

exportgraphics( ...
    figureHandle, ...
    figurePath, ...
    "Resolution", 180);

close(figureHandle);

%% Summary

summaryTable = table( ...
    directionCount, ...
    frequencyHz, ...
    csMps, ...
    ensembleRuntimeS, ...
    scalarCentralToOuterDensityRatio, ...
    axialCentralToOuterDensityRatio, ...
    axialHorizontalToVerticalRatio, ...
    totalAxialToScalarPowerRatio, ...
    expectedTotalAxialToScalarRatio, ...
    polarizationDiagnostics.maximum_orthogonality_error, ...
    polarizationDiagnostics.maximum_norm_error, ...
    VariableNames=[ ...
        "direction_count", ...
        "frequency_hz", ...
        "cs_m_s", ...
        "ensemble_runtime_s", ...
        "scalar_central_to_outer_density_ratio", ...
        "axial_central_to_outer_density_ratio", ...
        "axial_horizontal_to_vertical_outer_ratio", ...
        "total_axial_to_scalar_power_ratio", ...
        "expected_total_axial_to_scalar_ratio", ...
        "maximum_polarization_orthogonality_error", ...
        "maximum_polarization_norm_error"]);

summaryPath = fullfile( ...
    outputDirectory, ...
    "summary.csv");

writetable(summaryTable, summaryPath);

disp(summaryTable);

fprintf("\nScalar central/outer density ratio : %.4f\n", ...
    scalarCentralToOuterDensityRatio);

fprintf("Axial central/outer density ratio  : %.4f\n", ...
    axialCentralToOuterDensityRatio);

fprintf("Axial horizontal/vertical ratio    : %.4f\n", ...
    axialHorizontalToVerticalRatio);

fprintf("Measured total axial/scalar power  : %.4f\n", ...
    totalAxialToScalarPowerRatio);

fprintf("Expected total axial/scalar power  : %.4f\n", ...
    expectedTotalAxialToScalarRatio);

fprintf("Ensemble calculation runtime       : %.3f s\n", ...
    ensembleRuntimeS);

fprintf("Saved figure: %s\n", figurePath);
fprintf("Saved summary: %s\n", summaryPath);

%% Local functions

function [centers, profile] = ...
        radialAnnularMean(powerZX, normalizedRadiusZX, edges)

centers = 0.5 .* (edges(1:end-1) + edges(2:end));
profile = nan(size(centers));

for binIndex = 1:numel(centers)
    mask = ...
        normalizedRadiusZX >= edges(binIndex) & ...
        normalizedRadiusZX < edges(binIndex + 1);

    if any(mask(:))
        profile(binIndex) = mean(powerZX(mask));
    end
end

end

function normalizedProfile = ...
        normalizeRadialDensity(radius, profile)

validMask = isfinite(profile);

normalization = trapz( ...
    radius(validMask), ...
    profile(validMask) .* radius(validMask));

normalizedProfile = profile ./ normalization;

end

function [centers, profile] = angularAnnularMean( ...
    powerZX, normalizedRadiusZX, angleZX, ...
    minimumRadius, maximumRadius, edges)

centers = 0.5 .* (edges(1:end-1) + edges(2:end));
profile = nan(size(centers));

annulusMask = ...
    normalizedRadiusZX >= minimumRadius & ...
    normalizedRadiusZX <= maximumRadius;

for binIndex = 1:numel(centers)
    mask = ...
        annulusMask & ...
        angleZX >= edges(binIndex) & ...
        angleZX < edges(binIndex + 1);

    if any(mask(:))
        profile(binIndex) = mean(powerZX(mask));
    end
end

end
