%RUN_FINITE_CONTACT_SIZE_SWEEP
% Compare point, 4 mm, and 8 mm external contacts.

project_root = fileparts( ...
    fileparts(fileparts(mfilename('fullpath'))));

addpath(fullfile(project_root, 'src'));
addpath(fullfile(project_root, 'benchmarks'));

sweep = ...
    kwsim_benchmarks.finite_contacts_2d.runSizeSweep();

fprintf('%s\n', sweep.summary);

output_directory = fullfile( ...
    project_root, ...
    'outputs', ...
    'finite_contacts_2d', ...
    'contact_size_sweep');

paths = ...
    kwsim_benchmarks.finite_contacts_2d.saveSizeSweep( ...
        sweep, output_directory);

paths.figure_file = fullfile( ...
    output_directory, ...
    'contact_size_sweep.png');

[figure_handle, ~] = ...
    kwsim_benchmarks.finite_contacts_2d.plotSizeSweep( ...
        sweep, paths.figure_file);

close(figure_handle);

disp(paths);

if ~sweep.valid
    error( ...
        'kwsim:FiniteContactSizeSweepFailed', ...
        'One or more contact-size simulations failed validation.');
end
