function report = evaluateRun(result, raw, preflight)
%EVALUATERUN Apply stage-aware single-run physical reliability checks.
%
% Cross-run checks are handled by the validation suite for each stage. This
% function evaluates source purity, P/S content, harmonic stationarity,
% expected shear speed, numerical finiteness, and (for Stage 3) angular
% directionality for one simulation.

arguments
    result struct
    raw struct
    preflight struct
end

cfg = result.config_resolved;
checks = repmat(emptyCheck(), 0, 1);

addCheck("preflight", preflight.valid, double(preflight.valid), 1, ...
    "All configuration and resource checks must pass.");
addCheck("shear_ppw", ...
    cfg.derived.shear_points_per_wavelength >= cfg.grid.minimum_shear_ppw, ...
    cfg.derived.shear_points_per_wavelength, cfg.grid.minimum_shear_ppw, ...
    "Shear wavelength is under-resolved.");

source_fraction = result.source.diagnostics.fundamental_fraction;
addCheck("source_fundamental_fraction", ...
    source_fraction >= cfg.diagnostics.minimum_source_fundamental_fraction, ...
    source_fraction, cfg.diagnostics.minimum_source_fundamental_fraction, ...
    "The stationary source contains excessive non-fundamental energy.");

velocity = result.fields.velocity;
all_values = [velocity.axial_shear_zx(:); velocity.axial_compression_zx(:); ...
    velocity.lateral_shear_zx(:); velocity.lateral_compression_zx(:)];
finite_fields = all(isfinite(real(all_values))) && all(isfinite(imag(all_values)));
addCheck("finite_fields", finite_fields, double(finite_fields), 1, ...
    "One or more phasor fields contain NaN or Inf values.");

shear_energy = sum(abs(velocity.axial_shear_zx).^2, 'all') + ...
    sum(abs(velocity.lateral_shear_zx).^2, 'all');
compression_energy = sum(abs(velocity.axial_compression_zx).^2, 'all') + ...
    sum(abs(velocity.lateral_compression_zx).^2, 'all');
p_to_s_ratio = compression_energy / max(shear_energy, eps);
if cfg.stage == 1
    addCheck("p_to_s_energy_ratio", ...
        p_to_s_ratio <= cfg.diagnostics.maximum_p_to_s_energy_ratio, ...
        p_to_s_ratio, cfg.diagnostics.maximum_p_to_s_energy_ratio, ...
        "The homogeneous directional benchmark contains excessive compressional energy.");
end

% Preserve a broad first-half/second-half comparison as a descriptive
% transient metric, but enforce the acceptance criterion exactly as stated:
% compare the two final complete cycles. Absolute time is retained in every
% fit, so a stationary harmonic field has the same complex phasor.
Nt = numel(raw.t_record_s);
split = floor(Nt / 2);
first_index = 1:split;
second_index = (split + 1):Nt;
first_fit = kwsim.diagnostics.fitHarmonic( ...
    raw.uy_split_s(:, first_index), raw.t_record_s(first_index), cfg.source.f0_hz);
second_fit = kwsim.diagnostics.fitHarmonic( ...
    raw.uy_split_s(:, second_index), raw.t_record_s(second_index), cfg.source.f0_hz);
analysis_half_change = norm(second_fit.phasor - first_fit.phasor) / ...
    max(norm(second_fit.phasor), eps);

period_s = 1/cfg.source.f0_hz;
end_time_s = raw.t_record_s(end);
penultimate_index = raw.t_record_s >= end_time_s - 2*period_s & ...
    raw.t_record_s < end_time_s - period_s;
final_index = raw.t_record_s >= end_time_s - period_s;
penultimate_fit = kwsim.diagnostics.fitHarmonic( ...
    raw.uy_split_s(:, penultimate_index), raw.t_record_s(penultimate_index), ...
    cfg.source.f0_hz);
final_fit = kwsim.diagnostics.fitHarmonic( ...
    raw.uy_split_s(:, final_index), raw.t_record_s(final_index), ...
    cfg.source.f0_hz);
steady_change = norm(final_fit.phasor - penultimate_fit.phasor) / ...
    max(norm(final_fit.phasor), eps);
addCheck("steady_state_change", ...
    steady_change <= cfg.diagnostics.maximum_steady_state_change, ...
    steady_change, cfg.diagnostics.maximum_steady_state_change, ...
    "The recorded field has not reached a stable harmonic state.");

speed = kwsim.diagnostics.estimateShearSpeed( ...
    velocity.axial_shear_zx, result.axes.x_m, result.axes.z_m, ...
    result.source.center_m_xz(2), cfg.source.f0_hz);
speed_relative_error = abs(speed.speed_m_s - cfg.medium.cs_m_s) / cfg.medium.cs_m_s;
if cfg.stage == 1
    addCheck("shear_speed_relative_error", ...
        isfinite(speed_relative_error) && ...
        speed_relative_error <= cfg.diagnostics.maximum_speed_relative_error, ...
        speed_relative_error, cfg.diagnostics.maximum_speed_relative_error, ...
        "Phase-gradient shear speed does not match the homogeneous ground truth.");
end

symmetry = kwsim.diagnostics.symmetryMetrics(result);

if cfg.stage >= 3
    drive_error = result.source.drive_power_relative_error;
    addCheck("source_drive_normalization", ...
        drive_error <= cfg.diagnostics.maximum_drive_power_relative_error, ...
        drive_error, cfg.diagnostics.maximum_drive_power_relative_error, ...
        "The total prescribed RMS-squared velocity drive is not normalized.");

    contact = kwsim.diagnostics.contactMetrics(result);
    if lower(string(result.source.contact_model)) == "finite_segment"
        addCheck("finite_contact_span", ...
            contact.maximum_span_relative_error <= ...
            cfg.diagnostics.maximum_contact_span_relative_error, ...
            contact.maximum_span_relative_error, ...
            cfg.diagnostics.maximum_contact_span_relative_error, ...
            "The realized finite-contact span differs from the requested size.");
        addCheck("finite_contact_profile_symmetry", ...
            contact.maximum_profile_symmetry_error <= ...
            cfg.diagnostics.maximum_contact_profile_symmetry_error, ...
            contact.maximum_profile_symmetry_error, ...
            cfg.diagnostics.maximum_contact_profile_symmetry_error, ...
            "The finite-contact velocity profile is not symmetric.");
        addCheck("finite_contact_node_spacing", ...
            contact.minimum_node_spacing_points >= ...
            cfg.diagnostics.minimum_finite_contact_node_spacing_points, ...
            contact.minimum_node_spacing_points, ...
            cfg.diagnostics.minimum_finite_contact_node_spacing_points, ...
            "Finite-contact nodes are closer than the validated spacing.");
    end

    angular = kwsim.diagnostics.angularSpectrum2D(result);
    switch lower(string(cfg.source.regime))
        case "directional"
            addCheck("directional_angular_concentration", ...
                angular.target_concentration >= ...
                cfg.diagnostics.minimum_directional_concentration, ...
                angular.target_concentration, ...
                cfg.diagnostics.minimum_directional_concentration, ...
                "Too little shear energy lies in the requested angular sector.");
        case "diffuse"
            addCheck("diffuse_angular_entropy", ...
                angular.entropy_normalized >= ...
                cfg.diagnostics.minimum_diffuse_angular_entropy, ...
                angular.entropy_normalized, ...
                cfg.diagnostics.minimum_diffuse_angular_entropy, ...
                "The diffuse field angular entropy is too low.");
    end
else
    drive_error = NaN;
    contact = struct();
    angular = struct();
end

report = struct();
report.stage = cfg.stage;
report.valid = all([checks.pass]);
report.checks = checks;
report.metrics = struct();
report.metrics.source_fundamental_fraction = source_fraction;
report.metrics.p_to_s_energy_ratio = p_to_s_ratio;
report.metrics.steady_state_change = steady_change;
report.metrics.analysis_half_change = analysis_half_change;
report.metrics.shear_speed = speed;
report.metrics.shear_speed_relative_error = speed_relative_error;
report.metrics.symmetry = symmetry;
report.metrics.source_drive_relative_error = drive_error;
report.metrics.contact = contact;
report.metrics.angular = angular;
report.preflight = preflight;
if cfg.stage == 1
    report.summary = sprintf(['valid=%d, source fundamental=%.6f, ', ...
        'P/S energy=%.4g, steady change=%.4g, ', ...
        'cs estimate=%.4f m/s (error %.3f%%)'], ...
        report.valid, source_fraction, p_to_s_ratio, steady_change, ...
        speed.speed_m_s, 100*speed_relative_error);
elseif cfg.stage == 2
    report.summary = sprintf(['valid=%d, source fundamental=%.6f, ', ...
        'P/S energy=%.4g, steady change=%.4g, geometry objects=%d'], ...
        report.valid, source_fraction, p_to_s_ratio, steady_change, ...
        cfg.geometry.resolved.object_count);
else
    report.summary = sprintf(['valid=%d, regime=%s, source fundamental=%.6f, ', ...
        'drive error=%.3g, angular concentration=%.3f, entropy=%.3f'], ...
        report.valid, string(cfg.source.regime), source_fraction, drive_error, ...
        angular.target_concentration, angular.entropy_normalized);
end

    function addCheck(name, pass, value, threshold, message)
        check = emptyCheck();
        check.name = string(name);
        check.pass = logical(pass);
        check.value = double(value);
        check.threshold = double(threshold);
        check.message = string(message);
        checks(end + 1, 1) = check;
    end

end

function check = emptyCheck()
check = struct('name', "", 'pass', false, 'value', NaN, ...
    'threshold', NaN, 'message', "");
end
