function handles = plotMaterialGeometry3D(cfg, options)
%PLOTMATERIALGEOMETRY3D Visualize resolved 3D material-property maps.
%
% handles = kwsim.viz.plotMaterialGeometry3D(cfg)
%
% The input can be a requested or resolved 3D configuration. The function
% builds the material maps without executing k-Wave.
%
% Layout:
%   1. Orthogonal physical slices in a three-dimensional view.
%   2. x-z slice at fixed y.
%   3. x-y slice at fixed z.
%   4. y-z slice at fixed x.

arguments
    cfg struct
    options.Title (1,1) string = ""
    options.FigureVisible (1,1) string = "on"
    options.XIndex = []
    options.YIndex = []
    options.ZIndex = []
end

figure_visible = ...
    lower(options.FigureVisible);

if ~any(figure_visible == ["on", "off"])
    error( ...
        "kwsim:InvalidFigureVisibility", ...
        "FigureVisible must be on or off.");
end

if ~isfield(cfg, "geometry") || ...
        ~isfield(cfg.geometry, "resolved") || ...
        ~cfg.geometry.resolved
    [cfg, ~] = ...
        kwsim.three_d.validateConfig(cfg);
end

truth = ...
    kwsim.three_d.buildMaterialMaps(cfg);

cs_xyz = ...
    double(truth.cs_m_s_xyz);

material_id_xyz = ...
    truth.material_id_xyz;

x_m = ...
    double(cfg.derived.x_full_m(:).');

y_m = ...
    double(cfg.derived.y_full_m(:).');

z_m = ...
    double(cfg.derived.z_full_m(:).');

nx = ...
    numel(x_m);

ny = ...
    numel(y_m);

nz = ...
    numel(z_m);

x_index = ...
    resolveIndex( ...
        options.XIndex, ...
        nx, ...
        "XIndex");

y_index = ...
    resolveIndex( ...
        options.YIndex, ...
        ny, ...
        "YIndex");

z_index = ...
    resolveIndex( ...
        options.ZIndex, ...
        nz, ...
        "ZIndex");

x_mm = ...
    1e3 * x_m;

y_mm = ...
    1e3 * y_m;

z_mm = ...
    1e3 * z_m;

cs_xz = ...
    squeeze(cs_xyz(:, y_index, :)).';

cs_xy = ...
    squeeze(cs_xyz(:, :, z_index)).';

cs_yz = ...
    squeeze(cs_xyz(x_index, :, :)).';

cs_min = ...
    min(cs_xyz, [], "all");

cs_max = ...
    max(cs_xyz, [], "all");

material_ids = ...
    unique(material_id_xyz);

figure_title = ...
    resolveTitle( ...
        cfg, ...
        options.Title);

summary_title = ...
    sprintf( ...
        "%s | materials=%d | SWS %.2f-%.2f m/s", ...
        figure_title, ...
        numel(material_ids), ...
        cs_min, ...
        cs_max);

style = ...
    kwsim.viz.figureTemplate();

figure_handle = ...
    figure( ...
        "Visible", ...
        char(figure_visible), ...
        "Name", ...
        char(figure_title), ...
        "Color", ...
        style.background_color, ...
        "Position", ...
        [100, 100, 1400, 950]);

layout = ...
    tiledlayout( ...
        figure_handle, ...
        2, ...
        2, ...
        "TileSpacing", ...
        "compact", ...
        "Padding", ...
        "compact");

title( ...
    layout, ...
    summary_title, ...
    "Interpreter", ...
    "none");

axes_handles = ...
    gobjects(1, 4);

%% Three-dimensional orthogonal slices

axes_handles(1) = ...
    nexttile(layout, 1);

axes_3d = ...
    axes_handles(1);

% MATLAB slice expects volume ordering [Ny,Nx,Nz] when coordinate vectors
% are supplied as x, y, and z.
cs_yxz = ...
    permute(cs_xyz, [2, 1, 3]);

slice_handles = ...
    slice( ...
        axes_3d, ...
        x_mm, ...
        y_mm, ...
        z_mm, ...
        cs_yxz, ...
        x_mm(x_index), ...
        y_mm(y_index), ...
        z_mm(z_index));

set( ...
    slice_handles, ...
    "EdgeColor", ...
    "none", ...
    "FaceAlpha", ...
    0.88);

xlabel(axes_3d, "x (mm)");
ylabel(axes_3d, "y (mm)");
zlabel(axes_3d, "z (mm)");

title( ...
    axes_3d, ...
    "Orthogonal SWS slices");

xlim(axes_3d, [x_mm(1), x_mm(end)]);
ylim(axes_3d, [y_mm(1), y_mm(end)]);
zlim(axes_3d, [z_mm(1), z_mm(end)]);

axis(axes_3d, "equal");
grid(axes_3d, "on");
box(axes_3d, "on");
view(axes_3d, 38, 24);

clim(axes_3d, [cs_min, cs_max]);

colorbar_3d = ...
    colorbar(axes_3d);

colorbar_3d.Label.String = ...
    "Shear-wave speed (m/s)";

%% x-z

axes_handles(2) = ...
    nexttile(layout, 2);

imagesc( ...
    axes_handles(2), ...
    x_mm, ...
    z_mm, ...
    cs_xz);

formatSliceAxes( ...
    axes_handles(2), ...
    "x (mm)", ...
    "z (mm)", ...
    sprintf( ...
        "x-z at y = %.2f mm", ...
        y_mm(y_index)), ...
    cs_min, ...
    cs_max);

%% x-y

axes_handles(3) = ...
    nexttile(layout, 3);

imagesc( ...
    axes_handles(3), ...
    x_mm, ...
    y_mm, ...
    cs_xy);

formatSliceAxes( ...
    axes_handles(3), ...
    "x (mm)", ...
    "y (mm)", ...
    sprintf( ...
        "x-y at z = %.2f mm", ...
        z_mm(z_index)), ...
    cs_min, ...
    cs_max);

%% y-z

axes_handles(4) = ...
    nexttile(layout, 4);

imagesc( ...
    axes_handles(4), ...
    y_mm, ...
    z_mm, ...
    cs_yz);

formatSliceAxes( ...
    axes_handles(4), ...
    "y (mm)", ...
    "z (mm)", ...
    sprintf( ...
        "y-z at x = %.2f mm", ...
        x_mm(x_index)), ...
    cs_min, ...
    cs_max);

colorbar_2d = ...
    colorbar(axes_handles(4));

colorbar_2d.Label.String = ...
    "Shear-wave speed (m/s)";

kwsim.viz.applyFigureStyle( ...
    figure_handle, ...
    style);

handles = struct();

handles.figure = ...
    figure_handle;

handles.layout = ...
    layout;

handles.axes = ...
    axes_handles;

handles.truth = ...
    truth;

handles.config_resolved = ...
    cfg;

handles.indices = struct( ...
    "x", ...
    x_index, ...
    "y", ...
    y_index, ...
    "z", ...
    z_index);

handles.coordinates_m = struct( ...
    "x", ...
    x_m(x_index), ...
    "y", ...
    y_m(y_index), ...
    "z", ...
    z_m(z_index));

handles.material_ids = ...
    material_ids;

end


function formatSliceAxes( ...
        axes_handle, ...
        x_label, ...
        y_label, ...
        plot_title, ...
        minimum_value, ...
        maximum_value)

axis(axes_handle, "image");
axis(axes_handle, "xy");

xlabel(axes_handle, x_label);
ylabel(axes_handle, y_label);

title( ...
    axes_handle, ...
    plot_title, ...
    "Interpreter", ...
    "none");

clim( ...
    axes_handle, ...
    [minimum_value, maximum_value]);

box(axes_handle, "on");

end


function index = resolveIndex( ...
        requested_index, ...
        dimension_size, ...
        option_name)

if isempty(requested_index)
    index = ...
        round((dimension_size + 1) / 2);

    return
end

if ~( ...
        isnumeric(requested_index) && ...
        isscalar(requested_index) && ...
        isfinite(requested_index) && ...
        requested_index == fix(requested_index) && ...
        requested_index >= 1 && ...
        requested_index <= dimension_size)
    error( ...
        "kwsim:InvalidSliceIndex", ...
        "%s must be an integer between 1 and %d.", ...
        option_name, ...
        dimension_size);
end

index = ...
    double(requested_index);

end


function figure_title = resolveTitle( ...
        cfg, ...
        requested_title)

if strlength(requested_title) > 0
    figure_title = ...
        requested_title;

elseif isfield(cfg, "scenario")
    figure_title = ...
        replace( ...
            string(cfg.scenario), ...
            "_", ...
            " ");

else
    figure_title = ...
        "3D material geometry";
end

end
