function handles = plotSourceGeometry3D(cfg, options)
%PLOTSOURCEGEOMETRY3D Visualize resolved 3D source locations and directions.
%
% handles = kwsim.viz.plotSourceGeometry3D(cfg)
%
% The input configuration must contain a resolved 3D source. The figure
% contains:
%
%   1. Three-dimensional domain, acquisition plane, source centers, and
%      nominal propagation directions.
%   2. x-z projection.
%   3. x-y projection.
%   4. y-z projection.
%
% Sources intersecting the central x-z acquisition plane are distinguished
% from out-of-plane sources.
%
% Name-value options
% ------------------
% Title:
%   Figure title. Empty uses cfg.scenario or source.bank_name.
%
% FigureVisible:
%   "on" or "off".
%
% ShowContactNodes:
%   Show the actual finite-contact source nodes.
%
% ShowDirectionArrows:
%   Show nominal propagation directions.
%
% ArrowLengthFraction:
%   Arrow length relative to the domain diagonal.

arguments
    cfg struct
    options.Title (1,1) string = ""
    options.FigureVisible (1,1) string = "on"
    options.ShowContactNodes (1,1) logical = false
    options.ShowDirectionArrows (1,1) logical = true
    options.ArrowLengthFraction (1,1) double = 0.10
end

figure_visible = ...
    lower(options.FigureVisible);

if ~any(figure_visible == ["on", "off"])
    error( ...
        "kwsim:InvalidFigureVisibility", ...
        "FigureVisible must be on or off.");
end

if ~( ...
        isfinite(options.ArrowLengthFraction) && ...
        options.ArrowLengthFraction > 0)
    error( ...
        "kwsim:InvalidSourceGeometryPlot", ...
        "ArrowLengthFraction must be positive and finite.");
end

if ~isfield(cfg, "grid") || ...
        ~isfield(cfg, "source")
    error( ...
        "kwsim:InvalidSourceGeometryPlot", ...
        "A resolved 3D configuration is required.");
end

if isfield(cfg.source, "geometry_metrics")
    metrics = ...
        cfg.source.geometry_metrics;
else
    metrics = ...
        kwsim.analysis.summarizeSourceGeometry3D(cfg);
end

spacing_m_xyz = [
    double(cfg.grid.dx_m), ...
    double(cfg.grid.dy_m), ...
    double(cfg.grid.dz_m)
];

grid_size_xyz = [
    double(cfg.grid.Nx), ...
    double(cfg.grid.Ny), ...
    double(cfg.grid.Nz)
];

domain_max_mm_xyz = ...
    (grid_size_xyz - 1) .* ...
    spacing_m_xyz * ...
    1e3;

x_limits_mm = ...
    [0, domain_max_mm_xyz(1)];

y_limits_mm = ...
    [0, domain_max_mm_xyz(2)];

z_limits_mm = ...
    [0, domain_max_mm_xyz(3)];

centers_mm_xyz = ...
    (double(metrics.centers_index_xyz) - 1) .* ...
    spacing_m_xyz * ...
    1e3;

directions_xyz = ...
    double(metrics.propagation_directions_xyz);

in_plane = ...
    logical(metrics.contact_intersects_plane(:));

out_of_plane = ...
    ~in_plane;

acquisition_y_mm = ...
    (double(metrics.acquisition_plane_y_index_full) - 1) * ...
    spacing_m_xyz(2) * ...
    1e3;

domain_diagonal_mm = ...
    norm(domain_max_mm_xyz);

arrow_length_mm = ...
    options.ArrowLengthFraction * ...
    domain_diagonal_mm;

source_count = ...
    size(centers_mm_xyz, 1);

marker_size = ...
    max( ...
        18, ...
        min( ...
            48, ...
            400 / sqrt(source_count)));

style = ...
    kwsim.viz.figureTemplate();

figure_title = ...
    resolveFigureTitle( ...
        cfg, ...
        options.Title);

axis_p10 = ...
    metricOrNaN( ...
        metrics, ...
        "pairwise_axis_angle_p10_deg");

axis_median = ...
    metricOrNaN( ...
        metrics, ...
        "pairwise_axis_angle_median_deg");

summary_title = ...
    sprintf( ...
        "%s | N=%d, P=%d, D_eff=%.3f, bias=%.3f, " + ...
        "axis p10=%s, median=%s", ...
        figure_title, ...
        metrics.source_count, ...
        metrics.in_plane_contact_count, ...
        metrics.effective_angular_dimension, ...
        metrics.directional_bias, ...
        formatAngle(axis_p10), ...
        formatAngle(axis_median));

in_plane_color = ...
    [0.0000, 0.4470, 0.7410];

out_of_plane_color = ...
    [0.8500, 0.3250, 0.0980];

arrow_color = ...
    [0.15, 0.15, 0.15];

node_color = ...
    [0.55, 0.55, 0.55];

plane_color = ...
    [0.65, 0.65, 0.65];

figure_handle = ...
    figure( ...
        "Visible", ...
        char(figure_visible), ...
        "Name", ...
        char(figure_title), ...
        "Color", ...
        style.background_color, ...
        "Position", ...
        [100, 100, 1400, 950]);

layout = ...
    tiledlayout( ...
        figure_handle, ...
        2, ...
        2, ...
        "TileSpacing", ...
        "compact", ...
        "Padding", ...
        "compact");

title( ...
    layout, ...
    summary_title, ...
    "Interpreter", ...
    "none");

axes_handles = ...
    gobjects(1, 4);

%% Three-dimensional view

axes_handles(1) = ...
    nexttile(layout, 1);

axes_3d = ...
    axes_handles(1);

hold(axes_3d, "on");

drawDomainBox( ...
    axes_3d, ...
    x_limits_mm, ...
    y_limits_mm, ...
    z_limits_mm);

drawAcquisitionPlane( ...
    axes_3d, ...
    x_limits_mm, ...
    acquisition_y_mm, ...
    z_limits_mm, ...
    plane_color);

if options.ShowContactNodes
    node_coordinates_mm = ...
        collectContactNodesMm( ...
            cfg, ...
            spacing_m_xyz);

    if ~isempty(node_coordinates_mm)
        scatter3( ...
            axes_3d, ...
            node_coordinates_mm(:, 1), ...
            node_coordinates_mm(:, 2), ...
            node_coordinates_mm(:, 3), ...
            8, ...
            node_color, ...
            "filled", ...
            "MarkerFaceAlpha", ...
            0.45, ...
            "HandleVisibility", ...
            "off");
    end
end

legend_handles = ...
    gobjects(0);

legend_labels = ...
    strings(0);

if any(in_plane)
    handle_in_plane = ...
        scatter3( ...
            axes_3d, ...
            centers_mm_xyz(in_plane, 1), ...
            centers_mm_xyz(in_plane, 2), ...
            centers_mm_xyz(in_plane, 3), ...
            marker_size, ...
            in_plane_color, ...
            "o", ...
            "filled", ...
            "MarkerEdgeColor", ...
            "k");

    legend_handles(end + 1) = ...
        handle_in_plane;

    legend_labels(end + 1) = ...
        "In-plane source";
end

if any(out_of_plane)
    handle_out_of_plane = ...
        scatter3( ...
            axes_3d, ...
            centers_mm_xyz(out_of_plane, 1), ...
            centers_mm_xyz(out_of_plane, 2), ...
            centers_mm_xyz(out_of_plane, 3), ...
            marker_size, ...
            out_of_plane_color, ...
            "d", ...
            "filled", ...
            "MarkerEdgeColor", ...
            "k");

    legend_handles(end + 1) = ...
        handle_out_of_plane;

    legend_labels(end + 1) = ...
        "Out-of-plane source";
end

if options.ShowDirectionArrows
    quiver3( ...
        axes_3d, ...
        centers_mm_xyz(:, 1), ...
        centers_mm_xyz(:, 2), ...
        centers_mm_xyz(:, 3), ...
        arrow_length_mm * directions_xyz(:, 1), ...
        arrow_length_mm * directions_xyz(:, 2), ...
        arrow_length_mm * directions_xyz(:, 3), ...
        0, ...
        "Color", ...
        arrow_color, ...
        "LineWidth", ...
        0.9, ...
        "MaxHeadSize", ...
        0.55, ...
        "HandleVisibility", ...
        "off");
end

xlabel(axes_3d, "x (mm)");
ylabel(axes_3d, "y (mm)");
zlabel(axes_3d, "z (mm)");

title( ...
    axes_3d, ...
    "Domain, acquisition plane, and propagation directions");

xlim(axes_3d, x_limits_mm);
ylim(axes_3d, y_limits_mm);
zlim(axes_3d, z_limits_mm);

axis(axes_3d, "equal");
grid(axes_3d, "on");
box(axes_3d, "on");
view(axes_3d, 38, 24);

if ~isempty(legend_handles)
    legend( ...
        axes_3d, ...
        legend_handles, ...
        cellstr(legend_labels), ...
        "Location", ...
        "best");
end

hold(axes_3d, "off");

%% x-z projection

axes_handles(2) = ...
    nexttile(layout, 2);

plotProjection( ...
    axes_handles(2), ...
    centers_mm_xyz(:, 1), ...
    centers_mm_xyz(:, 3), ...
    directions_xyz(:, 1), ...
    directions_xyz(:, 3), ...
    in_plane, ...
    x_limits_mm, ...
    z_limits_mm, ...
    "x (mm)", ...
    "z (mm)", ...
    "x-z projection: acquisition plane", ...
    arrow_length_mm, ...
    marker_size, ...
    options.ShowDirectionArrows, ...
    in_plane_color, ...
    out_of_plane_color, ...
    arrow_color);

%% x-y projection

axes_handles(3) = ...
    nexttile(layout, 3);

plotProjection( ...
    axes_handles(3), ...
    centers_mm_xyz(:, 1), ...
    centers_mm_xyz(:, 2), ...
    directions_xyz(:, 1), ...
    directions_xyz(:, 2), ...
    in_plane, ...
    x_limits_mm, ...
    y_limits_mm, ...
    "x (mm)", ...
    "y (mm)", ...
    "x-y projection", ...
    arrow_length_mm, ...
    marker_size, ...
    options.ShowDirectionArrows, ...
    in_plane_color, ...
    out_of_plane_color, ...
    arrow_color);

yline( ...
    axes_handles(3), ...
    acquisition_y_mm, ...
    "--", ...
    "Acquisition plane", ...
    "Color", ...
    plane_color, ...
    "LabelHorizontalAlignment", ...
    "left");

%% y-z projection

axes_handles(4) = ...
    nexttile(layout, 4);

plotProjection( ...
    axes_handles(4), ...
    centers_mm_xyz(:, 2), ...
    centers_mm_xyz(:, 3), ...
    directions_xyz(:, 2), ...
    directions_xyz(:, 3), ...
    in_plane, ...
    y_limits_mm, ...
    z_limits_mm, ...
    "y (mm)", ...
    "z (mm)", ...
    "y-z projection", ...
    arrow_length_mm, ...
    marker_size, ...
    options.ShowDirectionArrows, ...
    in_plane_color, ...
    out_of_plane_color, ...
    arrow_color);

xline( ...
    axes_handles(4), ...
    acquisition_y_mm, ...
    "--", ...
    "Acquisition plane", ...
    "Color", ...
    plane_color, ...
    "LabelVerticalAlignment", ...
    "bottom");

kwsim.viz.applyFigureStyle( ...
    figure_handle, ...
    style);

handles = struct();

handles.figure = ...
    figure_handle;

handles.layout = ...
    layout;

handles.axes = ...
    axes_handles;

handles.metrics = ...
    metrics;

handles.centers_mm_xyz = ...
    centers_mm_xyz;

handles.directions_xyz = ...
    directions_xyz;

handles.in_plane = ...
    in_plane;

handles.out_of_plane = ...
    out_of_plane;

handles.acquisition_y_mm = ...
    acquisition_y_mm;

end


function plotProjection( ...
        axes_handle, ...
        coordinate_1_mm, ...
        coordinate_2_mm, ...
        direction_1, ...
        direction_2, ...
        in_plane, ...
        limits_1_mm, ...
        limits_2_mm, ...
        label_1, ...
        label_2, ...
        plot_title, ...
        arrow_length_mm, ...
        marker_size, ...
        show_arrows, ...
        in_plane_color, ...
        out_of_plane_color, ...
        arrow_color)

out_of_plane = ...
    ~in_plane;

hold(axes_handle, "on");

rectangle( ...
    axes_handle, ...
    "Position", ...
    [ ...
        limits_1_mm(1), ...
        limits_2_mm(1), ...
        diff(limits_1_mm), ...
        diff(limits_2_mm) ...
    ], ...
    "EdgeColor", ...
    [0.25, 0.25, 0.25], ...
    "LineWidth", ...
    0.8);

if any(in_plane)
    scatter( ...
        axes_handle, ...
        coordinate_1_mm(in_plane), ...
        coordinate_2_mm(in_plane), ...
        marker_size, ...
        in_plane_color, ...
        "o", ...
        "filled", ...
        "MarkerEdgeColor", ...
        "k");
end

if any(out_of_plane)
    scatter( ...
        axes_handle, ...
        coordinate_1_mm(out_of_plane), ...
        coordinate_2_mm(out_of_plane), ...
        marker_size, ...
        out_of_plane_color, ...
        "d", ...
        "filled", ...
        "MarkerEdgeColor", ...
        "k");
end

if show_arrows
    quiver( ...
        axes_handle, ...
        coordinate_1_mm, ...
        coordinate_2_mm, ...
        arrow_length_mm * direction_1, ...
        arrow_length_mm * direction_2, ...
        0, ...
        "Color", ...
        arrow_color, ...
        "LineWidth", ...
        0.75, ...
        "MaxHeadSize", ...
        0.5);
end

xlabel(axes_handle, label_1);
ylabel(axes_handle, label_2);

title( ...
    axes_handle, ...
    plot_title, ...
    "Interpreter", ...
    "none");

xlim(axes_handle, limits_1_mm);
ylim(axes_handle, limits_2_mm);

axis(axes_handle, "equal");
grid(axes_handle, "on");
box(axes_handle, "on");

hold(axes_handle, "off");

end


function drawDomainBox( ...
        axes_handle, ...
        x_limits_mm, ...
        y_limits_mm, ...
        z_limits_mm)

x0 = x_limits_mm(1);
x1 = x_limits_mm(2);

y0 = y_limits_mm(1);
y1 = y_limits_mm(2);

z0 = z_limits_mm(1);
z1 = z_limits_mm(2);

vertices = [
    x0, y0, z0
    x1, y0, z0
    x1, y1, z0
    x0, y1, z0
    x0, y0, z1
    x1, y0, z1
    x1, y1, z1
    x0, y1, z1
];

edges = [
    1, 2
    2, 3
    3, 4
    4, 1
    5, 6
    6, 7
    7, 8
    8, 5
    1, 5
    2, 6
    3, 7
    4, 8
];

for edge_index = 1:size(edges, 1)
    endpoints = ...
        vertices(edges(edge_index, :), :);

    plot3( ...
        axes_handle, ...
        endpoints(:, 1), ...
        endpoints(:, 2), ...
        endpoints(:, 3), ...
        "-", ...
        "Color", ...
        [0.20, 0.20, 0.20], ...
        "LineWidth", ...
        0.9, ...
        "HandleVisibility", ...
        "off");
end

end


function drawAcquisitionPlane( ...
        axes_handle, ...
        x_limits_mm, ...
        y_coordinate_mm, ...
        z_limits_mm, ...
        plane_color)

patch( ...
    axes_handle, ...
    [ ...
        x_limits_mm(1), ...
        x_limits_mm(2), ...
        x_limits_mm(2), ...
        x_limits_mm(1) ...
    ], ...
    [ ...
        y_coordinate_mm, ...
        y_coordinate_mm, ...
        y_coordinate_mm, ...
        y_coordinate_mm ...
    ], ...
    [ ...
        z_limits_mm(1), ...
        z_limits_mm(1), ...
        z_limits_mm(2), ...
        z_limits_mm(2) ...
    ], ...
    plane_color, ...
    "FaceAlpha", ...
    0.12, ...
    "EdgeColor", ...
    plane_color, ...
    "LineStyle", ...
    "--", ...
    "HandleVisibility", ...
    "off");

end


function node_coordinates_mm = ...
        collectContactNodesMm( ...
            cfg, ...
            spacing_m_xyz)

source = ...
    cfg.source;

node_indices = ...
    zeros(0, 1);

layout = ...
    lower(string(source.layout));

if layout == "vibrator_bank"
    for vibrator_index = 1:numel(source.vibrators)
        node_indices = [
            node_indices
            double( ...
                source.vibrators(vibrator_index). ...
                node_linear_indices(:))
        ];
    end
elseif isfield(source, "contact_node_subscripts_xyz")
    subscripts_xyz = ...
        double(source.contact_node_subscripts_xyz);

    node_coordinates_mm = ...
        (subscripts_xyz - 1) .* ...
        spacing_m_xyz * ...
        1e3;

    return
elseif isfield(source, "contact_mask_xyz")
    node_indices = ...
        find(source.contact_mask_xyz);
elseif isfield(source, "contact_node_subscripts_yz") && ...
        isfield(source, "source_x_index")

    yz = ...
        double(source.contact_node_subscripts_yz);

    subscripts_xyz = [
        repmat( ...
            double(source.source_x_index), ...
            size(yz, 1), ...
            1), ...
        yz
    ];

    node_coordinates_mm = ...
        (subscripts_xyz - 1) .* ...
        spacing_m_xyz * ...
        1e3;

    return
end

if isempty(node_indices)
    node_coordinates_mm = ...
        zeros(0, 3);

    return
end

[node_x, node_y, node_z] = ...
    ind2sub( ...
        [ ...
            cfg.grid.Nx, ...
            cfg.grid.Ny, ...
            cfg.grid.Nz ...
        ], ...
        node_indices);

subscripts_xyz = ...
    double([node_x, node_y, node_z]);

node_coordinates_mm = ...
    (subscripts_xyz - 1) .* ...
    spacing_m_xyz * ...
    1e3;

end


function figure_title = resolveFigureTitle( ...
        cfg, ...
        requested_title)

if strlength(requested_title) > 0
    figure_title = ...
        requested_title;

    return
end

if isfield(cfg, "scenario") && ...
        strlength(string(cfg.scenario)) > 0
    figure_title = ...
        replace( ...
            string(cfg.scenario), ...
            "_", ...
            " ");

    return
end

if isfield(cfg.source, "bank_name") && ...
        strlength(string(cfg.source.bank_name)) > 0
    figure_title = ...
        replace( ...
            string(cfg.source.bank_name), ...
            "_", ...
            " ");

    return
end

figure_title = ...
    "3D source geometry";

end


function value = metricOrNaN(metrics, field_name)

if isfield(metrics, field_name)
    value = ...
        double(metrics.(field_name));
else
    value = ...
        NaN;
end

end


function text_value = formatAngle(value)

if isnan(value)
    text_value = ...
        "n/a";
else
    text_value = ...
        sprintf("%.1f deg", value);
end

end
