function tests = test_swsynth_projected3d_multidirection_field
%TEST_SWSYNTH_PROJECTED3D_MULTIDIRECTION_FIELD Superposition tests.

tests = functiontests(localfunctions);

end

function testHomogeneousFieldMatchesAnalyticSuperposition(testCase)

xM = 0:0.0005:0.020;
zM = (0:0.0005:0.018).';

csMps = 2.0;
frequencyHz = 250;

csMapZX = csMps * ones(numel(zM), numel(xM));

directionsXYZ = [
    0.48, 0.60, 0.64
    0.80, 0.00, 0.60
];

weights = [
    1.0
    0.5i
];

[fieldZX, diagnostics] = ...
    swsynth.propagation.projected3d. ...
        synthesizeDirectionalField( ...
            csMapZX, ...
            xM, ...
            zM, ...
            directionsXYZ, ...
            weights, ...
            frequencyHz, ...
            csMps);

[X, Z] = meshgrid(xM, zM);
omegaRadS = 2*pi*frequencyHz;

expectedZX = complex(zeros(size(csMapZX)));

for directionIndex = 1:size(directionsXYZ, 1)
    delayZX = ...
        directionsXYZ(directionIndex, 1) .* X ./ csMps + ...
        directionsXYZ(directionIndex, 3) .* Z ./ csMps;

    expectedZX = expectedZX + ...
        weights(directionIndex) .* ...
        exp(1i .* omegaRadS .* delayZX);
end

verifyEqual( ...
    testCase, ...
    fieldZX, ...
    expectedZX, ...
    "AbsTol", 1e-10);

verifyEqual(testCase, diagnostics.direction_count, 2);
verifyEqual( ...
    testCase, ...
    diagnostics.solver_methods, ...
    repmat("homogeneous_exact", 2, 1));

end

function testOppositeYDirectionsProduceSameObservedField(testCase)

xM = 0:0.001:0.020;
zM = (0:0.001:0.020).';

csMps = 3.0;
frequencyHz = 300;

csMapZX = csMps * ones(numel(zM), numel(xM));

positiveY = [0.48, 0.60, 0.64];
negativeY = [0.48, -0.60, 0.64];

fieldPositive = ...
    swsynth.propagation.projected3d. ...
        synthesizeDirectionalField( ...
            csMapZX, xM, zM, ...
            positiveY, 1, ...
            frequencyHz, csMps);

fieldNegative = ...
    swsynth.propagation.projected3d. ...
        synthesizeDirectionalField( ...
            csMapZX, xM, zM, ...
            negativeY, 1, ...
            frequencyHz, csMps);

verifyEqual( ...
    testCase, ...
    fieldNegative, ...
    fieldPositive, ...
    "AbsTol", 1e-12);

end

function testWeightCountMismatchIsRejected(testCase)

csMapZX = 2 * ones(5, 6);
xM = 0:0.001:0.005;
zM = (0:0.001:0.004).';

directionsXYZ = [
    1, 0, 0
    0, 0, 1
];

verifyError( ...
    testCase, ...
    @() swsynth.propagation.projected3d. ...
        synthesizeDirectionalField( ...
            csMapZX, ...
            xM, ...
            zM, ...
            directionsXYZ, ...
            1, ...
            250, ...
            2), ...
    "swsynth:Projected3DWeightCountMismatch");

end
