function tests = test_heterogeneous_multifield_configs
%TEST_HETEROGENEOUS_MULTIFIELD_CONFIGS
% Validate heterogeneous geometries combined with multiface source banks.

tests = functiontests(localfunctions);

end


function setupOnce(~)

repository_root = findRepositoryRoot();
addpath(fullfile(repository_root, "src"));

end


function testSphereWithN8P2(testCase)

cfg = loadResolvedConfig( ...
    "heterogeneous_sphere_partial_3d_n8_p2.json");

verifyEqual( ...
    testCase, ...
    string(cfg.source.layout), ...
    "vibrator_bank");

verifyEqual( ...
    testCase, ...
    double(cfg.source.vibrator_count), ...
    8);

verifyEqual( ...
    testCase, ...
    numel(cfg.source.vibrators), ...
    8);

verifyBankContract(testCase, cfg);

metrics = ...
    kwsim.analysis.summarizeSourceGeometry3D(cfg);

verifyEqual( ...
    testCase, ...
    metrics.source_count, ...
    8);

verifyGreaterThanOrEqual( ...
    testCase, ...
    metrics.in_plane_contact_count, ...
    2);

verifyGreaterThanOrEqual( ...
    testCase, ...
    metrics.out_of_plane_contact_count, ...
    6);

truth = ...
    kwsim.three_d.buildMaterialMaps(cfg);

verifyEqual( ...
    testCase, ...
    sort(unique(truth.material_id_xyz)), ...
    uint16([1; 2]));

end


function testCombinedWithN32P8(testCase)

cfg = loadResolvedConfig( ...
    "heterogeneous_combined_generated_angular_n32_p8.json");

verifyEqual( ...
    testCase, ...
    string(cfg.source.layout), ...
    "vibrator_bank");

verifyEqual( ...
    testCase, ...
    double(cfg.source.vibrator_count), ...
    32);

verifyEqual( ...
    testCase, ...
    numel(cfg.source.vibrators), ...
    32);

verifyBankContract(testCase, cfg);

metrics = ...
    kwsim.analysis.summarizeSourceGeometry3D(cfg);

verifyEqual( ...
    testCase, ...
    metrics.source_count, ...
    32);

verifyGreaterThanOrEqual( ...
    testCase, ...
    metrics.unique_face_count, ...
    6);

verifyGreaterThanOrEqual( ...
    testCase, ...
    metrics.in_plane_contact_count, ...
    8);

verifyGreaterThanOrEqual( ...
    testCase, ...
    metrics.out_of_plane_contact_count, ...
    24);

verifyGreaterThanOrEqual( ...
    testCase, ...
    metrics.effective_angular_dimension, ...
    2.7);

verifyLessThanOrEqual( ...
    testCase, ...
    metrics.directional_bias, ...
    0.25);

verifyGreaterThanOrEqual( ...
    testCase, ...
    metrics.angular_eigenvalues_descending(3), ...
    0.2);

truth = ...
    kwsim.three_d.buildMaterialMaps(cfg);

verifyEqual( ...
    testCase, ...
    sort(unique(truth.material_id_xyz)), ...
    uint16([2; 3; 4; 5]));

end


function verifyBankContract(testCase, cfg)

source = cfg.source;
vibrators = source.vibrators;

centers = ...
    double(vertcat(vibrators.center_index_xyz));

verifyEqual( ...
    testCase, ...
    size(unique(centers, "rows"), 1), ...
    numel(vibrators));

all_nodes = zeros(0, 1);
node_counts = zeros(numel(vibrators), 1);

for vibrator_index = 1:numel(vibrators)
    nodes = double( ...
        vibrators(vibrator_index). ...
        node_linear_indices(:));

    node_counts(vibrator_index) = numel(nodes);

    all_nodes = [
        all_nodes
        nodes
    ]; %#ok<AGROW>
end

verifyEqual( ...
    testCase, ...
    numel(unique(all_nodes)), ...
    numel(all_nodes));

phases = ...
    double([vibrators.phase_rad]);

verifyGreaterThanOrEqual( ...
    testCase, ...
    numel(unique(phases)), ...
    2);

directions = ...
    double(vertcat( ...
        vibrators.nominal_propagation_xyz));

polarizations = ...
    double(vertcat( ...
        vibrators.polarization_xyz));

verifyLessThanOrEqual( ...
    testCase, ...
    max(abs(vecnorm(directions, 2, 2) - 1)), ...
    1e-10);

verifyLessThanOrEqual( ...
    testCase, ...
    max(abs(vecnorm(polarizations, 2, 2) - 1)), ...
    1e-10);

verifyLessThanOrEqual( ...
    testCase, ...
    max(abs(sum( ...
        directions .* polarizations, ...
        2))), ...
    1e-10);

amplitudes = ...
    double([ ...
        vibrators.velocity_amplitude_m_s]).';

realized_drive = ...
    sum(node_counts .* amplitudes.^2 / 2);

expected_drive = ...
    double( ...
        source.reference_single_contact_node_count) * ...
    double(source.velocity_amplitude_m_s)^2 / 2;

relative_drive_error = ...
    abs(realized_drive - expected_drive) / ...
    max(abs(expected_drive), eps);

verifyLessThanOrEqual( ...
    testCase, ...
    relative_drive_error, ...
    1e-10);

end


function cfg = loadResolvedConfig(filename)

repository_root = findRepositoryRoot();

path = fullfile( ...
    repository_root, ...
    "configs", ...
    "three_d", ...
    filename);

[requested_cfg, ~] = ...
    kwsim.io.loadConfigJson(path);

[cfg, ~] = ...
    kwsim.three_d.validateConfig(requested_cfg);

end


function repository_root = findRepositoryRoot()

repository_root = ...
    fileparts( ...
        fileparts( ...
        fileparts( ...
            mfilename("fullpath"))));

end
