function tests = test_swsynth_solid_angle_directions
%TEST_SWSYNTH_SOLID_ANGLE_DIRECTIONS Direction-support tests.

tests = functiontests(localfunctions);

end

function testFullSphereUsesRequestedCounts(testCase)

directionCount = 128;
inPlaneCount = 8;

[directionsXYZ, diagnostics] = ...
    swsynth.sampleSolidAngleDirections( ...
        directionCount, ...
        4*pi, ...
        [1, 0, 0], ...
        inPlaneCount);

verifySize(testCase, directionsXYZ, [directionCount, 3]);

verifyEqual( ...
    testCase, ...
    vecnorm(directionsXYZ, 2, 2), ...
    ones(directionCount, 1), ...
    "AbsTol", 1e-12);

verifyEqual( ...
    testCase, ...
    nnz(abs(directionsXYZ(:,2)) <= 1e-12), ...
    inPlaneCount);

verifyEqual(testCase, diagnostics.in_plane_count, inPlaneCount);
verifyEqual(testCase, diagnostics.out_of_plane_count, 120);
verifyEqual(testCase, diagnostics.half_angle_deg, 180, "AbsTol", 1e-12);

% Full sphere must include propagation from both x sides.
verifyLessThan(testCase, min(directionsXYZ(:,1)), 0);
verifyGreaterThan(testCase, max(directionsXYZ(:,1)), 0);

end

function testHemisphereHasCorrectSupport(testCase)

[directionsXYZ, diagnostics] = ...
    swsynth.sampleSolidAngleDirections( ...
        128, ...
        2*pi, ...
        [1, 0, 0], ...
        8);

verifyGreaterThanOrEqual( ...
    testCase, ...
    min(directionsXYZ(:,1)), ...
    -1e-12);

verifyEqual( ...
    testCase, ...
    diagnostics.half_angle_deg, ...
    90, ...
    "AbsTol", 1e-12);

verifyEqual( ...
    testCase, ...
    nnz(abs(directionsXYZ(:,2)) <= 1e-12), ...
    8);

end

function testIntermediateCapMatchesSolidAngle(testCase)

solidAngleSr = pi;

[directionsXYZ, diagnostics] = ...
    swsynth.sampleSolidAngleDirections( ...
        64, ...
        solidAngleSr, ...
        [0, 0, 1], ...
        4);

expectedHalfAngle = ...
    acos(1 - solidAngleSr/(2*pi));

verifyEqual( ...
    testCase, ...
    diagnostics.half_angle_rad, ...
    expectedHalfAngle, ...
    "AbsTol", 1e-12);

axisProjection = directionsXYZ * [0;0;1];

verifyGreaterThanOrEqual( ...
    testCase, ...
    min(axisProjection), ...
    cos(expectedHalfAngle) - 1e-12);

end

function testSamplingIsExactlyReproducible(testCase)

directionsA = ...
    swsynth.sampleSolidAngleDirections( ...
        96, 3*pi, [1, 2, -1], 6);

directionsB = ...
    swsynth.sampleSolidAngleDirections( ...
        96, 3*pi, [1, 2, -1], 6);

verifyEqual( ...
    testCase, ...
    directionsB, ...
    directionsA, ...
    "AbsTol", 0);

end

function testCapWithoutPlaneIntersectionRejectsInPlaneSources(testCase)

% Narrow cap centered on +y does not reach uy = 0.
verifyError( ...
    testCase, ...
    @() swsynth.sampleSolidAngleDirections( ...
        32, ...
        0.25*pi, ...
        [0, 1, 0], ...
        1), ...
    "swsynth:SolidAngleDoesNotIntersectObservationPlane");

end

function testInPlaneCountCannotExceedTotalCount(testCase)

verifyError( ...
    testCase, ...
    @() swsynth.sampleSolidAngleDirections( ...
        8, ...
        4*pi, ...
        [1, 0, 0], ...
        9), ...
    "swsynth:InvalidInPlaneDirectionCount");

end
