function tests = test_swsynth_projected3d_slowness
%TEST_SWSYNTH_PROJECTED3D_SLOWNESS Projected-3D direction tests.

tests = functiontests(localfunctions);

end

function testHomogeneousProjectionMatchesAnalyticRelation(testCase)

csMps = 2.0;
csMapZX = csMps * ones(7, 9);

directionXYZ = [0.6, 0.8, 0];

[slownessZX, diagnostics] = ...
    swsynth.propagation.projected3d.buildDirectionalSlowness( ...
        csMapZX, ...
        directionXYZ, ...
        csMps);

expectedProjectedSlowness = ...
    sqrt(directionXYZ(1)^2 + directionXYZ(3)^2) / csMps;

verifyEqual( ...
    testCase, ...
    slownessZX, ...
    expectedProjectedSlowness * ones(size(csMapZX)), ...
    "AbsTol", 1e-14);

verifyEqual( ...
    testCase, ...
    diagnostics.projected_direction_norm, ...
    0.6, ...
    "AbsTol", 1e-14);

verifyEqual( ...
    testCase, ...
    diagnostics.transverse_slowness_s_m, ...
    0.4, ...
    "AbsTol", 1e-14);

end

function testOppositeOutOfPlaneDirectionsHaveSameProjection(testCase)

csMapZX = 3.0 * ones(5, 6);

directionPositiveY = [0.5, sqrt(0.5), 0.5];
directionNegativeY = [0.5, -sqrt(0.5), 0.5];

slownessPositive = ...
    swsynth.propagation.projected3d.buildDirectionalSlowness( ...
        csMapZX, ...
        directionPositiveY, ...
        3.0);

slownessNegative = ...
    swsynth.propagation.projected3d.buildDirectionalSlowness( ...
        csMapZX, ...
        directionNegativeY, ...
        3.0);

verifyEqual( ...
    testCase, ...
    slownessNegative, ...
    slownessPositive, ...
    "AbsTol", 0);

end

function testMoreOutOfPlaneDirectionHasSmallerProjectedSlowness(testCase)

csMapZX = 2.0 * ones(4, 4);

mostlyInPlane = [sqrt(0.96), 0.2, 0];
mostlyOutOfPlane = [0.6, 0.8, 0];

slownessInPlane = ...
    swsynth.propagation.projected3d.buildDirectionalSlowness( ...
        csMapZX, ...
        mostlyInPlane, ...
        2.0);

slownessOutOfPlane = ...
    swsynth.propagation.projected3d.buildDirectionalSlowness( ...
        csMapZX, ...
        mostlyOutOfPlane, ...
        2.0);

verifyLessThan( ...
    testCase, ...
    slownessOutOfPlane(1), ...
    slownessInPlane(1));

end

function testPureOutOfPlaneDirectionHasZeroProjectedWavenumber(testCase)

csMps = 2.5;
csMapZX = csMps * ones(3, 8);

slownessZX = ...
    swsynth.propagation.projected3d.buildDirectionalSlowness( ...
        csMapZX, ...
        [0, 1, 0], ...
        csMps);

verifyEqual( ...
    testCase, ...
    slownessZX, ...
    zeros(size(csMapZX)), ...
    "AbsTol", 1e-14);

end

function testEvanescentRegionIsRejected(testCase)

csMapZX = [
    1, 1, 3
    1, 1, 3
];

verifyError( ...
    testCase, ...
    @() swsynth.propagation.projected3d.buildDirectionalSlowness( ...
        csMapZX, ...
        [0.6, 0.8, 0], ...
        1.0), ...
    "swsynth:Projected3DEvanescentRegion");

end
