function tests = test_3d_vibrator_bank_source
%TEST_3D_VIBRATOR_BANK_SOURCE Tests for resolved multi-contact sources.

tests = functiontests(localfunctions);

end


function setupOnce(~)

repository_root = fileparts(fileparts(fileparts( ...
    mfilename("fullpath"))));

addpath(fullfile(repository_root, "src"));

end


function testMaskAndSourceMatrixDimensions(testCase)

[cfg, kgrid] = resolvedSyntheticBank();

[source, metadata] = ...
    kwsim.three_d.buildVibratorBankSource( ...
        cfg, ...
        kgrid);

expected_source_points = ...
    sum(arrayfun( ...
        @(vibrator) numel(vibrator.node_linear_indices), ...
        cfg.source.vibrators));

expected_size = [
    expected_source_points, ...
    numel(kgrid.t_array)
];

verifySize(testCase, ...
    source.u_mask, ...
    [cfg.grid.Nx, cfg.grid.Ny, cfg.grid.Nz]);

verifyEqual(testCase, ...
    nnz(source.u_mask), ...
    expected_source_points);

verifySize(testCase, ...
    source.ux, ...
    expected_size);

verifySize(testCase, ...
    source.uy, ...
    expected_size);

verifySize(testCase, ...
    source.uz, ...
    expected_size);

verifyEqual(testCase, ...
    metadata.vibrator_count, ...
    2);

verifyEqual(testCase, ...
    metadata.contact_node_count, ...
    expected_source_points);

verifyEqual(testCase, ...
    metadata.active_linear_indices, ...
    find(source.u_mask));

end


function testWaveformsFollowLinearMaskOrdering(testCase)

[cfg, kgrid] = resolvedSyntheticBank();

[source, metadata] = ...
    kwsim.three_d.buildVibratorBankSource( ...
        cfg, ...
        kgrid);

t_s = ...
    double(kgrid.t_array(:).');

ramp_duration_s = ...
    cfg.source.ramp_cycles / ...
    cfg.source.f0_hz;

envelope = ...
    ones(size(t_s));

ramp_index = ...
    t_s < ramp_duration_s;

envelope(ramp_index) = ...
    0.5 * ...
    (1 - cos( ...
        pi*t_s(ramp_index) / ...
        ramp_duration_s));

for vibrator_index = 1:numel(cfg.source.vibrators)
    vibrator = ...
        cfg.source.vibrators(vibrator_index);

    rows = ...
        metadata.owner_vibrator_index_by_source_row == ...
        vibrator_index;

    waveform = ...
        vibrator.velocity_amplitude_m_s .* ...
        envelope .* ...
        sin( ...
            2*pi*cfg.source.f0_hz*t_s + ...
            vibrator.phase_rad);

    polarization = ...
        vibrator.polarization_xyz;

    expected_ux = repmat( ...
        single(polarization(1) .* waveform), ...
        nnz(rows), ...
        1);

    expected_uy = repmat( ...
        single(polarization(2) .* waveform), ...
        nnz(rows), ...
        1);

    expected_uz = repmat( ...
        single(polarization(3) .* waveform), ...
        nnz(rows), ...
        1);

    verifyEqual(testCase, ...
        source.ux(rows, :), ...
        expected_ux);

    verifyEqual(testCase, ...
        source.uy(rows, :), ...
        expected_uy);

    verifyEqual(testCase, ...
        source.uz(rows, :), ...
        expected_uz);
end

end


function testEqualTotalRmsNormalization(testCase)

[cfg, kgrid, base_amplitude] = ...
    resolvedSyntheticBank();

[~, metadata] = ...
    kwsim.three_d.buildVibratorBankSource( ...
        cfg, ...
        kgrid);

nodes_per_vibrator = ...
    numel(cfg.source.vibrators(1).node_linear_indices);

expected_total_rms_squared = ...
    nodes_per_vibrator * ...
    base_amplitude^2 / 2;

verifyEqual(testCase, ...
    metadata.nominal_total_drive_rms_squared_m2_s2, ...
    expected_total_rms_squared, ...
    "RelTol", ...
    1e-12);

end


function testOverlappingContactsRejected(testCase)

[cfg, kgrid] = resolvedSyntheticBank();

cfg.source.vibrators(2).node_linear_indices(1) = ...
    cfg.source.vibrators(1).node_linear_indices(1);

verifyError(testCase, ...
    @() kwsim.three_d.buildVibratorBankSource( ...
        cfg, ...
        kgrid), ...
    "kwsim:OverlappingVibratorContacts");

end


function [cfg, kgrid, base_amplitude] = ...
    resolvedSyntheticBank()

cfg = kwsim.three_d.defaultConfig();

cfg.grid.Nx = 8;
cfg.grid.Ny = 9;
cfg.grid.Nz = 10;

cfg.source.layout = ...
    "vibrator_bank";

cfg.source.phase_policy = ...
    "explicit";

cfg.source.amplitude_policy = ...
    "equal_total_rms";

base_amplitude = ...
    cfg.source.velocity_amplitude_m_s;

per_vibrator_amplitude = ...
    base_amplitude / sqrt(2);

mask_1 = false( ...
    cfg.grid.Nx, ...
    cfg.grid.Ny, ...
    cfg.grid.Nz);

mask_1(2, 2, 3) = true;
mask_1(2, 4, 3) = true;

mask_2 = false( ...
    cfg.grid.Nx, ...
    cfg.grid.Ny, ...
    cfg.grid.Nz);

mask_2(2, 6, 7) = true;
mask_2(2, 8, 7) = true;

template = struct( ...
    "name", "", ...
    "node_linear_indices", [], ...
    "center_index_xyz", [NaN, NaN, NaN], ...
    "center_m_xyz", [NaN, NaN, NaN], ...
    "polarization_xyz", [NaN, NaN, NaN], ...
    "nominal_propagation_xyz", [NaN, NaN, NaN], ...
    "phase_rad", NaN, ...
    "velocity_amplitude_m_s", NaN);

vibrators = ...
    repmat(template, 2, 1);

vibrators(1).name = ...
    "vibrator_1";

vibrators(1).node_linear_indices = ...
    find(mask_1);

vibrators(1).center_index_xyz = ...
    [2, 3, 3];

vibrators(1).center_m_xyz = ...
    [0.5e-3, 1.0e-3, 1.0e-3];

vibrators(1).polarization_xyz = ...
    [0, 0, 1];

vibrators(1).nominal_propagation_xyz = ...
    [1, 0, 0];

vibrators(1).phase_rad = ...
    0;

vibrators(1).velocity_amplitude_m_s = ...
    per_vibrator_amplitude;

vibrators(2).name = ...
    "vibrator_2";

vibrators(2).node_linear_indices = ...
    find(mask_2);

vibrators(2).center_index_xyz = ...
    [2, 7, 7];

vibrators(2).center_m_xyz = ...
    [0.5e-3, 3.0e-3, 3.0e-3];

vibrators(2).polarization_xyz = ...
    [0, 1, 0];

vibrators(2).nominal_propagation_xyz = ...
    [1, 0, 0];

vibrators(2).phase_rad = ...
    pi/2;

vibrators(2).velocity_amplitude_m_s = ...
    per_vibrator_amplitude;

cfg.source.vibrators = ...
    vibrators;

kgrid = struct();

sampling_frequency_hz = ...
    50e3;

duration_s = ...
    12 / cfg.source.f0_hz;

kgrid.t_array = ...
    0:(1/sampling_frequency_hz):duration_s;

end
