function tests = test_heterogeneous_harmonic_3d_validation
%TEST_HETEROGENEOUS_HARMONIC_3D_VALIDATION Test heterogeneous report logic.

tests = ...
    functiontests(localfunctions);

end


function setupOnce(~)

repository_root = ...
    findRepositoryRoot();

addpath(fullfile(repository_root, "src"));

end


function testValidCombinedSyntheticResult(testCase)

result = ...
    makeSyntheticCombinedResult();

report = ...
    kwsim.validation. ...
    evaluateHeterogeneousHarmonic3D(result);

verifyTrue( ...
    testCase, ...
    report.valid);

verifyEqual( ...
    testCase, ...
    string(report.scope), ...
    "heterogeneous_harmonic_3d");

verifyEqual( ...
    testCase, ...
    report.metrics.actual_material_ids, ...
    [2; 3; 4; 5]);

verifyGreaterThan( ...
    testCase, ...
    report.metrics.total_shear_energy, ...
    0);

end


function testMissingConfiguredMaterialFails(testCase)

result = ...
    makeSyntheticCombinedResult();

result.truth.material_id_zyx( ...
    result.truth.material_id_zyx == 5) = ...
    uint16(3);

report = ...
    kwsim.validation. ...
    evaluateHeterogeneousHarmonic3D(result);

verifyFalse( ...
    testCase, ...
    report.valid);

check_names = ...
    string({report.checks.name});

check_index = ...
    find( ...
        check_names == ...
        "configured_material_ids_present", ...
        1);

verifyNotEmpty( ...
    testCase, ...
    check_index);

verifyFalse( ...
    testCase, ...
    report.checks(check_index).pass);

end


function result = makeSyntheticCombinedResult()

repository_root = ...
    findRepositoryRoot();

configuration_file = ...
    fullfile( ...
        repository_root, ...
        "configs", ...
        "three_d", ...
        "heterogeneous_combined_3d.json");

[requested_cfg, ~] = ...
    kwsim.io.loadConfigJson( ...
        configuration_file);

[cfg, preflight] = ...
    kwsim.three_d.validateConfig( ...
        requested_cfg);

truth_internal = ...
    kwsim.three_d.buildMaterialMaps(cfg);

x_indices = ...
    cfg.sensor.x_indices;

y_indices = ...
    cfg.sensor.y_indices;

z_indices = ...
    cfg.sensor.z_indices;

cp_zyx = ...
    toPublicRoi( ...
        truth_internal.cp_m_s_xyz, ...
        x_indices, ...
        y_indices, ...
        z_indices);

cs_zyx = ...
    toPublicRoi( ...
        truth_internal.cs_m_s_xyz, ...
        x_indices, ...
        y_indices, ...
        z_indices);

rho_zyx = ...
    toPublicRoi( ...
        truth_internal.rho_kg_m3_xyz, ...
        x_indices, ...
        y_indices, ...
        z_indices);

material_id_zyx = ...
    toPublicRoi( ...
        truth_internal.material_id_xyz, ...
        x_indices, ...
        y_indices, ...
        z_indices);

volume_size = ...
    size(cs_zyx);

zero_volume = ...
    complex( ...
        zeros( ...
            volume_size, ...
            "single"));

z_shear = ...
    complex( ...
        ones( ...
            volume_size, ...
            "single"));

velocity = ...
    struct();

velocity.x_shear_zyx = ...
    zero_volume;

velocity.y_shear_zyx = ...
    zero_volume;

velocity.z_shear_zyx = ...
    z_shear;

velocity.x_compression_zyx = ...
    zero_volume;

velocity.y_compression_zyx = ...
    zero_volume;

velocity.z_compression_zyx = ...
    zero_volume;

result = ...
    struct();

result.config_resolved = ...
    cfg;

result.fields = ...
    struct();

result.fields.harmonic_velocity = ...
    velocity;

result.fields.frequency_hz = ...
    cfg.source.f0_hz;

result.truth = ...
    struct();

result.truth.cp_m_s_zyx = ...
    cp_zyx;

result.truth.cs_m_s_zyx = ...
    cs_zyx;

result.truth.rho_kg_m3_zyx = ...
    rho_zyx;

result.truth.material_id_zyx = ...
    material_id_zyx;

result.truth.homogeneous = ...
    false;

result.truth.orientation = ...
    "[Nz,Ny,Nx]";

result.preflight = ...
    preflight;

end


function roi_zyx = toPublicRoi( ...
        full_xyz, ...
        x_indices, ...
        y_indices, ...
        z_indices)

roi_xyz = ...
    full_xyz( ...
        x_indices, ...
        y_indices, ...
        z_indices);

roi_zyx = ...
    permute( ...
        roi_xyz, ...
        [3, 2, 1]);

end


function repository_root = findRepositoryRoot()

repository_root = ...
    fileparts( ...
        fileparts( ...
        fileparts( ...
            mfilename("fullpath"))));

end
