function tests = test_swsynth_cli_standardized_outputs
%TEST_SWSYNTH_CLI_STANDARDIZED_OUTPUTS Validate normalized run layout.

tests = functiontests(localfunctions);

end

function testRunCreatesStandardizedDirectoryTree(testCase)

repoRoot = fileparts(fileparts(fileparts(mfilename("fullpath"))));

configFile = fullfile( ...
    repoRoot, ...
    "configs", ...
    "swsynth", ...
    "validation", ...
    "homogeneous_eikonal_vs_plane_wave", ...
    "single_eikonal.json");

verifyTrue(testCase, isfile(configFile));

temporaryRoot = string(tempname);
runDirectory = fullfile(temporaryRoot, "standardized_run");

cleanup = onCleanup(@() removeDirectoryIfPresent(temporaryRoot));

outcome = swsynth.cli.runConfig( ...
    configFile, ...
    OutputDirectory=runDirectory);

verifyTrue(testCase, outcome.completed);

verifyTrue(testCase, isfolder(runDirectory));
verifyTrue(testCase, isfolder(fullfile(runDirectory, "config")));
verifyTrue(testCase, isfolder(fullfile(runDirectory, "data")));
verifyTrue(testCase, isfolder(fullfile(runDirectory, "figures")));
verifyTrue(testCase, isfolder(fullfile(runDirectory, "validation")));

verifyTrue(testCase, isfile(fullfile( ...
    runDirectory, ...
    "config", ...
    "requested_config.json")));

verifyTrue(testCase, isfile(fullfile( ...
    runDirectory, ...
    "config", ...
    "resolved_config.json")));

verifyTrue(testCase, isfile(fullfile( ...
    runDirectory, ...
    "data", ...
    "wavefield_sample.mat")));

sampleVariables = whos( ...
    "-file", ...
    fullfile(runDirectory,"data","wavefield_sample.mat"));

sampleVariableNames = string({sampleVariables.name});

verifyTrue( ...
    testCase, ...
    any(sampleVariableNames == "wavefield_sample"));

verifyFalse( ...
    testCase, ...
    any(sampleVariableNames == "wavefieldSample"));

verifyTrue(testCase, isfile(fullfile( ...
    runDirectory, ...
    "validation", ...
    "validation_report.json")));

verifyTrue(testCase, isfile(fullfile( ...
    runDirectory, ...
    "run_summary.json")));

verifyTrue(testCase, isfile(fullfile( ...
    runDirectory, ...
    "manifest.txt")));

summary = jsondecode(fileread(fullfile( ...
    runDirectory, ...
    "run_summary.json")));

verifyEqual( ...
    testCase, ...
    string(summary.schema_name), ...
    "swsynth_run_summary");

verifyEqual(testCase, summary.schema_version, 1);

verifyEqual( ...
    testCase, ...
    string(summary.files.wavefield_sample), ...
    "data/wavefield_sample.mat");

verifyEqual( ...
    testCase, ...
    string(outcome.paths.run), ...
    string(runDirectory));

end

function testExistingDirectoryRequiresOverwrite(testCase)

repoRoot = fileparts(fileparts(fileparts(mfilename("fullpath"))));

configFile = fullfile( ...
    repoRoot, ...
    "configs", ...
    "swsynth", ...
    "validation", ...
    "homogeneous_eikonal_vs_plane_wave", ...
    "single_eikonal.json");

temporaryRoot = string(tempname);
runDirectory = fullfile(temporaryRoot, "existing_run");

mkdir(runDirectory);

cleanup = onCleanup(@() removeDirectoryIfPresent(temporaryRoot));

verifyError( ...
    testCase, ...
    @() swsynth.cli.runConfig( ...
        configFile, ...
        OutputDirectory=runDirectory), ...
    "swsynth:OutputDirectoryExists");

end

function removeDirectoryIfPresent(directory)

if isfolder(directory)
    rmdir(directory, "s");
end

end
