function tests = test_swsynth_projected3d_run_integration
%TEST_SWSYNTH_PROJECTED3D_RUN_INTEGRATION Public runner integration.

tests = functiontests(localfunctions);

end

function testHomogeneousProjected3DRunIsReproducible(testCase)

cfg = minimalProjected3DConfig();

cfg.medium.background_cs_m_s = 3.0;
cfg.medium.objects = {};

resultA = swsynth.run(cfg);
resultB = swsynth.run(cfg);

verifyEqual( ...
    testCase, ...
    resultB.wavefield.U_zx, ...
    resultA.wavefield.U_zx, ...
    "AbsTol", 0);

verifyEqual( ...
    testCase, ...
    resultA.wavefield.propagation_model, ...
    "projected3d_eikonal");

verifyEqual( ...
    testCase, ...
    resultA.wavefield.diagnostics.requested_direction_count, ...
    16);

verifyEqual( ...
    testCase, ...
    resultA.wavefield.diagnostics.retained_direction_count, ...
    16);

verifySize( ...
    testCase, ...
    resultA.sample.wavefield.data_zx, ...
    size(resultA.medium.cs_map_zx));

end

function testBilayerCanFilterNonpropagatingDirections(testCase)

cfg = minimalProjected3DConfig();

cfg.directions.count = 64;
cfg.directions.in_plane_count = 4;
cfg.directions.support.solid_angle_sr = 4*pi;

cfg.medium.background_cs_m_s = 3.0;
cfg.medium.objects = {
    struct( ...
        "type", "bilayer", ...
        "cs_m_s", 2.0, ...
        "normal_angle_rad", 0.0, ...
        "offset_m", 0.01, ...
        "edge_sigma_m", 0.0)};

cfg.propagation.nonpropagating_policy = "filter";

result = swsynth.run(cfg);

verifyEqual( ...
    testCase, ...
    result.wavefield.diagnostics.retained_direction_count, ...
    result.wavefield.diagnostics.requested_direction_count);

verifyEqual( ...
    testCase, ...
    result.wavefield.diagnostics.rejected_direction_count, ...
    0);

verifyGreaterThan( ...
    testCase, ...
    result.wavefield.diagnostics.rejected_candidate_count, ...
    0);

verifyEqual( ...
    testCase, ...
    result.wavefield.diagnostics.selected_in_plane_count, ...
    cfg.directions.in_plane_count);

verifyTrue( ...
    testCase, ...
    all(isfinite(real(result.wavefield.U_zx(:)))));

verifyTrue( ...
    testCase, ...
    all(isfinite(imag(result.wavefield.U_zx(:)))));

end

function testErrorPolicyRejectsNonpropagatingDirections(testCase)

cfg = minimalProjected3DConfig();

cfg.directions.count = 64;
cfg.directions.support.solid_angle_sr = 4*pi;

cfg.medium.background_cs_m_s = 3.0;
cfg.medium.objects = {
    struct( ...
        "type", "bilayer", ...
        "cs_m_s", 2.0, ...
        "normal_angle_rad", 0.0, ...
        "offset_m", 0.01, ...
        "edge_sigma_m", 0.0)};

cfg.propagation.nonpropagating_policy = "error";

verifyError( ...
    testCase, ...
    @() swsynth.run(cfg), ...
    "swsynth:Projected3DNonpropagatingDirections");

end

function cfg = minimalProjected3DConfig()

cfg = swsynth.defaultConfig();

cfg.seed = 7301;

cfg.domain.Lx_m = 0.02;
cfg.domain.Lz_m = 0.02;
cfg.domain.dx_m = 0.001;
cfg.domain.dz_m = 0.001;

cfg.wavefield.frequency_hz = 200;

cfg.propagation.model = ...
    "projected3d_eikonal";
cfg.propagation.nonpropagating_policy = ...
    "error";

cfg.directions.count = 16;
cfg.directions.space = ...
    "three_dimensional";
cfg.directions.sampling_method = ...
    "fibonacci";
cfg.directions.in_plane_count = 2;

cfg.directions.support.type = ...
    "solid_angle_cap";
cfg.directions.support.axis_xyz = ...
    [1, 0, 0];
cfg.directions.support.solid_angle_sr = ...
    4*pi;

cfg.sources.amplitude_jitter_fraction = 0;
cfg.amplitude.geometric_decay_exponent = 0;
cfg.noise.snr_db = Inf;
cfg.execution.use_parallel = false;

end
