function tests = test_3d_material_geometry_plot
%TEST_3D_MATERIAL_GEOMETRY_PLOT Smoke-test material visualization.

tests = functiontests(localfunctions);

end


function setupOnce(~)

repository_root = ...
    findRepositoryRoot();

addpath(fullfile(repository_root, "src"));

end


function testCombinedMaterialPlot(testCase)

repository_root = ...
    findRepositoryRoot();

configuration_file = ...
    fullfile( ...
        repository_root, ...
        "configs", ...
        "three_d", ...
        "heterogeneous_combined_3d.json");

[requested_cfg, ~] = ...
    kwsim.io.loadConfigJson( ...
        configuration_file);

[cfg, ~] = ...
    kwsim.three_d.validateConfig( ...
        requested_cfg);

handles = ...
    kwsim.viz.plotMaterialGeometry3D( ...
        cfg, ...
        FigureVisible="off");

cleanup = ...
    onCleanup(@() closeIfValid(handles.figure));

verifyTrue( ...
    testCase, ...
    isgraphics(handles.figure, "figure"));

verifyEqual( ...
    testCase, ...
    numel(handles.axes), ...
    4);

verifyEqual( ...
    testCase, ...
    handles.config_resolved.geometry.object_count, ...
    2);

verifyTrue( ...
    testCase, ...
    handles.config_resolved.geometry.bilayer.enabled);

verifyEqual( ...
    testCase, ...
    sort(double(handles.material_ids)), ...
    [2; 3; 4; 5]);

verifyEqual( ...
    testCase, ...
    max(handles.truth.cs_m_s_xyz, [], "all"), ...
    single(5));

clear cleanup

end


function closeIfValid(figure_handle)

if isgraphics(figure_handle, "figure")
    close(figure_handle);
end

end


function repository_root = findRepositoryRoot()

repository_root = ...
    fileparts( ...
        fileparts( ...
        fileparts( ...
            mfilename("fullpath"))));

end
