function tests = test_3d_packed_face_grid_bank
%TEST_3D_PACKED_FACE_GRID_BANK Test high-count packed source banks.

tests = functiontests(localfunctions);

end


function setupOnce(~)

repository_root = ...
    fileparts( ...
        fileparts( ...
        fileparts( ...
        mfilename("fullpath"))));

addpath(fullfile(repository_root, "src"));

end


function testN32P8(testCase)

cfg = ...
    makeConfig(32);

generated = ...
    kwsim.three_d.generatePackedFaceGridBank( ...
        cfg, ...
        32, ...
        8);

verifyPackedBank( ...
    testCase, ...
    generated, ...
    32, ...
    8, ...
    2.30, ...
    0.08);

end


function testN128P8(testCase)

cfg = ...
    makeConfig(128);

cfg.grid.Ny = ...
    48;

generated = ...
    kwsim.three_d.generatePackedFaceGridBank( ...
        cfg, ...
        128, ...
        8);

verifyPackedBank( ...
    testCase, ...
    generated, ...
    128, ...
    8, ...
    2.50, ...
    0.15);

end


function verifyPackedBank( ...
        testCase, ...
        generated, ...
        expected_count, ...
        expected_in_plane, ...
        minimum_effective_dimension, ...
        minimum_third_eigenvalue)

metrics = ...
    generated.geometry_metrics;

verifyEqual( ...
    testCase, ...
    numel(generated.bank.vibrators), ...
    expected_count);

verifyEqual( ...
    testCase, ...
    metrics.in_plane_contact_count, ...
    expected_in_plane);

verifyEqual( ...
    testCase, ...
    metrics.centered_in_plane_contact_count, ...
    expected_in_plane);

verifyEqual( ...
    testCase, ...
    metrics.out_of_plane_contact_count, ...
    expected_count - expected_in_plane);

verifyEqual( ...
    testCase, ...
    metrics.unique_face_count, ...
    6);

verifyGreaterThan( ...
    testCase, ...
    metrics.effective_angular_dimension, ...
    minimum_effective_dimension);

verifyLessThan( ...
    testCase, ...
    metrics.directional_bias, ...
    0.20);

verifyGreaterThan( ...
    testCase, ...
    metrics.angular_eigenvalues_descending(3), ...
    minimum_third_eigenvalue);

verifyEqual( ...
    testCase, ...
    generated.mapping.maximum_angular_error_deg, ...
    0);

all_node_indices = ...
    vertcat( ...
        generated.bank.vibrators.node_linear_indices);

verifyEqual( ...
    testCase, ...
    numel(unique(all_node_indices)), ...
    numel(all_node_indices));

end


function cfg = makeConfig(vibrator_count)

cfg = ...
    kwsim.three_d.defaultConfig();

cfg.source.layout = ...
    "vibrator_bank";

cfg.source.side = ...
    "multiface";

cfg.source.bank_name = ...
    "generated_angular";

cfg.source.placement_policy = ...
    "packed_face_grid";

cfg.source.vibrator_count = ...
    vibrator_count;

cfg.source.contact_radius_m = ...
    1e-3;

cfg.source.boundary_margin_m = ...
    2e-3;

cfg.source.phase_policy = ...
    "random_uniform";

cfg.source.amplitude_policy = ...
    "equal_total_rms";

cfg.source.polarization_policy = ...
    "project_axial_transverse";

end
