function tests = test_swsynth_projected3d_homogeneous_field
%TEST_SWSYNTH_PROJECTED3D_HOMOGENEOUS_FIELD Field and spectrum validation.

tests = functiontests(localfunctions);

end

function testComplexFieldHasExpectedProjectedWavenumber(testCase)

dxM = 0.00025;
dzM = 0.00025;

xM = 0:dxM:0.050;
zM = (0:dzM:0.050).';

csMps = 2.0;
frequencyHz = 250;

% Unit direction with projected norm 0.8:
% sqrt(0.48^2 + 0.64^2) = 0.8.
directionXYZ = [0.48, 0.60, 0.64];

csMapZX = csMps * ones(numel(zM), numel(xM));

phaseDelayZX = ...
    swsynth.propagation.projected3d. ...
        computeDirectionalPhaseDelay( ...
            csMapZX, ...
            xM, ...
            zM, ...
            directionXYZ, ...
            csMps);

[X, Z] = meshgrid(xM, zM);

expectedPhaseDelayZX = ...
    directionXYZ(1) .* X ./ csMps + ...
    directionXYZ(3) .* Z ./ csMps;

verifyEqual( ...
    testCase, ...
    phaseDelayZX, ...
    expectedPhaseDelayZX, ...
    "AbsTol", 1e-10);

omegaRadS = 2*pi*frequencyHz;

fieldZX = exp(1i .* omegaRadS .* phaseDelayZX);

powerSpectrumZX = abs(fftshift(fft2(fieldZX))).^2;

[~, linearPeakIndex] = max(powerSpectrumZX(:));
[peakZIndex, peakXIndex] = ind2sub( ...
    size(powerSpectrumZX), ...
    linearPeakIndex);

Nx = numel(xM);
Nz = numel(zM);

kxRadM = ...
    2*pi .* ((-floor(Nx/2)):(ceil(Nx/2)-1)) ./ ...
    (Nx * dxM);

kzRadM = ...
    2*pi .* ((-floor(Nz/2)):(ceil(Nz/2)-1)) ./ ...
    (Nz * dzM);

detectedKxRadM = kxRadM(peakXIndex);
detectedKzRadM = kzRadM(peakZIndex);

referenceWavenumberRadM = omegaRadS / csMps;

expectedKxRadM = ...
    referenceWavenumberRadM * directionXYZ(1);

expectedKzRadM = ...
    referenceWavenumberRadM * directionXYZ(3);

expectedProjectedMagnitudeRadM = ...
    referenceWavenumberRadM * ...
    hypot(directionXYZ(1), directionXYZ(3));

detectedProjectedMagnitudeRadM = ...
    hypot(detectedKxRadM, detectedKzRadM);

deltaKxRadM = 2*pi / (Nx * dxM);
deltaKzRadM = 2*pi / (Nz * dzM);

verifyLessThanOrEqual( ...
    testCase, ...
    abs(detectedKxRadM - expectedKxRadM), ...
    0.55 * deltaKxRadM);

verifyLessThanOrEqual( ...
    testCase, ...
    abs(detectedKzRadM - expectedKzRadM), ...
    0.55 * deltaKzRadM);

verifyLessThanOrEqual( ...
    testCase, ...
    abs( ...
        detectedProjectedMagnitudeRadM - ...
        expectedProjectedMagnitudeRadM), ...
    hypot(0.55 * deltaKxRadM, 0.55 * deltaKzRadM));

end
