function tests = test_kwave_wavefield_sample_dimension_contract
tests = functiontests(localfunctions);
end

function testTwoDimensionalTruthIsCroppedToSensorRoi(testCase)
addSourcePath();
result = mock2DResult();
sample = kwsim.samples.buildWavefieldSample(result,Quantity="displacement");

verifyEqual(testCase,double(sample.spatial_dimension),2);
verifySize(testCase,sample.wavefield.data_zx,[3 4]);
verifySize(testCase,sample.truth.cs_map_zx,[3 4]);
verifyEqual(testCase,sample.truth.cs_map_zx,result.truth.cs_m_s_zx([2 3 4],[3 4 5 6]));
verifyEqual(testCase,string(sample.coordinates.array_order),"zx");
wavefield.validateSample(sample);
end

function testThreeDimensionalResultExportsFullSensorVolume(testCase)
addSourcePath();
result = mock3DResult();
sample = kwsim.samples.buildWavefieldSample(result,Quantity="velocity");

verifyEqual(testCase,double(sample.spatial_dimension),3);
verifySize(testCase,sample.wavefield.data_zyx,[3 4 5]);
verifySize(testCase,sample.truth.cs_map_zyx,[3 4 5]);
verifyEqual(testCase,string(sample.coordinates.array_order),"zyx");
verifyEqual(testCase,sample.wavefield.data_zyx,result.fields.velocity.z_total_zyx);
wavefield.validateSample(sample);
end

function result = mock2DResult()
field = complex(ones(3,4),0.25*ones(3,4));
result = struct();
result.dimension = 2;
result.schema_version = "3.0";
result.config_resolved = struct( ...
    "dimension",2, ...
    "scenario","mock_2d", ...
    "seed",1, ...
    "medium",struct("cs_m_s",2), ...
    "source",struct("f0_hz",500,"vibrator_count",1), ...
    "sensor",struct("x_indices",3:6,"z_indices",2:4));
result.axes = struct( ...
    "x_m",(2:5)*0.5e-3, ...
    "z_m",(1:3)*0.5e-3, ...
    "f0_hz",500);
result.sensor = struct("x_indices",3:6,"z_indices",2:4);
result.fields = struct();
result.fields.displacement = struct( ...
    "axial_total_zx",field, ...
    "units","m", ...
    "phasor_convention","u(t)=real{U exp(iwt)}");
fullCs = reshape(1:48,6,8);
result.truth = struct( ...
    "cs_m_s_zx",fullCs, ...
    "rho_kg_m3_zx",1000*ones(6,8), ...
    "material_id_zx",ones(6,8,"uint16"));
result.valid = true;
result.provenance = struct();
end

function result = mock3DResult()
field = complex(ones(3,4,5),0.5*ones(3,4,5));
result = struct();
result.dimension = 3;
result.schema_version = "3.0";
result.config_resolved = struct( ...
    "dimension",3, ...
    "scenario","mock_3d", ...
    "seed",2, ...
    "medium",struct("cs_m_s",2), ...
    "source",struct("f0_hz",500,"vibrator_count",8));
result.axes = struct( ...
    "x_m",(0:4)*0.5e-3, ...
    "y_m",(0:3)*0.5e-3, ...
    "z_m",(0:2)*0.5e-3);
result.fields = struct();
result.fields.frequency_hz = 500;
result.fields.velocity = struct( ...
    "z_total_zyx",field, ...
    "units","m/s", ...
    "phasor_convention","v(t)=real{V exp(iwt)}");
result.truth = struct( ...
    "cs_m_s_zyx",2*ones(3,4,5), ...
    "rho_kg_m3_zyx",1000*ones(3,4,5), ...
    "material_id_zyx",ones(3,4,5,"uint16"));
result.valid = true;
result.provenance = struct();
end

function addSourcePath()
root = fileparts(fileparts(fileparts(mfilename("fullpath"))));
addpath(fullfile(root,"src"));
end
