function tests = test_directional_harmonic_3d_validation
%TEST_DIRECTIONAL_HARMONIC_3D_VALIDATION Test quantitative 3D diagnostics.

tests = functiontests(localfunctions);

end


function setupOnce(~)

root = fileparts(fileparts(fileparts( ...
    mfilename("fullpath"))));

addpath(fullfile(root, "src"));

end


function testExactPlaneWavePasses(testCase)

result = syntheticResult( ...
    CoreCrossRatio=0, ...
    OuterCrossRatio=0, ...
    ZCenterShiftVoxels=0);

report = ...
    kwsim.validation.evaluateDirectionalHarmonic3D( ...
        result);

verifyTrue(testCase, report.valid);

verifyLessThan(testCase, ...
    report.metrics.speed_relative_error, ...
    1e-10);

verifyGreaterThan(testCase, ...
    report.metrics.speed.r_squared, ...
    1 - 1e-10);

verifyLessThan(testCase, ...
    report.metrics.field.core_cross_polarization_ratio, ...
    1e-12);

verifyLessThan(testCase, ...
    report.metrics.field.longitudinal_leakage_ratio, ...
    1e-12);

verifyLessThan(testCase, ...
    report.metrics.field.y_even_symmetry_error, ...
    1e-12);

verifyLessThan(testCase, ...
    report.metrics.field.z_even_symmetry_error, ...
    1e-12);

verifyFalse(testCase, ...
    report.frequency_evaluated);

end


function testExcessiveCoreCrossPolarizationFails(testCase)

result = syntheticResult( ...
    CoreCrossRatio=0.10, ...
    OuterCrossRatio=0.10, ...
    ZCenterShiftVoxels=0);

report = ...
    kwsim.validation.evaluateDirectionalHarmonic3D( ...
        result);

check_names = [report.checks.name];

cross_check = report.checks( ...
    check_names == ...
    "directional_core_cross_polarization_ratio");

verifyFalse(testCase, ...
    cross_check.pass);

verifyEqual(testCase, ...
    cross_check.value, ...
    0.10, ...
    AbsTol=1e-10);

verifyFalse(testCase, ...
    report.valid);

end


function testOffAxisCrossPolarizationIsDescriptive(testCase)

result = syntheticResult( ...
    CoreCrossRatio=0.01, ...
    OuterCrossRatio=1.00, ...
    ZCenterShiftVoxels=0);

report = ...
    kwsim.validation.evaluateDirectionalHarmonic3D( ...
        result);

verifyGreaterThan(testCase, ...
    report.metrics.field.global_cross_polarization_ratio, ...
    result.config_resolved.diagnostics. ...
        maximum_cross_polarization_ratio);

verifyLessThan(testCase, ...
    report.metrics.field.core_cross_polarization_ratio, ...
    result.config_resolved.diagnostics. ...
        maximum_cross_polarization_ratio);

verifyTrue(testCase, ...
    report.valid);

end


function testHalfVoxelEffectiveCenterCanPassSymmetry(testCase)

result = syntheticResult( ...
    CoreCrossRatio=0, ...
    OuterCrossRatio=0, ...
    ZCenterShiftVoxels=0.5);

report = ...
    kwsim.validation.evaluateDirectionalHarmonic3D( ...
        result);

verifyGreaterThan(testCase, ...
    report.metrics.field.z_nominal_even_symmetry_error, ...
    report.metrics.field.z_even_symmetry_error);

verifyEqual(testCase, ...
    report.metrics.field.z_symmetry_center_offset_voxels, ...
    0.5, ...
    AbsTol=0.05);

verifyLessThan(testCase, ...
    report.metrics.field.z_even_symmetry_error, ...
    result.config_resolved.diagnostics. ...
        maximum_symmetry_error);

verifyTrue(testCase, ...
    report.valid);

end


function result = syntheticResult(options)

arguments
    options.CoreCrossRatio (1,1) double = 0
    options.OuterCrossRatio (1,1) double = 0
    options.ZCenterShiftVoxels (1,1) double = 0
end

cfg = kwsim.three_d.defaultConfig();

cfg.medium.cs_m_s = 2;
cfg.source.f0_hz = 500;

dx_m = 0.5e-3;
dy_m = 0.5e-3;
dz_m = 0.5e-3;

x_m = (0:31).' * dx_m;
y_m = (-8:8).' * dy_m;
z_m = (-8:8).' * dz_m;

cfg.source.center_m_xyz = ...
    [0, 0, 0];

cfg.source.polarization_xyz = ...
    [0, 0, 1];

cfg.source.target_direction_xyz = ...
    [1, 0, 0];

[Z, Y, X] = ndgrid( ...
    z_m, ...
    y_m, ...
    x_m);

wavenumber_rad_m = ...
    2*pi*cfg.source.f0_hz / ...
    cfg.medium.cs_m_s;

z_shift_m = ...
    options.ZCenterShiftVoxels * dz_m;

transverse_envelope = exp( ...
    -(Y.^2 + (Z - z_shift_m).^2) / ...
    (2 * (2.5e-3)^2));

z_shear = ...
    transverse_envelope .* ...
    exp(-1i * wavenumber_rad_m * X);

lambda_s_m = ...
    cfg.medium.cs_m_s / ...
    cfg.source.f0_hz;

core_geometry = ...
    X >= lambda_s_m & ...
    abs(Y) <= 0.5 * lambda_s_m & ...
    abs(Z) <= 0.5 * lambda_s_m;

x_shear = complex(zeros(size(z_shear)));

x_shear(core_geometry) = ...
    sqrt(options.CoreCrossRatio) .* ...
    z_shear(core_geometry);

x_shear(~core_geometry) = ...
    sqrt(options.OuterCrossRatio) .* ...
    z_shear(~core_geometry);

zero_field = ...
    complex(zeros(size(z_shear)));

result = struct();

result.schema_version = ...
    cfg.schema_version;

result.dimension = 3;

result.config_requested = cfg;
result.config_resolved = cfg;
result.cfg = cfg;

result.axes = struct();

result.axes.x_m = x_m;
result.axes.y_m = y_m;
result.axes.z_m = z_m;

result.fields = struct();
result.fields.harmonic_velocity = struct();

result.fields.harmonic_velocity.z_shear_zyx = ...
    z_shear;

result.fields.harmonic_velocity.x_shear_zyx = ...
    x_shear;

result.fields.harmonic_velocity.y_shear_zyx = ...
    zero_field;

result.fields.harmonic_velocity.x_compression_zyx = ...
    zero_field;

result.fields.harmonic_velocity.y_compression_zyx = ...
    zero_field;

result.fields.harmonic_velocity.z_compression_zyx = ...
    zero_field;

result.truth = struct();
result.truth.homogeneous = true;

result.preflight = struct();
result.preflight.valid = true;

end
