function tests = test_swsynth_projected3d_reference_speed_vector
%TEST_SWSYNTH_PROJECTED3D_REFERENCE_SPEED_VECTOR Reference-speed API tests.

tests = functiontests(localfunctions);

end

function testHomogeneousScalarAndVectorAreEquivalent(testCase)

dxM = 0.0005;
dzM = 0.0005;

xM = 0:dxM:0.02;
zM = (0:dzM:0.02).';

csMps = 3.0;
frequencyHz = 250;

csMapZX = csMps * ones(numel(zM), numel(xM));

directionsXYZ = [
     1.0,  0.0,  0.0
     0.8,  0.6,  0.0
    -0.6,  0.0,  0.8
     0.4, -0.5, -sqrt(0.59)];

directionsXYZ = ...
    directionsXYZ ./ vecnorm(directionsXYZ, 2, 2);

weights = [
    1.0
    0.7i
   -0.4
    0.2 - 0.3i];

scalarReference = csMps;
vectorReference = csMps * ones(size(directionsXYZ,1),1);

[fieldScalarZX, diagnosticsScalar] = ...
    swsynth.propagation.projected3d. ...
        synthesizeDirectionalField( ...
            csMapZX, ...
            xM, ...
            zM, ...
            directionsXYZ, ...
            weights, ...
            frequencyHz, ...
            scalarReference, ...
            struct("UseParallel", false));

[fieldVectorZX, diagnosticsVector] = ...
    swsynth.propagation.projected3d. ...
        synthesizeDirectionalField( ...
            csMapZX, ...
            xM, ...
            zM, ...
            directionsXYZ, ...
            weights, ...
            frequencyHz, ...
            vectorReference, ...
            struct("UseParallel", false));

verifyEqual( ...
    testCase, ...
    fieldVectorZX, ...
    fieldScalarZX, ...
    "AbsTol", 1e-12);

verifyEqual( ...
    testCase, ...
    diagnosticsScalar.reference_cs_m_s, ...
    vectorReference, ...
    "AbsTol", 0);

verifyEqual( ...
    testCase, ...
    diagnosticsVector.reference_cs_m_s, ...
    vectorReference, ...
    "AbsTol", 0);

end

function testReferenceVectorMustMatchDirectionCount(testCase)

xM = 0:0.001:0.01;
zM = (0:0.001:0.01).';

csMapZX = 3 * ones(numel(zM), numel(xM));

directionsXYZ = [
    1, 0, 0
    0, 0, 1];

verifyError( ...
    testCase, ...
    @() swsynth.propagation.projected3d. ...
        synthesizeDirectionalField( ...
            csMapZX, ...
            xM, ...
            zM, ...
            directionsXYZ, ...
            [], ...
            250, ...
            [3; 3; 3], ...
            struct("UseParallel", false)), ...
    "swsynth:Projected3DReferenceSpeedCountMismatch");

end
