function tests = test_swsynth_spectral_entropy
%TEST_SWSYNTH_SPECTRAL_ENTROPY Spectral entropy tests.

tests = functiontests(localfunctions);

end

function testSingleSpectralPointHasLowEntropy(testCase)

kAxis = -4:4;

powerSpectrum = zeros(9, 9);
powerSpectrum(5, 8) = 1;

metrics = swsynth.metrics.computeSpectralEntropy( ...
    powerSpectrum, ...
    kAxis, ...
    kAxis, ...
    struct( ...
        "AngularBinCount", 16, ...
        "RadialBinCount", 8));

verifyEqual( ...
    testCase, ...
    metrics.angular_entropy, ...
    0, ...
    "AbsTol", 1e-12);

verifyEqual( ...
    testCase, ...
    metrics.radial_entropy, ...
    0, ...
    "AbsTol", 1e-12);

verifyEqual( ...
    testCase, ...
    metrics.angular_effective_bins, ...
    1, ...
    "AbsTol", 1e-12);

end

function testUniformAngularRingHasHighAngularEntropy(testCase)

kAxis = linspace(-1, 1, 201);

[KX, KZ] = meshgrid(kAxis, kAxis);

radius = hypot(KX, KZ);

powerSpectrum = double(abs(radius - 0.7) <= 0.02);

metrics = swsynth.metrics.computeSpectralEntropy( ...
    powerSpectrum, ...
    kAxis, ...
    kAxis, ...
    struct( ...
        "AngularBinCount", 36, ...
        "RadialBinCount", 20, ...
        "MinimumRadiusRadM", 0.5, ...
        "MaximumRadiusRadM", 0.9));

verifyGreaterThan( ...
    testCase, ...
    metrics.angular_entropy, ...
    0.95);

verifyLessThan( ...
    testCase, ...
    metrics.radial_entropy, ...
    0.35);

end

function testUniformDiskHasHighAngularAndRadialEntropy(testCase)

kAxis = linspace(-1, 1, 201);

[KX, KZ] = meshgrid(kAxis, kAxis);

powerSpectrum = double(hypot(KX, KZ) <= 1);

metrics = swsynth.metrics.computeSpectralEntropy( ...
    powerSpectrum, ...
    kAxis, ...
    kAxis, ...
    struct( ...
        "AngularBinCount", 36, ...
        "RadialBinCount", 20, ...
        "MinimumRadiusRadM", 0, ...
        "MaximumRadiusRadM", 1));

verifyGreaterThan( ...
    testCase, ...
    metrics.angular_entropy, ...
    0.95);

verifyGreaterThan( ...
    testCase, ...
    metrics.radial_entropy, ...
    0.75);

end

function testPositiveHalfPlaneExcludesNegativeKxEnergy(testCase)

kAxis = -2:2;

powerSpectrum = zeros(5, 5);

powerSpectrum(3, 1) = 10;
powerSpectrum(3, 5) = 1;

metrics = swsynth.metrics.computeSpectralEntropy( ...
    powerSpectrum, ...
    kAxis, ...
    kAxis, ...
    struct( ...
        "AngularBinCount", 8, ...
        "RadialBinCount", 4, ...
        "HalfPlane", "positive_kx"));

verifyEqual( ...
    testCase, ...
    metrics.total_selected_power, ...
    1, ...
    "AbsTol", 0);

end

function testSizeMismatchIsRejected(testCase)

verifyError( ...
    testCase, ...
    @() swsynth.metrics.computeSpectralEntropy( ...
        ones(4, 5), ...
        1:4, ...
        1:4, ...
        struct()), ...
    "swsynth:SpectralEntropySizeMismatch");

end
