function tests = test_3d_vibrator_bank_config
%TEST_3D_VIBRATOR_BANK_CONFIG Test automatic bank resolution.

tests = functiontests(localfunctions);

end


function setupOnce(~)

repository_root = fileparts(fileparts(fileparts( ...
    mfilename("fullpath"))));

addpath(fullfile(repository_root, "src"));

end


function testPartialDiffuseEightResolves(testCase)

cfg = bankConfig();

[resolved, ~] = ...
    kwsim.three_d.validateConfig(cfg);

verifyEqual(testCase, ...
    numel(resolved.source.vibrators), ...
    8);

verifyEqual(testCase, ...
    resolved.source.vibrator_count, ...
    8);

verifyEqual(testCase, ...
    resolved.source.contact_node_count, ...
    sum([resolved.source.vibrators.contact_node_count]));

centers = ...
    vertcat(resolved.source.vibrators.center_index_xyz);

verifyEqual(testCase, ...
    numel(unique(centers(:,1))), ...
    1);

verifyEqual(testCase, ...
    unique(centers(:,1)), ...
    resolved.source.source_x_index);

verifyEqual(testCase, ...
    size(unique(centers(:,2:3), "rows"), 1), ...
    8);

center_y = ...
    round((resolved.grid.Ny + 1) / 2);

verifyTrue(testCase, ...
    any(centers(:,2) == center_y));

verifyEqual(testCase, ...
    nnz(resolved.source.contact_mask_yz), ...
    resolved.source.contact_node_count);

verifyEqual(testCase, ...
    size( ...
        resolved.source.contact_node_subscripts_yz, ...
        1), ...
    resolved.source.contact_node_count);

verifyEqual(testCase, ...
    resolved.source.realized_radius_y_m, ...
    max([ ...
        resolved.source.vibrators. ...
        realized_radius_y_m]));

verifyEqual(testCase, ...
    resolved.source.realized_radius_z_m, ...
    max([ ...
        resolved.source.vibrators. ...
        realized_radius_z_m]));

end


function testResolutionIsDeterministic(testCase)

cfg = bankConfig();

[first, ~] = ...
    kwsim.three_d.validateConfig(cfg);

[second, ~] = ...
    kwsim.three_d.validateConfig(cfg);

first_phases = ...
    [first.source.vibrators.phase_rad];

second_phases = ...
    [second.source.vibrators.phase_rad];

verifyEqual(testCase, ...
    first_phases, ...
    second_phases);

verifyGreaterThan(testCase, ...
    numel(unique(first_phases)), ...
    1);

end


function testPolarizationsAreTransverse(testCase)

cfg = bankConfig();

[resolved, ~] = ...
    kwsim.three_d.validateConfig(cfg);

for index = 1:numel(resolved.source.vibrators)
    vibrator = ...
        resolved.source.vibrators(index);

    verifyEqual(testCase, ...
        norm(vibrator.polarization_xyz), ...
        1, ...
        "AbsTol", ...
        1e-12);

    verifyEqual(testCase, ...
        norm(vibrator.nominal_propagation_xyz), ...
        1, ...
        "AbsTol", ...
        1e-12);

    verifyEqual(testCase, ...
        dot( ...
            vibrator.polarization_xyz, ...
            vibrator.nominal_propagation_xyz), ...
        0, ...
        "AbsTol", ...
        1e-12);
end

end


function testTotalDriveMatchesSingleContactReference(testCase)

cfg = bankConfig();

[resolved, ~] = ...
    kwsim.three_d.validateConfig(cfg);

kgrid = struct();

kgrid.t_array = ...
    0:(1/50e3):(12/resolved.source.f0_hz);

[~, metadata] = ...
    kwsim.three_d.buildVibratorBankSource( ...
        resolved, ...
        kgrid);

expected_rms_squared = ...
    resolved.source.reference_single_contact_node_count * ...
    resolved.source.velocity_amplitude_m_s^2 / 2;

verifyEqual(testCase, ...
    metadata.nominal_total_drive_rms_squared_m2_s2, ...
    expected_rms_squared, ...
    "RelTol", ...
    1e-12);

end


function cfg = bankConfig()

cfg = ...
    kwsim.three_d.defaultConfig();

cfg.source.layout = ...
    "vibrator_bank";

cfg.source.regime = ...
    "partial_diffuse_3d";

cfg.source.bank_name = ...
    "partial_diffuse_8";

cfg.source.vibrator_count = ...
    8;

cfg.source.phase_policy = ...
    "random_uniform";

cfg.source.amplitude_policy = ...
    "equal_total_rms";

cfg.source.polarization_policy = ...
    "project_axial_transverse";

end
