function tests = test_swsynth_projected3d_filter_propagating_directions
%TEST_SWSYNTH_PROJECTED3D_FILTER_PROPAGATING_DIRECTIONS Propagation filter.

tests = functiontests(localfunctions);

end

function testHomogeneousMediumRetainsAllDirections(testCase)

csMps = 3.0;
csMapZX = csMps * ones(21, 31);

directionsXYZ = ...
    swsynth.sampleSolidAngleDirections( ...
        128, ...
        4*pi, ...
        [1, 0, 0], ...
        8);

referenceCsMps = ...
    swsynth.propagation.projected3d. ...
        resolveReferenceSpeeds( ...
            csMapZX, ...
            directionsXYZ);

[keepMask, diagnostics] = ...
    swsynth.propagation.projected3d. ...
        filterPropagatingDirections( ...
            csMapZX, ...
            directionsXYZ, ...
            referenceCsMps);

verifyTrue(testCase, all(keepMask));
verifyEqual(testCase, diagnostics.direction_count_retained, 128);
verifyEqual(testCase, diagnostics.direction_count_rejected, 0);

end

function testSlowToFastDirectionsCanBeRejected(testCase)

leftCsMps = 3.0;
rightCsMps = 2.0;

csMapZX = leftCsMps * ones(21, 31);
csMapZX(:,17:end) = rightCsMps;

directionsXYZ = [
     0.8, 0.9, 0.0
    -0.8, 0.9, 0.0
    -0.8, 0.4, 0.0];

directionsXYZ = ...
    directionsXYZ ./ vecnorm(directionsXYZ, 2, 2);

referenceCsMps = ...
    swsynth.propagation.projected3d. ...
        resolveReferenceSpeeds( ...
            csMapZX, ...
            directionsXYZ);

[keepMask, diagnostics] = ...
    swsynth.propagation.projected3d. ...
        filterPropagatingDirections( ...
            csMapZX, ...
            directionsXYZ, ...
            referenceCsMps);

% Left-incident direction begins in c=3 and propagates into c=2.
verifyTrue(testCase, keepMask(1));

% Right-incident high-|uy| direction begins in c=2 and cannot propagate
% throughout the c=3 region.
verifyFalse(testCase, keepMask(2));

% Right-incident smaller-|uy| direction remains propagating.
verifyTrue(testCase, keepMask(3));

verifyEqual(testCase, diagnostics.direction_count_rejected, 1);
verifyEqual(testCase, diagnostics.rejected_indices, 2);

end

function testScalarAndVectorReferenceSpeedsAreEquivalent(testCase)

csMapZX = 3 * ones(11, 13);

directionsXYZ = [
    1.0,  0.0, 0.0
    0.8,  0.6, 0.0
   -0.8, -0.6, 0.0];

keepScalar = ...
    swsynth.propagation.projected3d. ...
        filterPropagatingDirections( ...
            csMapZX, ...
            directionsXYZ, ...
            3);

keepVector = ...
    swsynth.propagation.projected3d. ...
        filterPropagatingDirections( ...
            csMapZX, ...
            directionsXYZ, ...
            [3;3;3]);

verifyEqual(testCase, keepVector, keepScalar);

end

function testReferenceSpeedCountMismatchIsRejected(testCase)

csMapZX = 3 * ones(5,5);

directionsXYZ = [
    1, 0, 0
   -1, 0, 0];

verifyError( ...
    testCase, ...
    @() swsynth.propagation.projected3d. ...
        filterPropagatingDirections( ...
            csMapZX, ...
            directionsXYZ, ...
            [3;3;3]), ...
    "swsynth:Projected3DReferenceSpeedCountMismatch");

end
