function tests = test_3d_multi_source_validation
%TEST_3D_MULTI_SOURCE_VALIDATION Unit tests for multi-source validation.

tests = functiontests(localfunctions);

end


function setupOnce(~)

repository_root = fileparts(fileparts(fileparts( ...
    mfilename("fullpath"))));

addpath(fullfile(repository_root, "src"));

end


function testDirectionalFailuresRemainDescriptive(testCase)

[result, directional_report] = ...
    syntheticCase();

verifyFalse(testCase, ...
    directional_report.valid);

report = ...
    kwsim.validation. ...
    evaluateMultiSourceHarmonic3D( ...
        result, ...
        DirectionalReport=directional_report);

verifyTrue(testCase, ...
    report.valid, ...
    report.summary);

verifyFalse(testCase, ...
    report.directional_thresholds_applicable);

verifyEqual(testCase, ...
    report.scope, ...
    "homogeneous_multi_source_harmonic_3d");

verifyEqual(testCase, ...
    report.metrics.apparent_directional_speed.speed_m_s, ...
    2.75);

verifyGreaterThan(testCase, ...
    report.metrics.apparent_speed_relative_error, ...
    0.30);

check_names = ...
    string([report.checks.name]);

verifyFalse(testCase, ...
    any(check_names == ...
        "shear_speed_relative_error"));

verifyFalse(testCase, ...
    any(check_names == ...
        "directional_core_cross_polarization_ratio"));

verifyFalse(testCase, ...
    any(check_names == ...
        "y_even_symmetry_error"));

end


function testLongitudinalLeakageIsAcceptanceCheck(testCase)

[result, directional_report] = ...
    syntheticCase();

directional_report.metrics.field. ...
    longitudinal_leakage_ratio = 0.25;

report = ...
    kwsim.validation. ...
    evaluateMultiSourceHarmonic3D( ...
        result, ...
        DirectionalReport=directional_report);

verifyFalse(testCase, ...
    report.valid);

check = ...
    findCheck( ...
        report, ...
        "global_longitudinal_leakage_ratio");

verifyFalse(testCase, ...
    check.pass);

end


function testIdenticalPhasesAreRejected(testCase)

[result, directional_report] = ...
    syntheticCase();

for index = 1:numel( ...
        result.config_resolved.source.vibrators)
    result.config_resolved.source. ...
        vibrators(index).phase_rad = 0;
end

report = ...
    kwsim.validation. ...
    evaluateMultiSourceHarmonic3D( ...
        result, ...
        DirectionalReport=directional_report);

verifyFalse(testCase, ...
    report.valid);

check = ...
    findCheck( ...
        report, ...
        "distinct_source_phases");

verifyFalse(testCase, ...
    check.pass);

end


function testIncorrectDriveNormalizationIsRejected(testCase)

[result, directional_report] = ...
    syntheticCase();

result.config_resolved.source. ...
    vibrators(1).velocity_amplitude_m_s = ...
    2 * result.config_resolved.source. ...
        vibrators(1).velocity_amplitude_m_s;

report = ...
    kwsim.validation. ...
    evaluateMultiSourceHarmonic3D( ...
        result, ...
        DirectionalReport=directional_report);

verifyFalse(testCase, ...
    report.valid);

check = ...
    findCheck( ...
        report, ...
        "normalized_total_drive_rms");

verifyFalse(testCase, ...
    check.pass);

end


function check = findCheck(report, name)

names = ...
    string([report.checks.name]);

index = ...
    find(names == string(name), 1);

if isempty(index)
    error( ...
        "Test:MissingValidationCheck", ...
        "Validation check '%s' was not found.", ...
        name);
end

check = ...
    report.checks(index);

end


function [result, directional_report] = syntheticCase()

cfg = ...
    kwsim.three_d.defaultConfig();

cfg.source.layout = ...
    "vibrator_bank";

cfg.source.regime = ...
    "partial_diffuse_3d";

cfg.source.bank_name = ...
    "partial_diffuse_8";

cfg.source.phase_policy = ...
    "random_uniform";

cfg.source.amplitude_policy = ...
    "equal_total_rms";

cfg.source.vibrator_count = ...
    8;

cfg.source.reference_single_contact_node_count = ...
    1;

base_amplitude = ...
    cfg.source.velocity_amplitude_m_s;

per_vibrator_amplitude = ...
    base_amplitude / sqrt(8);

template = struct( ...
    "node_linear_indices", [], ...
    "center_index_xyz", [NaN, NaN, NaN], ...
    "polarization_xyz", [NaN, NaN, NaN], ...
    "nominal_propagation_xyz", [NaN, NaN, NaN], ...
    "phase_rad", NaN, ...
    "velocity_amplitude_m_s", NaN);

vibrators = ...
    repmat(template, 8, 1);

for index = 1:8
    vibrators(index).node_linear_indices = ...
        index;

    vibrators(index).center_index_xyz = ...
        [2, index, index + 1];

    if mod(index, 2) == 0
        vibrators(index).polarization_xyz = ...
            [0, 1, 0];
    else
        vibrators(index).polarization_xyz = ...
            [0, 0, 1];
    end

    vibrators(index).nominal_propagation_xyz = ...
        [1, 0, 0];

    vibrators(index).phase_rad = ...
        2*pi*(index - 1)/8;

    vibrators(index).velocity_amplitude_m_s = ...
        per_vibrator_amplitude;
end

cfg.source.vibrators = ...
    vibrators;

cfg.source.contact_node_count = ...
    8;

result = struct();

result.config_resolved = ...
    cfg;

result.truth = struct();

result.truth.homogeneous = ...
    true;

directional_report = struct();

directional_report.valid = ...
    false;

directional_report.metrics = struct();

directional_report.metrics.speed = struct();

directional_report.metrics.speed.speed_m_s = ...
    2.75;

directional_report.metrics.speed.r_squared = ...
    0.99;

field = struct();

field.finite_fields = ...
    true;

field.longitudinal_leakage_ratio = ...
    2e-5;

field.global_cross_polarization_ratio = ...
    0.32;

field.core_cross_polarization_ratio = ...
    0.54;

field.central_axis_cross_polarization_ratio = ...
    0.024;

field.y_nominal_even_symmetry_error = ...
    0.74;

field.y_even_symmetry_error = ...
    0.67;

field.y_symmetry_center_offset_voxels = ...
    0.2;

field.z_nominal_even_symmetry_error = ...
    0.30;

field.z_even_symmetry_error = ...
    0.29;

field.z_symmetry_center_offset_voxels = ...
    -0.1;

directional_report.metrics.field = ...
    field;

end
