function tests = test_3d_angular_vibrator_bank_generator
%TEST_3D_ANGULAR_VIBRATOR_BANK_GENERATOR Test optimized N/P banks.

tests = functiontests(localfunctions);

end


function setupOnce(~)

repository_root = ...
    fileparts( ...
        fileparts( ...
        fileparts( ...
        mfilename("fullpath"))));

addpath(fullfile(repository_root, "src"));

end


function testGeneratesThreeDimensionalN8P2Bank(testCase)

cfg = ...
    makeConfig(8);

generated = ...
    kwsim.three_d.generateAngularVibratorBank( ...
        cfg, ...
        8, ...
        2, ...
        Seed=8202, ...
        CandidateCount=400, ...
        MinimumUniqueFaces=5, ...
        MinimumEffectiveDimension=2.20, ...
        MaximumDirectionalBias=0.35, ...
        MinimumThirdEigenvalue=0.12, ...
        MinimumAxisSeparationDeg=8, ...
        MaximumMappingErrorDeg=8);

metrics = ...
    generated.geometry_metrics;

verifyEqual( ...
    testCase, ...
    numel(generated.bank.vibrators), ...
    8);

verifyEqual( ...
    testCase, ...
    metrics.in_plane_contact_count, ...
    2);

verifyEqual( ...
    testCase, ...
    metrics.centered_in_plane_contact_count, ...
    2);

verifyEqual( ...
    testCase, ...
    metrics.out_of_plane_contact_count, ...
    6);

verifyGreaterThanOrEqual( ...
    testCase, ...
    metrics.unique_face_count, ...
    5);

verifyGreaterThanOrEqual( ...
    testCase, ...
    metrics.effective_angular_dimension, ...
    2.20);

verifyLessThanOrEqual( ...
    testCase, ...
    metrics.directional_bias, ...
    0.35);

verifyGreaterThanOrEqual( ...
    testCase, ...
    metrics.angular_eigenvalues_descending(3), ...
    0.12);

verifyGreaterThanOrEqual( ...
    testCase, ...
    metrics.pairwise_axis_angle_min_deg, ...
    8);

verifyLessThanOrEqual( ...
    testCase, ...
    generated.mapping.maximum_angular_error_deg, ...
    8);

end


function testGeneratesN8P4Bank(testCase)

cfg = ...
    makeConfig(8);

generated = ...
    kwsim.three_d.generateAngularVibratorBank( ...
        cfg, ...
        8, ...
        4, ...
        Seed=8404, ...
        CandidateCount=400, ...
        MinimumUniqueFaces=5, ...
        MinimumEffectiveDimension=2.05, ...
        MaximumDirectionalBias=0.40, ...
        MinimumThirdEigenvalue=0.08, ...
        MinimumAxisSeparationDeg=6, ...
        MaximumMappingErrorDeg=8);

metrics = ...
    generated.geometry_metrics;

verifyEqual( ...
    testCase, ...
    metrics.in_plane_contact_count, ...
    4);

verifyEqual( ...
    testCase, ...
    metrics.out_of_plane_contact_count, ...
    4);

verifyGreaterThanOrEqual( ...
    testCase, ...
    metrics.effective_angular_dimension, ...
    2.05);

verifyGreaterThanOrEqual( ...
    testCase, ...
    metrics.angular_eigenvalues_descending(3), ...
    0.08);

end


function testGenerationIsDeterministic(testCase)

cfg = ...
    makeConfig(8);

first = ...
    kwsim.three_d.generateAngularVibratorBank( ...
        cfg, ...
        8, ...
        2, ...
        Seed=8102, ...
        CandidateCount=150, ...
        MinimumUniqueFaces=4);

second = ...
    kwsim.three_d.generateAngularVibratorBank( ...
        cfg, ...
        8, ...
        2, ...
        Seed=8102, ...
        CandidateCount=150, ...
        MinimumUniqueFaces=4);

verifyEqual( ...
    testCase, ...
    first.desired_directions_xyz, ...
    second.desired_directions_xyz);

verifyEqual( ...
    testCase, ...
    first.contact_specs, ...
    second.contact_specs);

verifyEqual( ...
    testCase, ...
    first.score, ...
    second.score, ...
    "AbsTol", ...
    1e-12);

verifyEqual( ...
    testCase, ...
    first.candidate_index, ...
    second.candidate_index);

end


function cfg = makeConfig(vibrator_count)

cfg = ...
    kwsim.three_d.defaultConfig();

cfg.grid.Nx = ...
    48;

cfg.grid.Ny = ...
    32;

cfg.grid.Nz = ...
    48;

cfg.source.layout = ...
    "vibrator_bank";

cfg.source.side = ...
    "multiface";

cfg.source.vibrator_count = ...
    vibrator_count;

cfg.source.phase_policy = ...
    "random_uniform";

cfg.source.amplitude_policy = ...
    "equal_total_rms";

cfg.source.polarization_policy = ...
    "project_axial_transverse";

cfg.source.contact_radius_m = ...
    1.0e-3;

cfg.source.boundary_margin_m = ...
    2.0e-3;

cfg.seed = ...
    12345;

end
