function tests = test_swsynth_eikonal_solver
%TEST_SWSYNTH_EIKONAL_SOLVER Internal fast-sweeping tests.

tests = functiontests(localfunctions);

end

function testHomogeneousPlaneWaveOnRectangularGrid(testCase)

dxM = 0.0004;
dzM = 0.0007;

Nx = 51;
Nz = 31;

xM = (0:Nx-1) * dxM;

csMps = 2.0;
slownessZX = ones(Nz, Nx) / csMps;

initialTimeZX = Inf(Nz, Nx);
fixedMaskZX = false(Nz, Nx);

initialTimeZX(:, 1) = 0;
fixedMaskZX(:, 1) = true;

[travelTimeZX, diagnostics] = ...
    swsynth.numerics.eikonal.solveFastSweeping2D( ...
        slownessZX, ...
        dxM, ...
        dzM, ...
        initialTimeZX, ...
        fixedMaskZX);

expectedZX = repmat(xM / csMps, Nz, 1);

verifyEqual( ...
    testCase, ...
    travelTimeZX, ...
    expectedZX, ...
    "AbsTol", 1e-12);

verifyTrue(testCase, diagnostics.converged);
verifyEqual(testCase, diagnostics.finite_fraction, 1);

end

function testDoesNotConvergeWhenFrontOnlyJustBecameFinite(testCase)

gridSize = 41;
spacingM = 0.001;

slownessZX = ones(gridSize) / 2;

initialTimeZX = Inf(gridSize);
fixedMaskZX = false(gridSize);

centerIndex = (gridSize + 1) / 2;

initialTimeZX(centerIndex, centerIndex) = 0;
fixedMaskZX(centerIndex, centerIndex) = true;

options = struct( ...
    "MaximumIterations", 1, ...
    "ToleranceS", 1);

[~, diagnostics] = ...
    swsynth.numerics.eikonal.solveFastSweeping2D( ...
        slownessZX, ...
        spacingM, ...
        spacingM, ...
        initialTimeZX, ...
        fixedMaskZX, ...
        options);

verifyFalse(testCase, diagnostics.converged);
verifyEqual(testCase, diagnostics.iterations, 1);
verifyEqual(testCase, diagnostics.last_change_s, Inf);

end

function testPointSourceConvergesAfterAdditionalSweeps(testCase)

gridSize = 41;
spacingM = 0.001;

slownessZX = ones(gridSize) / 2;

initialTimeZX = Inf(gridSize);
fixedMaskZX = false(gridSize);

centerIndex = (gridSize + 1) / 2;

initialTimeZX(centerIndex, centerIndex) = 0;
fixedMaskZX(centerIndex, centerIndex) = true;

options = struct( ...
    "MaximumIterations", 50, ...
    "ToleranceS", 1e-12);

[travelTimeZX, diagnostics] = ...
    swsynth.numerics.eikonal.solveFastSweeping2D( ...
        slownessZX, ...
        spacingM, ...
        spacingM, ...
        initialTimeZX, ...
        fixedMaskZX, ...
        options);

verifyTrue(testCase, diagnostics.converged);
verifyGreaterThan(testCase, diagnostics.iterations, 1);
verifyTrue(testCase, all(isfinite(travelTimeZX(:))));
verifyEqual( ...
    testCase, ...
    travelTimeZX(centerIndex, centerIndex), ...
    0, ...
    "AbsTol", 0);

end

function testFixedBoundaryValuesArePreserved(testCase)

slownessZX = ones(15, 20) / 2;

initialTimeZX = Inf(size(slownessZX));
fixedMaskZX = false(size(slownessZX));

initialTimeZX(:, 1) = linspace(0, 0.003, size(slownessZX, 1));
fixedMaskZX(:, 1) = true;

travelTimeZX = ...
    swsynth.numerics.eikonal.solveFastSweeping2D( ...
        slownessZX, ...
        0.001, ...
        0.002, ...
        initialTimeZX, ...
        fixedMaskZX);

verifyEqual( ...
    testCase, ...
    travelTimeZX(:, 1), ...
    initialTimeZX(:, 1), ...
    "AbsTol", 0);

end

function testMissingBoundaryConditionIsRejected(testCase)

slownessZX = ones(10);
initialTimeZX = Inf(10);
fixedMaskZX = false(10);

verifyError( ...
    testCase, ...
    @() swsynth.numerics.eikonal.solveFastSweeping2D( ...
        slownessZX, ...
        0.001, ...
        0.001, ...
        initialTimeZX, ...
        fixedMaskZX), ...
    "swsynth:EikonalMissingBoundaryCondition");

end
