function tests = test_swsynth_projected3d_circular_inclusion
%TEST_SWSYNTH_PROJECTED3D_CIRCULAR_INCLUSION Validate heterogeneous Eikonal.

tests = functiontests(localfunctions);

end

function testCircularInclusionSatisfiesEikonalEquation(testCase)

%% Medium

dxM = 0.00025;
dzM = 0.00025;

xM = 0:dxM:0.05;
zM = (0:dzM:0.05).';

[X, Z] = meshgrid(xM,zM);

backgroundCsMps = 3.0;
inclusionCsMps = 2.0;

centerXM = 0.025;
centerZM = 0.025;
radiusM = 0.007;

distanceFromCenterM = hypot( ...
    X - centerXM, ...
    Z - centerZM);

inclusionMaskZX = ...
    distanceFromCenterM <= radiusM;

csMapZX = ...
    backgroundCsMps .* ones(size(X));

csMapZX(inclusionMaskZX) = ...
    inclusionCsMps;

%% One in-plane wave propagating toward +x

directionXYZ = [1,0,0];
referenceCsMps = backgroundCsMps;

[delayZX, diagnostics] = ...
    swsynth.propagation.projected3d. ...
        computeDirectionalPhaseDelay( ...
            csMapZX, ...
            xM, ...
            zM, ...
            directionXYZ, ...
            referenceCsMps, ...
            struct());

%% Basic solver checks

verifyTrue(testCase, diagnostics.solver.converged);

verifyEqual( ...
    testCase, ...
    diagnostics.solver.method, ...
    "fast_sweeping_2d");

verifyTrue(testCase, all(isfinite(delayZX(:))));

verifySize(testCase, delayZX, size(csMapZX));

verifyEqual( ...
    testCase, ...
    diagnostics.phase_reference, ...
    "global_origin_x0_z0");

%% The heterogeneous solution must differ from the homogeneous plane wave

homogeneousDelayZX = X ./ backgroundCsMps;

relativeHeterogeneousDifference = ...
    norm(delayZX(:) - homogeneousDelayZX(:)) ./ ...
    norm(homogeneousDelayZX(:));

verifyGreaterThan( ...
    testCase, ...
    relativeHeterogeneousDifference, ...
    1e-3);

%% Symmetry about the horizontal centerline

mirroredDelayZX = flipud(delayZX);

symmetryError = ...
    norm(delayZX(:) - mirroredDelayZX(:)) ./ ...
    norm(delayZX(:));

verifyLessThan( ...
    testCase, ...
    symmetryError, ...
    5e-3);

%% Numerical Eikonal residual away from boundaries and interface

delayX = ...
    (delayZX(2:end-1,3:end) - ...
     delayZX(2:end-1,1:end-2)) ./ ...
    (2*dxM);

delayZ = ...
    (delayZX(3:end,2:end-1) - ...
     delayZX(1:end-2,2:end-1)) ./ ...
    (2*dzM);

gradientMagnitude = hypot(delayX,delayZ);

expectedSlowness = ...
    1 ./ csMapZX(2:end-1,2:end-1);

distanceInterior = ...
    distanceFromCenterM(2:end-1,2:end-1);

interfaceExclusionWidthM = 3*max(dxM,dzM);

awayFromInterfaceMask = ...
    abs(distanceInterior - radiusM) >= ...
    interfaceExclusionWidthM;

% Exclude several pixels near the outer boundary, where one-sided
% boundary conditions and finite-difference derivatives dominate.
boundaryMask = true(size(awayFromInterfaceMask));
boundaryMarginPixels = 4;

boundaryMask( ...
    1:boundaryMarginPixels,:) = false;

boundaryMask( ...
    end-boundaryMarginPixels+1:end,:) = false;

boundaryMask( ...
    :,1:boundaryMarginPixels) = false;

boundaryMask( ...
    :,end-boundaryMarginPixels+1:end) = false;

evaluationMask = ...
    awayFromInterfaceMask & boundaryMask;

relativeResidual = abs( ...
    gradientMagnitude - expectedSlowness) ./ ...
    expectedSlowness;

residualValues = ...
    relativeResidual(evaluationMask);

verifyGreaterThan(testCase, numel(residualValues), 1000);

verifyLessThan( ...
    testCase, ...
    median(residualValues), ...
    0.02);

verifyLessThan( ...
    testCase, ...
    prctile(residualValues,95), ...
    0.10);

end
