function tests = test_swsynth_projected3d_bilayer
%TEST_SWSYNTH_PROJECTED3D_BILAYER Heterogeneous projected-3D tests.

tests = functiontests(localfunctions);

end

function testVerticalBilayerMatchesPiecewiseAnalyticDelay(testCase)

dxM = 0.00025;
dzM = 0.00025;

xM = 0:dxM:0.050;
zM = (0:dzM:0.030).';

interfaceXM = 0.025;

incidentCsMps = 3.0;
transmittedCsMps = 2.0;

csMapZX = incidentCsMps * ...
    ones(numel(zM), numel(xM));

csMapZX(:, xM > interfaceXM) = ...
    transmittedCsMps;

% Unit direction with no z component.
directionXYZ = [0.8, 0.6, 0];

[phaseDelayZX, diagnostics] = ...
    swsynth.propagation.projected3d. ...
        computeDirectionalPhaseDelay( ...
            csMapZX, ...
            xM, ...
            zM, ...
            directionXYZ, ...
            incidentCsMps);

pySPerM = ...
    directionXYZ(2) / incidentCsMps;

pxIncidentSPerM = ...
    directionXYZ(1) / incidentCsMps;

pxTransmittedSPerM = sqrt( ...
    1/transmittedCsMps^2 - ...
    pySPerM^2);

expectedDelayX = zeros(size(xM));

incidentMask = xM <= interfaceXM;
transmittedMask = xM > interfaceXM;

expectedDelayX(incidentMask) = ...
    pxIncidentSPerM .* xM(incidentMask);

expectedDelayAtInterfaceS = ...
    pxIncidentSPerM * interfaceXM;

expectedDelayX(transmittedMask) = ...
    expectedDelayAtInterfaceS + ...
    pxTransmittedSPerM .* ...
        (xM(transmittedMask) - interfaceXM);

expectedDelayZX = repmat( ...
    expectedDelayX, ...
    numel(zM), ...
    1);

verifyEqual( ...
    testCase, ...
    phaseDelayZX, ...
    expectedDelayZX, ...
    "AbsTol", 2e-5);

verifyTrue( ...
    testCase, ...
    diagnostics.solver.converged);

verifyEqual( ...
    testCase, ...
    diagnostics.solver.method, ...
    "fast_sweeping_2d");

verifyGreaterThan( ...
    testCase, ...
    diagnostics.solver.iterations, ...
    0);

end

function testBilayerDelayIsContinuousAcrossInterface(testCase)

dxM = 0.00025;

xM = 0:dxM:0.050;
zM = (0:dxM:0.020).';

interfaceXM = 0.025;

csMapZX = 3.0 * ...
    ones(numel(zM), numel(xM));

csMapZX(:, xM > interfaceXM) = 2.0;

phaseDelayZX = ...
    swsynth.propagation.projected3d. ...
        computeDirectionalPhaseDelay( ...
            csMapZX, ...
            xM, ...
            zM, ...
            [0.8, 0.6, 0], ...
            3.0);

interfaceIndex = find( ...
    xM == interfaceXM, ...
    1);

leftIncrementS = ...
    phaseDelayZX(:, interfaceIndex) - ...
    phaseDelayZX(:, interfaceIndex - 1);

rightIncrementS = ...
    phaseDelayZX(:, interfaceIndex + 1) - ...
    phaseDelayZX(:, interfaceIndex);

verifyGreaterThan( ...
    testCase, ...
    mean(rightIncrementS), ...
    mean(leftIncrementS));

verifyLessThanOrEqual( ...
    testCase, ...
    max(abs(diff( ...
        phaseDelayZX(:, interfaceIndex)))), ...
    1e-12);

end

function testFastLayerCanCreateEvanescentRegion(testCase)

xM = 0:0.001:0.010;
zM = (0:0.001:0.010).';

csMapZX = ones(numel(zM), numel(xM));
csMapZX(:, xM > 0.005) = 3.0;

% py = 0.8 s/m in the incident c=1 m/s material.
% The c=3 m/s region cannot support that transverse slowness.
directionXYZ = [0.6, 0.8, 0];

verifyError( ...
    testCase, ...
    @() swsynth.propagation.projected3d. ...
        computeDirectionalPhaseDelay( ...
            csMapZX, ...
            xM, ...
            zM, ...
            directionXYZ, ...
            1.0), ...
    "swsynth:Projected3DEvanescentRegion");

end
