function tests = test_swsynth_projected3d_resolve_reference_speeds
%TEST_SWSYNTH_PROJECTED3D_RESOLVE_REFERENCE_SPEEDS Boundary-speed tests.

tests = functiontests(localfunctions);

end

function testHomogeneousMediumReturnsConstantVector(testCase)

csMps = 3.0;

csMapZX = csMps * ones(21, 31);

directionsXYZ = [
     1,  0,  0
    -1,  0,  0
     1,  0,  1
    -1,  0, -1
     0,  1,  0];

[referenceCsMps, diagnostics] = ...
    swsynth.propagation.projected3d. ...
        resolveReferenceSpeeds( ...
            csMapZX, ...
            directionsXYZ);

verifyEqual( ...
    testCase, ...
    referenceCsMps, ...
    csMps * ones(5,1), ...
    "AbsTol", 0);

verifyEqual( ...
    testCase, ...
    diagnostics.unique_reference_cs_m_s, ...
    csMps, ...
    "AbsTol", 0);

end

function testVerticalBilayerUsesLeftAndRightIncidentMedia(testCase)

leftCsMps = 3.0;
rightCsMps = 2.0;

csMapZX = leftCsMps * ones(21, 31);
csMapZX(:, 17:end) = rightCsMps;

directionsXYZ = [
     1.0,  0.0,  0.0
     0.8,  0.6,  0.0
     0.6, -0.4,  0.7
    -1.0,  0.0,  0.0
    -0.8,  0.6,  0.0
    -0.6, -0.4, -0.7];

referenceCsMps = ...
    swsynth.propagation.projected3d. ...
        resolveReferenceSpeeds( ...
            csMapZX, ...
            directionsXYZ);

expectedReferenceCsMps = [
    leftCsMps
    leftCsMps
    leftCsMps
    rightCsMps
    rightCsMps
    rightCsMps];

verifyEqual( ...
    testCase, ...
    referenceCsMps, ...
    expectedReferenceCsMps, ...
    "AbsTol", 0);

end

function testUpstreamCornerDependsOnXAndZSigns(testCase)

csMapZX = [
    1, 5
    2, 6];

directionsXYZ = [
     1, 0,  1
    -1, 0,  1
     1, 0, -1
    -1, 0, -1];

[referenceCsMps, diagnostics] = ...
    swsynth.propagation.projected3d. ...
        resolveReferenceSpeeds( ...
            csMapZX, ...
            directionsXYZ);

verifyEqual( ...
    testCase, ...
    referenceCsMps, ...
    [1; 5; 2; 6], ...
    "AbsTol", 0);

verifyEqual( ...
    testCase, ...
    diagnostics.upstream_x_index, ...
    [1; 2; 1; 2]);

verifyEqual( ...
    testCase, ...
    diagnostics.upstream_z_index, ...
    [1; 1; 2; 2]);

end

function testZeroDirectionIsRejected(testCase)

csMapZX = 3 * ones(5,5);

verifyError( ...
    testCase, ...
    @() swsynth.propagation.projected3d. ...
        resolveReferenceSpeeds( ...
            csMapZX, ...
            [0, 0, 0]), ...
    "swsynth:InvalidProjected3DDirection");

end
