function tests = test_swsynth_projected3d_phase_delay
%TEST_SWSYNTH_PROJECTED3D_PHASE_DELAY Directional Eikonal tests.

tests = functiontests(localfunctions);

end

function testPositiveProjectedDirectionMatchesHomogeneousPlaneWave(testCase)

xM = 0:0.0005:0.020;
zM = (0:0.0007:0.014).';

csMps = 2.0;
csMapZX = csMps * ones(numel(zM), numel(xM));

% Unit vector: 0.48^2 + 0.60^2 + 0.64^2 = 1.
directionXYZ = [0.48, 0.60, 0.64];

[phaseDelayZX, diagnostics] = ...
    swsynth.propagation.projected3d. ...
        computeDirectionalPhaseDelay( ...
            csMapZX, ...
            xM, ...
            zM, ...
            directionXYZ, ...
            csMps);

[X, Z] = meshgrid(xM, zM);

expectedZX = ...
    directionXYZ(1) .* X ./ csMps + ...
    directionXYZ(3) .* Z ./ csMps;

verifyEqual( ...
    testCase, ...
    phaseDelayZX, ...
    expectedZX, ...
    "AbsTol", 1e-10);

verifyTrue(testCase, diagnostics.solver.converged);
verifyEqual( ...
    testCase, ...
    diagnostics.solver.method, ...
    "homogeneous_exact");
verifyEqual(testCase, diagnostics.solver.iterations, 0);

end

function testNegativeProjectedDirectionUsesGlobalPhaseOrigin(testCase)

xM = 0:0.0005:0.020;
zM = (0:0.0007:0.014).';

csMps = 2.0;
csMapZX = csMps * ones(numel(zM), numel(xM));

directionXYZ = [-0.48, 0.60, -0.64];

phaseDelayZX = ...
    swsynth.propagation.projected3d. ...
        computeDirectionalPhaseDelay( ...
            csMapZX, ...
            xM, ...
            zM, ...
            directionXYZ, ...
            csMps);

[X, Z] = meshgrid(xM, zM);

expectedZX = ...
    directionXYZ(1) .* X ./ csMps + ...
    directionXYZ(3) .* Z ./ csMps;

verifyEqual( ...
    testCase, ...
    phaseDelayZX, ...
    expectedZX, ...
    "AbsTol", 1e-10);

end

function testOppositeYDirectionsGiveSameObservedPhaseDelay(testCase)

xM = 0:0.001:0.020;
zM = (0:0.001:0.020).';

csMps = 3.0;
csMapZX = csMps * ones(numel(zM), numel(xM));

positiveY = [0.48, 0.60, 0.64];
negativeY = [0.48, -0.60, 0.64];

phasePositiveY = ...
    swsynth.propagation.projected3d. ...
        computeDirectionalPhaseDelay( ...
            csMapZX, xM, zM, positiveY, csMps);

phaseNegativeY = ...
    swsynth.propagation.projected3d. ...
        computeDirectionalPhaseDelay( ...
            csMapZX, xM, zM, negativeY, csMps);

verifyEqual( ...
    testCase, ...
    phaseNegativeY, ...
    phasePositiveY, ...
    "AbsTol", 1e-12);

end

function testMoreOutOfPlaneDirectionHasSmallerPhaseGradient(testCase)

xM = 0:0.001:0.030;
zM = (0:0.001:0.020).';

csMps = 2.0;
csMapZX = csMps * ones(numel(zM), numel(xM));

mostlyInPlane = [sqrt(0.96), 0.20, 0];
mostlyOutOfPlane = [0.60, 0.80, 0];

phaseInPlane = ...
    swsynth.propagation.projected3d. ...
        computeDirectionalPhaseDelay( ...
            csMapZX, xM, zM, mostlyInPlane, csMps);

phaseOutOfPlane = ...
    swsynth.propagation.projected3d. ...
        computeDirectionalPhaseDelay( ...
            csMapZX, xM, zM, mostlyOutOfPlane, csMps);

gradientInPlane = mean(diff(phaseInPlane, 1, 2), "all");
gradientOutOfPlane = mean(diff(phaseOutOfPlane, 1, 2), "all");

verifyLessThan( ...
    testCase, ...
    gradientOutOfPlane, ...
    gradientInPlane);

end

function testPureOutOfPlaneDirectionIsSpatiallyConstant(testCase)

xM = 0:0.001:0.010;
zM = (0:0.001:0.012).';

csMapZX = 2.5 * ones(numel(zM), numel(xM));

[phaseDelayZX, diagnostics] = ...
    swsynth.propagation.projected3d. ...
        computeDirectionalPhaseDelay( ...
            csMapZX, ...
            xM, ...
            zM, ...
            [0, 1, 0], ...
            2.5);

verifyEqual( ...
    testCase, ...
    phaseDelayZX, ...
    zeros(size(csMapZX)), ...
    "AbsTol", 0);

verifyEqual( ...
    testCase, ...
    diagnostics.solver.method, ...
    "pure_out_of_plane_exact");

end

function testBoundaryConditionFixesCorrectInflowEdges(testCase)

xM = 0:0.001:0.010;
zM = (0:0.001:0.008).';

[~, fixedMaskZX, diagnostics] = ...
    swsynth.propagation.projected3d. ...
        buildIncidentBoundaryCondition( ...
            xM, ...
            zM, ...
            [0.48, 0.60, -0.64], ...
            2.0);

verifyTrue(testCase, all(fixedMaskZX(:, 1)));
verifyTrue(testCase, all(fixedMaskZX(end, :)));

verifyFalse( ...
    testCase, ...
    any(fixedMaskZX(1, 2:end)));

verifyFalse( ...
    testCase, ...
    any(fixedMaskZX(1:end-1, end)));

verifyEqual( ...
    testCase, ...
    diagnostics.mode, ...
    "directional_inflow");

end
