function tests = test_swsynth_projected3d_polarization
%TEST_SWSYNTH_PROJECTED3D_POLARIZATION Shear-polarization tests.

tests = functiontests(localfunctions);

end

function testPolarizationsAreUnitAndTransverse(testCase)

directionsXYZ = [
     1.00,  0.00,  0.00
     0.00,  1.00,  0.00
     0.00,  0.00,  1.00
     0.48,  0.60,  0.64
    -0.48, -0.60,  0.64
];

rng(12001);

[polarizationXYZ, diagnostics] = ...
    swsynth.propagation.projected3d. ...
        sampleTransversePolarization(directionsXYZ);

unitDirectionsXYZ = ...
    directionsXYZ ./ vecnorm(directionsXYZ, 2, 2);

dotProducts = sum( ...
    polarizationXYZ .* unitDirectionsXYZ, ...
    2);

polarizationNorms = vecnorm( ...
    polarizationXYZ, ...
    2, ...
    2);

verifyEqual( ...
    testCase, ...
    dotProducts, ...
    zeros(size(dotProducts)), ...
    "AbsTol", 1e-12);

verifyEqual( ...
    testCase, ...
    polarizationNorms, ...
    ones(size(polarizationNorms)), ...
    "AbsTol", 1e-12);

verifyLessThanOrEqual( ...
    testCase, ...
    diagnostics.maximum_orthogonality_error, ...
    1e-12);

verifyLessThanOrEqual( ...
    testCase, ...
    diagnostics.maximum_norm_error, ...
    1e-12);

end

function testSamplingIsReproducibleFromRngState(testCase)

directionsXYZ = [
    0.48, 0.60, 0.64
    0.80, 0.00, 0.60
    0.00, 1.00, 0.00
];

rng(22002);
polarizationA = ...
    swsynth.propagation.projected3d. ...
        sampleTransversePolarization(directionsXYZ);

rng(22002);
polarizationB = ...
    swsynth.propagation.projected3d. ...
        sampleTransversePolarization(directionsXYZ);

verifyEqual( ...
    testCase, ...
    polarizationB, ...
    polarizationA, ...
    "AbsTol", 0);

end

function testMeanAxialPowerMatchesTheory(testCase)

sampleCount = 20000;

directionXYZ = [0.48, 0.60, 0.64];

directionsXYZ = repmat( ...
    directionXYZ, ...
    sampleCount, ...
    1);

rng(32003);

polarizationXYZ = ...
    swsynth.propagation.projected3d. ...
        sampleTransversePolarization(directionsXYZ);

measuredMeanAxialPower = ...
    mean(polarizationXYZ(:, 3).^2);

expectedMeanAxialPower = ...
    (1 - directionXYZ(3)^2) / 2;

verifyLessThanOrEqual( ...
    testCase, ...
    abs( ...
        measuredMeanAxialPower - ...
        expectedMeanAxialPower), ...
    0.01);

end

function testZeroDirectionIsRejected(testCase)

verifyError( ...
    testCase, ...
    @() swsynth.propagation.projected3d. ...
        sampleTransversePolarization([0, 0, 0]), ...
    "swsynth:InvalidProjected3DDirection");

end
