function tests = test_simcampaigns_configuration
%TEST_SIMCAMPAIGNS_CONFIGURATION Test generic campaign loading and expansion.

tests = functiontests(localfunctions);

end

function setupOnce(testCase)

repository_root = fileparts(fileparts(fileparts( ...
    mfilename("fullpath"))));

addpath(fullfile(repository_root, "src"));

testCase.TestData.repository_root = ...
    string(repository_root);

end

function testLegacyCampaignDefaultsToKwsim(testCase)

campaign_file = fullfile( ...
    testCase.TestData.repository_root, ...
    "configs", ...
    "campaigns", ...
    "homogeneous_partial_3d_n8_p2_smoke.json");

[campaign, metadata] = ...
    simcampaigns.loadCampaignJson(campaign_file);

verifyEqual(testCase, ...
    campaign.schema_version, ...
    "1.0");

verifyEqual(testCase, ...
    campaign.backend, ...
    "kwsim");

verifyEqual(testCase, ...
    metadata.expanded_run_count, ...
    2);

verifyEqual(testCase, ...
    metadata.base_config.dimension, ...
    3);

end

function testLoadsSwsynthCampaign(testCase)

campaign_file = fullfile( ...
    testCase.TestData.repository_root, ...
    "configs", ...
    "campaigns", ...
    "swsynth_homogeneous_smoke.json");

[campaign, metadata] = ...
    simcampaigns.loadCampaignJson(campaign_file);

verifyEqual(testCase, ...
    campaign.schema_version, ...
    "1.1");

verifyEqual(testCase, ...
    campaign.backend, ...
    "swsynth");

verifyEqual(testCase, ...
    metadata.expanded_run_count, ...
    4);

verifyTrue(testCase, ...
    iscell(metadata.base_config.medium.objects));

end

function testExpandsSwsynthCartesianSweep(testCase)

campaign_file = fullfile( ...
    testCase.TestData.repository_root, ...
    "configs", ...
    "campaigns", ...
    "swsynth_homogeneous_smoke.json");

[runs, expansion] = ...
    simcampaigns.expandCampaign(campaign_file);

verifyEqual(testCase, ...
    expansion.backend, ...
    "swsynth");

verifyEqual(testCase, ...
    expansion.run_count, ...
    4);

verifyEqual(testCase, ...
    string({runs.backend})', ...
    repmat("swsynth", 4, 1));

seeds = arrayfun( ...
    @(run) run.config.seed, ...
    runs);

verifyEqual(testCase, ...
    seeds, ...
    [1001; 1002; 1001; 1002]);

values = arrayfun( ...
    @(run) run.config.medium.background_cs_m_s, ...
    runs);

verifyEqual(testCase, ...
    values, ...
    [2; 2; 3; 3]);

verifyEqual(testCase, ...
    numel(unique(string({runs.run_id}))), ...
    4);

end
