function tests = test_3d_contact_specs_from_directions
%TEST_3D_CONTACT_SPECS_FROM_DIRECTIONS Test direction-first source design.

tests = functiontests(localfunctions);

end


function setupOnce(~)

repository_root = ...
    fileparts( ...
        fileparts( ...
        fileparts( ...
        mfilename("fullpath"))));

addpath(fullfile(repository_root, "src"));

end


function testPrincipalDirectionsMapToSixFaces(testCase)

cfg = ...
    kwsim.three_d.defaultConfig();

directions = [
     1, 0, 0
    -1, 0, 0
     0, 1, 0
     0,-1, 0
     0, 0, 1
     0, 0,-1
];

[specs, metadata] = ...
    kwsim.three_d.contactSpecsFromDirections( ...
        cfg, ...
        directions);

verifyEqual( ...
    testCase, ...
    string({specs.face}).', ...
    [ ...
        "x_min"
        "x_max"
        "y_min"
        "y_max"
        "z_min"
        "z_max"
    ]);

% With even grid dimensions, the physical domain center lies between
% nodes. Mapping the contact to integer grid indices therefore introduces
% a small and expected angular discretization error.
verifyLessThanOrEqual( ...
    testCase, ...
    metadata.maximum_angular_error_deg, ...
    6);

requested_unit_directions = ...
    directions ./ ...
    vecnorm(directions, 2, 2);

direction_dot_products = ...
    sum( ...
        requested_unit_directions .* ...
        metadata.realized_directions_xyz, ...
        2);

verifyGreaterThanOrEqual( ...
    testCase, ...
    direction_dot_products, ...
    cosd(6) * ones(6, 1));

end


function testInPlaneDirectionsRemainOnAcquisitionPlane(testCase)

cfg = ...
    kwsim.three_d.defaultConfig();

directions = [
     1, 0, 0
     0, 0, 1
    -1, 0, 0
     0, 0,-1
];

[~, metadata] = ...
    kwsim.three_d.contactSpecsFromDirections( ...
        cfg, ...
        directions);

acquisition_y_index = ...
    round((cfg.grid.Ny + 1) / 2);

verifyEqual( ...
    testCase, ...
    metadata.centers_index_xyz(:, 2), ...
    repmat( ...
        acquisition_y_index, ...
        4, ...
        1));

end


function testAngledDirectionsArePreservedAfterDiscretization(testCase)

cfg = ...
    kwsim.three_d.defaultConfig();

directions = [
     1.0, 0.25, 0.40
    -0.8, 0.30,-0.45
     0.2,-1.00, 0.25
];

[specs, metadata] = ...
    kwsim.three_d.contactSpecsFromDirections( ...
        cfg, ...
        directions);

verifyEqual( ...
    testCase, ...
    numel(specs), ...
    3);

verifyLessThanOrEqual( ...
    testCase, ...
    metadata.maximum_angular_error_deg, ...
    3);

for spec_index = 1:numel(specs)
    verifyGreaterThanOrEqual( ...
        testCase, ...
        specs(spec_index).center_fraction_tangent, ...
        [0, 0]);

    verifyLessThanOrEqual( ...
        testCase, ...
        specs(spec_index).center_fraction_tangent, ...
        [1, 1]);
end

end


function testOutputIsDeterministic(testCase)

cfg = ...
    kwsim.three_d.defaultConfig();

directions = [
     1.0, 0.2, 0.3
    -0.4, 1.0, 0.2
     0.3,-0.4, 1.0
];

[first_specs, first_metadata] = ...
    kwsim.three_d.contactSpecsFromDirections( ...
        cfg, ...
        directions);

[second_specs, second_metadata] = ...
    kwsim.three_d.contactSpecsFromDirections( ...
        cfg, ...
        directions);

verifyEqual( ...
    testCase, ...
    first_specs, ...
    second_specs);

verifyEqual( ...
    testCase, ...
    first_metadata, ...
    second_metadata);

end
