function tests = test_3d_multiface_bank_resolver
%TEST_3D_MULTIFACE_BANK_RESOLVER Unit tests for generic face-bank resolution.

tests = functiontests(localfunctions);

end

function testResolvesSixFaceBank(testCase)

cfg = makeBaseConfig();
specs = makeSixFaceSpecs();
cfg.source.vibrator_count = numel(specs);

bank = ...
    kwsim.three_d.resolveVibratorBankFromFaceSpecs( ...
        cfg, ...
        specs);

verifyEqual(testCase, bank.contact_count, 6);
verifyEqual(testCase, numel(bank.vibrators), 6);
verifyEqual(testCase, bank.faces, [specs.face].');
verifyEqual(testCase, bank.face_counts, ones(6, 1));
verifyEqual(testCase, nnz(bank.union_mask_xyz), ...
    bank.total_contact_node_count);

for vibrator_index = 1:numel(bank.vibrators)
    vibrator = bank.vibrators(vibrator_index);

    verifyTrue( ...
        testCase, ...
        all(bank.union_mask_xyz(vibrator.node_linear_indices)));

    verifyEqual( ...
        testCase, ...
        vibrator.contact_node_count, ...
        numel(vibrator.node_linear_indices));

    fixed_axis = ...
        fixedAxisForFace(vibrator.face);

    [node_x, node_y, node_z] = ...
        ind2sub( ...
            size(bank.union_mask_xyz), ...
            vibrator.node_linear_indices);

    node_subscripts_xyz = ...
        [node_x, node_y, node_z];

    verifyEqual( ...
        testCase, ...
        unique(node_subscripts_xyz(:, fixed_axis)), ...
        vibrator.center_index_xyz(fixed_axis));
end

end

function testDirectionsPointInwardAndPolarizationsAreTransverse(testCase)

cfg = makeBaseConfig();
specs = makeSixFaceSpecs();
cfg.source.vibrator_count = numel(specs);

bank = ...
    kwsim.three_d.resolveVibratorBankFromFaceSpecs( ...
        cfg, ...
        specs);

domain_center_m_xyz = ...
    0.5 * ( ...
        [cfg.grid.Nx, cfg.grid.Ny, cfg.grid.Nz] - 1) .* ...
        [cfg.grid.dx_m, cfg.grid.dy_m, cfg.grid.dz_m];

for vibrator_index = 1:numel(bank.vibrators)
    vibrator = bank.vibrators(vibrator_index);

    expected_direction = ...
        domain_center_m_xyz - ...
        vibrator.center_m_xyz;

    expected_direction = ...
        expected_direction / norm(expected_direction);

    verifyEqual( ...
        testCase, ...
        vibrator.nominal_propagation_xyz, ...
        expected_direction, ...
        "AbsTol", ...
        1e-12);

    verifyEqual( ...
        testCase, ...
        norm(vibrator.nominal_propagation_xyz), ...
        1, ...
        "AbsTol", ...
        1e-12);

    verifyEqual( ...
        testCase, ...
        norm(vibrator.polarization_xyz), ...
        1, ...
        "AbsTol", ...
        1e-12);

    verifyEqual( ...
        testCase, ...
        dot( ...
            vibrator.nominal_propagation_xyz, ...
            vibrator.polarization_xyz), ...
        0, ...
        "AbsTol", ...
        1e-12);

    verifyGreaterThan( ...
        testCase, ...
        dot( ...
            vibrator.nominal_propagation_xyz, ...
            -vibrator.face_normal_xyz), ...
        0);
end

end

function testDriveNormalization(testCase)

cfg = makeBaseConfig();
specs = makeSixFaceSpecs();
cfg.source.vibrator_count = numel(specs);

bank = ...
    kwsim.three_d.resolveVibratorBankFromFaceSpecs( ...
        cfg, ...
        specs);

verifyEqual( ...
    testCase, ...
    bank.nominal_total_drive_rms_squared_m2_s2, ...
    bank.reference_single_contact_drive_rms_squared_m2_s2, ...
    "RelTol", ...
    1e-12);

node_counts = ...
    [bank.vibrators.contact_node_count].';

amplitudes = ...
    [bank.vibrators.velocity_amplitude_m_s].';

per_contact_drive = ...
    node_counts .* amplitudes.^2 / 2;

verifyEqual( ...
    testCase, ...
    per_contact_drive, ...
    repmat( ...
        bank.reference_single_contact_drive_rms_squared_m2_s2 / ...
        bank.contact_count, ...
        bank.contact_count, ...
        1), ...
    "RelTol", ...
    1e-12);

end

function testDeterministicWithoutChangingGlobalRandomState(testCase)

cfg = makeBaseConfig();
specs = makeSixFaceSpecs();
cfg.source.vibrator_count = numel(specs);

rng(24680);
state_before = rng;

first = ...
    kwsim.three_d.resolveVibratorBankFromFaceSpecs( ...
        cfg, ...
        specs);

state_after = rng;

second = ...
    kwsim.three_d.resolveVibratorBankFromFaceSpecs( ...
        cfg, ...
        specs);

verifyEqual(testCase, state_after, state_before);
verifyEqual(testCase, first, second);

end

function testFractionEndpointsMapToValidExtremes(testCase)

cfg = makeBaseConfig();
cfg.source.vibrator_count = 1;

low_spec = struct( ...
    "name", "low", ...
    "face", "x_min", ...
    "center_fraction_tangent", [0, 0]);

high_spec = struct( ...
    "name", "high", ...
    "face", "x_min", ...
    "center_fraction_tangent", [1, 1]);

low_bank = ...
    kwsim.three_d.resolveVibratorBankFromFaceSpecs( ...
        cfg, ...
        low_spec);

high_bank = ...
    kwsim.three_d.resolveVibratorBankFromFaceSpecs( ...
        cfg, ...
        high_spec);

radius_points_y = ...
    ceil(cfg.source.contact_radius_m / cfg.grid.dy_m);

radius_points_z = ...
    ceil(cfg.source.contact_radius_m / cfg.grid.dz_m);

verifyEqual( ...
    testCase, ...
    low_bank.vibrators.center_index_xyz(2:3), ...
    [1 + radius_points_y, 1 + radius_points_z]);

verifyEqual( ...
    testCase, ...
    high_bank.vibrators.center_index_xyz(2:3), ...
    [cfg.grid.Ny - radius_points_y, ...
     cfg.grid.Nz - radius_points_z]);

end

function testRejectsOverlappingContacts(testCase)

cfg = makeBaseConfig();
cfg.source.vibrator_count = 2;

specs(1) = struct( ...
    "name", "first", ...
    "face", "x_min", ...
    "center_fraction_tangent", [0.5, 0.5]);

specs(2) = struct( ...
    "name", "second", ...
    "face", "x_min", ...
    "center_fraction_tangent", [0.5, 0.5]);

verifyError( ...
    testCase, ...
    @() kwsim.three_d.resolveVibratorBankFromFaceSpecs( ...
        cfg, ...
        specs), ...
    "kwsim:OverlappingVibratorContacts");

end

function testRejectsInvalidSpecification(testCase)

cfg = makeBaseConfig();
cfg.source.vibrator_count = 1;

invalid_fraction = struct( ...
    "name", "invalid", ...
    "face", "x_min", ...
    "center_fraction_tangent", [1.1, 0.5]);

verifyError( ...
    testCase, ...
    @() kwsim.three_d.resolveVibratorBankFromFaceSpecs( ...
        cfg, ...
        invalid_fraction), ...
    "kwsim:InvalidVibratorCenterFraction");

missing_fraction = struct( ...
    "name", "invalid", ...
    "face", "x_min");

verifyError( ...
    testCase, ...
    @() kwsim.three_d.resolveVibratorBankFromFaceSpecs( ...
        cfg, ...
        missing_fraction), ...
    "kwsim:InvalidVibratorBankSpecification");

end

function testRejectsCountAndPolicyMismatch(testCase)

cfg = makeBaseConfig();
specs = makeSixFaceSpecs();

cfg.source.vibrator_count = 1;

verifyError( ...
    testCase, ...
    @() kwsim.three_d.resolveVibratorBankFromFaceSpecs( ...
        cfg, ...
        specs), ...
    "kwsim:VibratorCountMismatch");

cfg.source.vibrator_count = numel(specs);
cfg.source.phase_policy = "fixed_zero";

verifyError( ...
    testCase, ...
    @() kwsim.three_d.resolveVibratorBankFromFaceSpecs( ...
        cfg, ...
        specs), ...
    "kwsim:Invalid3DSourceBank");

end

function cfg = makeBaseConfig()

cfg = ...
    kwsim.three_d.defaultConfig();

cfg.grid.Nx = 52;
cfg.grid.Ny = 46;
cfg.grid.Nz = 50;

cfg.grid.dx_m = 0.4e-3;
cfg.grid.dy_m = 0.5e-3;
cfg.grid.dz_m = 0.6e-3;

cfg.source.boundary_margin_m = 4e-3;
cfg.source.contact_radius_m = 1.2e-3;
cfg.source.contact_node_spacing_points = 2;

cfg.source.phase_policy = "random_uniform";
cfg.source.amplitude_policy = "equal_total_rms";
cfg.source.polarization_policy = ...
    "project_axial_transverse";

end

function specs = makeSixFaceSpecs()

specs(1) = struct( ...
    "name", "x_min_contact", ...
    "face", "x_min", ...
    "center_fraction_tangent", [0.20, 0.25]);

specs(2) = struct( ...
    "name", "x_max_contact", ...
    "face", "x_max", ...
    "center_fraction_tangent", [0.75, 0.70]);

specs(3) = struct( ...
    "name", "y_min_contact", ...
    "face", "y_min", ...
    "center_fraction_tangent", [0.30, 0.75]);

specs(4) = struct( ...
    "name", "y_max_contact", ...
    "face", "y_max", ...
    "center_fraction_tangent", [0.70, 0.30]);

specs(5) = struct( ...
    "name", "z_min_contact", ...
    "face", "z_min", ...
    "center_fraction_tangent", [0.25, 0.65]);

specs(6) = struct( ...
    "name", "z_max_contact", ...
    "face", "z_max", ...
    "center_fraction_tangent", [0.70, 0.20]);

end

function fixed_axis = fixedAxisForFace(face)

switch string(face)
    case {"x_min", "x_max"}
        fixed_axis = 1;

    case {"y_min", "y_max"}
        fixed_axis = 2;

    case {"z_min", "z_max"}
        fixed_axis = 3;
end

end
