function tests = test_swsynth_adaptive_fibonacci_directions
%TEST_SWSYNTH_ADAPTIVE_FIBONACCI_DIRECTIONS
% Validate Fibonacci direction sets used by adaptive Dnom campaigns.

tests = functiontests(localfunctions);

end


function setupOnce(~)

root = fileparts(fileparts(fileparts( ...
    mfilename("fullpath"))));

addpath(fullfile(root, "src"));

end


function testAdaptiveCombinationRespectsRequestedSupport(testCase)

direction_count = 99;
solid_angle_sr = 10.422883;
axis_xyz = [1 0 0];
in_plane_count = 10;

[directions, diagnostics] = ...
    swsynth.sampleSolidAngleDirections( ...
        direction_count, ...
        solid_angle_sr, ...
        axis_xyz, ...
        in_plane_count);

verifySize(testCase, directions, [direction_count 3]);

verifyEqual(testCase, ...
    vecnorm(directions, 2, 2), ...
    ones(direction_count,1), ...
    AbsTol=1e-12);

cos_half_angle = 1 - solid_angle_sr/(2*pi);

verifyGreaterThanOrEqual(testCase, ...
    directions * axis_xyz(:), ...
    cos_half_angle - 1e-12);

verifyEqual(testCase, ...
    nnz(abs(directions(:,2)) <= 1e-12), ...
    in_plane_count);

verifyEqual(testCase, ...
    diagnostics.direction_count, ...
    direction_count);

verifyEqual(testCase, ...
    diagnostics.solid_angle_sr, ...
    solid_angle_sr, ...
    AbsTol=1e-12);

end


function testSamplingIsDeterministic(testCase)

a = swsynth.sampleSolidAngleDirections( ...
    78, ...
    3.838474, ...
    [1 0 0], ...
    9);

b = swsynth.sampleSolidAngleDirections( ...
    78, ...
    3.838474, ...
    [1 0 0], ...
    9);

verifyEqual(testCase, a, b, AbsTol=0);

end


function testSmallCapStaysInsideSupport(testCase)

solid_angle_sr = 0.255055;
axis_xyz = [1 0 0];

directions = swsynth.sampleSolidAngleDirections( ...
    87, ...
    solid_angle_sr, ...
    axis_xyz, ...
    9);

cos_half_angle = 1 - solid_angle_sr/(2*pi);

verifyGreaterThanOrEqual(testCase, ...
    min(directions * axis_xyz(:)), ...
    cos_half_angle - 1e-12);

end


function testFullSphereIsApproximatelyBalanced(testCase)

directions = swsynth.sampleSolidAngleDirections( ...
    128, ...
    4*pi, ...
    [1 0 0], ...
    0);

centroid = mean(directions, 1);
second_moment = mean(directions.^2, 1);

verifyLessThan(testCase, norm(centroid), 0.03);

verifyEqual(testCase, ...
    second_moment, ...
    [1/3 1/3 1/3], ...
    AbsTol=0.03);

end


function testAllCurrentAdaptiveConfigurationsAreValid(testCase)

parameters = [
     10,  7.573591
     28,  9.991049
     99, 10.422883
     78,  3.838474
    119, 11.670916
     87,  0.255055
    108,  2.505041
    124, 12.515904
     45,  5.782078
    126, 10.538371
    ];

for index = 1:size(parameters,1)
    count = parameters(index,1);
    omega = parameters(index,2);
    in_plane_count = min( ...
        count, ...
        max(1, round(sqrt(count))));

    directions = ...
        swsynth.sampleSolidAngleDirections( ...
            count, ...
            omega, ...
            [1 0 0], ...
            in_plane_count);

    verifySize(testCase, directions, [count 3]);

    verifyEqual(testCase, ...
        vecnorm(directions,2,2), ...
        ones(count,1), ...
        AbsTol=1e-12);

    verifyEqual(testCase, ...
        nnz(abs(directions(:,2)) <= 1e-12), ...
        in_plane_count);
end

end
