function tests = ...
        test_swsynth_projected3d_select_propagating_directions

tests = functiontests(localfunctions);

end

function testHomogeneousSampleIsUnchanged(testCase)

csMapZX = 3 * ones(31,41);

initialXYZ = ...
    swsynth.sampleSolidAngleDirections( ...
        32, ...
        4*pi, ...
        [1,0,0], ...
        4);

[selectedXYZ, referenceCsMps, diagnostics] = ...
    swsynth.propagation.projected3d. ...
        selectPropagatingDirections( ...
            csMapZX, ...
            initialXYZ, ...
            4*pi, ...
            [1,0,0], ...
            4);

verifyEqual(testCase, selectedXYZ, initialXYZ, "AbsTol", 1e-14);
verifyEqual(testCase, referenceCsMps, 3*ones(32,1));
verifyEqual(testCase, diagnostics.candidate_direction_count, 32);
verifyEqual(testCase, diagnostics.rejected_candidate_count, 0);

end

function testBilayerReturnsExactRequestedCount(testCase)

csMapZX = 3 * ones(31,41);
csMapZX(:,22:end) = 2;

initialXYZ = ...
    swsynth.sampleSolidAngleDirections( ...
        128, ...
        4*pi, ...
        [1,0,0], ...
        8);

[selectedXYZ, referenceCsMps, diagnostics] = ...
    swsynth.propagation.projected3d. ...
        selectPropagatingDirections( ...
            csMapZX, ...
            initialXYZ, ...
            4*pi, ...
            [1,0,0], ...
            8);

verifySize(testCase, selectedXYZ, [128,3]);
verifySize(testCase, referenceCsMps, [128,1]);

verifyEqual( ...
    testCase, ...
    nnz(abs(selectedXYZ(:,2)) <= 1e-12), ...
    8);

verifyGreaterThan( ...
    testCase, ...
    diagnostics.rejected_candidate_count, ...
    0);

[keepMask, ~] = ...
    swsynth.propagation.projected3d. ...
        filterPropagatingDirections( ...
            csMapZX, ...
            selectedXYZ, ...
            referenceCsMps);

verifyTrue(testCase, all(keepMask));

end

function testSelectionIsReproducible(testCase)

csMapZX = 3 * ones(21,31);
csMapZX(:,17:end) = 2;

initialXYZ = ...
    swsynth.sampleSolidAngleDirections( ...
        64, ...
        4*pi, ...
        [1,0,0], ...
        6);

[selectedA, referenceA, diagnosticsA] = ...
    swsynth.propagation.projected3d. ...
        selectPropagatingDirections( ...
            csMapZX, ...
            initialXYZ, ...
            4*pi, ...
            [1,0,0], ...
            6);

[selectedB, referenceB, diagnosticsB] = ...
    swsynth.propagation.projected3d. ...
        selectPropagatingDirections( ...
            csMapZX, ...
            initialXYZ, ...
            4*pi, ...
            [1,0,0], ...
            6);

verifyEqual(testCase, selectedB, selectedA, "AbsTol", 0);
verifyEqual(testCase, referenceB, referenceA, "AbsTol", 0);
verifyEqual(testCase, diagnosticsB, diagnosticsA);

end
