function tests = test_source_configuration
%TEST_SOURCE_CONFIGURATION Unit tests for reusable source configuration.

tests = functiontests(localfunctions);

end

function setupOnce(~)

root = fileparts( ...
    fileparts(fileparts(mfilename('fullpath'))));

addpath(fullfile(root, 'src'));

end

function testRegimeDefaults(testCase)

regimes = [ ...
    "directional", ...
    "partially_diffuse", ...
    "diffuse"];

counts = [12, 24, 24];
fractions = [1, 0.5, 0];

for index = 1:numel(regimes)
    cfg = kwsim.two_d.defaultConfig();

    cfg = kwsim.sources.configureVibratorBank( ...
        cfg, regimes(index), counts(index));

    verifyEqual( ...
        testCase, cfg.source.layout, "vibrator_bank");

    verifyEqual( ...
        testCase, cfg.source.regime, regimes(index));

    verifyEqual( ...
        testCase, cfg.source.vibrator_count, counts(index));

    verifyEqual( ...
        testCase, ...
        cfg.source.coherent_power_fraction, ...
        fractions(index));
end

end

function testPartiallyDiffuseFractionCanBeSelected(testCase)

cfg = kwsim.two_d.defaultConfig();

cfg = kwsim.sources.configureVibratorBank( ...
    cfg, ...
    "partially_diffuse", ...
    20, ...
    CoherentPowerFraction=0.3, ...
    TargetAngleDeg=25, ...
    TotalDriveRmsSquaredM2S2=2e-12);

verifyEqual( ...
    testCase, cfg.source.coherent_power_fraction, 0.3);

verifyEqual( ...
    testCase, cfg.source.target_angle_deg, 25);

verifyEqual( ...
    testCase, ...
    cfg.source.total_drive_rms_squared_m2_s2, ...
    2e-12);

end

function testPointBankResolves(testCase)

cfg = kwsim.two_d.defaultConfig();
cfg.stage = 3;
cfg.scenario = "point_bank_unit_test";

cfg = kwsim.sources.configureVibratorBank( ...
    cfg, "directional", 12);

cfg = kwsim.sources.configurePointContact(cfg);

[resolved, preflight] = ...
    kwsim.two_d.validateConfig(cfg);

verifyTrue(testCase, preflight.valid);

verifyEqual( ...
    testCase, resolved.source.contact_model, "point");

verifyEqual( ...
    testCase, resolved.source.contact_sampling, "point");

verifyEqual( ...
    testCase, ...
    [resolved.source.resolved_bank.vibrators.contact_node_count], ...
    ones(1, 12));

end

function testFiniteBankResolves(testCase)

cfg = kwsim.two_d.defaultConfig();
cfg.stage = 3;
cfg.scenario = "finite_bank_unit_test";

cfg = kwsim.sources.configureVibratorBank( ...
    cfg, "directional", 8);

cfg = kwsim.sources.configureFiniteContact( ...
    cfg, ...
    ContactRadiusM=2e-3, ...
    NodeSpacingPoints=4);

[resolved, preflight] = ...
    kwsim.two_d.validateConfig(cfg);

verifyTrue(testCase, preflight.valid);

verifyEqual( ...
    testCase, ...
    resolved.source.contact_model, ...
    "finite_segment");

verifyEqual( ...
    testCase, ...
    unique([ ...
        resolved.source.resolved_bank.vibrators.contact_node_count]), ...
    3);

end

function testSinglePointContactResolves(testCase)

cfg = kwsim.two_d.defaultConfig();
cfg.scenario = "single_point_contact_unit_test";

cfg = kwsim.sources.configureSingleContact( ...
    cfg, ...
    VelocityAmplitudeMPerS=2e-6, ...
    PhaseRad=pi/4);

cfg = kwsim.sources.configurePointContact(cfg);

[resolved, preflight] = ...
    kwsim.two_d.validateConfig(cfg);

verifyTrue(testCase, preflight.valid);

verifyEqual( ...
    testCase, resolved.source.layout, "single_contact");

verifyEqual( ...
    testCase, resolved.source.contact_model, "point");

verifyEqual( ...
    testCase, ...
    resolved.source.velocity_amplitude_m_s, ...
    2e-6);

verifyEqual( ...
    testCase, resolved.source.phase_rad, pi/4);

end

function testRejectsInconsistentDirectionalFraction(testCase)

cfg = kwsim.two_d.defaultConfig();

verifyError( ...
    testCase, ...
    @() kwsim.sources.configureVibratorBank( ...
        cfg, ...
        "directional", ...
        12, ...
        CoherentPowerFraction=0.5), ...
    'kwsim:InvalidSourceConfiguration');

end
