function tests = test_3d_boundary_face_contact
%TEST_3D_BOUNDARY_FACE_CONTACT Unit tests for finite disks on 3D faces.

tests = functiontests(localfunctions);

end

function testAllSupportedFaces(testCase)

cfg = makeTestConfig();

faces = [
    "x_min"
    "x_max"
    "y_min"
    "y_max"
    "z_min"
    "z_max"
];

expected_normals = [
    -1,  0,  0
     1,  0,  0
     0, -1,  0
     0,  1,  0
     0,  0, -1
     0,  0,  1
];

for face_index = 1:numel(faces)
    face = faces(face_index);
    center = centerForFace(cfg, face);

    contact = ...
        kwsim.three_d.makeSparseDiskMaskOnFace( ...
            cfg, ...
            face, ...
            center);

    verifyEqual( ...
        testCase, ...
        string(contact.face), ...
        face);

    verifyEqual( ...
        testCase, ...
        size(contact.mask_xyz), ...
        [cfg.grid.Nx, cfg.grid.Ny, cfg.grid.Nz]);

    verifyTrue( ...
        testCase, ...
        contact.mask_xyz( ...
            center(1), ...
            center(2), ...
            center(3)));

    verifyEqual( ...
        testCase, ...
        contact.face_normal_xyz, ...
        expected_normals(face_index, :), ...
        "AbsTol", ...
        1e-12);

    verifyEqual( ...
        testCase, ...
        norm(contact.face_normal_xyz), ...
        1, ...
        "AbsTol", ...
        1e-12);

    fixed_axis = fixedAxisForFace(face);

    verifyEqual( ...
        testCase, ...
        unique(contact.node_subscripts_xyz(:, fixed_axis)), ...
        contact.source_plane_index);

    verifyEqual( ...
        testCase, ...
        contact.node_linear_indices, ...
        find(contact.mask_xyz));

    [node_x, node_y, node_z] = ...
        ind2sub( ...
            size(contact.mask_xyz), ...
            contact.node_linear_indices);

    verifyEqual( ...
        testCase, ...
        contact.node_subscripts_xyz, ...
        [node_x, node_y, node_z]);

    verifyGreaterThanOrEqual( ...
        testCase, ...
        contact.node_count, ...
        3);
end

end

function testSparseSamplingAndPhysicalRadius(testCase)

cfg = makeTestConfig();

cfg.grid.dx_m = 0.4e-3;
cfg.grid.dy_m = 0.5e-3;
cfg.grid.dz_m = 0.8e-3;
cfg.source.contact_radius_m = 2.0e-3;
cfg.source.contact_node_spacing_points = 2;

center = centerForFace(cfg, "x_min");

contact = ...
    kwsim.three_d.makeSparseDiskMaskOnFace( ...
        cfg, ...
        "x_min", ...
        center);

node_y = ...
    contact.node_subscripts_xyz(:, 2);

node_z = ...
    contact.node_subscripts_xyz(:, 3);

offset_y_m = ...
    (node_y - center(2)) * cfg.grid.dy_m;

offset_z_m = ...
    (node_z - center(3)) * cfg.grid.dz_m;

radius_m = ...
    hypot(offset_y_m, offset_z_m);

verifyLessThanOrEqual( ...
    testCase, ...
    max(radius_m), ...
    cfg.source.contact_radius_m + ...
        10*eps(cfg.source.contact_radius_m));

verifyEqual( ...
    testCase, ...
    mod( ...
        node_y - center(2), ...
        cfg.source.contact_node_spacing_points), ...
    zeros(size(node_y)));

verifyEqual( ...
    testCase, ...
    mod( ...
        node_z - center(3), ...
        cfg.source.contact_node_spacing_points), ...
    zeros(size(node_z)));

verifyLessThanOrEqual( ...
    testCase, ...
    contact.realized_radius_tangent_m, ...
    [cfg.source.contact_radius_m, ...
     cfg.source.contact_radius_m] + ...
        10*eps(cfg.source.contact_radius_m));

end

function testXMinMatchesLegacyYZHelper(testCase)

cfg = makeTestConfig();
center = centerForFace(cfg, "x_min");

contact = ...
    kwsim.three_d.makeSparseDiskMaskOnFace( ...
        cfg, ...
        "x_min", ...
        center);

legacy = ...
    kwsim.three_d.makeSparseDiskMaskYZ( ...
        cfg, ...
        center(2), ...
        center(3));

resolved_yz = ...
    squeeze( ...
        contact.mask_xyz( ...
            contact.source_plane_index, ...
            :, ...
            :));

verifyEqual( ...
    testCase, ...
    resolved_yz, ...
    legacy.mask_yz);

end

function testRepeatedCallsAreDeterministic(testCase)

cfg = makeTestConfig();
center = centerForFace(cfg, "z_max");

first = ...
    kwsim.three_d.makeSparseDiskMaskOnFace( ...
        cfg, ...
        "z_max", ...
        center);

second = ...
    kwsim.three_d.makeSparseDiskMaskOnFace( ...
        cfg, ...
        "z_max", ...
        center);

verifyEqual( ...
    testCase, ...
    first, ...
    second);

end

function testRejectsUnsupportedFace(testCase)

cfg = makeTestConfig();

verifyError( ...
    testCase, ...
    @() kwsim.three_d.makeSparseDiskMaskOnFace( ...
        cfg, ...
        "diagonal_face", ...
        [10, 10, 10]), ...
    "kwsim:Unsupported3DSourceFace");

end

function testRejectsCenterOnWrongPlane(testCase)

cfg = makeTestConfig();
center = centerForFace(cfg, "x_min");
center(1) = center(1) + 1;

verifyError( ...
    testCase, ...
    @() kwsim.three_d.makeSparseDiskMaskOnFace( ...
        cfg, ...
        "x_min", ...
        center), ...
    "kwsim:SourceCenterNotOnResolvedFace");

end

function testRejectsContactNearTangentEdge(testCase)

cfg = makeTestConfig();
center = centerForFace(cfg, "x_min");
center(2) = 1;

verifyError( ...
    testCase, ...
    @() kwsim.three_d.makeSparseDiskMaskOnFace( ...
        cfg, ...
        "x_min", ...
        center), ...
    "kwsim:SourceContactExceedsTangentGrid");

end

function testRejectsInvalidCenters(testCase)

cfg = makeTestConfig();
center = centerForFace(cfg, "x_min");

verifyError( ...
    testCase, ...
    @() kwsim.three_d.makeSparseDiskMaskOnFace( ...
        cfg, ...
        "x_min", ...
        center + [0, 0.5, 0]), ...
    "kwsim:Invalid3DSourceCenter");

verifyError( ...
    testCase, ...
    @() kwsim.three_d.makeSparseDiskMaskOnFace( ...
        cfg, ...
        "x_min", ...
        [center(1), cfg.grid.Ny + 1, center(3)]), ...
    "kwsim:Invalid3DSourceCenter");

end

function cfg = makeTestConfig()

cfg = ...
    kwsim.three_d.defaultConfig();

cfg.grid.Nx = 48;
cfg.grid.Ny = 40;
cfg.grid.Nz = 44;

cfg.grid.dx_m = 0.5e-3;
cfg.grid.dy_m = 0.5e-3;
cfg.grid.dz_m = 0.5e-3;

cfg.source.boundary_margin_m = 4e-3;
cfg.source.contact_radius_m = 1e-3;
cfg.source.contact_node_spacing_points = 2;

end

function center = centerForFace(cfg, face)

margin_points = round( ...
    cfg.source.boundary_margin_m ./ ...
    [cfg.grid.dx_m, cfg.grid.dy_m, cfg.grid.dz_m]);

center = [
    round((cfg.grid.Nx + 1) / 2), ...
    round((cfg.grid.Ny + 1) / 2), ...
    round((cfg.grid.Nz + 1) / 2)
];

switch string(face)
    case "x_min"
        center(1) = 1 + margin_points(1);

    case "x_max"
        center(1) = cfg.grid.Nx - margin_points(1);

    case "y_min"
        center(2) = 1 + margin_points(2);

    case "y_max"
        center(2) = cfg.grid.Ny - margin_points(2);

    case "z_min"
        center(3) = 1 + margin_points(3);

    case "z_max"
        center(3) = cfg.grid.Nz - margin_points(3);
end

end

function fixed_axis = fixedAxisForFace(face)

switch string(face)
    case {"x_min", "x_max"}
        fixed_axis = 1;

    case {"y_min", "y_max"}
        fixed_axis = 2;

    case {"z_min", "z_max"}
        fixed_axis = 3;
end

end
