function tests = test_make_explicit_runs
tests = functiontests(localfunctions);
end


function testBuildsGenericScalarOverrides(testCase)

plan = table( ...
    ["run_a";"run_b"], ...
    [101;102], ...
    [300;500], ...
    VariableNames=[ ...
        "my_id", ...
        "rng_seed", ...
        "frequency"]);

mapping = [
    "seed"                    "rng_seed"
    "wavefield.frequency_hz"  "frequency"
];

runs = simcampaigns.makeExplicitRuns( ...
    plan,mapping, ...
    DesignIdColumn="my_id");

verifyEqual(testCase,numel(runs),2);

verifyEqual(testCase,string(runs(1).design_id),"run_a");

verifyEqual( ...
    testCase, ...
    string({runs(1).overrides.path})', ...
    ["seed";"wavefield.frequency_hz"]);

verifyEqual(testCase,runs(1).overrides(1).value,101);
verifyEqual(testCase,runs(2).overrides(2).value,500);

verifyFalse(testCase,isfield(runs,"condition_id"));
verifyFalse(testCase,isfield(runs,"realization_id"));

end


function testPreservesOptionalProvenance(testCase)

plan = table( ...
    ["r1";"r2"], ...
    ["condition_a";"condition_a"], ...
    [1;2], ...
    [11;12], ...
    VariableNames=[ ...
        "id","condition","replicate","seed_value"]);

mapping = [
    "seed" "seed_value"
];

runs = simcampaigns.makeExplicitRuns( ...
    plan,mapping, ...
    DesignIdColumn="id", ...
    ConditionIdColumn="condition", ...
    RealizationIdColumn="replicate");

verifyEqual(testCase,string(runs(2).condition_id),"condition_a");
verifyEqual(testCase,double(runs(2).realization_id),2);

end


function testPreservesVectorValues(testCase)

axes = [
    1 0 0
    0 1 0
];

plan = table( ...
    ["a";"b"], ...
    axes, ...
    VariableNames=["id","axis"]);

mapping = [
    "directions.support.axis_xyz" "axis"
];

runs = simcampaigns.makeExplicitRuns( ...
    plan,mapping, ...
    DesignIdColumn="id");

verifyEqual(testCase,runs(1).overrides(1).value,[1 0 0]);
verifyEqual(testCase,runs(2).overrides(1).value,[0 1 0]);

end


function testPreservesCellStructuredValues(testCase)

values = {
    struct("kind","first","value",1)
    struct("kind","second","value",[2 3])
};

plan = table( ...
    ["a";"b"], ...
    values, ...
    VariableNames=["id","payload"]);

mapping = [
    "some.configuration.path" "payload"
];

runs = simcampaigns.makeExplicitRuns( ...
    plan,mapping, ...
    DesignIdColumn="id");

verifyEqual(testCase,string(runs(1).overrides(1).value.kind),"first");
verifyEqual(testCase,runs(2).overrides(1).value.value,[2 3]);

end


function testRejectsDuplicateDesignIds(testCase)

plan = table( ...
    ["same";"same"], ...
    [1;2], ...
    VariableNames=["id","seed"]);

mapping = ["seed" "seed"];

verifyError( ...
    testCase, ...
    @() simcampaigns.makeExplicitRuns( ...
        plan,mapping,DesignIdColumn="id"), ...
    "simcampaigns:DuplicateExplicitDesignId");

end


function testRejectsMissingMappedColumn(testCase)

plan = table( ...
    "a", ...
    VariableNames="id");

mapping = ["seed" "does_not_exist"];

verifyError( ...
    testCase, ...
    @() simcampaigns.makeExplicitRuns( ...
        plan,mapping,DesignIdColumn="id"), ...
    "simcampaigns:ExplicitRunPlanColumnMissing");

end


function testRejectsPartialProvenance(testCase)

plan = table( ...
    "a", ...
    "condition", ...
    1, ...
    VariableNames=["id","condition","seed"]);

mapping = ["seed" "seed"];

verifyError( ...
    testCase, ...
    @() simcampaigns.makeExplicitRuns( ...
        plan,mapping, ...
        DesignIdColumn="id", ...
        ConditionIdColumn="condition"), ...
    "simcampaigns:IncompleteExplicitRunProvenance");

end
