function tests = test_swsynth_wavefield_spectral_metrics
%TEST_SWSYNTH_WAVEFIELD_SPECTRAL_METRICS Test global spectrum metrics.

tests = functiontests(localfunctions);

end


function testDirectionalFieldHasLowAngularEntropy(testCase)

Nx = 96;
Nz = 80;

dxM = 1e-3;
dzM = 1e-3;

xM = (0:Nx-1) * dxM;
zM = (0:Nz-1) * dzM;

[X, Z] = meshgrid(xM, zM);

fieldZX = exp(1i * (420*X + 0*Z));

metrics = ...
    swsynth.metrics.computeWavefieldSpectralMetrics( ...
        fieldZX, ...
        dxM, ...
        dzM);

verifyGreaterThanOrEqual( ...
    testCase, ...
    metrics.angular_entropy, ...
    0);

verifyLessThan( ...
    testCase, ...
    metrics.angular_entropy, ...
    0.35);

verifyGreaterThanOrEqual( ...
    testCase, ...
    metrics.angular_effective_bins, ...
    1);

end


function testMultidirectionalFieldHasHigherEntropy(testCase)

Nx = 96;
Nz = 80;

dxM = 1e-3;
dzM = 1e-3;

xM = (0:Nx-1) * dxM;
zM = (0:Nz-1) * dzM;

[X, Z] = meshgrid(xM, zM);

directionalFieldZX = ...
    exp(1i * 420*X);

multidirectionalFieldZX = ...
    exp(1i * 420*X) + ...
    exp(1i * 420*Z) + ...
    exp(1i * 300*(X + Z)) + ...
    exp(1i * 300*(X - Z));

directionalMetrics = ...
    swsynth.metrics.computeWavefieldSpectralMetrics( ...
        directionalFieldZX, ...
        dxM, ...
        dzM);

multidirectionalMetrics = ...
    swsynth.metrics.computeWavefieldSpectralMetrics( ...
        multidirectionalFieldZX, ...
        dxM, ...
        dzM);

verifyGreaterThan( ...
    testCase, ...
    multidirectionalMetrics.angular_entropy, ...
    directionalMetrics.angular_entropy);

verifyGreaterThan( ...
    testCase, ...
    multidirectionalMetrics.angular_effective_bins, ...
    directionalMetrics.angular_effective_bins);

end


function testMetricsAreExactlyReproducible(testCase)

rng(19, "twister");

fieldZX = ...
    randn(30,40) + ...
    1i*randn(30,40);

metricsA = ...
    swsynth.metrics.computeWavefieldSpectralMetrics( ...
        fieldZX, ...
        2e-4, ...
        2e-4);

metricsB = ...
    swsynth.metrics.computeWavefieldSpectralMetrics( ...
        fieldZX, ...
        2e-4, ...
        2e-4);

verifyEqual(testCase, metricsA, metricsB);

end


function testAnalysisConventionIsRecorded(testCase)

fieldZX = ...
    exp(1i * reshape(0:99,10,10));

metrics = ...
    swsynth.metrics.computeWavefieldSpectralMetrics( ...
        fieldZX, ...
        1e-3, ...
        2e-3);

verifyTrue(testCase, metrics.analysis.remove_mean);

verifyEqual( ...
    testCase, ...
    metrics.analysis.window, ...
    "separable_hann");

verifyEqual( ...
    testCase, ...
    metrics.analysis.fft, ...
    "fftshift_fft2");

verifyEqual( ...
    testCase, ...
    metrics.analysis.array_order, ...
    "zx");

verifyEqual(testCase, metrics.analysis.Nx, 10);
verifyEqual(testCase, metrics.analysis.Nz, 10);

end


function testZeroFieldIsRejected(testCase)

verifyError( ...
    testCase, ...
    @() swsynth.metrics.computeWavefieldSpectralMetrics( ...
        zeros(8,8), ...
        1e-3, ...
        1e-3), ...
    "swsynth:ZeroWavefieldSpectralInput");

end
