function tests = test_simviz_theme

tests = functiontests(localfunctions);

end


function testSwsColormap(testCase)

addSourcePath();

theme = simviz.paperTheme();
map = simviz.colormapSws(256);

verifyEqual(testCase, size(map), [256, 3]);
verifyEqual( ...
    testCase, ...
    map(1, :), ...
    theme.rgb.blue.main, ...
    "AbsTol", ...
    1e-12);

verifyEqual( ...
    testCase, ...
    map(end, :), ...
    theme.rgb.red.main, ...
    "AbsTol", ...
    1e-12);

end


function testAmplitudeColormap(testCase)

addSourcePath();

theme = simviz.paperTheme();
map = simviz.colormapAmplitude(256);

verifyEqual(testCase, size(map), [256, 3]);

verifyEqual( ...
    testCase, ...
    map(1, :), ...
    theme.rgb.gray.dark, ...
    "AbsTol", ...
    1e-12);

verifyEqual( ...
    testCase, ...
    map(end, :), ...
    theme.rgb.yellow.main, ...
    "AbsTol", ...
    1e-12);

end


function testFieldRealColormap(testCase)

addSourcePath();

theme = simviz.paperTheme();
map = simviz.colormapFieldReal(257);

verifyEqual(testCase, size(map), [257, 3]);

verifyEqual( ...
    testCase, ...
    map(1, :), ...
    theme.rgb.blue.main, ...
    "AbsTol", ...
    1e-12);

verifyEqual( ...
    testCase, ...
    map(129, :), ...
    theme.rgb.gray.dark, ...
    "AbsTol", ...
    1e-12);

verifyEqual( ...
    testCase, ...
    map(end, :), ...
    theme.rgb.yellow.main, ...
    "AbsTol", ...
    1e-12);

end


function testPhaseColormap(testCase)

addSourcePath();

theme = simviz.paperTheme();
map = simviz.colormapPhase(257);

verifyEqual(testCase, size(map), [257, 3]);

verifyEqual( ...
    testCase, ...
    map(1, :), ...
    theme.rgb.blue.main, ...
    "AbsTol", ...
    1e-12);

verifyEqual( ...
    testCase, ...
    map(129, :), ...
    [1, 1, 1], ...
    "AbsTol", ...
    1e-12);

verifyEqual( ...
    testCase, ...
    map(end, :), ...
    theme.rgb.red.main, ...
    "AbsTol", ...
    1e-12);

end


function addSourcePath()

root = fileparts( ...
    fileparts( ...
        fileparts(mfilename("fullpath"))));

addpath(fullfile(root, "src"));

end
