function tests = test_3d_source_geometry_metrics
%TEST_3D_SOURCE_GEOMETRY_METRICS Test objective angular-coverage metrics.

tests = functiontests(localfunctions);

end


function setupOnce(~)

repository_root = ...
    findRepositoryRoot();

addpath(fullfile(repository_root, "src"));

end


function testSingleDirectionHasDimensionOne(testCase)

cfg = ...
    makeSyntheticConfig( ...
        [1, 0, 0], ...
        "x_min");

metrics = ...
    kwsim.analysis.summarizeSourceGeometry3D(cfg);

verifyEqual( ...
    testCase, ...
    metrics.effective_angular_dimension, ...
    1, ...
    "AbsTol", ...
    1e-12);

verifyEqual( ...
    testCase, ...
    metrics.directional_bias, ...
    1, ...
    "AbsTol", ...
    1e-12);

verifyEqual( ...
    testCase, ...
    metrics.angular_eigenvalues_descending, ...
    [1; 0; 0], ...
    "AbsTol", ...
    1e-12);

end


function testOppositeDirectionsRemainLineLike(testCase)

directions = [
     1, 0, 0
    -1, 0, 0
];

cfg = ...
    makeSyntheticConfig( ...
        directions, ...
        ["x_min"; "x_max"]);

metrics = ...
    kwsim.analysis.summarizeSourceGeometry3D(cfg);

verifyEqual( ...
    testCase, ...
    metrics.effective_angular_dimension, ...
    1, ...
    "AbsTol", ...
    1e-12);

verifyEqual( ...
    testCase, ...
    metrics.directional_bias, ...
    0, ...
    "AbsTol", ...
    1e-12);

verifyEqual( ...
    testCase, ...
    metrics.pairwise_direction_angle_max_deg, ...
    180, ...
    "AbsTol", ...
    1e-12);

verifyEqual( ...
    testCase, ...
    metrics.pairwise_axis_angle_max_deg, ...
    0, ...
    "AbsTol", ...
    1e-12);

verifyEqual( ...
    testCase, ...
    metrics.pairwise_direction_angle_p10_deg, ...
    180, ...
    "AbsTol", ...
    1e-12);

verifyEqual( ...
    testCase, ...
    metrics.pairwise_axis_angle_p10_deg, ...
    0, ...
    "AbsTol", ...
    1e-12);

end


function testPlanarDirectionsHaveDimensionTwo(testCase)

directions = [
     1, 0, 0
    -1, 0, 0
     0, 0, 1
     0, 0,-1
];

faces = [
    "x_min"
    "x_max"
    "z_min"
    "z_max"
];

cfg = ...
    makeSyntheticConfig( ...
        directions, ...
        faces);

metrics = ...
    kwsim.analysis.summarizeSourceGeometry3D(cfg);

verifyEqual( ...
    testCase, ...
    metrics.effective_angular_dimension, ...
    2, ...
    "AbsTol", ...
    1e-12);

verifyEqual( ...
    testCase, ...
    metrics.directional_bias, ...
    0, ...
    "AbsTol", ...
    1e-12);

verifyEqual( ...
    testCase, ...
    metrics.angular_eigenvalues_descending, ...
    [0.5; 0.5; 0], ...
    "AbsTol", ...
    1e-12);

verifyEqual( ...
    testCase, ...
    metrics.weighted_mean_plane_deviation_deg, ...
    0, ...
    "AbsTol", ...
    1e-12);

end


function testIsotropicAxesHaveDimensionThree(testCase)

directions = [
     1, 0, 0
    -1, 0, 0
     0, 1, 0
     0,-1, 0
     0, 0, 1
     0, 0,-1
];

faces = [
    "x_min"
    "x_max"
    "y_min"
    "y_max"
    "z_min"
    "z_max"
];

cfg = ...
    makeSyntheticConfig( ...
        directions, ...
        faces);

metrics = ...
    kwsim.analysis.summarizeSourceGeometry3D(cfg);

verifyEqual( ...
    testCase, ...
    metrics.effective_angular_dimension, ...
    3, ...
    "AbsTol", ...
    1e-12);

verifyEqual( ...
    testCase, ...
    metrics.directional_bias, ...
    0, ...
    "AbsTol", ...
    1e-12);

verifyEqual( ...
    testCase, ...
    metrics.angular_eigenvalues_descending, ...
    ones(3, 1) / 3, ...
    "AbsTol", ...
    1e-12);

verifyEqual( ...
    testCase, ...
    metrics.unique_face_count, ...
    6);

verifyEqual( ...
    testCase, ...
    metrics.face_counts, ...
    ones(6, 1));

end


function testCanonicalGeometriesResolveMetrics(testCase)

repository_root = ...
    findRepositoryRoot();

config_files = [
    fullfile( ...
        repository_root, ...
        "configs", ...
        "three_d", ...
        "homogeneous_directional_req_validation.json")
    fullfile( ...
        repository_root, ...
        "configs", ...
        "three_d", ...
        "homogeneous_partial_diffuse8_req_validation.json")
    fullfile( ...
        repository_root, ...
        "configs", ...
        "three_d", ...
        "homogeneous_partial_3d_n8_p2_req_validation.json")
];

resolved = ...
    cell(3, 1);

for config_index = 1:3
    [requested, ~] = ...
        kwsim.io.loadConfigJson( ...
            config_files(config_index));

    % This test compares resolved source geometry only. Numerical
    % points-per-wavelength acceptance is covered by configuration and
    % solver tests, so do not let it block geometry characterization.
    requested.grid.minimum_shear_ppw = ...
        1;

    [resolved{config_index}, ~] = ...
        kwsim.three_d.validateConfig(requested);
end

directional = ...
    resolved{1}.source.geometry_metrics;

single_face_n8 = ...
    resolved{2}.source.geometry_metrics;

multiface_n8_p2 = ...
    resolved{3}.source.geometry_metrics;

verifyEqual( ...
    testCase, ...
    directional.source_count, ...
    1);

verifyEqual( ...
    testCase, ...
    directional.unique_face_count, ...
    1);

verifyEqual( ...
    testCase, ...
    directional.effective_angular_dimension, ...
    1, ...
    "AbsTol", ...
    1e-12);

verifyEqual( ...
    testCase, ...
    single_face_n8.source_count, ...
    8);

verifyEqual( ...
    testCase, ...
    single_face_n8.unique_face_count, ...
    1);

verifyGreaterThanOrEqual( ...
    testCase, ...
    single_face_n8.effective_angular_dimension, ...
    1);

verifyLessThanOrEqual( ...
    testCase, ...
    single_face_n8.effective_angular_dimension, ...
    3);

verifyEqual( ...
    testCase, ...
    multiface_n8_p2.source_count, ...
    8);

verifyEqual( ...
    testCase, ...
    multiface_n8_p2.unique_face_count, ...
    6);

verifyEqual( ...
    testCase, ...
    multiface_n8_p2.in_plane_contact_count, ...
    2);

verifyEqual( ...
    testCase, ...
    multiface_n8_p2.out_of_plane_contact_count, ...
    6);

verifyGreaterThanOrEqual( ...
    testCase, ...
    multiface_n8_p2.effective_angular_dimension, ...
    1);

verifyLessThanOrEqual( ...
    testCase, ...
    multiface_n8_p2.effective_angular_dimension, ...
    3);

end


function cfg = makeSyntheticConfig(directions_xyz, faces)

directions_xyz = ...
    double(directions_xyz);

number_of_sources = ...
    size(directions_xyz, 1);

faces = ...
    string(faces(:));

if isscalar(faces) && number_of_sources > 1
    faces = ...
        repmat( ...
            faces, ...
            number_of_sources, ...
            1);
end

cfg = struct();

cfg.grid = struct();
cfg.grid.Nx = 20;
cfg.grid.Ny = 20;
cfg.grid.Nz = 20;
cfg.grid.dx_m = 0.5e-3;
cfg.grid.dy_m = 0.5e-3;
cfg.grid.dz_m = 0.5e-3;

cfg.sensor = struct();
cfg.sensor.acquisition_y_index_full = 10;

cfg.source = struct();
cfg.source.layout = "vibrator_bank";
cfg.source.side = "multiface";
cfg.source.boundary_margin_m = 2e-3;
cfg.source.acquisition_plane_y_index_full = 10;

template = struct( ...
    "face", "", ...
    "center_index_xyz", [NaN, NaN, NaN], ...
    "nominal_propagation_xyz", [NaN, NaN, NaN], ...
    "node_linear_indices", [], ...
    "velocity_amplitude_m_s", 1, ...
    "intersects_acquisition_plane", true);

vibrators = ...
    repmat( ...
        template, ...
        number_of_sources, ...
        1);

for source_index = 1:number_of_sources
    direction = ...
        directions_xyz(source_index, :);

    direction = ...
        direction / norm(direction);

    center = [
        2 + source_index, ...
        10, ...
        10
    ];

    node_index = ...
        sub2ind( ...
            [ ...
                cfg.grid.Nx, ...
                cfg.grid.Ny, ...
                cfg.grid.Nz ...
            ], ...
            center(1), ...
            center(2), ...
            center(3));

    vibrators(source_index).face = ...
        faces(source_index);

    vibrators(source_index).center_index_xyz = ...
        center;

    vibrators(source_index).nominal_propagation_xyz = ...
        direction;

    vibrators(source_index).node_linear_indices = ...
        node_index;

    vibrators(source_index).velocity_amplitude_m_s = ...
        1;

    vibrators(source_index). ...
        intersects_acquisition_plane = ...
        true;
end

cfg.source.vibrators = ...
    vibrators;

end


function repository_root = findRepositoryRoot()

repository_root = ...
    fileparts( ...
        fileparts( ...
        fileparts( ...
        mfilename("fullpath"))));

end
