function tests = test_3d_partial_n8_p2_config
%TEST_3D_PARTIAL_N8_P2_CONFIG Test the canonical multi-face N8 P2 bank.

tests = functiontests(localfunctions);

end

function setupOnce(~)

repository_root = ...
    findRepositoryRoot();

addpath(fullfile(repository_root, "src"));

end

function testCanonicalConfigResolves(testCase)

config_file = ...
    canonicalConfigPath();

[requested, ~] = ...
    kwsim.io.loadConfigJson(config_file);

[resolved, ~] = ...
    kwsim.three_d.validateConfig(requested);

verifyEqual( ...
    testCase, ...
    string(resolved.scenario), ...
    "homogeneous_partial_3d_n8_p2");

verifyEqual( ...
    testCase, ...
    string(resolved.source.side), ...
    "multiface");

verifyEqual( ...
    testCase, ...
    string(resolved.source.bank_name), ...
    "partial_3d_n8_p2");

verifyEqual( ...
    testCase, ...
    numel(resolved.source.vibrators), ...
    8);

verifyEqual( ...
    testCase, ...
    resolved.source.face_counts, ...
    [2; 2; 1; 1; 1; 1]);

verifyEqual( ...
    testCase, ...
    resolved.source.in_plane_vibrator_count, ...
    2);

verifyEqual( ...
    testCase, ...
    resolved.source.centered_in_plane_vibrator_count, ...
    2);

verifyEqual( ...
    testCase, ...
    resolved.source.out_of_plane_vibrator_count, ...
    6);

intersects_plane = ...
    logical([ ...
        resolved.source.vibrators. ...
        intersects_acquisition_plane]);

centered_on_plane = ...
    logical([ ...
        resolved.source.vibrators. ...
        centered_on_acquisition_plane]);

verifyEqual(testCase, nnz(intersects_plane), 2);
verifyEqual(testCase, nnz(centered_on_plane), 2);

verifyEqual( ...
    testCase, ...
    resolved.source.acquisition_plane_y_index_full, ...
    resolved.sensor.acquisition_y_index_full);

verifyTrue( ...
    testCase, ...
    ismember( ...
        resolved.sensor.acquisition_y_index_full, ...
        resolved.sensor.y_indices));

centers = ...
    vertcat(resolved.source.vibrators.center_index_xyz);

verifyEqual( ...
    testCase, ...
    size(unique(centers, "rows"), 1), ...
    8);

end

function testSensorDoesNotContainSourceNodes(testCase)

config_file = ...
    canonicalConfigPath();

[requested, ~] = ...
    kwsim.io.loadConfigJson(config_file);

[resolved, ~] = ...
    kwsim.three_d.validateConfig(requested);

sensor_mask = ...
    false( ...
        resolved.grid.Nx, ...
        resolved.grid.Ny, ...
        resolved.grid.Nz);

sensor_mask( ...
    resolved.sensor.x_indices, ...
    resolved.sensor.y_indices, ...
    resolved.sensor.z_indices) = ...
    true;

source_nodes = ...
    vertcat( ...
        resolved.source.vibrators. ...
        node_linear_indices);

verifyFalse( ...
    testCase, ...
    any(sensor_mask(source_nodes)));

end

function testSourceBuilderPreservesDrive(testCase)

config_file = ...
    canonicalConfigPath();

[requested, ~] = ...
    kwsim.io.loadConfigJson(config_file);

[resolved, ~] = ...
    kwsim.three_d.validateConfig(requested);

kgrid = struct();
kgrid.t_array = ...
    0:(1/50e3):(12/resolved.source.f0_hz);

[source, metadata] = ...
    kwsim.three_d.buildVibratorBankSource( ...
        resolved, ...
        kgrid);

verifyEqual( ...
    testCase, ...
    nnz(source.u_mask), ...
    resolved.source.contact_node_count);

verifyEqual( ...
    testCase, ...
    metadata.vibrator_count, ...
    8);

expected_rms_squared = ...
    resolved.source.reference_single_contact_node_count * ...
    resolved.source.velocity_amplitude_m_s^2 / 2;

verifyEqual( ...
    testCase, ...
    metadata.nominal_total_drive_rms_squared_m2_s2, ...
    expected_rms_squared, ...
    "RelTol", ...
    1e-12);

end

function testResolutionIsDeterministic(testCase)

config_file = ...
    canonicalConfigPath();

[first_requested, ~] = ...
    kwsim.io.loadConfigJson(config_file);

[second_requested, ~] = ...
    kwsim.io.loadConfigJson(config_file);

[first, ~] = ...
    kwsim.three_d.validateConfig(first_requested);

[second, ~] = ...
    kwsim.three_d.validateConfig(second_requested);

verifyEqual( ...
    testCase, ...
    first.source.vibrators, ...
    second.source.vibrators);

end

function testCliDryRun(testCase)

outcome = ...
    kwsim.cli.runConfig( ...
        canonicalConfigPath(), ...
        DryRun=true);

verifyEqual( ...
    testCase, ...
    string(outcome.status), ...
    "dry_run_valid");

verifyEqual( ...
    testCase, ...
    string(outcome.scenario), ...
    "homogeneous_partial_3d_n8_p2");

verifyEqual( ...
    testCase, ...
    outcome.config_resolved.source. ...
        in_plane_vibrator_count, ...
    2);

verifyEqual( ...
    testCase, ...
    outcome.config_resolved.source. ...
        out_of_plane_vibrator_count, ...
    6);

end

function path_value = canonicalConfigPath()

path_value = ...
    fullfile( ...
        findRepositoryRoot(), ...
        "configs", ...
        "three_d", ...
        "homogeneous_partial_3d_n8_p2_req_validation.json");

end

function repository_root = findRepositoryRoot()

repository_root = ...
    fileparts( ...
        fileparts( ...
        fileparts( ...
        mfilename("fullpath"))));

end
