function tests = test_swsynth_projected3d_global_phase_reference
%TEST_SWSYNTH_PROJECTED3D_GLOBAL_PHASE_REFERENCE Common phase origin.

tests = functiontests(localfunctions);

end

function testHomogeneousDelayMatchesAnalyticPlaneWave(testCase)

csMps = 3.0;

xM = 0:0.001:0.020;
zM = (0:0.001:0.015).';

csMapZX = csMps * ones(numel(zM),numel(xM));

directionsXYZ = [
     1.0,  0.0,  0.0
    -1.0,  0.0,  0.0
     0.6,  0.0,  0.8
    -0.6,  0.0, -0.8
     0.6,  0.6,  0.529150262212918];

directionsXYZ = ...
    directionsXYZ ./ vecnorm(directionsXYZ,2,2);

[X, Z] = meshgrid(xM,zM);

for directionIndex = 1:size(directionsXYZ,1)

    directionXYZ = directionsXYZ(directionIndex,:);

    [actualDelayZX, diagnostics] = ...
        swsynth.propagation.projected3d. ...
            computeDirectionalPhaseDelay( ...
                csMapZX, ...
                xM, ...
                zM, ...
                directionXYZ, ...
                csMps, ...
                struct());

    expectedDelayZX = ...
        directionXYZ(1) .* X ./ csMps + ...
        directionXYZ(3) .* Z ./ csMps;

    verifyEqual( ...
        testCase, ...
        actualDelayZX, ...
        expectedDelayZX, ...
        "AbsTol", 1e-13);

    verifyEqual( ...
        testCase, ...
        diagnostics.phase_reference, ...
        "global_origin_x0_z0");
end

end

function testPhaseGradientIsUnchangedByReferenceShift(testCase)

csMps = 2.5;

xM = 0:0.001:0.020;
zM = (0:0.001:0.020).';

csMapZX = csMps * ones(numel(zM),numel(xM));

directionXYZ = [-0.8,0.0,0.6];

[delayZX, ~] = ...
    swsynth.propagation.projected3d. ...
        computeDirectionalPhaseDelay( ...
            csMapZX, ...
            xM, ...
            zM, ...
            directionXYZ, ...
            csMps, ...
            struct());

dxM = mean(diff(xM));
dzM = mean(diff(zM));

gradientX = diff(delayZX,1,2) ./ dxM;
gradientZ = diff(delayZX,1,1) ./ dzM;

verifyEqual( ...
    testCase, ...
    gradientX, ...
    directionXYZ(1)/csMps .* ones(size(gradientX)), ...
    "AbsTol", 1e-12);

verifyEqual( ...
    testCase, ...
    gradientZ, ...
    directionXYZ(3)/csMps .* ones(size(gradientZ)), ...
    "AbsTol", 1e-12);

end
