function tests = test_3d_material_geometry
%TEST_3D_MATERIAL_GEOMETRY Test 3D sphere, cylinder, and bilayer maps.

tests = functiontests(localfunctions);

end


function setupOnce(~)

repository_root = ...
    findRepositoryRoot();

addpath(fullfile(repository_root, "src"));

end


function testDefaultMediumRemainsHomogeneous(testCase)

cfg = ...
    kwsim.three_d.defaultConfig();

[cfg, ~] = ...
    kwsim.three_d.validateConfig(cfg);

[medium, truth] = ...
    kwsim.three_d.buildMedium(cfg);

verifyTrue( ...
    testCase, ...
    truth.homogeneous);

verifyTrue( ...
    testCase, ...
    isscalar(medium.sound_speed_shear));

verifyEqual( ...
    testCase, ...
    unique(truth.material_id_xyz), ...
    uint16(1));

verifyEqual( ...
    testCase, ...
    unique(truth.cs_m_s_xyz), ...
    single(2));

end


function testSphereOverridesBackground(testCase)

cfg = ...
    makeBaseConfig();

sphere = ...
    makeObject( ...
        "sphere", ...
        "hard_sphere", ...
        [14e-3, 7.5e-3, 12e-3], ...
        2e-3, ...
        uint16(2), ...
        4.0);

cfg.geometry.objects = ...
    sphere;

[cfg, ~] = ...
    kwsim.three_d.validateConfig(cfg);

[medium, truth] = ...
    kwsim.three_d.buildMedium(cfg);

center_index = ...
    physicalPointToIndex( ...
        sphere.center_m_xyz, ...
        cfg);

verifyFalse( ...
    testCase, ...
    truth.homogeneous);

verifyFalse( ...
    testCase, ...
    isscalar(medium.sound_speed_shear));

verifyEqual( ...
    testCase, ...
    cfg.geometry.minimum_cs_m_s, ...
    2, ...
    "AbsTol", ...
    1e-12);

verifyEqual( ...
    testCase, ...
    cfg.geometry.maximum_cs_m_s, ...
    4, ...
    "AbsTol", ...
    1e-12);

verifyEqual( ...
    testCase, ...
    cfg.geometry.maximum_cp_m_s, ...
    40, ...
    "AbsTol", ...
    1e-12);

verifyEqual( ...
    testCase, ...
    truth.material_id_xyz( ...
        center_index(1), ...
        center_index(2), ...
        center_index(3)), ...
    uint16(2));

verifyEqual( ...
    testCase, ...
    truth.cs_m_s_xyz( ...
        center_index(1), ...
        center_index(2), ...
        center_index(3)), ...
    single(4));

verifyEqual( ...
    testCase, ...
    truth.cp_m_s_xyz( ...
        center_index(1), ...
        center_index(2), ...
        center_index(3)), ...
    single(40));

verifyGreaterThan( ...
    testCase, ...
    nnz(truth.material_id_xyz == 2), ...
    0);

end


function testArbitraryCylinderIsResolved(testCase)

cfg = ...
    makeBaseConfig();

cylinder = ...
    makeObject( ...
        "cylinder", ...
        "oblique_cylinder", ...
        [14e-3, 7.5e-3, 12e-3], ...
        1.5e-3, ...
        uint16(3), ...
        3.5);

cylinder.axis_xyz = ...
    [1, 0, 1];

cylinder.length_m = ...
    6e-3;

cfg.geometry.objects = ...
    cylinder;

[cfg, ~] = ...
    kwsim.three_d.validateConfig(cfg);

[~, truth] = ...
    kwsim.three_d.buildMedium(cfg);

center_index = ...
    physicalPointToIndex( ...
        cylinder.center_m_xyz, ...
        cfg);

verifyEqual( ...
    testCase, ...
    norm(cfg.geometry.objects(1).axis_xyz), ...
    1, ...
    "AbsTol", ...
    1e-12);

verifyEqual( ...
    testCase, ...
    truth.material_id_xyz( ...
        center_index(1), ...
        center_index(2), ...
        center_index(3)), ...
    uint16(3));

verifyGreaterThan( ...
    testCase, ...
    nnz(truth.material_id_xyz == 3), ...
    0);

end


function testBilayerAssignsBothMaterials(testCase)

cfg = ...
    makeBaseConfig();

cfg.geometry.require_objects_inside_sensor_roi = ...
    false;

cfg.geometry.bilayer.enabled = ...
    true;

cfg.geometry.bilayer.interface_point_m_xyz = ...
    [14e-3, 0, 0];

cfg.geometry.bilayer.normal_xyz = ...
    [1, 0, 0];

cfg.geometry.bilayer.negative_material = ...
    makeMaterial( ...
        uint16(2), ...
        2.5);

cfg.geometry.bilayer.positive_material = ...
    makeMaterial( ...
        uint16(3), ...
        4.0);

[cfg, ~] = ...
    kwsim.three_d.validateConfig(cfg);

[~, truth] = ...
    kwsim.three_d.buildMedium(cfg);

negative_index = ...
    physicalPointToIndex( ...
        [12e-3, 7.5e-3, 12e-3], ...
        cfg);

positive_index = ...
    physicalPointToIndex( ...
        [16e-3, 7.5e-3, 12e-3], ...
        cfg);

verifyEqual( ...
    testCase, ...
    truth.material_id_xyz( ...
        negative_index(1), ...
        negative_index(2), ...
        negative_index(3)), ...
    uint16(2));

verifyEqual( ...
    testCase, ...
    truth.material_id_xyz( ...
        positive_index(1), ...
        positive_index(2), ...
        positive_index(3)), ...
    uint16(3));

verifyEqual( ...
    testCase, ...
    sort(unique(truth.material_id_xyz)), ...
    uint16([2; 3]));

end


function testSphereOverridesBilayer(testCase)

cfg = ...
    makeBaseConfig();

cfg.geometry.require_objects_inside_sensor_roi = ...
    false;

cfg.geometry.bilayer.enabled = ...
    true;

cfg.geometry.bilayer.interface_point_m_xyz = ...
    [14e-3, 0, 0];

cfg.geometry.bilayer.normal_xyz = ...
    [1, 0, 0];

cfg.geometry.bilayer.negative_material = ...
    makeMaterial( ...
        uint16(2), ...
        2.5);

cfg.geometry.bilayer.positive_material = ...
    makeMaterial( ...
        uint16(3), ...
        3.5);

sphere = ...
    makeObject( ...
        "sphere", ...
        "embedded_sphere", ...
        [16e-3, 7.5e-3, 12e-3], ...
        1.5e-3, ...
        uint16(4), ...
        5.0);

cfg.geometry.objects = ...
    sphere;

[cfg, ~] = ...
    kwsim.three_d.validateConfig(cfg);

[~, truth] = ...
    kwsim.three_d.buildMedium(cfg);

center_index = ...
    physicalPointToIndex( ...
        sphere.center_m_xyz, ...
        cfg);

verifyEqual( ...
    testCase, ...
    truth.material_id_xyz( ...
        center_index(1), ...
        center_index(2), ...
        center_index(3)), ...
    uint16(4));

verifyEqual( ...
    testCase, ...
    truth.cs_m_s_xyz( ...
        center_index(1), ...
        center_index(2), ...
        center_index(3)), ...
    single(5));

end


function cfg = makeBaseConfig()

cfg = ...
    kwsim.three_d.defaultConfig();

cfg.geometry.minimum_boundary_clearance_m = ...
    1e-3;

end


function object = makeObject( ...
        type, ...
        name, ...
        center_m_xyz, ...
        radius_m, ...
        material_id, ...
        cs_m_s)

object = struct();
object.type = string(type);
object.name = string(name);
object.center_m_xyz = center_m_xyz;
object.axis_xyz = [NaN, NaN, NaN];
object.radius_m = radius_m;
object.length_m = NaN;
object.material_id = material_id;
object.cs_m_s = cs_m_s;
object.cp_m_s = NaN;
object.rho_kg_m3 = NaN;

end


function material = makeMaterial( ...
        material_id, ...
        cs_m_s)

material = struct();
material.material_id = material_id;
material.cs_m_s = cs_m_s;
material.cp_m_s = NaN;
material.rho_kg_m3 = NaN;

end


function index_xyz = physicalPointToIndex( ...
        point_m_xyz, ...
        cfg)

spacing_m_xyz = [
    cfg.grid.dx_m, ...
    cfg.grid.dy_m, ...
    cfg.grid.dz_m
];

index_xyz = ...
    round(point_m_xyz ./ spacing_m_xyz) + ...
    1;

end


function repository_root = findRepositoryRoot()

repository_root = ...
    fileparts( ...
        fileparts( ...
        fileparts( ...
            mfilename("fullpath"))));

end
