%VISUALIZE_3D_MATERIAL_GEOMETRIES Visualize canonical 3D material maps.
%
% This example validates configurations and builds truth maps without
% executing the k-Wave solver.

clear;
clc;

script_directory = ...
    fileparts(mfilename("fullpath"));

repository_root = ...
    fileparts(fileparts(script_directory));

addpath(fullfile(repository_root, "src"));

configuration_directory = ...
    fullfile( ...
        repository_root, ...
        "configs", ...
        "three_d");

configuration_files = [
    "heterogeneous_sphere_3d.json"
    "heterogeneous_cylinder_3d.json"
    "heterogeneous_bilayer_3d.json"
    "heterogeneous_combined_3d.json"
];

geometry_names = [
    "sphere"
    "oblique_cylinder"
    "bilayer"
    "combined"
];

% Physical locations selected to show the important geometry rather than
% simply using the center voxel of the numerical grid.
slice_points_mm_xyz = [
    15.0, 7.5, 12.0
    15.0, 7.5, 12.0
    15.0, 7.5, 12.0
    17.5, 7.5, 12.0
];

output_directory = ...
    fullfile( ...
        repository_root, ...
        "outputs", ...
        "examples", ...
        "three_d_material_geometries");

if ~isfolder(output_directory)
    mkdir(output_directory);
end

style = ...
    kwsim.viz.figureTemplate();

number_of_geometries = ...
    numel(configuration_files);

material_count = ...
    zeros(number_of_geometries, 1);

object_count = ...
    zeros(number_of_geometries, 1);

bilayer_enabled = ...
    false(number_of_geometries, 1);

minimum_cs_m_s = ...
    zeros(number_of_geometries, 1);

maximum_cs_m_s = ...
    zeros(number_of_geometries, 1);

fprintf("\nCreating 3D material-geometry gallery...\n");

for geometry_index = 1:number_of_geometries
    configuration_file = ...
        fullfile( ...
            configuration_directory, ...
            configuration_files(geometry_index));

    fprintf( ...
        "\n[%d/%d] %s\n", ...
        geometry_index, ...
        number_of_geometries, ...
        geometry_names(geometry_index));

    [requested_cfg, ~] = ...
        kwsim.io.loadConfigJson( ...
            configuration_file);

    [cfg, ~] = ...
        kwsim.three_d.validateConfig( ...
            requested_cfg);

    truth = ...
        kwsim.three_d.buildMaterialMaps(cfg);

    material_count(geometry_index) = ...
        numel(unique(truth.material_id_xyz));

    object_count(geometry_index) = ...
        cfg.geometry.object_count;

    bilayer_enabled(geometry_index) = ...
        cfg.geometry.bilayer.enabled;

    minimum_cs_m_s(geometry_index) = ...
        min(truth.cs_m_s_xyz, [], "all");

    maximum_cs_m_s(geometry_index) = ...
        max(truth.cs_m_s_xyz, [], "all");

    requested_slice_m_xyz = ...
        1e-3 * slice_points_mm_xyz(geometry_index, :);

    [~, x_index] = ...
        min(abs( ...
            cfg.derived.x_full_m - ...
            requested_slice_m_xyz(1)));

    [~, y_index] = ...
        min(abs( ...
            cfg.derived.y_full_m - ...
            requested_slice_m_xyz(2)));

    [~, z_index] = ...
        min(abs( ...
            cfg.derived.z_full_m - ...
            requested_slice_m_xyz(3)));

    handles = ...
        kwsim.viz.plotMaterialGeometry3D( ...
            cfg, ...
            Title=replace( ...
                geometry_names(geometry_index), ...
                "_", ...
                " "), ...
            XIndex=x_index, ...
            YIndex=y_index, ...
            ZIndex=z_index, ...
            FigureVisible="off");

    output_file = ...
        fullfile( ...
            output_directory, ...
            geometry_names(geometry_index) + ...
                "_material_geometry.png");

    exportgraphics( ...
        handles.figure, ...
        output_file, ...
        "Resolution", ...
        style.export_resolution_dpi, ...
        "BackgroundColor", ...
        style.background_color);

    close(handles.figure);

    fprintf("Saved: %s\n", output_file);
end

summary = ...
    table( ...
        geometry_names, ...
        material_count, ...
        object_count, ...
        bilayer_enabled, ...
        minimum_cs_m_s, ...
        maximum_cs_m_s);

writetable( ...
    summary, ...
    fullfile( ...
        output_directory, ...
        "material_geometry_summary.csv"));

disp(summary);

fprintf( ...
    "\nFigures saved in:\n%s\n", ...
    output_directory);
