function csv_file = writeCampaignRunsCsv(report, runs)
%WRITECAMPAIGNRUNSCSV Write one campaign row per expanded simulation.
%
% The table combines:
%   - deterministic campaign identity and state;
%   - selected configuration parameters;
%   - paths to saved artifacts;
%   - scientific metrics when completed outputs are available.
%
% Missing metrics are represented by NaN or empty strings.

arguments
    report struct
    runs struct
end

run_count = numel(report.runs);

ordinal = zeros(run_count, 1);
run_id = strings(run_count, 1);
hash_sha256 = strings(run_count, 1);
status = strings(run_count, 1);
outcome_status = strings(run_count, 1);

scenario = strings(run_count, 1);
dimension = NaN(run_count, 1);
seed = NaN(run_count, 1);
frequency_hz = NaN(run_count, 1);

background_cs_m_s = NaN(run_count, 1);
background_cp_m_s = NaN(run_count, 1);
inclusion_cs_m_s = NaN(run_count, 1);
inclusion_cp_m_s = NaN(run_count, 1);

solver_elapsed_s = NaN(run_count, 1);
valid = NaN(run_count, 1);
p_to_s_energy_ratio = NaN(run_count, 1);
total_shear_energy = NaN(run_count, 1);
total_compression_energy = NaN(run_count, 1);
req_ready = NaN(run_count, 1);

source_count = NaN(run_count, 1);
directional_bias = NaN(run_count, 1);
effective_angular_dimension = NaN(run_count, 1);

run_directory = strings(run_count, 1);
resolved_config_path = strings(run_count, 1);
summary_path = strings(run_count, 1);
validation_report_path = strings(run_count, 1);
req_sample_path = strings(run_count, 1);

error_identifier = strings(run_count, 1);
error_message = strings(run_count, 1);

for index = 1:run_count
    record = report.runs(index);
    requested_config = runs(index).config;

    ordinal(index) = record.ordinal;
    run_id(index) = string(record.run_id);
    hash_sha256(index) = string(record.hash_sha256);
    status(index) = string(record.status);
    outcome_status(index) = string(record.outcome_status);
    run_directory(index) = string(record.run_directory);
    error_identifier(index) = string(record.error_identifier);
    error_message(index) = string(record.error_message);

    resolved_config_path(index) = fullfile( ...
        run_directory(index), ...
        "config", ...
        "resolved_config.json");

    summary_path(index) = fullfile( ...
        run_directory(index), ...
        "data", ...
        "summary.mat");

    validation_report_path(index) = fullfile( ...
        run_directory(index), ...
        "data", ...
        "validation_report.mat");

    req_sample_path(index) = fullfile( ...
        run_directory(index), ...
        "data", ...
        "req_validation_sample.mat");

    config = requested_config;

    if isfile(resolved_config_path(index))
        try
            config = jsondecode( ...
                fileread(resolved_config_path(index)));
        catch
            config = requested_config;
        end
    end

    scenario(index) = textField(config, "scenario");
    dimension(index) = numericField(config, "dimension");
    seed(index) = numericField(config, "seed");

    if isfield(config, "source") && isstruct(config.source)
        frequency_hz(index) = ...
            numericField(config.source, "f0_hz");
    end

    if isfield(config, "medium") && isstruct(config.medium)
        background_cs_m_s(index) = ...
            numericField(config.medium, "cs_m_s");

        background_cp_m_s(index) = ...
            numericField(config.medium, "cp_m_s");
    end

    if isfield(config, "geometry") && ...
            isstruct(config.geometry) && ...
            isfield(config.geometry, "objects") && ...
            ~isempty(config.geometry.objects)

        object = config.geometry.objects(1);

        inclusion_cs_m_s(index) = ...
            numericField(object, "cs_m_s");

        inclusion_cp_m_s(index) = ...
            numericField(object, "cp_m_s");
    end

    if isfile(summary_path(index))
        try
            loaded = load(summary_path(index), "summary");

            if isfield(loaded, "summary")
                saved_summary = loaded.summary;

                solver_elapsed_s(index) = ...
                    numericField( ...
                        saved_summary, ...
                        "elapsed_solver_time_s");
            end
        catch
            % Leave unavailable summary metrics as NaN.
        end
    end

    if isfile(validation_report_path(index))
        try
            loaded = load( ...
                validation_report_path(index), ...
                "validation_report");

            if isfield(loaded, "validation_report")
                validation = loaded.validation_report;

                valid(index) = ...
                    numericField(validation, "valid");

                if isfield(validation, "metrics") && ...
                        isstruct(validation.metrics)

                    metrics = validation.metrics;

                    p_to_s_energy_ratio(index) = ...
                        numericField( ...
                            metrics, ...
                            "longitudinal_leakage_ratio");

                    total_shear_energy(index) = ...
                        numericField( ...
                            metrics, ...
                            "total_shear_energy");

                    total_compression_energy(index) = ...
                        numericField( ...
                            metrics, ...
                            "total_compression_energy");
                end

                if isfield(validation, "req_validation") && ...
                        isstruct(validation.req_validation)

                    req_ready(index) = ...
                        numericField( ...
                            validation.req_validation, ...
                            "valid");
                end

                if isfield(validation, "preflight") && ...
                        isstruct(validation.preflight) && ...
                        isfield(validation.preflight, "source") && ...
                        isstruct(validation.preflight.source) && ...
                        isfield( ...
                            validation.preflight.source, ...
                            "geometry_metrics")

                    geometry_metrics = ...
                        validation.preflight.source.geometry_metrics;

                    source_count(index) = ...
                        numericField( ...
                            geometry_metrics, ...
                            "source_count");

                    directional_bias(index) = ...
                        numericField( ...
                            geometry_metrics, ...
                            "directional_bias");

                    effective_angular_dimension(index) = ...
                        numericField( ...
                            geometry_metrics, ...
                            "effective_angular_dimension");
                end
            end
        catch
            % Leave unavailable validation metrics as NaN.
        end
    end
end

campaign_runs = table( ...
    ordinal, ...
    run_id, ...
    hash_sha256, ...
    status, ...
    outcome_status, ...
    scenario, ...
    dimension, ...
    seed, ...
    frequency_hz, ...
    background_cs_m_s, ...
    background_cp_m_s, ...
    inclusion_cs_m_s, ...
    inclusion_cp_m_s, ...
    solver_elapsed_s, ...
    valid, ...
    p_to_s_energy_ratio, ...
    total_shear_energy, ...
    total_compression_energy, ...
    req_ready, ...
    source_count, ...
    directional_bias, ...
    effective_angular_dimension, ...
    run_directory, ...
    resolved_config_path, ...
    summary_path, ...
    validation_report_path, ...
    req_sample_path, ...
    error_identifier, ...
    error_message);

campaign_runs.Properties.VariableNames = cellstr([ ...
    "ordinal", ...
    "run_id", ...
    "hash_sha256", ...
    "status", ...
    "outcome_status", ...
    "scenario", ...
    "dimension", ...
    "seed", ...
    "frequency_hz", ...
    "background_cs_m_s", ...
    "background_cp_m_s", ...
    "inclusion_cs_m_s", ...
    "inclusion_cp_m_s", ...
    "solver_elapsed_s", ...
    "valid", ...
    "p_to_s_energy_ratio", ...
    "total_shear_energy", ...
    "total_compression_energy", ...
    "req_ready", ...
    "source_count", ...
    "directional_bias", ...
    "effective_angular_dimension", ...
    "run_directory", ...
    "resolved_config_path", ...
    "summary_path", ...
    "validation_report_path", ...
    "req_sample_path", ...
    "error_identifier", ...
    "error_message"]);


csv_file = fullfile( ...
    string(report.campaign_directory), ...
    "campaign_runs.csv");

temporary_file = csv_file + ".tmp.csv";

deleteIfPresent(temporary_file);

writetable( ...
    campaign_runs, ...
    temporary_file, ...
    FileType="text", ...
    Delimiter=",");

[moved, message] = movefile( ...
    temporary_file, ...
    csv_file, ...
    "f");

if ~moved
    deleteIfPresent(temporary_file);

    error("kwsim:CampaignTableWriteFailed", ...
        "Could not publish campaign table '%s': %s", ...
        csv_file, ...
        message);
end

end


function value = numericField(value_struct, field_name)

value = NaN;

if ~isstruct(value_struct) || ...
        ~isscalar(value_struct) || ...
        ~isfield(value_struct, field_name)
    return
end

candidate = value_struct.(field_name);

if (isnumeric(candidate) || islogical(candidate)) && ...
        isscalar(candidate) && ...
        isfinite(double(candidate))
    value = double(candidate);
end

end


function value = textField(value_struct, field_name)

value = "";

if ~isstruct(value_struct) || ...
        ~isscalar(value_struct) || ...
        ~isfield(value_struct, field_name)
    return
end

candidate = value_struct.(field_name);

if (isstring(candidate) && isscalar(candidate)) || ...
        (ischar(candidate) && isrow(candidate))
    value = string(candidate);
end

end


function deleteIfPresent(path)

if isfile(path)
    delete(path);
end

end
